### ISSUE TITLE
Problems about solving implicits, default behavior of methods and finding implementations.

### ISSUE THREAD

**Issue by alissa42** [idris-lang/Idris2#1005]
# Steps to Reproduce

The issue was found in `Version 0.3.0-9c54d659f`.

Just use the default behavior of `(>>=)`, everything works fine:

```idris
data Maybe' a = Just' a | Nothing'

Functor Maybe' where
  map f (Just' x) = Just' $ f x
  map f Nothing' = Nothing'
Applicative Maybe' where
  pure x = Just' x
  (Just' f) <*> (Just' x) = Just' $ f x
  _ <*> _ = Nothing'
Monad Maybe' where
  join (Just' (Just' x)) = Just' x
  join _ = Nothing'
```

One may write the following code:

```idris
module Main
%default total

data S : Type where -- place holder
ST : Type -> Type
ST x = S -> (x, S)

Id : Type -> Type
Id x = x
```

... then tries to make them monadic:

```idris
Functor ST where
  map f xs = \s => let (x, s') = xs s in (f x, s')
Applicative ST where
  pure x s = (x, s)
  f <*> x = \s => let (xa, xs) = x s
                      (fa, fs) = f s
                  in (fa xa, s)

Id : Type -> Type
Id x = x

Functor Id where
  map f x = f x
Applicative Id where
  pure x = x
  f <*> x = f x
```

So far nothing happens. When adding the implementations of `Monad`:

```idris
Monad Id where
  join = ?fn_join
```

Idris 2 says : `While processing right hand side of >>=. Can't find an implementation for Functor ?f.`. However, it is okay to just imply the `(>>=)` instead.

# Expected Behavior

It is okay to give a hand made version of `Monad` without reduction via `Applicative`:

```idris
interface Monad' m where
  bind' : m a -> (a -> m b) -> m b
  join' : m $ m a -> m a
```

But changing the order of methods cases error message: `While processing right hand side of join''. Can't solve constraint between: ?a [locals in scope: m] and a.` However it got solved by adding hint `m : Type -> Type`, but still wondering what caused the order sensitive?

```idris
interface Monad'' m where
  join'' : m $ m a -> m a
  bind'' : m a -> (a -> m b) -> m b
```

# Observed Behavior

```Idris
ST : (x : Type) -> Type
ST x = State → (x, State)
```

reported that use “x” 0 times.

Can not find implementations, can not use default behaviors of methods and can not solve constraint.

**Comment by gallais** [comment]
[From the documentation](https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html?highlight=resolution#interfaces):

> To help with resolution, the arguments of an implementation
  must be constructors (either data or type constructors) or
  variables (i.e. you cannot give an implementation for a function).

**Comment by alissa42** [comment]
> [From the documentation](https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html?highlight=resolution#interfaces):
> 
> > To help with resolution, the arguments of an implementation
> > must be constructors (either data or type constructors) or
> > variables (i.e. you cannot give an implementation for a function).
> 
> So you should use a record or data wrapper.

Thanks.
