### ISSUE TITLE
Different behavoir of adding qualified names.

### ISSUE THREAD

**Issue by alissa42** [idris-lang/Idris2#1006]
# Steps to Reproduce

It is okay to write:

```idris
interface MonadWith m where
  map' : (a -> b) -> (m a -> m b)
  unit' : a -> (m a)
  join' : m $ m a -> m a
  mapId : (xs : m a) -> (f : a -> a) -> (p : (x : a) -> f x = x) -> map' f xs = xs
```
But modify to ` mapId : (xs : m a) -> (f : a -> a) -> (p : (x : a) -> f x = x) -> map' f xs = f xs` cause error: `While processing constructor MonadWith at /home/alissa/Scratch/Main.idr:4:1--8:84. Can't solve constraint between: ?a [locals in scope: m, map', unit', join'] and m ?a.`.

# Expected Behavior

I do not know is this an expected behavior, but change the function `f` along with its identity proof to `Prelude.id` at different places can behave differently.
That is, `map' Prelude.id xs = id xs`, `map' id xs = Prelude.id xs` and `map' Prelude.id xs = Prelude.id xs` 

# Observed Behavior

The goals of holes are different and the type can not match in one case.

![图片](https://user-images.githubusercontent.com/68433824/106374134-32f6c780-63bb-11eb-9325-a5c0e39462e5.png)
![图片](https://user-images.githubusercontent.com/68433824/106374137-3b4f0280-63bb-11eb-84ff-f979b2c8b41a.png)
![图片](https://user-images.githubusercontent.com/68433824/106374139-4144e380-63bb-11eb-8636-122894db81e6.png)
![图片](https://user-images.githubusercontent.com/68433824/106374141-47d35b00-63bb-11eb-9a87-8cc30295afc4.png)

**Comment by buzden** [comment]
Well, having written
```idris
 mapId : (xs : m a) -> (f : a -> a) -> (p : (x : a) -> f x = x) -> map' f xs = xs
```
you set that `f` maps not any `a` to `a` but a particular `a`, the same `a` that is used inside `m a` in the same signature.
`Prelude.id` function is polymorphic on `a` it uses, i.e. it has the signature `forall a. a -> a`, or `{0 a : Type} -> a -> a` if you will.

If you do the same with your function `f`, you'll reach the same result:
```idris
 mapId : (xs : m a) -> (f : forall a. a -> a) -> (p : (x : a) -> f x = x) -> map' f xs = f xs
```
typecheks. In this case `a` in the signature of `a` and `a` in the rest of the signature of `mapId` are not the same, thus `a` inside `f` can be instantiated as `m a` as you want in the expression `f xs`.

So, compiler's behaviour is completely expected.

**Comment by alissa42** [comment]
> Well, having written
> 
> ```idris
>  mapId : (xs : m a) -> (f : a -> a) -> (p : (x : a) -> f x = x) -> map' f xs = xs
> ```
> 
> you set that `f` maps not any `a` to `a` but a particular `a`, the same `a` that is used inside `m a` in the same signature.
> `Prelude.id` function is polymorphic on `a` it uses, i.e. it has the signature `forall a. a -> a`, or `{0 a : Type} -> a -> a` if you will.
> 
> If you do the same with your function `f`, you'll reach the same result:
> 
> ```idris
>  mapId : (xs : m a) -> (f : forall a. a -> a) -> (p : (x : a) -> f x = x) -> map' f xs = f xs
> ```
> 
> typecheks. In this case `a` in the signature of `f` and `a` in the rest of the signature of `mapId` are not the same, thus `a` inside `f` can be instantiated as `m a` as you want in the expression `f xs`.
> 
> So, compiler's behaviour is completely expected.

LGtM, thank you!
But still confused with the case when using `Prelude.id` though. Anyway, the `contrib/Interfaces/Verified.idr` in Idris 1 used the `f` way.

**Comment by buzden** [comment]
> But still confused with the case when using `Prelude.id` though. Anyway, the `contrib/Interfaces/Verified.idr` in Idris 1 used the `f` way.

You can use an approach with an arbitrary monomorphic `f` what is extensionally equivalent to monomorphised `Prelude.id` (which is witnessed by the argument `(p : (x : a) -> f x = x)`), but then you shouldn't apply `f` to anything except of type `a` (unlike you did when you were applying `f` to `xs` which has a type `m a`), again because `f` is not polymorphic.
