### ISSUE TITLE
Impossible pattern error when proving Not (Nat = String)

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#1022]
# Steps to Reproduce

```idris
test : Not (Nat = String)
test Refl impossible
```

# Expected Behavior

No error like in Idris 1.

# Observed Behavior

```idris
Error: Impossible pattern gives an error:
When unifying String = String and Nat = String.
Mismatch between: String and Nat.
     |
     | test Refl impossible
     |      ^^^^
```

**Comment by gallais** [comment]
I think the error is valid: you should not be able to pattern-match on `Refl`
because `Nat` and `String` do not unify.

However it should be possible to write `test eq impossible` and have idris
accept it. I have a patch incoming fixing this issue.

**Comment by michaelmesser** [comment]
```idris
test : Not (True = False)
test Refl impossible
```
works fine. Why should `Type` be different?

**Comment by gallais** [comment]
Hmm. This is strange. My impression was that `impossible` was looking for variables
whose type is empty. I'll take a look.
