### ISSUE TITLE
Strange behavior of large hexadecimal literals

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#1023]
# Steps to Reproduce
Start up a REPL and enter the following expressions:

`the Bits64 0xffffffffffffffff`
`the Bits64 0x8000000000000000`

# Expected Behavior
`the Bits64 0xffffffffffffffff` prints 18446744073709551615 (2^64 - 1: max unsigned 64bit number)
`the Bits64 0x8000000000000000` prints 9223372036854775808 (= 2^63)

# Observed Behavior
`the Bits64 0xffffffffffffffff` prints 9223372036854775807 (2^63 - 1: max signed 64bit number)
`the Bits64 0x8000000000000000` prints 0

Replacing Bits64 by Integer behaves the same. Entering the numbers in decimal form behaves correctly.

**Comment by gallais** [comment]
At least this bug is easy to track down: the code is decoding these literals
into an `Int`. :sweat_smile:
