### ISSUE TITLE
let-in in do notation fails to parse

### ISSUE THREAD

**Issue by mb64** [idris-lang/Idris2#1042]
```idris
foo : IO ()
foo = do
  let x = 5 in printLn x
```
#### Steps to Reproduce

Use `let ... in ...` syntax in `do`-notation.

#### Expected Behavior

It should parse fine, and define a local variable for that statement in do-notation.

#### Observed Behavior
```
Error: Parse error at line 3:13:
Expected end of input (next tokens: [in, identifier printLn, identifier x, end of input])
```

**Comment by buzden** [comment]
> It should parse fine, and define a local variable for that statement in do-notation.

It shouldn't since `do`-notation uses the syntax without `in`: https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html?highlight=let#monads-and-do-notation

This typechecks fine as it should:
```idris
foo : IO ()
foo = do
  let x = 5
  printLn x
```

**Comment by mb64** [comment]
Could you elaborate on why let-in should be disallowed in do-notation?  It seems somewhat arbitrary to me.  One [of the options](https://idris.readthedocs.io/en/latest/reference/syntax-reference.html#grammar-token-doblock) for a statement in a do-block is an expression, and `let x = 5 in printLn x` is a valid expression.

Your example is not the same -- it defines `x` as a local variable for the rest of the `do` block, not for that single expression.  For instance, this should print `5\n10\n`, since the second `x` temporarily shadows the first:
```idr
foo : IO ()
foo x = do
  let x = 10
  let x = 5 in printLn x
  printLn x
```
With your suggestion, `do { let x = 10 ; let x = 5 ; printLn x ; printLn x }` prints 5 twice.

Here's some things that work, and that print `10\n5\n`:

```hs
-- in Haskell
foo = do
  let x = 10
  let x = 5 in print x
  print x
```

```idr
-- in both Idris 1 and Idris 2
foo : IO ()
foo = do
  let x = 10
  (let x = 5 in printLn x)
  printLn x
```

**Comment by gallais** [comment]
Is this what you are looking for?

```idris
foo : IO ()                                                                                                                     
foo = do
  let x = 10
  do let x = 5
     printLn x
  printLn x
```

**Comment by buzden** [comment]
> Your example is not the same -- it defines `x` as a local variable for the rest of the `do` block, not for that single expression. For instance, this should print `5\n10\n`, since the second `x` temporarily shadows the first:

Oh, I see what you mean. Well, `let-in` syntax clashed with `let` syntax of `do`-notation. But since each line of the `do`-notation is an expression, you can surround is with parentheses like this:
```idris
f : IO ()
f = do
  let x = 10
  (let x = 5 in printLn x)
  printLn x
```

**Comment by mb64** [comment]
> Is this what you are looking for?

Yes, that has the behavior I am looking for, thanks.

Is there motivation for not having let-in in `do` blocks, or would you accept a PR to make it parse?

**Comment by gallais** [comment]
> or would you accept a PR to make it parse?

I wouldn't be opposed to it.

**Comment by andrevidela** [comment]
closing after #2926
