### ISSUE TITLE
Error in gambit backend: Unbound variable: exact-integer?

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris2#1043]
Trying to run `:exec main` in #1039 using the gambit backend, I get:

```
*** ERROR IN #<procedure #2> -- Unbound variable: exact-integer?
```

We should fix this & check whether any other primitives are missing!

**Comment by abdelq** [comment]
What version are you using? You might be using a very old version.

**Comment by gallais** [comment]
`gsc -v` returns v4.8.8

It's the version that ships with the Ubuntu LTS released last April:
https://packages.ubuntu.com/focal/gambc

**Comment by stefan-hoeck** [comment]
When I build and run the program from #1039 with gambit v4.9.3 on Nixos, I get a segmentation fault. When I change the (-1) to 1 it prints "2" correctly.

**Comment by abdelq** [comment]
I was going to comment this. Don't get the error, but get a segfault. Will look into that.

**Comment by stefan-hoeck** [comment]
There is a funny typo in `support.scm`: `arithmetic-shitt` instead of `shift`. Am testing a fix right now.

**Comment by stefan-hoeck** [comment]
Changing the typo fixes the bug. So far, there seem to be no tests for gambit, is that correct? Would be great if we could add the tests from #1038 for the rackent and gambit backends as well. I'll draft a PR if that's OK for all.

**Comment by gallais** [comment]
I still get

```
*** ERROR IN #<procedure #2> -- Unbound variable: exact-integer?
```

Do we have a lower bound on a version of gambit that ought to work?

**Comment by stefan-hoeck** [comment]
Not sure, whether this is what we are looking for, but it seems like `exact-integer?` was introduced in [this commit](https://github.com/gambit/gambit/commit/125eecedc12c996a78384133bfe53a550b9bcd99), so it should be available from 4.9.2 on onward. That's also the reason why we experienced a segfault in one case and your error, gallais, for earlier versions of gambit: The two bugs are unrelated.

However, I'm not sure why we need the `exact-integer?` check in `support.scm` in the first place (not enough of a Scheme expert). The other Scheme backends just call `remainder` directly without such a check.

**Comment by gallais** [comment]
It seems to be working cf. #1052 (using macos to easily get gambit 4.9.3).
That being said, I am not too keen on turning this test on: an extra 6 minutes 
of runtime just for that one test!

**Comment by stefan-hoeck** [comment]
Could we just opt to leave the test there but not turn it on in the CI? I guess having a bunch of tests about primitives behaving consistently across backends wouldn't be a bad thing.

**Comment by gallais** [comment]
I think I'll deal with it like the `api` test: remove it from the
test runner and maybe add a separate CI target that runs it in
parallel with the rest of the test suite on mac.
