### ISSUE TITLE
Exception from running Idris after installing on WSL2 through homebrew.

### ISSUE THREAD

**Issue by KySpace** [idris-lang/Idris2#1064]
The exception 
``` Exception: (while loading libidris2_support.so) libidris2_support.so: cannot open shared object file: No such file or directory ```
is thrown whenever I use the command idris2 (for interactive or otherwise).

Installation info
![image](https://user-images.githubusercontent.com/23047275/107861586-c1843380-6e14-11eb-9b45-ecbb6c9def13.png)

environment
![image](https://user-images.githubusercontent.com/23047275/107861593-d95bb780-6e14-11eb-9569-20ccd833d2c5.png)

**Comment by gallais** [comment]
I believe this is an issue in the homebrew installer.
They are aware of it: Homebrew/linuxbrew-core/issues/22225

**Comment by KySpace** [comment]
Just use nix then

**Comment by danielnachun** [comment]
Homebrew maintainer here - I looked into this issue and it was indeed a problem with our installation script.  It was a very simple fix and Idris2 is now available as a binary package on Linux.  Please let us know if there are any other issues!
