### ISSUE TITLE
Unreachability warning is not fired sometimes

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#1079]
Consider a pure function that matches its argument and has an unreachable clause:

```idris
g1 : Nat -> Nat
g1 x = 5
g1 _ = 6
```

You expectedly get
```
Warning: Unreachable clause: g1 _

.../UnreachableInDo.idr:3:1--3:4
 1 | g1 : Nat -> Nat
 2 | g1 x = 5
 3 | g1 _ = 6
     ^^^^
```

The same would be if you have some more complicated match:

```idris
g2 : (Nat, Nat) -> Nat
g2 (x, y) = x
g2 (a, b) = 6
```

gives

```
Warning: Unreachable clause: g2 (a, b)

.../UnreachableInDo.idr:7:1--7:10
 3 | g1 _ = 6
 4 |
 5 | g2 : (Nat, Nat) -> Nat
 6 | g2 (x, y) = x
 7 | g2 (a, b) = 6
     ^^^^^^^^^
```

The same in match inside `do`:

```idris
f : Monad m => m (Nat, Nat)

h2 : Monad m => m Nat
h2 = do
  (x, y) <- f
    | (a, b) => pure 5
  pure x
```

gives

```
Warning: Unreachable clause: case (a, b) of
                             {(x, y) => pure x;
                             (a, b) => pure (fromInteger 5)}

.../UnreachableInDo.idr:18:7--18:23
 14 |
 15 | h2 : Monad m => m Nat
 16 | h2 = do
 17 |   (x, y) <- f
 18 |     | (a, b) => pure 5
            ^^^^^^^^^^^^^^^^
```

but...

# Steps to Reproduce

Try unreachably match `_` after non-trivial match, both in pure functions and inside `do`:

```idris
g3 : (Nat, Nat) -> Nat
g3 (x, y) = x
g3 _ = 6
```

and

```idris
h3 : Monad m => m Nat
h3 = do
  (x, y) <- f
    | _ => pure 5
  pure x
```

# Expected Behavior

The warnings of unreachable clauses similar to those above.

# Observed Behavior

No warnings.

**Comment by gallais** [comment]
I believe this is a duplicate for #550

**Comment by buzden** [comment]
Well, this is not obvious, since this issue talks about unreachability warning (i.e. about lack of warning that some case is unreachable) but #550 talks about the case when compiler considers some case to be uncovered when they are.

**Comment by gallais** [comment]
My bad.
