### ISSUE TITLE
cannot find compatible chez.boot in search path

### ISSUE THREAD

**Issue by err0r500** [idris-lang/Idris2#108]
Hello,
I had a problem installing Idris on a Fedora 31, the bootstrap command was failing with

```
cannot find compatible chez.boot in search path
```

### Chez Scheme installation
```
git clone git@github.com:cisco/ChezScheme.git
cd ChezScheme
./configure --threads --disable-X11
make install
```
check : 
```
$ scheme --version
9.5.3
```
(no chez in PATH)

### Idris2 installation (attempt)
```
git clone git@github.com:idris-lang/Idris2.git
cd Idris2
make bootstrap SCHEME=scheme

....
134/134: Building Idris.Main (src/Idris/Main.idr)
cannot find compatible chez.boot in search path
  "/usr/lib/csv%v/%m"
```

## Workaround
I actually don't have the chez.boot file, but I've a scheme.boot so when I did 
```
ln -s /usr/lib/csv9.5.3/ta6le/scheme.boot /usr/lib/csv9.5.3/ta6le/chez.boot
```

Everything ran fine and I was able to install Idris2

**Comment by edwinb** [comment]
This seems like an issue with your chez scheme installation, or possibly something in the system paths, rather than an error with Idris... has anyone else seen this error?

**Comment by err0r500** [comment]
I reattempted the build just to investigate. I guess here's what happened : 

I first ran :
```
make bootstrap SCHEME=chez
```
which failed and then my other attempts were with 
```
make bootstrap SCHEME=scheme
```
but without cleaning up with `make bootstrap-clean` ... so I guess something was corrupted.

Running `bootstrap-clean` at the beginning of `bootstrap` may be an idea ?

**Comment by err0r500** [comment]
I guess we can close this issue since I'm not sure a "fix" is expected... and it will still lie around if someone hits the problem too.

**Comment by petrusboniatus** [comment]
Seems like this issue also happens with the current [Gentoo package](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-scheme/chez/chez-9.5.6-r2.ebuild). The fix was the same.

**Comment by devosalain** [comment]
Having same error on gentoo.
