### ISSUE TITLE
One-line exception in REPL : "Exception: variable DataC-45Strings-fastUnpack is not bound"

### ISSUE THREAD

**Issue by felipegchi** [idris-lang/Idris2#1086]
# Steps to Reproduce
```idris
public export
simpleMd : String
simpleMd = "#eita"

simpleMdRes : String
simpleMdRes = (fixTkns revertTokens (lexMd simpleMd))

simpleLex : simpleMdRes = simpleMd 
simpleLex = Refl
```

and then, i reloaded it in REPL and i got an error saying that i cant unify the types BUT i saw that `simpleMdRes` was evaluating a strange weird code:

```idris
case case let (ts, (l, (c, str'))) =
                case case scan (Pred (\{arg:0} => intToBool (prim__eq_Char arg '['))) [] (fastUnpack "#eita") of
                     {Just (tok, rest) => Just (MkToken line col (fn (pack (reverse Char tok))),
                     (line + cast (countNLs a str tmap acc col line pred tok), (getCols a str tmap acc col line pred tok col, rest)));
                     Nothing => getFirstToken a str tmap acc col line pred ts str} of
                {Just (tok, (line', (col', rest))) => if pred tok
                                                        then (reverse ?a acc, (line, (col, [])))
                                                        else assert_total (tokenise pred line' col' (tok :: acc) tmap rest);
                Nothing => (reverse ?a acc, (line, (col, str)))}
          in (ts, (l, (c, pack str'))) of
     {(tokens, (_, (_, ""))) => Right tokens;
     (_, (line, (column, _))) => Left (line, column)} of
{Left x => "";
Right list => fn (map tok list)}
```

So i thought that i could just run `:exec putStrLn simpleMdRes` and then i got the issue.

# Expected Behavior
```
#eita
```

# Observed Behavior
```
Exception: variable DataC-45Strings-fastUnpack is not bound
```

**Comment by gallais** [comment]
Can you please make sure the example is self-contained?
Your code won't load as is (even after commenting `simpleLex` out).

**Comment by Chiyoku** [comment]
```
➜  Md git:(main) ✗ idris2 LexerTest.idr -p contrib
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.3.0-e13e069c2
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/      Type :? for help                     

Welcome to Idris 2.  Enjoy yourself!
2/2: Building LexerTest (LexerTest.idr)
Error: While processing right hand side of simpleLex. When unifying simpleMd = simpleMd and simpleMdRes = simpleMd.
Mismatch between: simpleMd and simpleMdRes.

LexerTest.idr:25:13--25:17
    |
 25 | simpleLex = Refl
    |             ^^^^

LexerTest> simpleMd
"#eita"
```
The code *loads* in some way

**Comment by gallais** [comment]
```ìdris
LexerTest.idr:25:13--25:17
    |
 25 | simpleLex = Refl
    |             ^^^^
```

In this error message, `simpleLex = Refl` is on line 25 but the snippet you
posted only has 9 lines. This is not self-contained.

**Comment by Chiyoku** [comment]
Now i think that it is self contained.
```idris
module LexerTest

simpleMd : String
simpleMd = "a"

simpleMdRes : String
simpleMdRes = "b"

simpleLex : simpleMd = simpleMdRes
simpleLex = Refl
```
And stills with the same problem
```
➜  Md git:(main) ✗ idris2 LexerTest.idr -p contrib --no-banner
1/1: Building LexerTest (LexerTest.idr)
Error: While processing right hand side of simpleLex. When unifying simpleMdRes = simpleMdRes and simpleMd = simpleMdRes.
Mismatch between: simpleMdRes and simpleMd.

LexerTest.idr:10:13--10:17
    |
 10 | simpleLex = Refl
    |             ^^^^

LexerTest> simpleMd
"a"
```

**Comment by gallais** [comment]
It is not true that `"a"` is equal to `"b"` so why do you expect `Refl` to succeed?

**Comment by Chiyoku** [comment]
I dont expect Refl to succeed. When code not compiled it should not make the other functions run i think
```
... (After the Refl Error)
LexerTest> simpleMd
"a"
```
i got this error with my new installation of idris with AUR  
```
LexerTest> :exec putStrLn simpleMdRes
sh: build/exec/_tmpchez: Permission denied
```
and with the previous installation of idris2 the REPL was returning this error for the same code above.
```
Exception: variable DataC-45Strings-fastUnpack is not bound
```

**Comment by gallais** [comment]
This is what I'm getting:

```repl
1/1: Building Issue1086 (Issue1086.idr)
Loaded file Issue1086.idr
Issue1086> :exec putStrLn simpleMdRes
b
```

> sh: build/exec/_tmpchez: Permission denied

To `exec` an expression, idris2 needs to be able to produce an executable. This means
emitting a program in a temporary directory and compiling it using the backend you have
picked (chez scheme by default) and then running the result.

This error shows that you are running idris2 from a directory where it is not allowed
to create such a temporary directory. You should either use a different directory where
that is possible or change the file system permissions of this directory.

**Comment by Chiyoku** [comment]
I create a gist: https://gist.github.com/Chiyoku/e1ac7aa4c8696f53dc7333569fe22048

```
➜  Md git:(main) ✗ idris2 LexerTest.idr -p contrib --no-banner
1/1: Building LexerTest (LexerTest.idr)
Error: While processing right hand side of simpleLex. When unifying simpleMd = simpleMd and simpleMdRes = simpleMd.
Mismatch between: simpleMd and simpleMdRes.

LexerTest.idr:42:13--42:17
    |
 42 | simpleLex = Refl
    |             ^^^^

LexerTest> :exec putStrLn simpleMdRes
Exception: variable DataC-45Strings-fastUnpack is not bound

**Comment by gallais** [comment]
That file loads just fine for me & the exec command succeeds after printing `####`.
My guess is that there was a problem during the installation of Idris2.

How did you install Idris?

**Comment by Chiyoku** [comment]
i installed Idris2 from AUR

**Comment by buzden** [comment]
This issue suspiciously reminds #850, but there underscores in names were wrong.

**Comment by gallais** [comment]
Can you add `import Data.Strings` at the top of your file and see whether that
fixes the issue?

I just had a similar issue in a different module and that was solved by
importing the module defining the function that was missing from the executable
generated by Idris.

**Comment by Chiyoku** [comment]
I imported and now i have this problem lol.
```
:exec putStrLn reversedMd
Exception: variable DataC-45List-reverse is not bound
```

**Comment by gallais** [comment]
Can you import `Data.List`? And similarly keep importing all the modules
corresponding to the missing definitions? For some strange reason Idris
seems to be ignoring the modules that are not explicitly imported.

**Comment by Chiyoku** [comment]
i imported Data.List and now it works

**Comment by ShinKage** [comment]
I can report that I've also encountered a similar kind of error due to missing imports, in particular when using interface instances. To solve you either need to explicitly import the missing module or import publicly the dependancy in the original module.

**Comment by gallais** [comment]
The one I encountered today was indeed interface-related.
