### ISSUE TITLE
Meta: Mark some issues as good first issue

### ISSUE THREAD

**Issue by turion** [idris-lang/Idris2#1090]
It seems that the label [good first issue](https://github.com/idris-lang/Idris2/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) is not used at all currently. To onboard new maintainers it would be great if there were a lot of such issues. Can you mark some existing ones as such, or open simple ones? Ideal candidates are:

* Refactoring,
* Small clean up tasks
* Small simple delimited features

**Comment by gallais** [comment]
This morning I went through 6 pages of issues and tagged 15 of them as
[good first issues](https://github.com/idris-lang/Idris2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22).

This has allowed me to find a lot of stale issues and duplicates too so
the tracker should be cleaner too. I'll do more tagging after lunch.

**Comment by gallais** [comment]
Done. And with the cleanup of already solved issues and expected behaviours we
are now below the 200 mark!
