### ISSUE TITLE
Include laziness information in CExp, Lifted etc.

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#1104]
### Motivation
I have been trying to write a GRIN backend for Idris2, however it is way more complicated than it needs to be because laziness is always turned into a lambda in ANF and LambdaLift form. This prohibits memoization and more efficient backend dependant implementations.

### Implementation ideas
This could be done with `Force` and `Delay` constructors with `LazyReason`
Or with the function application constructors (eg. `AAppName : FC -> Name -> Maybe LazyReason -> List AVar -> ANF` where `Nothing` represents strict).

I am happy make a PR for this, but I wanted to know how this should be done first.

**Comment by melted** [comment]
An alternative solution would be to compile from NamedCExp which has force and delay (or CExp I guess, but I prefer to have the names instead of indices). Is there any reason that would be a bad fit?

**Comment by melted** [comment]
Deleted comment, I missunderstood the issue.

**Comment by gallais** [comment]
> I have been trying to write a GRIN backend for Idris2,

This is very exciting!

> This could be done with Force and Delay constructors with LazyReason
  Or with the function application constructors 

I'd rather have annotations on lambdas & applications so that backend writers
who do not want to think about this yet can get started quickly and simply
ignore the annotation and rely on the current encoding of thunks as functions.

**Comment by Z-snails** [comment]
I'm currently adding laziness annotations to `LambdaLift` and I have a question. Should there be a `Force` function (like the `eval` function in GRIN), or should each function assume values could be lazy and force them first (like Haskell/STG)?

There is potential for some optimisations (reduced number of function calls) if the backend know exactly when a value goes from lazy to strict, but I have no idea how much difference that would actually make (it will be a known function call which should be well optimised). Whereas the second option is slightly easier when writing a new backend.
