### ISSUE TITLE
RFC - Create a Golden package

### ISSUE THREAD

**Issue by mattpolzin** [idris-lang/Idris2#1105]
The code needed to run the Idris 2 test suite was (somewhat recently) duplicated from its place in the compiler source files into the contrib package. At face value, this is nice. I just started to use Golden in a personal project and immediately saw value in not having to roll my own test framework for testing. 

The duplication means we have an opportunity for unintentional code drift between the two copies of Golden, though. 

If we fully move Golden to contrib, we have an additional compiler dependency on contrib (whereas it makes sense to me to move away from the compiler or even it's test suite depending on the contrib package). So, I propose we move Golden into a new package alongside network, base, contrib, etc. and let the test suite depend on this new package. I'd call the package "golden" but other bike shed painters might prefer a name like "testing". 

If folks like the idea of a new package, I'm happy to tackle the PR that creates the package and removes the code currently living in contrib and src.

**Comment by andylokandy** [comment]
Besides the golden test, I'd like to introduce an intrusive test framework as rust does. Because every golden test brings 3 more files which make the test too heavy and discourages us to write unit tests. It may look like:

```idris
module MyBoolOps

not : Bool -> Bool
not True = False
not False = True

%test
testNot : Test
testNot = do
  assert $ (not . not) True == True 
  assert $ not False == True
```

**Comment by mattpolzin** [comment]
@andylokandy a unit test framework would definitely be nice. 

Do you think this motivates a single package ("testing") where `golden` is a module and unit test functionality stems from another module in the same package? I think that might be nice. A single package dependency anywhere that testing of either kind is going to be performed.

**Comment by andylokandy** [comment]
Maybe good or not... It's indeed very convenience of providing as many functionaloties (including test framework, various parsers, benchmark framework, getops) in stdlib at this immature stage of idris. But once backward compatibility has became important, these things have better move out of std, for instance, to an official package in package manager registry.

**Comment by mattpolzin** [comment]
In this latest comment I think you are talking pretty exclusively about the differences between the testing framework being located inside this git repository or not, as opposed to whether it should live in its own package or not, right?

I’m currently suggesting it move to its own package but remain in this repository. The advantage I care about most being that it can easily be used by the compiler project _and_ third parties without it needing to be maintained in both the compiler source code and the `contrib` package. 

I see this as potentially a stepping stone to it eventually being a standalone project pulled from a package registry but the two steps seem separable to me.

**Comment by andylokandy** [comment]
Yeah, can't agree more. As we suggest putting the golden test and assertion test into the `contrib` package, I think it's fine that they're in the same module. And if we're going to settle them in different packages eventually, it'll certainly be a breaking change, so splitting them into two modules will be of no consequence.

**Comment by gallais** [comment]
After thinking about it for a while, I'd be in favour of a `testing` package.
Not only could we rely on it to avoid code duplication, but it's an important
signal to send to the newcomers: typing and testing go hand in hand.

I am also planning to have a look at quickch(e/i)ck & related work after I'm
done with #1093 and that may yield other candidates for inclusion in a wider
testing package.

**Comment by mattpolzin** [comment]
Quickcheck functionality would be a fantastic thing to offer as part of the "standard testing package" IMO. Too often it is some optional thing you need to go and grab whereas a tight interface that feels like part of the same unit testing framework used more broadly would be really nice. 

Tangentially, when I saw the current contrib work that touched on generators I was excitedly hopeful it was heading in the direction of quickcheck!

**Comment by zenntenn** [comment]
Out of curiosity, what would be the advantage of quickcheck in Idris? It
seems pretty easy to do any of those sorts of tests at the type level.

**Comment by stefan-hoeck** [comment]
> Out of curiosity, what would be the advantage of quickcheck in Idris? It seems pretty easy to do any of those sorts of tests at the type level.

Several reasons: Tests at the type level can only be performed if all functions involved are `public export`. For instance, I wrote a simple parser the other day (using the Parser library from contrib) and had to write quite a few property tests, since they are not exported publicly. Also, testing at the type level is rather slow right now. Therefore, even if a function definition is available during elaboration, it might be too slow to be computed in reasonable time.

**Comment by andylokandy** [comment]
@stefan-hoeck Plus one: `fastPack` doesn't get reduced in unification.
