### ISSUE TITLE
Unable to install idris2 api on NixOS - (Error: Can't make directory idris2)

### ISSUE THREAD

**Issue by phenax** [idris-lang/Idris2#1106]
I'm trying to install just the idris2 library but I keep running into this error -

```
Uncaught error: INTERNAL ERROR: Can't make directory idris2
make: *** [Makefile:111: install-api] Error 1
```

I've written this derivation for testing -

```nix
{ nixpkgs ? import <nixpkgs> {} }:
let
  inherit (nixpkgs) pkgs;

  idris2Library = pkgs.stdenv.mkDerivation rec {
    name = "idris2-dev-${version}";
    version = "0.3.0";
    src = pkgs.fetchFromGitHub {
      owner = "idris-lang";
      repo = "idris2";
      rev = "v0.3.0";
      sha256 = "0sa2lpb7n6xqfknwld9rzm4bnb6qcd0ja1n63cnc5v8wdzr8q7kh";
    };

    buildInputs = with pkgs; [ idris2 ];

    buildPhase = ''echo "--------- no build ---------"'';
    installPhase = ''make PREFIX=$out DESTDIR="" install-api'';
  };

  idrisPackages = pkgs.idrisPackages.override {
    idris-no-deps = idris2Library;
    overrides = self: super: {
      idris = super.idris.override { idris-no-deps = idris2Library; };
    };
  };

  packages = with pkgs; [
    idris2
    idrisPackages.idris
  ];
in pkgs.stdenv.mkDerivation {
  name = "testidr";
  buildInputs = packages;
}
```

### System
```
OS: NixOS unstable
Idris2 version: 0.3.0
```

Am I missing something?

**Comment by gallais** [comment]
> Am I missing something?

Are filesystem permissions such that idris is not allowed to create `~/.idris2/`?

**Comment by gallais** [comment]
If you can try the patched version on the branch used in #1109, you should
get more information about the failure.

**Comment by phenax** [comment]
> Are filesystem permissions such that idris is not allowed to create `~/.idris2/`?

Yes, in the nix environment, it won't be able to. But even when I try running `make install-api` directly on my system it still gives me the same error.


> If you can try the patched version on the branch used in #1109, you should
> get more information about the failure.

No luck. Got the same error again. I saw the pr and the error message that I get seems to be a little different than the ones mentioned there (singular `directory` instead of `directories`). Do you know where that error is coming from?

**Comment by gallais** [comment]
> Yes, in the nix environment, it won't be able to. 

Then I think you're out of luck until we support DESTDIR (cf. #1078  for preliminary work).

> Do you know where that error is coming from?

With the exact error message it'd be easier to source.

**Comment by phenax** [comment]
The full error I got when trying to run nix-shell with the above file

```
...
...
160/161: Building Yaffle.Main (src/Yaffle/Main.idr)
161/161: Building Idris.Driver (src/Idris/Driver.idr)
Uncaught error: INTERNAL ERROR: Can't make directory idris2
make: *** [Makefile:111: install-api] Error 1
builder for '/nix/store/r9z7r1mkvr6bichjx9hn0xjfwiax1dlg-idris2-dev-0.3.0.drv' failed with exit code 2
cannot build derivation '/nix/store/93cq07q2glkh8gkwc8sgi9f9j4g4cx4y-idris2-dev-0.3.0.drv': 1 dependencies
couldn't be built
error: build of '/nix/store/93cq07q2glkh8gkwc8sgi9f9j4g4cx4y-idris2-dev-0.3.0.drv' failed
```

**Comment by guilhermehas** [comment]
When I run `idris2 --install mypkg.ipkg`, it can not create the directory `idris2-0.3.0` in the directory that it should install, so I have to create it manually.

**Comment by fabianhjr** [comment]
Hey @phenax, also on NixOS but I would advise to change the `installPhase` to do the install manually

What install does is copy over the TTC files to a specific $HOME/.idris2 structured directory; something like:

```Installing /home/fabian/Development/Open/Idris2/libs/network/build/ttc/Control/Linear/Network.ttc to /home/fabian/.idris2/idris2-0.3.0/network-0.3.0/Control/Linear```

So you should be able to just copy over the `ttc` files to your `$out` manually in whatever subdirectory works for you. (Though, the next challenge would be to read the packages from a specific `.nix-profile` path)

**Comment by sagehane** [comment]
Has this issue actually been resolved? I was trying to build https://github.com/idris-community/idris2-lsp using Nix and it requires `idris2api` to be built too. Is it possible to get `flake.nix` to expose it as a package along with `idris2` or am I missing something?
