### ISSUE TITLE
Local blocks should delay solving auto implicits

### ISSUE THREAD

**Issue by mb64** [idris-lang/Idris2#1140]
This problem was found by someone on the FP Discord.

Minimal example:
```idris
data A = A0
interface Cool a where cool : a -> a
implementation Cool A where cool x = x

please : A
please = cool (let x : String; x = "hello" in A0)
```

#### Steps to Reproduce

Use a local block in a situation where not every type with typeclass constraints has been inferred yet.

The easiest way is in `do`-notation; here is the original example:
```idris
data A = A0

giveA : HasIO io => io A
giveA = pure A0

please : HasIO io => io ()
please = do
     value_a <- giveA

     let a : A 
         a = value_a 
     
     pure ()
```
Here, it hasn't yet unified the `?io` hole from `giveA` with the `io` type from `please` by the time it typechecks the declaration of `a`, so it's unable to figure out that it has a monad implementation.

#### Expected Behavior

It should typecheck fine.

#### Observed Behavior

Error from minimized example:
```
Error: While processing right hand side of please. While processing type of please,x. Can't find an implementation for Cool ?a.

t.idr:6:10--6:50
 2 | interface Cool a where cool : a -> a
 3 | implementation Cool A where cool x = x
 4 | 
 5 | please : A
 6 | please = cool (let x : String; x = "hello" in A0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Error from the example using `do`-notation:
```
Error: While processing right hand side of please. While processing type of please,a. Can't find an implementation for Monad ?m.

t.idr:8:6--8:22
 4 | giveA = pure A0
 5 | 
 6 | please : HasIO io => io ()
 7 | please = do
 8 |      value_a <- giveA
          ^^^^^^^^^^^^^^^^
```

**Comment by SmiVan** [comment]
Thanks! For the record this is the evolution of my incorrect #1139 issue.
