### ISSUE TITLE
:let broken on the repl

### ISSUE THREAD

**Issue by vrescobar** [idris-lang/Idris2#1156]
Following typedd book in idris 2 (cross checking the docs about the updates). Some REPL functionalities seem to be broken on **idris 2 version 0.30** installed via nix.

# Steps to Reproduce
1. throw an idris2 repl
2. try to use the `:let` binding as follows ` :let hello = "world"`
3. an error m
# Expected Behavior
the value "world" is bounded to the name `hello` as the help says;

` :let            <decls>     Define a new value`

# Observed Behavior
```
Main> :let hello = "world"
Error: No type declaration for Main.hello.

(interactive):1:6--1:21
   |
 1 | :let hello = "world"
   |      ^^^^^^^^^^^^^^^
```

**Comment by gallais** [comment]
As the error message explains you need to give a type declaration
for the `let`-bound top-level value.

The following works:

```idris
Main> :let hello : String
Main> :let hello = "world"
```

**Comment by vrescobar** [comment]
I thought some type declarations may be omitted at the REPL.
Your example it does, so I guess it is a problem with the book and the documentation which explains the changes from v1.

the issue is solved from my side; should I close the issue or do I left it open as to-do reminder or something?
