### ISSUE TITLE
unhandled division 0/0

### ISSUE THREAD

**Issue by vrescobar** [idris-lang/Idris2#1160]
As I am following the book and play around for the examples I found out an error that I didn't expect to happen in Idris2 with all its security at compile time. The example comes directly from the book and I wonder if that would have been prevented by the type system in any other way which I still ignore.

# Steps to Reproduce
1. Load the average example in the REPL
2. execute `average` with an empty string (the last line at `average` will become a double type 0/0)

# Expected Behavior
The compiler preventing this behave, as it is was an actual bug at my small program. I didn't think about it until I got surprised trying out in the REPL.

# Observed Behavior
```
Main> average ""
+nan.0
```

# Code
``` idris
import Data.Strings -- for `words`
import Data.List -- for `length` on lists
import System.REPL

average : String -> Double
average str = let numWords = wordCount str
                  totalLength = sum (allLengths (words str)) in
                  cast totalLength / cast numWords
  where
 
    wordCount : String -> Nat
    wordCount str = length (words str)
    allLengths : List String -> List Nat
    allLengths strs = map length strs


showAverage : string -> string
showAverage str = "The average word is: " ++
                 show(average str) ++ "\n"
```

**Comment by vrescobar** [comment]
If this behave was expected I would like to encourage a more secure way to convert between Fractional Nat and doubles.
If this is a mere misuse of the language, please let me know where can I post such questions, (I guess StackOverflow?)

**Comment by ohad** [comment]
Thanks for this question!

I think that's expected behaviour: the double-precision floating point operations define the division `0 / 0` to be "a quiet NaN".

A nice exercise would be to redesign this function using types that guarantee we never divide by zero.
(A harder one would be to guarantee that we never end up with a NaN.)

**Comment by vrescobar** [comment]
the thing is that it ended up in the console stdout printed as `the average is: -0.nan` or something quite similar, and it was a legit bug, I totally forgot the use case. I can try to redesign the division or the cast to prevent this behave when I get a bit of experience with the type system/language (I am still a bit lost and cannot easily find APIs, etc).

**Comment by buzden** [comment]
> I am still a bit lost and cannot easily find APIs, etc

Did you try to use https://idris2docs.sinyax.net/ for that?

**Comment by vrescobar** [comment]
Oh perfect, thanks, I could not find a link anywhere (and  I use duck duck go instead of Google).

Atentamente/ Kind regards/ mit freundlichen Grüßen

Víctor R. Escobar
vrescobar.com
