### ISSUE TITLE
False positive coverage-checking on primitive types

### ISSUE THREAD

**Issue by Russoul** [idris-lang/Idris2#1169]
# Steps to Reproduce
```Idris
%default total

test : (String, ()) -> ()
test ("a", ()) = ()

test' : (Int, ()) -> ()
test' (1, ()) = ()

```
The problem seems to occur when a primitive type is at least one constructor deep into some inductive type.
# Expected Behavior
Both definitions shouldn't pass the coverage-checker.

# Observed Behavior
Both definitions pass the coverage-checker.

**Comment by gallais** [comment]
Interestingly

```idris
test'' : Type -> Type
test'' (List a) = a
```

does report a missing clause (`test'' _ = ?hole`) so there seems to be some logic in there
for mandatory catchalls in cases where you couldn't possibly have enumerated all possible
patterns.

**Comment by gallais** [comment]
Looks like the evaluator returns `String` as an `NTCon` rather than the `NPrimVal` we expect.
