### ISSUE TITLE
Comparison operations on Nat should be O(1)

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#1182]
Right now, arithmetic functions like addition and multiplication on `Nat` are optimized to be O(1) by the compiler. It would be great, if this would also be the case for comparison operators like `(==)` and `(<=)` and probably even `lte` and friends from `Data.Nat` in base. Right now, these seem to be linear. For instance, building and running the following example takes 20 seconds on my system:

```idris
main : IO ()
main = printLn (the Nat 10000000000 == 10000000000)
```

while the following is instantaneous (which I think is already pretty cool :-) )

```idris
main : IO ()
main = printLn . the Nat $ 10000000000 * 10000000000
```

Feel free to close this issue, if this is not feasible or not desired.

**Comment by Z-snails** [comment]
I think it would be better if every `Nat`-like type could be optimised by the compiler.
One way this could be done is like Agda's Builtin pragma, which would mean types like `Fin` are as fast as `Nat`.
Alternatively the compiler could try checking every data type but that might slow down compilation too much.

**Comment by gallais** [comment]
The hard thing is that the definition used in the compiler should work
for open terms too. I suppose we could have some special logic to patch
these defined names on the fly so that evaluation would be using a
different implementation for closed terms. Checking whether a term is
closed could be expensive though.

**Comment by Z-snails** [comment]
I don't know the codebase very well except the backends, but currently `Nat`s are optimised when going to `CExp` (are they optimised elsewhere?). I don't know if `CExp` is used during typechecking but if it isn't surely we can add that optimisation when going to `CExp` before passing that to the backend?

**Comment by Z-snails** [comment]
I'm about to start work on adding O(1) `Nat` `Ord` and `Eq`, but I need to add some more constructors to `BuiltinType`, does anyone have an opinion on using a `String` instead (fewer ttc version changes) or extend the `BuitlinType` ADT (nicer?)?

**Comment by stefan-hoeck** [comment]
@Z-snails have you seen #1357?

**Comment by Z-snails** [comment]
Yep, but %transform works on `Term` but nats are only transformed to `Integer`s in `CExp` so there'll be some time where it is wrong. Unless there is something else you mean?

**Comment by Z-snails** [comment]
It's easier to optimise natToInteger and integerToNat then define (or %transform) other operations to use that, so that's what I'll do. Is that what you meant?

**Comment by stefan-hoeck** [comment]
I'm sorry my comment caused confusion. I didn't "mean" anything by it, since I have not so far thought about how to solve the problem at hand. All I wanted is to point you to the possibility of using `%transfrom` in case you didn't know Edwin was already using it for other optimizations.

So, please go ahead with whatever you think is the best solutions. Thanks for working on this!

**Comment by stefan-hoeck** [comment]
This has been fixed, so I'll close it.
