### ISSUE TITLE
RefC backend invalid free

### ISSUE THREAD

**Issue by mderveeuw** [idris-lang/Idris2#1191]
# Steps to Reproduce

Compiling this code to an executable using the RefC backend, then running the resulting executable gives a SIGABRT (Aborted) / free(): invalid pointer.
```idris
main : IO ()
main = printLn (the Nat (1 + 2))
```

# Expected Behavior

3 printed to `stdout`

# Observed Behavior

Executable crashes with free(): invalid pointer / SIGABRT (Aborted).

I quickly debugged the code and the problem seems to be that a return `Value` is freed twice.

**Comment by gallais** [comment]
This has been fixed.
