### ISSUE TITLE
Syntax for complex numbers

### ISSUE THREAD

**Issue by Atomotron** [idris-lang/Idris2#1200]
Idris 2 supports complex numbers, but lacks an easy way to write them. Presently, the only way I know to get the imaginary unit `i` is with,
`sqrt (-1)`
or,
`log (-1) / pi`
Since stringification will happily print `0.0 + 1.0i` after evaluating `log (-1) / pi`, and since `the Double (cast "0.0+1.0i")` will return successfully, it stands to reason that it should work the same way in source code. Most other types have a bijection between parsing and printing, and it stands to reason that the complex part of the double type should also.

Of course it is possible to write expressions that evaluate to complex numbers, but that lacks the nice property of the printed form of types being valid source code. Idris would be best if it only had one Double parsing behavior, and not two subtly distinct behaviors, one for parsing source, and the other for `cast`.

**Comment by gallais** [comment]
Wait, does it?

The type of `sqrt` is `Double -> Double` so I don't see why it
should return a complex number (it's not even well-defined on `-1`).

This seems more of a bug due to a weird thing the backend decides to
do with `Double`?

**Comment by Atomotron** [comment]
Here are a few lines from a recent REPL session on the latest master branch:
```Haskell
Main> :let x : Double
Main> :let x = sqrt(-1)
Main> x
0.0+1.0i
```
I think it is weird that the Double type can do this, especially because of its correspondence with doubles in the C API. However I love that Idris supports complex numbers natively, because I write a lot of programs that use them. :)

**Comment by gallais** [comment]
I think this is an undefined behaviour. The expected behaviour is probably
that it should raise an exception if called with a negative number.

Chez scheme seems to indeed specify that it'll try to make the best of it
but I wouldn't be surprised if you can break things by using a different
backend: https://www.scheme.com/tspl4/objects.html#./objects:s127

**Comment by gallais** [comment]
There we go:

```idris
idris2 --cg node --no-banner
Main> :let main : IO ()
Main> :let main = print (sqrt (-1))
Main> :exec main
NaNMain> 
```

vs

```idris
idris2 --no-banner
Main> :let main : IO ()
Main> :let main = print (sqrt (-1))
Main> :exec main
0.0+1.0iMain> 
```

**Comment by Atomotron** [comment]
Do you think it would be better to return NaN like `0.0/0.0` does, or to violate totality? I think it might be better to keep totality, if for nothing else than to ease totality proofs. (It would be difficult to prove that a double would be in the range of acos, given that it's delimited by transcendental numbers.)

**Comment by stefan-hoeck** [comment]
Returning `NaN` in case of `0.0/0.0` does not violate totality. `NaN` is a valid `Double` according to the IEEE standard (though these constants are right now not officially supported by Idris2, see #29) and the program does not crash when returning a `NaN` result. It should be possible to refine `Double` in your own code (by using `Data.DPair.Subset` for instance) in such a way that it does not include `NaN` or `Infinity`.

Concerning proofs about floating point numbers: Alas, these will be very hard to do properly. For instance, even the following most basic axiom does not hold for `Double` (even without the above mentioned constants): `x,y > 0 => x * y > 0`.

**Comment by Atomotron** [comment]
> Returning `NaN` in case of `0.0/0.0` does not violate totality.

Yes, I agree. I think it would be better to return NaN for expressions like `sqrt(-1)` than it would be to crash on a misapplied partial function, both of which are better than undefined behavior.

**Comment by ohad** [comment]
I support making `sqrt` partial, and adding a safe version in the library for use in proofs (using proof reflection):
```idris
import Syntax.WithProof

sqrtSafe : (d : Double) -> {auto 0 prf : d >= 0 = True} -> Double
sqrtSafe d = assert_total (sqrt d)

One : Double
One = sqrtSafe 1

{-
Error : Double
Error = sqrtSafe (-1)  
-- While processing right hand side of Error. Can't find an implementation for False = True.
-}

Complicated : Double -> Double
Complicated x = case @@(x >= 0) of
  (True ** prf) => sqrtSafe x
  (False** _  ) => 0
  
Zero : Double
Zero = Complicated (-1)

```

**Comment by Atomotron** [comment]
`sqrt` on doubles should be partial iff division on doubles is partial.

**Comment by ShinKage** [comment]
IMHO as @Atomotron is saying, consistency is the most important factor. `Double` should be treated as a primitive implementing the IEEE standard with its sentinel values such that all operation are total even if mathematically undefined. Library abstractions should, instead, be in charge of providing a more safe abstraction on top of `Double` which may be closer to the mathematical approach. Now that we also have double literal overloading, it would be also an ergonomic approach.

**Comment by Atomotron** [comment]
Another point to consider is that if there will ever be a codegen targeted at high performance, mirroring IEEE (i.e. whatever Intel believes should happen) will be the only reasonable option - as putting checks after every `sqrtsd` to conform to a language specification that demands crashing would not be appropriate.

**Comment by gallais** [comment]
Yes, I think you're right: consistent, well-specified behaviour for the builtins
plus a (choice of) library layers offering a safer interface (something à la [Flocq](http://flocq.gforge.inria.fr/))
would be a natural candidate).
