### ISSUE TITLE
ANF contains multiple definitions of the same function

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#1208]
# Steps to Reproduce
test.idr
```idris
main : IO ()
main = do
    let x = sum [0 .. 100]
    printLn x
```
`$ idris2 test.idr -o test --dumpanf test.anf`

# Expected Behavior

All functions are uniquely named.

# Observed Behavior

Overlapping function names

```
Prelude.EqOrd.== = [0, 1]: %case v0 of { %constalt(0) => %case v1 of { %constalt(0) => 0 Just 1 }| %constalt(1) => %case v1 of { %constalt(1) => 0 Just 1 }| %constalt(2) => %case v1 of { %constalt(2) => 0 Just 1 } Just 1 }
Prelude.EqOrd.== = [0, 1]: %let v2 = (%op ==Integer(v0, v1)) in (%case v2 of { %constalt(0) => 1 Just 0 })
Prelude.EqOrd.== = [0, 1]: %let v2 = (%op ==Char(v0, v1)) in (%case v2 of { %constalt(0) => 1 Just 0 })
```

I believe this is a problem with interfaces, however I've only tested this with a small program so far.

**Comment by cypheon** [comment]
This is more an issue with how the ANF representation is "dumped". The overloaded operators from the interface `EqOrd` are created as `DN "=="` (= DisplayName) which means that their printed name should be different from the actual (generated) name. I believe this is done to make error messages (and other places where function names are user-visible) more readable. The underlying "real" names are all unique.

See this example of your example's VMCode (not ANF, but the names should be more or less the same) exported with a custom S-exp syntax (not via the "dumping" mechanism), you can see the real names `(UN "==_Eq_Ordering")` and `(UN "==_Eq_Integer")` "shadowed" by the `DN "==" […]` name.

    (defun (NS (EqOrd Prelude) (DN "==" (UN "==_Eq_Ordering"))) ("v0" "v1") ((START) (CONSTCASE "v0" (default ((MKCONSTANT RVAL (I "1")))) ((I "0") ((CONSTCASE "v1" (default ((MKCONSTANT RVAL (I "1")))) ((I "0") ((MKCONSTANT RVAL (I "0"))))))) ((I "1") ((CONSTCASE "v1" (default ((MKCONSTANT RVAL (I "1")))) ((I "1") ((MKCONSTANT RVAL (I "0"))))))) ((I "2") ((CONSTCASE "v1" (default ((MKCONSTANT RVAL (I "1")))) ((I "2") ((MKCONSTANT RVAL (I "0"))))))))))
    (defun (NS (EqOrd Prelude) (DN "==" (UN "==_Eq_Integer"))) ("v0" "v1") ((DECLARE "v2") (START) (OP "v2" (EQ (Integer)) "v0" "v1") (CONSTCASE "v2" (default ((MKCONSTANT RVAL (I "0")))) ((I "0") ((MKCONSTANT RVAL (I "1")))))))
    (defun (NS (EqOrd Prelude) (DN "==" (UN "==_Eq_Char"))) ("v0" "v1") ((DECLARE "v2") (START) (OP "v2" (EQ (Char)) "v0" "v1") (CONSTCASE "v2" (default ((MKCONSTANT RVAL (I "0")))) ((I "0") ((MKCONSTANT RVAL (I "1")))))))

**Comment by Z-snails** [comment]
Ah, that makes sense thanks.
