### ISSUE TITLE
Nix flake output `apps` is malformed

### ISSUE THREAD

**Issue by claymager** [idris-lang/Idris2#1212]
`nix flake show ./.` fails with an EvalError.

This could be fixed with a block like this:
```nix
{
  apps = {
    emacs-dev = {
       type = "app";
       program = "${text-editor.emacs-dev}/bin/emacs-dev";
    };
  };
}
```

but I'm not sure what `apps` offers us, if we're already offering emacs packages.
`nix run .#emacs-dev` works just fine without it.

**Comment by gallais** [comment]
cc @guilhermehas

**Comment by guilhermehas** [comment]
I created a pull request #1213 to remove apps because they are not necessary.
