### ISSUE TITLE
Improve out-of-scope error messages by listing existing similar names

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#1230]
# Steps to Reproduce

```haskell
record R where
  constructor MkR
  field : Nat

myRec1 : R
myRec1 = MkR 3
```
works. But the following example
```haskell
record R where
  constructor MkR
  field : Nat

myRec1 : R
myRec1 = MkR 3

mkRec2 : R
myRec2 = MkR 3
```
fails with error "No type declaration for Main.myRec2."
Tested on 71abc8e33

# Expected Behavior

Second example should work.

**Comment by gallais** [comment]
For anyone reading and wondering what the issue is: in

```idris
mkRec2 : R
myRec2 = MkR 3
```

there is a typo in the type declaration: `mkRec2` instead of `myRec2`.

**Comment by gallais** [comment]
This has been one of my pet peeves for a while so let me reopen this
as a feature request.
