### ISSUE TITLE
Access modifiers of definitions overwrite forward definitions

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1236]
# Steps to Reproduce
```idris
$ cat Mutual.idr
module Mutual
private
data Foo : Type 

public export
data Foo : Type where
------------------------------
$ cat Import.idr
import Mutual

x : Foo

```
# Expected Behavior
Type-checking `Mutual.idr` should report an error because the access modifiers are incompatible.

# Observed Behavior

The latest definition overwrites the access modifier, and `Import.idr` type-checks fine.

**Comment by gallais** [comment]
I'm going to go ahead and tag this as good first issue because I assume it's something silly
like overwriting the existing value with a record update instead of making sure it's not set yet.

**Comment by gallais** [comment]
If only we had a gadget that allowed us to express that something is the default
without conflating it with the default value it takes. :thinking: 

http://gallais.github.io/blog/ceci-pas-default

**Comment by gallais** [comment]
Yeah I think it'd be nice to complain if there are conflicting declarations which means changing
the merge strategy to take into account lack of value vs. value that happens to equal the default.

**Comment by emdash** [comment]
Is this still an issue? It seems like we get correctly warned now...
