### ISSUE TITLE
Allow implicit parameters and multiplicities in parameter blocks

### ISSUE THREAD

**Issue by andrevidela** [idris-lang/Idris2#1242]
Recently I've been needing parameter blocks a lot and I noticed that I could not declare them with a custom multiplicity nor could I make the arguments implicit. While I suspect the multiplicity problem is a simple oversight, I think there is a bit more to talk about implicit parameter blocks.

Ideally I would like something like this:

```
parameters {auto m : Monoid a} 
           {0 proof1 : {v : a} -> (<+>) m v (neutral m) === v}
           {0 proof2 :  {v : a} -> (<+>) m (neutral m) v === v}
           {0 proof3 : (<+>) m ((<+>) m a b) c = (<+>) m a ((<+>) m b c)}
```

Now the question is, should we support the following?

```
parameters {auto m : Monoid a
           ,0 proof1 : {v : a} -> (<+>) m v (neutral m) === v}
           ,0 proof2 :  {v : a} -> (<+>) m (neutral m) v === v}
           ,0 proof3 : (<+>) m ((<+>) m a b) c = (<+>) m a ((<+>) m b c)}
```

Since this is how explicit parameters are declared?

The arguments for supporting it is that it would be consistent with explicit parameter declaration. The argument for _not_ supporting it is that nowhere else you can use this syntax to declare parameters, and I would argue this is also a bit awkward for explicit parameters since `(a, b c, : Nat)` is forbidden when declaring parameter arguments.

Additionally supporting it would mean that we should allow this interleaving of explicit and implicit arguments:

```
parameters {a : Ty, b : Sy} (f : a %% b, g : a %% b) {check : (x : Ty) -> f $$ x = g $$ x, auto m : Monad c}
```

I don't have a strong opinion either way but I would like to know what people think about it. I would tend toward not supporting the current `,`-syntax but that would break backward compatibility.

@Russoul  maybe we can unify that with your proposal for a new syntax for implicit/auto parameters?

**Comment by Russoul** [comment]
You mean this one: #1181 ?

**Comment by andrevidela** [comment]
Yes

**Comment by gallais** [comment]
> I would tend toward not supporting the current ,-syntax but that would break backward compatibility.

I agree. I think the syntax should be exactly the same (save for arrows) as
the one used in the telescopes in types as these are essentially the same.

**Comment by Russoul** [comment]
Under my proposal your last snippet with interleaved Pi flavours would map to something like(`@` are optional):
```
parameters $(a : Ty) 
           $(b : Sy) 
           @(f : a %% b) 
           @(g : a %% b)
           $(check : (x : Ty) -> f $$ x = g $$ x)
           #(m : Monad c)
```
I haven't got much feedback on it though. Ohad liked the `@$#` thing in Pis but disliked the idea of using `:` for named args.
Though any proposed symbols are provisional, more important question is whether the idea itself is sensible and improves on the current syntax.

**Comment by andrevidela** [comment]
that looks very sensible to me!
