### ISSUE TITLE
Separate testing from bootstrapping

### ISSUE THREAD

**Issue by wchresta** [idris-lang/Idris2#125]
Currently, `make bootstrap` will both build and test Idris2. The [test command is part of `bootstrap.sh`](https://github.com/idris-lang/Idris2/blob/master/bootstrap.sh#L49) which is also used to build.

To be able to separate building from testing for automatic builds (like the [nix expression we are working on](https://github.com/NixOS/nixpkgs/pull/88645)), it would be very useful to be able to expose bootstrapping/building and testing separately.

This request is to split `make bootstrap` into two targets: `bootstrap-build` and `bootstrap-test` such that they can be called as separate stages in automatic builds.

**Comment by edwinb** [comment]
This sounds like a good idea to me, especially if it helps with packaging, and wouldn't interfere with the build process anywhere else. It is likely to be low priority for the moment though, I'm afraid, but you're welcome to go ahead and do it if it helps you!
