### ISSUE TITLE
Harmonizing HasLength

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris2#1258]
Currently `HasLength` is defined both [in the core](https://github.com/idris-lang/Idris2/blob/master/src/Core/TT.idr#L438) and [in contrib](https://github.com/idris-lang/Idris2/blob/master/libs/contrib/Data/List/HasLength.idr), but there are quite a few differences:

* The two versions have different order of indices, core has `Nat -> List a ->`, whereas contrib's version has `List a -> Nat ->`. It seems the latter is more useful for partial application.
* Core seems to have more functions supplied, but the two sets don't overlap fully.
* Core defines a `SizeOf` record to hide the size relation, whereas contrib uses the `Subset` mechanism and a couple of views on top of it.

I think it would be nice to have one canonical version that could perhaps be moved to `base` and duplicated within `libraries`. Question is, which version do we use as a baseline?

**Comment by gallais** [comment]
`Subset` is pretty verbose so I'd be in favour of having `SizeOf` (which could
very well be defined in terms of `Subset`, mind you).

**Comment by clayrat** [comment]
Looks like this has been dealt with in https://github.com/idris-lang/Idris2/pull/2844 ?
