### ISSUE TITLE
\NUL characters inside of strings lead to truncation

### ISSUE THREAD

**Issue by cypheon** [idris-lang/Idris2#1260]
`\NUL` characters inside of strings are not handled correctly and sometimes
lead to truncation.

# Steps to Reproduce

Create the file `NulStrings.idr`:

```idris
import Data.Buffer

s : String
s = "string\NUL containing a NUL character"

main : IO ()
main = do
  printLn s
  printLn $ stringByteLength s
```

It is important to put the code inside a file, as REPL behaviour is slightly
different (see below).

Run:

    idris2 --exec main NulStrings.idr                                                                                                   :( 130 21-04-02 - 10:36:35

# Expected Behaviour

    "string\NUL containing a NUL character"
    34

# Observed Behaviour

    "string"
    6

## Note Regarding REPL Rehaviour

On the REPL, strings are not truncated (probably because no step to->from TTC
occurs), but the `stringByteLength` error can be verified:

    Main> :module Data.Buffer
    Imported module Data.Buffer
    Main> :exec printLn $ "abc\NULdef"
    "abc\NULdef"
    Main> :exec printLn $ stringByteLength "abc\NULdef"
    3

**Comment by gallais** [comment]
> On the REPL, strings are not truncated

They actually are AFAICT. The `:exec printLn "abc\NULdef"` you're testing is first showing the
string & then `putStrLn` it. `show` is correctly escaping the `\NUL` character.

If you try `:t "abc\NULdef"` instead you only get `fromString "abc` back.

So my understanding is that the lexer for string literals should escape `\NUL` characters?
Ping @andrevidela

**Comment by andrevidela** [comment]
I'm not quite sure what the correct behaviour should be in that case. The lexer already escapes the `NUL` sequence and inserts it into the string as a _control character_ (https://github.com/idris-lang/Idris2/blob/71abc8e33b17adba61173f3ce1c7564a1d9ce4dc/src/Libraries/Text/Lexer.idr#L342-L357). But maybe the correct behaviour would be to error when parsing. I just checked Scala Swift and Python and that's what they seem to be doing.

Also I tried 

```
:exec putStr "Hello \BEL"
```

and my computer isn't beeping, so the feature is clearly broken :)

@cypheon since you're using `stringByteLength` instead of `length` I'm guessing you're having a special use-case for this? What is it?

**Comment by cypheon** [comment]
@gallais Thanks for looking into this. Yes, I deliberately used `show` (via `printLn`) to demonstrate that the truncation happens _before_ the actual output (because I think there is a different issue at play when `putStr`ing a String containing NUL characters [1], and I didn't want to touch that one _yet_).

So my point is that the _value_ of the string (as written to and later read from the TTC file) is already wrong (i.e. truncated), before the program can do anything with it (even before it is compiled to Chez). I checked this with a hex dump of the TTC file and there you can see, that the part after the NUL is not included in the TTC. See an excerpt here: [ttc-hexdump2.txt](https://github.com/idris-lang/Idris2/files/6276594/ttc-hexdump2.txt)
 (I used the string `AAAAAAAA\NULXXXXXXXX` for this one to make the grep easier).

Maybe this piece of code shows the core of the issue a bit better:

```idris
module NulStr

s : String
s = "ABC\NULXYZ"

main : IO ()
main = putStrLn $ show $ map ord $ unpack s
```
`idris2 --exec main NulStr.idr` prints: `[65, 66, 67]`
Where I would expect it to print: `[65, 66, 67, 0, 88, 89, 90]`

I think the question really comes down to "Are NUL characters allowed inside an Idris `String`?" I would argue "yes of course", because
a) Idris is not C ;)
b) The lexer already correctly excapes/parses them
c) In many places they already are (if you construct a string with a NUL character at runtime, e.g. using 'pack') `s = pack $ map chr [65, 66, 67, 0, 88, 89, 90]` in the code given above, the example works.

@andrevidela Tbh I don't have a specific use case for NUL characters inside strings right now. I just stumbled upon what feels like an inconsistency (`show`ed Strings do not equal the source string).

[1]: The separate issue I mentioned is more an inherent property of the Chez->C FFI: Whereas Chez strings are represented in memory as an array of (I think UTF-32) characters with an explicit length (and thus may contain NULs), in the C FFI they get translated to a sequence of bytes (which C expects to be NUL-terminated, so they can never _contain_ a NUL). So I first wanted to take care of getting the string value correctly _inside_ the program and the next (more involved) step would be to figure out a way how (or if) the C support functions could/should be extended to take a pair of a byte-pointer and a length instead of just a byte-pointer to a NUL-terminated string. That would allow to get the value correctly _out_ of the program.

**Comment by andrevidela** [comment]
I agree with you but I think it's a bit more complicated than this. Currently strings are grossly underspecified in Idris, do they support unicode characters? Are they null terminated? Do they support control characters? All those questions have different answers depending on the the backend you use and your lenience for "support". For example I would argue strings don't support unicode characters correctly. Using a function `fn x = putStrLn "\{x} : \{show (length x)}` you see that lengths of characters is inconsistent with unicode glyphs

```
Main> :exec fn "e\x301"
é : 2
Main> :exec fn "é"
é : 1
Main> :exec fn "👨‍👨‍👧‍👧"
👨‍👨‍👧‍👧 : 7
```

This makes Idris strings closer to simple "bags of chars" than legitimate strings. In that setting should `\0` be part of the string or not? What if you're using the C backend?

Those questions lead me to believe that we should:
1. Be more thorough with the specification of strings.
2. Support null-terminated strings as a separate type.
3. (extra credit: Support unicode glyphs and have a unicode codepoint view for strings)

Number 1 and 3 are extremely difficult to achieve but I think nº2 is a good start. It would clear up this particular problem and would make the interop with cStrings a lot more predictable. In essence a PR that would implement nº2 would:
- Always allow \NUL and other control characters in strings.
- Allow to convert from `String` into `CString` which would use `\0` as the terminator for strings.

Under those conditions, `String = CString` when using the C backend, it would probably be a separate issue to support non-null-terminated strings in C (and correct support for unicode)
