### ISSUE TITLE
Cast from Char to Bits32/Bits64

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#1270]
The only way to get a `Bits64` or `Bits32` from a `Char` is by going through `Int`, which on some backends truncates it (`Char` is unsigned 32 bit int, `Int` is sometimes a 32 bit signed int, which can't hold the highest values of `Char`).

This might want to wait for https://github.com/idris-lang/Idris2/pull/1211.

**Comment by stefan-hoeck** [comment]
I'll try and work some more on #1211 during the next week. Do you happen to know, which backends represent `Int` with only 32 bits? The Scheme and Javascript backends use 64 bits.

**Comment by Z-snails** [comment]
From super quick skim reading of the refc source code it appears refc uses 32 bit ints, and possibly some of the out-of-tree backends too.
