### ISSUE TITLE
How to modify emacs-with-idris to disable the bell?

### ISSUE THREAD

**Issue by VladimirMarko** [idris-lang/Idris2#1271]
As a newcomer to both Emacs and NixOS, I have a burning question: How do I turn off the bloody bell?

As `README.md` suggests I open Emacs with `nix run github:idris-lang/Idris2#emacs-with-idris idrisCode.idr`.

(BTW, if I just run `nix profile install github:idris-lang/Idris2` first, the suggested `nix run idris-lang/Idris2#emacs-with-idris idrisCode.idr` does not work, because `idris-lang/Idris2` is not registered in the flake repository.)

Now there is a bell that sounds for example if you enter an invalid keyboard shortcut. I believe the source is Emacs itself.

I tried creating a `~/.emacs.d/settings/bell.el` file containing just the line `(setq ring-bell-function 'ignore)`, but this does not seem to do anything.

I believe that I could create a nix script that starts with `Idris2/nix/text-editor.nix` and adds the bell-silencing option to it, but I do not quite know where to begin.

**Comment by gallais** [comment]
Strangely enough I don't have this problem on my personal laptop but I did experience
it on my work laptop. So, just for you because I sympathise with the struggle, I extracted
myself from the sofa and stumbled into my office.

Putting this in your `~/.emacs` should solve that problem:

```elisp
;; do NOT ring that bell
(setq ring-bell-function 'ignore)
```

**Comment by VladimirMarko** [comment]
Thank you for your ardunous physical effort.

However I believe that putting it in `~/.emacs` is semantically the same as putting it in `~/.emacs.d/settings/whatever.el`.

Either way, I tried it and it changed nothing - my Emacs keeps bleeping.

**Comment by unsafeDrop** [comment]
> Now there is a bell that sounds for example if you enter an invalid keyboard shortcut.

Is the PC Speaker caused the problem? If so, how about remove the corresponding kernel module.

**Comment by ohad** [comment]
At the risk of also receiving much sarcasm: Did you tell emacs to load `settings/whatever.el`?

I'd appreciate it if you just say 'of course' rather reply sarcastically nonetheless, please.

**Comment by claymager** [comment]
I know Nix, not emacs.

`emacs-with-idris` hides any emacs in your environment, replacing it with a version of that also has `idris2-mode`.
It then provides the initial emacs arguments `-q -l Idris2/nix/init.el`. Does that prevent emacs from sourcing `~/.emacs`?
