### ISSUE TITLE
Tests fail because of output line ordering

### ISSUE THREAD

**Issue by hyphenrf** [idris-lang/Idris2#1279]
expected outputs in the chez (and node) parts of the test suite are nonintuitively structured in the general form of:
```
<program output>
<compiler message>
<interpreter prompt>
```
or concretely like so:
```
[1, 2, 2, 4, 3, 6, 4, 8, 5, 10]
1/1: Building Total (Total.idr)
Main> Main> Bye for now!
```
while the actual output is (as one would expect):
```
1/1: Building Total (Total.idr)
[1, 2, 2, 4, 3, 6, 4, 8, 5, 10]
Main> Main> Bye for now!
```
This causes 45 tests to fail

**Comment by Russoul** [comment]
I was starting to think we'd never see this come up. If I remember that right, it is a one-line fix. stdout of the Idris executable process has to be flushed before running the compiled code (what currently does not happen). The fix will entail quite a huge diff.

**Comment by gallais** [comment]
There's #871 and #1136 seems like the fix @Russoul is mentioning but
the build is broken so... :man_shrugging:

**Comment by gallais** [comment]
Please try again with the latest commit now that #1136 has been merged! :crossed_fingers:

**Comment by hyphenrf** [comment]
awesome! my setup is exactly like nmeum's so I have good confidence it'll work
testing it

**Comment by hyphenrf** [comment]
(I didn't get to report back then, sorry! Yes, the patch works flawlessly)
