### ISSUE TITLE
Usage site of an interface with 2 functions selects the wrong function

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#1288]
Code for package `hashable`: https://github.com/Z-snails/Idris2-hashable
Code for package `hashmap`: https://github.com/Z-snails/idris2-hashmap
Relevant code for package `hashmap`: https://gist.github.com/Z-snails/27012d217080e1926f571857a7235aaa

# Steps to Reproduce

```idris
-- pkg: hashable, module: Data.Hashable

public export
interface Hashable a where
    hashWithSalt : Bits64 -> a -> Bits64
    hash : a -> Bits64
    hash = hashWithSalt defaultSalt
```

```idris
-- pkg: hashable, module: Data.HashMap

export
empty : Eq k => Hashable k => HashMap k v
empty = MkHM (==) hashWithSalt Internal.empty
```

```idris
-- file: test01.idr

import Data.HashMap

main : IO ()
main = go max_n empty
  where
    max_n : Int
    max_n = 10

    go : Int -> HashMap String Int -> IO ()
    go 0 hm = putStrLn "finished"
    go n hm = do
        str <- getLine
        let hm' = insert str n hm
        go (n - 1) hm'
```

# Expected Behavior

Inserts 10 strings into the hashmap, without error.

# Observed Behavior

Runtime error:

```
Exception in string->list: 14695981039346656037 is not a string
```

The number `14695981039346656037` is used in the `hashable` package as the default salt, used in the implementation of `hash` in terms of `hashWithSalt`.

# Compiled output

```scheme
;; from Data.Hashable
(define DataC-45Hashable-__Impl_Hashable_String
  (lambda ()
    (vector
      0
      (lambda (arg-3918)
        (lambda (arg-3919)
          (DataC-45Hashable-hashWithSalt_Hashable_String arg-3918 arg-3919))) ;; (1)
      (lambda (arg-3920)
        (DataC-45Hashable-hash_Hashable_String arg-3920)))))

;; from test01.idr
(define DataC-45HashMap-empty
  (lambda (arg-0 arg-1 arg-2 arg-3)
    (vector
      0
      (let ((sc0 arg-2))
        (let ((e-1 (vector-ref sc0 1)))
          (lambda (arg-4)
            (lambda (arg-5)
              ((e-1 arg-4) arg-5)))))
      (let ((sc0 arg-3))
        (let ((e-2 (vector-ref sc0 2))) ;; (2)
          (lambda (arg-4)
            (lambda (arg-5)
              ((e-2 arg-4) arg-5)))))
      (DataC-45HashMapC-45Internal-empty 'erased 'erased))))
```

Note that in the implementation of `Hashable String`, `hashWithSalt` is the first element in the vector (see (1)), whereas at the use site, the second element is extracted (see (2)).

**Comment by gallais** [comment]
Any chance we can have a self-contained file reproducing the bug?

**Comment by Z-snails** [comment]
So I put it all in one [file](https://gist.github.com/Z-snails/00a58f936e2cdcd4c1e76f4969db9cb9) and it suddenly started working.

Next I put it in multiple [files](https://gist.github.com/Z-snails/e1a1c5f41f7603c4b078193acefdf3f5) and it still works.

Even when I put Hashable in it's own [package](https://gist.github.com/Z-snails/bfafc55eb3d6bf09e443f28c4c3e2334) it still works

And when I put HashMap also in it's own [package](https://gist.github.com/Z-snails/45afc66dc357fdec23587848e08b6b3e) (hashable is unchanged) it still works.

But the error still happens with the test in the `hashmap` [repo](https://github.com/Z-snails/idris2-hashmap/blob/main/tests/test01.idr).

Sorry I couldn't get a smaller example.

**Comment by stefan-hoeck** [comment]
I had a look at your repos. Could it be, that the `hashable` package is not available when running your `hashmap` tests? After cloning your repos, installing both `hashable` and `hashmap` and setting up `tests.ipkg` (see below) to have these two packages as a dependency, everything worked without error on my machine.

Here's the `tests.ipkg` I used (I renamed `tests/test01.idr` to `tests/Main.idr`):

```
package hashmap-tests

version = 0.1.0

sourcedir = "tests"

main    = Main

executable = runTest

depends = hashable >= 0.1.0
        , hashmap >= 0.1.0
```

**Comment by stefan-hoeck** [comment]
You know, gallais, I never really got the meaning of that "eyes" emoji. :-)

**Comment by Z-snails** [comment]
@stefan-hoeck have you been able to reproduce the error when running it as
`base64 /dev/random | idris2 -p hashable -p hashmap --exec main test01.idr`?

If it was not available how could it compile that code, and not give a type error?
I really doubt it but maybe it's trying to use `Core.Hash` which has the `hash` and `hashWithSalt` the other way round, but I haven't included the idris2 package nor have I imported `Core.Hash`?

**Comment by stefan-hoeck** [comment]
`/dev/random` did not work on my system. With
`base64 /dev/urandom | idris2 -p hashable -p hashmap --exec main test01.idr` I got the output below. But maybe we are not using the same Idris2 commit? I'll update to the latest version and report back here.

```
10
YNC6J/j0FynhBc4mZvwYVlG8GUn4TRCZudaDA0EWo5dLj61UGWCdpbyS4cCUJ7AW0ueZO/fmEu/0
9
Wz7tciKp+YBrLYYnoCTh/w+D7B7BowY0DyFs0DMLfip5cBeAW+w2iNXmRDSPVicjV65hoU0eahLe
8
LYUparL0NJsFLeSNDFbuJMfwwtNkIaUNfyqNAgK/qGy6Jo8m2JagPQM+yGCuC1iiJoMvZntUxKQz
7
E9xD+HdFP4drHdbtRHyIA4QZwRqiiI8ecwo8vZKQ5OK93z2P8X7f/X9D/wcHaC/nd6zORMli/KYL
6
VoV3Tf+HaPsWt4C5MhLFXDdNC6+ERCbl2lW9zHOqRRi3vdo0IV2pn30GKwoNo1UCtNH5yG2f4MQN
5
TGeGP4jD7zxW6ZmdpZHXsiYOc9xSSo++WL9WGW4QElEup2i6XaFX1Ta3qQGIQ6gvmhlDMD1Gd1XF
4
C1g0dGH2DjOAVVEYxur9GbaypQdt5OvoJIJhtl8owIHfmz81LgbOrQ+FMOwe/6CruY3wAmyB7M6O
3
VsbxqIZbQu+tldl1ARpJUqUu+WRp1BpFBIakm0CfyiLm5oJpXfMBmBpUjl64H1r5Olqzd4rGn833
2
kV0BDY5JYfD3aXAxxAY789xTgcWSXRfK/a4GfXLGNpLvGxHabDN2I0MsHrJHjC6PSrr18VH6p/jK
1
RCA1FUTjTPZysRmu2lwnQa9yUTxJ6G/T19eblNHNvVP531aJ+eIYEYNJcyKayDqpZCCGAOHnyVCe
finished
```

**Comment by stefan-hoeck** [comment]
Same result when using Idris2 commit c725b11c891b9f9f1e25ead66d9fc75a91b69836. As additional information: I'm running chez scheme 9.5.2 on NixOS.

**Comment by Z-snails** [comment]
I've just rebuilt idris2 with the latest commit ([c725b11](https://github.com/idris-lang/Idris2/commit/c725b11c891b9f9f1e25ead66d9fc75a91b69836)), rebuilt hashable and hashmap and added a ipkg to tests and it still has the same error: `Exception in string->list: 14695981039346656037 is not a string`.
I'm running chez scheme 9.5.4, but the same thing happens with the node backend.

Weirdly the other tests (eg [strmap.idr](https://github.com/Z-snails/idris2-hashmap/blob/main/strmap.idr)) works fine.

**Comment by Z-snails** [comment]
It appears to have fixed itself and I can't reproduce this error any more. I have absolutely no idea what I could have done to fix it but now it's working fine.

Is there any reason to keep this issue open?
