### ISSUE TITLE
Add windows to CI

### ISSUE THREAD

**Issue by RaoulHC** [idris-lang/Idris2#1293]
Many of the tests currently fail on windows (see [here](https://github.com/RaoulHC/Idris2/runs/2318215478)), these tests should be fixed and then windows tests can be added to the CI as it currently only bootstraps Idris.

# Steps to Reproduce
Run test suite on windows

# Expected Behavior
Test suite passes

# Observed Behavior
Test suite does not pass

**Comment by gallais** [comment]
AFAIK we (core devs) don't have access to a windows machine (and little knowledge
about windows at large). So help would be appreciated.

**Comment by melted** [comment]
I have Windows machines. But it might not be that useful because I have no failing tests locally.

**Comment by melted** [comment]
Hmm, there's that stdout commit that may have messed things up.

**Comment by melted** [comment]
I guess tests were never disabled for windows, it's just that they were moved out of the bootstrap and never added to the workflow. I'll put it in there so we can see the damage.

**Comment by melted** [comment]
Ok, it's not that bad, there's something wrong with a space in the node path, I don't have that failure locally, but a couple of node tests fail anyway. And it finds a C compiler so it tries to run the C tests. And a couple of Chez tests have regressed. I will disable testing for C (and Racket) on windows as they have never really been made to work there and try to fix the offending chez and node tests.
