### ISSUE TITLE
Implicit should not be accessible

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#1305]
# Steps to Reproduce

```haskell
ffff : {a:Nat} -> Nat
ffff = a
```
This code currently compiles under Idris 2.

# Expected Behavior

The code above should fail with "No such variable a" error message as in Idris 1

The correct source code is:
```haskell
ffff : {a:Nat} -> Nat
ffff {a} = a
```

**Comment by gallais** [comment]
I believe this is a feature rather than a bug?

**Comment by buzden** [comment]
It is intentional and is documented in the last paragraph [in the appropriate section](https://idris2.readthedocs.io/en/latest/tutorial/typesfuns.html?highlight=implicit#implicit-arguments).
