### ISSUE TITLE
Can't define linear append, complains about non-linear context.

### ISSUE THREAD

**Issue by kanashimia** [idris-lang/Idris2#1333]
Even tho Edwin clearly defines literally the same function [in his video](https://youtu.be/nbClauMCeds?t=1593) :100:  

Also totality check seems to be wrong? Probably needs a separate issue?

Tested v0.3.0 in nixpkgs, and master through `nix shell github:idris-lang/Idris2`, on NixOS.

#### Broken examples

```idris
> cat Main.idr
append : (1 xs : List a) -> (1 ys : List a) -> List a
append [] ys = ys
append (x :: xs) ys = x :: append xs ys

> idris2 -q Main.idr
Error: While processing right hand side of append. Trying to use linear name ys in non-linear context.

Main.idr:5:38--5:40
   |
 5 | append (x :: xs) ys = x :: append xs ys
   |                                      ^^

Main>
```

#### Working examples

```idris
> cat Main.idr
append : List a -> List a -> List a
append [] ys = ys
append (x :: xs) ys = x :: append xs ys

> idris2 -q Main.idr
Main> 
```

```idris
> cat Main.idr
append : (1 xs : List a) -> (1 ys : List a) -> List a
append [] ys = ys
append xs [] = xs -- without this line it complains about function not being total? but it is total???? 
append (x :: xs) (y :: ys) = x :: append xs (y :: ys)

> idris2 -q Main.idr
Main> 
```

**Comment by gallais** [comment]
The `(::)` constructor of `List` is not linear anymore (perhaps since we
removed linear subtyping? Can't remember).

You could define

```
data LinearList : Type -> Type where                                              
  Nil : LinearList a
  (::) : (1 _ : a) -> (1 _ : LinearList a) -> LinearList a
```

instead if you want to prove append linear.

**Comment by kanashimia** [comment]
Yeah it seems like it is because of the https://github.com/idris-lang/Idris2/pull/879
Oh well, it would be nice to make this work, should this issue be transformed into a feature request for multiplicity polymorphism, or a separate issue be made?
