### ISSUE TITLE
A parser issue (?) likely related to parsing of comments

### ISSUE THREAD

**Issue by Russoul** [idris-lang/Idris2#1345]
# Steps to Reproduce

Wrap the snippet into a file and run `idris2 filename.idr`
```
infixr 0 -->
(-->) : (Type -> Type) -> (Type -> Type) -> Type
```

# Expected Behavior

Type checks normally, without any errors.
Or alternatively, throws a parse error if `-->` is interpreted as a comment.

# Observed Behavior

`Uncaught error: Error: INTERNAL ERROR: filename.idr: File Not Found`

**Comment by SmiVan** [comment]
Tried the snippet in Idris 2, version 0.3.0, didn't get the `INTERNAL ERROR`, but got
```
Error: Parse error at line 1:1:
Couldn't parse declaration (next tokens: [infixr, literal 0, symbol (, end of input])
```
