### ISSUE TITLE
Use unification for proof search

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1346]
During proof search, at some point (before failing) try to use unification to make progress on the goal.

# Use case
Using contrib:
```idris
sak : (a,b,c : Nat) -> a + (b + c) = b + (a + c)      
sak a b c = Calc $
  |~ ?hole
  ~~ ?hole2 ...(?demo)
```
The type-checker now has enough information to uniquely fill both holes with the LHS and RHS.
It would be useful if the interactive proof-search command was able to fill these holes.

**Comment by gallais** [comment]
This is now fixed.
