### ISSUE TITLE
Enclosed: Minimal working IntelliJ syntax highlighting 🎁

### ISSUE THREAD

**Issue by kristleifur** [idris-lang/Idris2#135]
Here's a minimal working syntax highlighting schema for Idris 2, for Jetbrains' IntelliJ-based IDEs. I used the File Types schema mechanism to knock this together.

I'm unsure how best to share it. The File Type schema is simple enough, see below.

Would you like this cleaned up with nice instructions submitted as a PR somewhere, and if so, to the main Idris2 repo or somewhere else?

**How it works:**
This is very simple common-heuristics-and-keywords-based highlighting added through the IntelliJ settings UI. (I just mimicked the Emacs highlighting result rather than actually studying the language syntax/grammar so this is probably not complete.) Then _Export Settings_ to XML.  The XML file ought to be importable into IntellliJ-based IDEs through _File: Manage IDE Settings: Import Settings_.

**Delivery:**
Probably the ideal way to share this with the world is to make this into an IntelliJ plugin? That can then be expanded upon with deeper IDE integration? I haven't yet built and published a plugin so I don't yet know what the process entails. So meanwhile this is here in case it's useful to anyone.

[IntelliJ Idris2 File Type highlighting.zip](https://github.com/idris-lang/Idris2/files/4673374/IntelliJ.Idris2.File.Type.highlighting.zip)

**About:**
File navigation and project-level find and find-replace are rather powerful and fast in IntelliJ, so even if this is just the most shallow highlighting it's still surprisingly useful when hacking on Idris imo.

Screenshot, including the IntelliJ spelling/grammar-check wagging its tail in an amusing way:
<img width="955" alt="Screenshot 2020-05-24 at 11 16 57" src="https://user-images.githubusercontent.com/49295/82752800-1f1caf80-9db0-11ea-8243-f8a27df1c13b.png">
```xml
<filetype binary="false" description="idris2" name="idris2">
  <highlighting>
    <options>
      <option name="LINE_COMMENT" value="--" />
      <option name="COMMENT_START" value="" />
      <option name="COMMENT_END" value="" />
      <option name="HEX_PREFIX" value="" />
      <option name="NUM_POSTFIXES" value="" />
      <option name="HAS_BRACES" value="true" />
      <option name="HAS_BRACKETS" value="true" />
      <option name="HAS_PARENS" value="true" />
      <option name="HAS_STRING_ESCAPES" value="true" />
    </options>
    <keywords keywords="%default;constructor;data;do;else;export;if;import;module;record;then;where" ignore_case="false" />
    <keywords2 keywords="$;';+;++;-;-&gt;;:;::;&lt;-;&lt;|&gt;;=;==;=&gt;;\;|" />
    <keywords3 keywords="(;);[;];{;}" />
    <keywords4 keywords="_" />
  </highlighting>
  <extensionMap>
    <mapping ext="idr" />
  </extensionMap>
</filetype>
```

**Comment by gallais** [comment]
It's not clear to me how to act on this. Closing as it's probably out of step with the language now.

**Comment by kristleifur** [comment]
Makes sense, @gallais! It’s here as a point of reference and doesn’t need to be dangling open.
