### ISSUE TITLE
Idris2 type checker slower than Idris1

### ISSUE THREAD

**Issue by raffopazzo** [idris-lang/Idris2#1365]
While porting some code from an existing Idris1 project to Idris2, I found a case where the type checker in Idris2 is massively slower than Idris1. I managed to reproduce the issue with a simplified version of the code, pasted at the bottom. Please note that before compiling the snippet with Idris1 you need to change the relative order of definitions in the mutual block, by commenting and uncommenting the lines indicated in the snippet.

# Steps to Reproduce
Copy the code pasted below into `Test.idr` and load it with both Idris1 and Idris2.

For Idris1 I used
```sh
time (echo ':q' | idris Test.idr)
```
For Idris2 I used
```sh
time idris2 Test.idr --client ''
```

# Expected Behavior
Idris2 is at least as fast as Idris1

# Observed Behavior
Idris1 takes 3 seconds
Idris2 takes **13 minutes**
Incidentally, Idris2 is not even convinced that the programme is total, whereas idris1 is, but this is not the main issue.

# Test.idr
```idris
import Data.Vect

%default total

infixr 7 .:.
infixr 7 :::

data Ts: Nat -> (t: Type) -> Type where
  TBase: Ts Z t
  (.:.): t -> Ts n t -> Ts (S n) t

data Fs: Nat -> (t: Type) -> Type where
  FBase: Fs Z t
  (:::): (f: (String, t)) -> Fs n t -> Fs (S n) t

Show (Ts n String) where
  show TBase = ""
  show (x .:. xs) = show x ++ show xs

Show (Fs n String) where
  show FBase = ""
  show (x ::: xs) = show x ++ show xs

mutual
  -- Idris1 and Idris2 disagree where TsExpr and FsExpr
  -- must be defined relative to Record.
  -- So, use this version for Idris1 ...
{-TsExpr: Nat -> (t: Type) -> Type
  TsExpr n t = Ts n (Record t)
  
  FsExpr: Nat -> (t: Type) -> Type
  FsExpr n t = Fs n (Record t)
  -}

  data Record: (t: Type) -> Type where
    Tuple: TsExpr n t -> Record t
    NamedTuple: FsExpr n t -> Record t

  -- ... or this version for Idris2
  TsExpr: Nat -> (t: Type) -> Type
  TsExpr n t = Ts n (Record t)
 
  FsExpr: Nat -> (t: Type) -> Type
  FsExpr n t = Fs n (Record t)

  -- I need to explicitly specialise `Show` for
  -- both `Ts n (Record t)` and `Fs n (Record t)`
  -- and delegate to the specialisation for `String`
  -- in order to convince Idris1 that this is total.
  -- But it is not enough to convince Idris2.
  Show t => Show (Ts n (Record t)) where
    show xs = show (toStrings xs)
    where
      toStrings: TsExpr k t -> Ts k String
      toStrings TBase = TBase
      toStrings (x .:. y) = show x .:. toStrings y

  Show t => Show (Fs n (Record t)) where
    show xs = show (toStrings xs)
    where
      toStrings: FsExpr k t -> Fs k String
      toStrings FBase = FBase
      toStrings ((a, x) ::: y) = (a, show x) ::: toStrings y

  Show t => Show (Record t) where
    show (Tuple xs) = show xs
    show (NamedTuple xs) = show xs
```

**Comment by edwinb** [comment]
Wow, that's impressive for such a small program. You probably noticed, but it typechecks straight away if you remove the "%default total" so this must be something wrong in the totality checker - perhaps repeating some work a lot of times. Even non-total things shouldn't get into a loop like that!

**Comment by buzden** [comment]
> if you remove the "%default total" so this must be something wrong in the totality checker

The same thing was found in the #1277

**Comment by raffopazzo** [comment]
I think #645 is also related or even the same

**Comment by edwinb** [comment]
I just had another quick look at this. I think it's to do with the mutual block and having lots of mutual dependencies between functions. We don't do anything clever, just go through the functions in the order they happen to be in a Map, and exploring the size change graph ends up taking ages and probably repeating some work.

I don't know if I'll get a chance to dig deeper in the next few days, but hopefully I will. Just leaving this note in case I don't... of course if anyone else can spot a way to stop repeating work when exploring the graph, that's great too!

**Comment by edwinb** [comment]
Oh. It turns out, when we explore the graph, we just don't bother storing intermediate results so we end up calculating them over and over again!

As for why this is total in Idris 1 and not Idris 2, I don't immediately know. Idris 2 is certainly a bit more picky, in that it checks smaller arguments are of the same type. So some refinements on what it means to be 'smaller' are probably necessary.

**Comment by edwinb** [comment]
This is certainly what affects #645 too, but #1277 appears to be something else.
