### ISSUE TITLE
INTERNAL ERROR: Called `getCons` on something that is not a Type constructor

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#1366]
Today I started getting a new kind of error when checking the docs of [elab-util](https://github.com/stefan-hoeck/idris2-elab-util) against a recent version of Idris2. I tried to break this down to a smaller example, but so far to no avail. Anyway, when I typecheck the docs of the package mentioned above (`idris2 --type-check elab-util-docs.ipkg`) I get the following error:

```
11/15: Building Doc.Generic3 (src/Doc/Generic3.md)
Error: While processing right hand side of implGenericDocGeneric3Crazy. INTERNAL
ERROR: Called `getCons` on something that is not a Type constructor
```

Note that the above module typechecked fine until very recently.

I'll try an break this down to something smaller tomorrow. But probably someone already knows what the culprit might be here.

**Comment by gallais** [comment]
> Note that the above module typechecked fine until very recently.

This was introduced by the fix in #1340. Prior to that we were silently
failing when this function was used in a way that was breaking an assumption
and that lead to a coverage checking bug. So I decided to make the failure
explicit.

**Comment by stefan-hoeck** [comment]
Oh, this happens during coverage checking! I was led in a completely wrong direction by this error, since in my case it occurred in an elaborator script where I was invoking `Language.Reflection.getCons`, haha. So, here is a pretty small example:

```idris
public export
data NP : (ts : List Type) -> Type where
  Nil  : NP []
  (::) : (v : t) -> (vs : NP ts) -> NP (t :: ts)

public export
data NS : (kss : List $ List Type) -> Type where
  Z : (vs : NP ts) -> NS (ts :: tss)
  S : NS tss -> NS (ts :: tss)

data Funny : (a : Type) -> (f : Type -> Type) -> Type where
  A : List a -> f a -> Funny a f
  B : Funny a f

decode : NS [[List a, f a], []] -> Funny a f
decode (Z [a,b])  = A a b
decode (S (Z [])) = B
```

**Comment by gallais** [comment]
Shrunk down:
```idris
data D : List (List a) -> Type where
  C1 : D [ts]
  C2 : D [ts]

f : D [[List a]] -> Nat
f C1 = 0
f C2 = 0
```

It seems crucial that we have a parametrised type here rather than e.g. just:
* a type variable `a`
* a primitive value `"hi"`
* a primitive type `String`
* a defined type `Nat`

**Comment by gallais** [comment]
Edit: seems to be the same problem as in #1340 but for `Type` this time.

**Comment by gallais** [comment]
Well, I'm glad I turned this into an internal error and you uncovered it before the minor
release because it caught this other bug in the coverage checker

The fix means that the coverage checker is a bit more conservative and demands and an
additional `decode (S _)` clause. I think it's related to #1079 where the checker would
see the case is covered if only it were to case-split on the `_`.
