### ISSUE TITLE
Problem with Eta expansion

### ISSUE THREAD

**Issue by cxandru** [idris-lang/Idris2#1370]
I have a puzzling error trying to port https://github.com/statebox/idris-ct/blob/master/idris2/Idris/TypesAsCategory.idr to Idris2. I can't seem to get a term for the following type, Refl ought to work and is actually what is returned by Proof Search, but leads to an error, which in any case does not seem to be correct. The expected type of the term is '\x => f x = x', so eta-expansion.

# Steps to Reproduce
https://gist.github.com/cxandru/0f591ba8f0e9b3176a34fe13bee9c52c
```Idris
identity : (a : Type) -> a -> a
identity a = id

rightIdentity :
  (a, b : Type )
  -> (f : a -> b)
  -> (identity b) . f = f
rightIdentity a b f = Refl
```
# Expected Behavior
Typechecks
# Observed Behavior
Error: While processing right hand side of rightIdentity. When unifying f = f and identity b . f = f.
Mismatch between: b and a.
# Discord link
https://discord.com/channels/827106007712661524/836903399932690482/838722292040466433

**Comment by gallais** [comment]
`getEtaType` picks up `b` from the application `identity b (f x)` and the ill typed
`\ (x : b) => f x` is generated on the RHS.
