### ISSUE TITLE
Parse error for ipkg version number

### ISSUE THREAD

**Issue by joelberkeley** [idris-lang/Idris2#1373]
If I follow [the instructions](https://idris2.readthedocs.io/en/latest/reference/packages.html#package-descriptions) for making an ipkg file starting
```
package test
version = 0.1
```
when I run
```
idris2 --build spidr.ipkg
```
I get
```
Uncaught error: Parse error (Lex error at (1, 10) input: 0.1
)
```
I don't get an error if I enclose the version identifier in quotes, but that's explicitly not what the docs say
> version = \<version number\>, a version number, which must be in the form of integers separated by dots (e.g. 1.0, 0.3.0, 3.1.4.1.5 etc)

**Comment by stefan-hoeck** [comment]
The new version numbers have been introduced rather recently (in #1134), therefore the Idris2 commit you are using to build your package might still be using the old parser for version numbers. When I try to build your spidr project with a recent build (actual master), I get a deprecation warning about using an outdated version format, and when I change to an unquoted version number, everything is fine (well, it doesn't build, but I assume it's still work in progress) :-).

**Comment by joelberkeley** [comment]
thanks @stefan-hoeck. I've also found the option to view the _stable_ version of the docs.
