### ISSUE TITLE
Pattern matching on records broken

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#1376]
# Steps to Reproduce
```idris
$ cat foo.idr
record Foo where
    constructor MkFoo
    bah : String
    baz : Bits64

unFoo : Foo -> String
unFoo (MkFoo{bah}) = ""
$ idris2 foo.idr
Error: While processing left hand side of unFoo. When unifying Bits64 -> Foo and Foo.
Mismatch between: Bits64 -> Foo and Foo.

test.idr:7:8--7:18
 3 |     bah : String
 4 |     baz : Bits64
 5 | 
 6 | unFoo : Foo -> String
 7 | unFoo (MkFoo{bah}) = ""
```
# Expected Behavior
Type checks fine.
# Observed Behavior
Throws an error.
I don't think it used to do this, also it works when you don't match on any arguments
```idris
unFoo : Foo -> String
unFoo (MkFoo{}) = ""
```

**Comment by Z-snails** [comment]
Probably related issue, if you match on the second argument to `MkFoo`, then you get a different error.
```idris
$ cat foo.idr
record Foo where
    constructor MkFoo
    bah : String
    baz : Bits64

unFoo : Foo -> String
unFoo (MkFoo{baz}) = ""
$ idris2 foo.idr
Error: While processing left hand side of unFoo. baz is not a valid argument in MkFoo.

test.idr:7:8--7:18
 3 |     bah : String
 4 |     baz : Bits64
 5 | 
 6 | unFoo : Foo -> String
 7 | unFoo (MkFoo{baz}) = ""
```

**Comment by buzden** [comment]
Well, isn't `_` forgotten in the original example? I mean, 

```idris
record Foo where
    constructor MkFoo
    bah : String
    baz : Bits64

unFoo : Foo -> String
unFoo (MkFoo{bah, _}) = ""
```

typechecks

**Comment by CodingCellist** [comment]
Yes, @buzden is correct afaik. You could also obtain this through interactive editing:
```idris
unFoo : Foo -> String
unFoo x = ?unFoo_rhs
```

Case-splitting on `x` produces
```
unFoo : Foo -> String
unFoo (MkFoo bah baz) = ?unFoo_rhs_1
```
which type-checks fine, even if you write the arguments to `MkFoo` as `{bah, baz}`

**Comment by Z-snails** [comment]
Oh, I thought just matching on one was allowed, like in Haskell. But anyway the second example is definitely an error/misleading message.

**Comment by gallais** [comment]
> But anyway the second example is definitely an error/misleading message. 

The notation for names arguments is ambiguous so Idris cannot tell whether you
meant to bind the implicit argument `baz` (in which case it's invalid) or whether
you were using the named application syntax.

This is related to #965
