### ISSUE TITLE
expected reduction of DPair.fst

### ISSUE THREAD

**Issue by alrunner4** [idris-lang/Idris2#1401]
Perhaps this is silly, but it seems like DPair.fst should reduce?

# Steps to Reproduce
```
import Data.HVect
import Data.Vect

neutral: (props: Vect k (t ** Monoid t)) -> HVect (map fst props)
neutral Nil = Nil
neutral ((t**monoid)::ts) = neutral @{monoid} :: neutral ts
```

# Expected Behavior
Interfaces+DPairs, a handy existential?

# Observed Behavior
```
1/1: Building Builder (Builder.idr)
Error: While processing right hand side of neutral. Can't solve constraint between: t and fst (MkDPair t monoid).
```

**Comment by ohad** [comment]
If it helps with diagnosis, using the projection `(.fst)` seems to work fine, as in:
```idris
import Data.HVect
import Data.Vect

neutral : (props: Vect k (t ** Monoid t)) -> HVect (map (.fst) props)
neutral Nil = Nil
neutral ((t**monoid)::ts) = neutral @{monoid} :: neutral ts
```

IIRC, the real name is the one with dots `.fst` but we do some additional stuff to also have the name without the dot `fst`.

**Comment by Russoul** [comment]
ziman added definitional equality for `(.x)` and `x`, so you can safely use them interchangeably in type-level computations.

The problem here is actually yet another instance of #621 :sweat_smile:
Qualifying `fst` solves the problem:
```Idris
import Data.HVect
import Data.Vect

neutral: (props: Vect k (t ** Monoid t)) -> HVect (map DPair.fst props)
neutral Nil = Nil
neutral ((t**monoid)::ts) = neutral @{monoid} :: neutral ts

```

**Comment by ohad** [comment]
Oh dear, unbound implicits at work again :D.

**Comment by alrunner4** [comment]
Aha. I suspected it wasn't really a reduction issue after thinking about it some more last night, but I overlooked that `fst` isn't directly applied in `map fst props`. Always the `map` that gets me on this one.
