### ISSUE TITLE
Totality annotation for data type definitions

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1404]
So that the following should produce an error:
```idris
total
data Foo : Type where
  AFoo : (Foo -> Foo) -> Foo

-- Foo is not total, not strictly positive
```

Currently we have to add a `%default` directive:

```idris
%default total

data Foo : Type where
  AFoo : (Foo -> Foo) -> Foo
```

But this directive affects the entire file, rather than just the definition in question.

**Comment by ngeiswei** [comment]
I also that sort of cases in mind

```idris
data NullNat : (n : Nat) -> Type where
  MkNullNat : (n = Z) -> NullNat n
```

**Comment by gallais** [comment]
`NullNat` is perfectly fine: it is the predicate that certifies that a natural number is `Z`.
