### ISSUE TITLE
JS backend maintenance

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#1416]
After the tail-call optimization issue in #1400, I think I gained a pretty clear picture about how the JS backends in Idris are implemented. I therefore would like to volunteer to take over maintenance of the Idris2 JS backends (if the orginial author, @rbarreiro , is OK with this). Personally, I think these backends are a strong selling point for Idris, therefore, if possible, I'd like to keep them as a part of the main Idris2 code base. Below is a list of things I am could imagine working for the next couple of weeks / months:

- [x] Cleanup and document the JS code.
- [x] Look into the possibilities of tail-call optimizations and document, with examples, the limitations.
- [x] Use the new `ConInfo` tags to optimize representations of enums, records, and (possibly) list-like types.
- [x] Experiment with a more flexible representation for large integers (`Int64`, `Bits64`, `Integer`): It should be possible for these to switch between `Number` for small values and `BigInt` for larger values, thus improving both FFI interop and (after some profiling) performance.
- [x] Look into possibilities to allow the definition of properly named toplevel functions that can be called from JS code.

Please let me know, what you think of this.

**Comment by bamboo** [comment]
That's great news, @stefan-hoeck. Please keep in mind there are other backends relying on the imperative expression representation. :)

**Comment by stefan-hoeck** [comment]
That's good to know, @bamboo. Do you happen to know, which ones those are? This would allow us to get in touch with maintainers before changing parts of that representation.

**Comment by Russoul** [comment]
Here is a list of known backends and their authors, if you haven't seen it already: https://github.com/idris-lang/Idris2/wiki/External-backends.
But I have no idea which of those rely on the imperative representation. At least mine (Lua) doesn't

**Comment by stefan-hoeck** [comment]
Thanks @Russoul . I had a quick look at the backends in the list you linked, and only @bamboo 's [dart backend](https://github.com/bamboo/idris2dart) seems to be using the imperative expressions from the JS backends. Anybody, please correct me if I've overlooked something.

**Comment by gallais** [comment]
I'm guessing some of the checkboxes in the original message can be ticked.
Maybe even all of them now that we also have `%noMangle`

**Comment by stefan-hoeck** [comment]
I think we can close this. The one thing I'm not yet sure about is how and if to optimize non-tail-recursive code. Mutually tail-recursive functions are optimized correctly. There might also be some optimizations possible for some of the integer primops, but this seems not to be very urgent at the moment.

**Comment by gallais** [comment]
Right and we already have an issue specifically about tail recursion. :+1:
