### ISSUE TITLE
Order of Non-Overlapping Clauses in Function Defintiion Should Not Matter

### ISSUE THREAD

**Issue by stephen-smith** [idris-lang/Idris2#1421]
# Steps to Reproduce

* Idris 2, version 0.3.0-881a5e7fb

clause_order_good.idr:
```idris
plus2 : Nat -> Nat
plus2 = S . S

plus2Injective : (x, y : Nat) -> Equal (plus2 x) (plus2 y) -> Equal x y
plus2Injective Z Z Refl = Refl
plus2Injective (S n) (S n) Refl = Refl
plus2Injective Z (S _) _ impossible
plus2Injective (S _) Z _ impossible
```

clause_order_bad.idr
```idris
plus2 : Nat -> Nat
plus2 = S . S

plus2Injective : (x, y : Nat) -> Equal (plus2 x) (plus2 y) -> Equal x y
plus2Injective Z Z Refl = Refl
plus2Injective Z (S _) _ impossible
plus2Injective (S _) Z _ impossible
plus2Injective (S n) (S n) Refl = Refl
```

Note that the only difference is the order of the clauses in `plus2Injective`, the contents of each clause is identical.  Note also that the clauses do not overlap at all.

# Expected Behavior

Both files type check and compile to very similar function.

# Observed Behavior

clause_order_good.idr is accepted.  clause_order_bad.idr is rejected with "Error: plus2Injective is not covering." and "Missing cases: plus2Injective (S _) (S _) _".

See also: https://www.reddit.com/r/Idris/comments/nd7kcj/q_why_does_function_clause_order_matter_here/

**Comment by gallais** [comment]
Very strange: when you manually add the `impossible` case `plus2Injective Z (S _) _ impossible`
(that Idris otherwise automatically detects as impossible) the generated case tree ends up with
additional catch-all cases beyond the unique `Refl` constructor. Cleaned up logs:

### Without the additional `impossible`

```idris
  case {arg:0} : Nat of
    Z => case {arg:1} : Nat of
      Z =>
        case {arg:2} : (Equal Nat Nat (plus2 Z) (plus2 Z)) of
          Refl {e:1} {e:2} => (Refl [__] [__])
    S {e:0} => case {arg:1} : Nat of
      S {e:3} =>
        case {arg:2} : (Equal Nat Nat (plus2 (S {pat1::0})) (plus2 (S {e:0}[1]))) of
          Refl {e:4} {e:5} => (Refl [__] [__])
```

### With the additional `impossible`:

```idris
  case {arg:0} : Nat of
    Z => case {arg:1} : Nat of
      Z =>
        case {arg:2} : (Equal Nat Nat (plus2 Z) (plus2 Z)) of
          Refl {e:1} {e:2} => (Refl [__] [__])
          _ =>
            (idris_crash [__] "Unhandled input for badplus2Injective at Issue1421.idr:12:1--12:34")
      _ =>
        (idris_crash [__] "Unhandled input for badplus2Injective at Issue1421.idr:12:1--12:34")
    S {e:0} => case {arg:1} : Nat of
      S {e:3} =>
        case {arg:2} : (Equal Nat Nat (plus2 (S {pat1::0})) (plus2 (S {e:0}[1]))) of
          Refl {e:4} {e:5} => (Refl [__] [__])
          _ =>
            (idris_crash [__] "Unhandled input for badplus2Injective at Issue1421.idr:12:1--12:34")
      _ =>
        (idris_crash [__] "Unhandled input for badplus2Injective at Issue1421.idr:12:1--12:34")
    _ =>
      (idris_crash [__] "Unhandled input for badplus2Injective at Issue1421.idr:12:1--12:34")
```

I wonder whether this is the same bug as #550 & friends where record constructors are not
detected as covering!

**Comment by gallais** [comment]
I think I get it: for the compile time & coverage checking tree we actually care about
the `impossible` cases and keep them around when generating the tree (whereas they are
checked to be impossible and then filtered out when generating the runtime tree).

In that process the `f xs impossible` clauses are replaced with `f xs = Erased` and are
used when choosing which variable to split on. This may lead to a different tree. I've
tried moving all of the `impossible` at the end of the definition as some sorts of
catchalls we don't care much about but that seems to break code in the compiler which
suggests deeper issues: AFAIU moving `impossible` cases around should be benign semantically.
