### ISSUE TITLE
Linearity escape via lets

### ISSUE THREAD

**Issue by fabianhjr** [idris-lang/Idris2#1447]
While working on a fix for #55 (on #1444) I came around this linearity escape and attempted a fix but went down a rabbit-hole I am not quite ready to deal with DX

# Steps to Reproduce

```idris
1
foo : Bool
foo = True

bar : Bool
bar = q
  where
    q : Bool
    q = foo
```

# Expected Behavior

Linearity error

# Observed Behavior

Checks succesfully

**Comment by gallais** [comment]
I think this is #818
