### ISSUE TITLE
Code used to compile but now doesn't

### ISSUE THREAD

**Issue by nickdrozd** [idris-lang/Idris2#1453]
I have some code like this:

```idris
import Data.Fin

%default total

data State = H |
  A | B | C |
  D | E | F

Cast State (Fin 1) where
  cast A = FZ
  cast _  = FZ

Cast State (Fin 2) where
  cast B = FS FZ
  cast x  = weaken $ cast x

Cast State (Fin 3) where
  cast C = FS $ FS FZ
  cast x  = weaken $ cast x

Cast State (Fin 4) where
  cast D = FS $ FS $ FS FZ
  cast x  = weaken $ cast x

Cast State (Fin 5) where
  cast E = FS $ FS $ FS $ FS FZ
  cast x  = weaken $ cast x

Cast State (Fin 6) where
  cast F = FS $ FS $ FS $ FS $ FS FZ
  cast x  = weaken $ cast x
```

It compiles fine with commit f721281b, but b457d157 gives errors:

```
- + Errors (5)
 |-- cast.idr line 15 col 26:
 |   While processing right hand side of cast. When unifying State and ?m = ?n.
 |   Mismatch between: State and ?m = ?n.
 |
 |   cast.idr:15:27--15:28
 |    11 |   cast _  = FZ
 |    12 |
 |    13 | Cast State (Fin 2) where
 |    14 |   cast B = FS FZ
 |    15 |   cast x  = weaken $ cast x
 |                                   ^
```

What changed since then? Was it a bug then or is it a bug now?

Certainly the code itself is not great. I think the idea was to use
these "states" to index into a vect. It was obvious at the time that
this was not the right way to do that, and the shame of its inelegance
weighs on me to this day. Nevertheless, I'd prefer if it still
compiled.

For more context, see [the full code](https://github.com/nickdrozd/rado/blob/master/Rado.idr).

**Comment by gallais** [comment]
It's due to the overloading introduced by #830 and the following fixes it:

```idris
%hide Data.Fin.cast
```

I'd merge a PR changing `Data.Fin.cast` to e.g. `coerce`.

**Comment by nickdrozd** [comment]
The fix works for me. Thanks!

Besides the fix in behavior, an Idris program that took ~165s to run a week ago now takes ~145s. That's with no changes on my end, just updating Idris. What accounts for the change? (Obviously the change is good!)

**Comment by gallais** [comment]
Edwin has been pushing some optimisations: https://github.com/idris-lang/Idris2/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+author%3Aedwinb
