### ISSUE TITLE
Incorrect parsing of let expressions with mixed local definitions and let binding

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1485]
# Steps to Reproduce
```idris
Works : Nat
Works = let n = 0
            k : Nat
            k = 1
        in n + k
                
Fails : Nat
Fails = let k : Nat
            k = 1
            n = 0
        in n + k        
```
# Expected Behavior
Both definitions should type-check --- the only difference is the order of the local definitions and the let-binding clauses.

# Observed Behavior
```
     While processing right hand side of Fails. No type declaration for Main.n.
     
      06 |                 
      07 | Fails : Nat
      08 | Fails = let k : Nat
      09 |             k = 1
      10 |             n = 0
                       ^^^^^
```

**Comment by ohad** [comment]
Parsing collections of local definitions seems to be too greedy, and so we treat `n` as a local definition without an accompanying local claim, instead of another let-binding clause.

**Comment by ohad** [comment]
Workarounds: 

If there is no dependency between the clauses, can re-order them so that local definitions appear last.

If there is a dependency, but it's not mutual, can split into two nested lets.

If there's a mutual dependency, promote the let-binding into a local definition by adding a corresponding claim.

**Comment by gallais** [comment]
Following #691 you can use `:=` to force something to be a let-binding.

**Comment by gallais** [comment]
I'll close this because, as I've mentioned above, I'd rather have users rely on the unambiguous `:=`.
