### ISSUE TITLE
Failure to unify after case analysis

### ISSUE THREAD

**Issue by danielwaterworth** [idris-lang/Idris2#1491]
# Steps to Reproduce
```idris
module Main

import Data.Vect

interface Sized x where
  size : Nat

Sized Bool where
  size = 1

foo :
  (fx:Sized y) =>
  Vect (size @{fx}) Bool
foo {fx} =
  case size @{fx} of
    Z => []
    S n => replicate (S n) False
```

# Expected Behavior

I expect 0 to unify with `size @{fx}` in the branch where they are equal.

# Observed Behavior

```
Error: While processing right hand side of foo. Can't solve constraint between: 0 and size.

Bug.idr:16:10--16:12
 12 |   (fx:Sized y) =>
 13 |   Vect (size @{fx}) Bool
 14 | foo {fx} =
 15 |   case size @{fx} of
 16 |     Z => []
               ^^
```

**Comment by ohad** [comment]
Dependent case splitting doesn't have this behaviour. However, the `with` construct has this behaviour (I think it's called the 'magic with behaviour', but I might be wrong). So this works:

```idris
fooWith :
  (fx:Sized y) =>
  Vect (size @{fx}) Bool
fooWith  {fx} with (size @{fx})
 fooWith {fx} | Z = []
 fooWith {fx} | S n = replicate (S n) False
``` 

If you don't want to use the `with` construct but use `case`, you can use the function ` `contrib`'s
```idris
Syntax.WithProof.(@@) : (t : a) -> (u : a ** t = u)
```
like so:
```idris
import Data.Vect

import Syntax.WithProof    -- import (@@) from `contrib`

interface Sized x where
  size : Nat

Sized Bool where
  size = 1

fooCase :
  (fx:Sized y) =>
  Vect (size @{fx}) Bool
fooCase {fx} =
  case @@(size @{fx}) of
        --  vvv    proof that size @{fx} = Z
    (Z   ** prf) => replace {p = \n => Vect n Bool} (sym prf) $ []
    (S n ** prf) => replace {p = \n => Vect n Bool} (sym prf) $ replicate (S n) False
        --  ^^^    proof that size @{fx} = S n
```

Finally, case splitting on a **variable** does have the behaviour you are interested in, so this code does type-check:
```idris
bar : (n : Nat) -> Vect n Bool
bar n = case n of
  0     => []
  (S n) => True :: bar n
```
It's only when you want to reduce an **expression** in a type that you should `with`-abstract over it.

**Comment by danielwaterworth** [comment]
I see. Thanks for the explanation!

**Comment by danielwaterworth** [comment]
@ohad, it doesn't seem to always work with `with`. As in this case:

```idris
import Data.Vect

foo : {a:Nat} -> {b:Nat} -> Vect (a + b) Bool -> Bool
foo x with (a + b)
  foo [] | Z =
    let prf = the (a + b = 0) Refl
    in False
```
I get:

```
Error: While processing right hand side of with block in foo. Can't solve constraint
between: 0 and plus a b.

Bug.idr:8:31--8:35
 4 | 
 5 | foo : {a:Nat} -> {b:Nat} -> Vect (a + b) Bool -> Bool
 6 | foo x with (a + b)
 7 |   foo [] | Z =
 8 |     let prf = the (a + b = 0) Refl
                                   ^^^^
```

This is weird, because without the `with`, it won't match on `[]`. So, it's both able and unable to solve the 0 = a + b constraint.

**Comment by buzden** [comment]
> it doesn't seem to always work with `with`. As in this case:
> 
> ```idris
> import Data.Vect
> 
> foo : {a:Nat} -> {b:Nat} -> Vect (a + b) Bool -> Bool
> foo x with (a + b)
>   foo [] | Z =
>     let prf = the (a + b = 0) Refl
>     in False
> ```
> 
> I get:
> 
> ```
> Error: While processing right hand side of with block in foo. Can't solve constraint
> between: 0 and plus a b.
> ```

Since an expression under `with` is not a variable but rather an expression, it's not automatically unified with `0`. But you can extract a proof of equality using a `proof` syntax:

```idris
foo : {a:Nat} -> {b:Nat} -> Vect (a + b) Bool -> Bool      
foo x with (a + b) proof eq      
  foo [] | Z =      
    let prf = the (a + b = 0) $ rewrite eq in Refl      
    in False
```

or even simpler

```idris
foo : {a:Nat} -> {b:Nat} -> Vect (a + b) Bool -> Bool      
foo x with (a + b) proof eq      
  foo [] | Z =      
    let prf = the (a + b = 0) eq                        
    in False
```

**Comment by danielwaterworth** [comment]
Aha! Thanks @ohad, you've been very helpful!

In case you're interested, I'm using idris because I'm working on a embedded hardware description language inspired by [clash](https://clash-lang.org/): https://github.com/danielwaterworth/eucalyptus
