### ISSUE TITLE
Tuple bug

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#1510]
# Steps to Reproduce

```idris
tupleBug : ((), a) -> ()
tupleBug (_, _, _) = ()
```

# Expected Behavior

Should error

# Observed Behavior

No error

**Comment by buzden** [comment]
Shrunk:

```idris
u : a -> ()                   
u () = ()
```

typecheks

**Comment by glyh** [comment]
In the current design, (a,b,c) is equivlent to (a,(b,c)), so the code is valid, since it actually treat a as a tuple in your pattern match.

**Comment by michaelmesser** [comment]
@glyh It should not be valid it should generate a not covering error at minimum

**Comment by glyh** [comment]
@michaelmesser  I agree.

**Comment by edwinb** [comment]
Idris ought to notice that the pattern you're matching is more specific than the type you gave. I'm not sure exactly how to achieve that, but I'll take a look. At the minute it only notices if you have more patterns (say, adding `tupleBug (_, _) = ()`) which unfortunately doesn't help here.

**Comment by edwinb** [comment]
Oh, interesting, manually desugaring fails as it's supposed to:

    tupleBug : Pair () a -> ()
    tupleBug (MkPair _ (MkPair _ _)) = ()

So it's probably related to the ambiguity of the `(x, y)` syntax.

(Mostly leaving this note since I'm about to go and do something else, so hopefully it'll help when I or someone else comes back to it...)

**Comment by edwinb** [comment]
Oh! I see. This is indeed about ambiguity.

So, when we check a pattern on the LHS, we make sure that it's not more specific than it's supposed to be. Meanwhile, if an ambiguity can't be resolved immediately, we delay the elaboration and come back to it later. It turns out that when we come back to it, we don't go back to the check... so it's accepted when it shouldn't be.

**Comment by edwinb** [comment]
Phew, that turned out to be quite a rabbit hole. But I've changed the way we check whether LHS arguments are polymorphic enough now, to make sure we check all of them, not just the ones that happen to be checkable on a first pass.
