### ISSUE TITLE
Change `needsBuilding` from `ttcTime` to a `ttcHash`

### ISSUE THREAD

**Issue by fabianhjr** [idris-lang/Idris2#1519]
While experimenting with caching in #1517 there is an issue where the Idris2 compiler will use modification dates rather than content hashes so:

- When a source file has not been modified but has been checked out by git more recently than its last modification it will have a more recent date than the ttcTime so Idris2 will rebuild unnecessarily. (Eg, `make`, `git checkout v0.2.0`, `git checkout -`, `make`)
- If the modification time is set to the commit time by a script (or someone resets the file to a previous version and somehow ends with a previous modification time) then Idris2 would not rebuild source files previous dates than those on the ttcFile even if they have changed and need rebuilding.

A challenge would be that there is currently no hash function in Idris2 so I am opening this as discussion and for tracking.

https://github.com/idris-lang/Idris2/blob/7aee7c9b7c50d16461e8d96d22d4ced2f19a52ef/src/Idris/ModTree.idr#L177-L180

**Comment by gallais** [comment]
> A challenge would be that there is currently no hash function in Idris2 

We do have hashes and we use them to decide whether the TTC is up to date
(if the hash matches up with what we expected then we additionally check whether
it the source file is more recent):

https://github.com/idris-lang/Idris2/blob/aa94dd235115137d56193f0db82d4f297758ee40/src/Idris/ProcessIdr.idr#L257-L259

**Comment by fabianhjr** [comment]
Yeah, but I don't think that hash function will be enough to use as a single indicator of file change or not. It is an Int and likely prone to collisions. :?

I don't believe I could safely remove the time checks unu
