### ISSUE TITLE
void should work in linear context

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#1545]
```
module LinearVoid

foo : (1 _ : Char) -> (x : Maybe (Int -> Void)) -> Char
foo v Nothing = v
foo v (Just y) = void (y 5)
```
The above doesn't typecheck with: `While processing right hand side of foo. There are 0 uses of linear name v. `

`void` should work regardless if in a linear context or not.

**Comment by ohad** [comment]
It's going to be difficult to achieve for `void` specifically until we have something like quantity polymorphism (an open research question).

In the meanwhile, you can use `void` to gobble up linear arguments:
```idris
linearVoid : Void -> (1 _ : a) -> b
linearVoid x y = the ((1 _ : a) -> b) (void x) y

foo : (1 _ : Char) -> (x : Maybe (Int -> Void)) -> Char
foo v Nothing = v
foo v (Just y) = linearVoid (y 5) v

```

**Comment by edwinb** [comment]
This looks like correct behaviour to me. `v` isn't used in the second clause, and there's nothing magical about `void` that would make the linearity checker know it can ignore `v`. So, I'm going to close this one.
