### ISSUE TITLE
Functions not fully evaluated in REPL 

### ISSUE THREAD

**Issue by glyh** [idris-lang/Idris2#1546]
# Steps to Reproduce

Open REPL, import module "Debug.Trace"

evaluate: 
```idris
trace "abc" 1
```
# Expected Behavior
```idris
abc 
1
```
# Observed Behavior
```idris
let MkIORes res w' =
      let MkIORes x' w' = prim__putStr "abc" %MkWorld
      in let MkIO res = k x' in res w'
in unsafeDestroyWorld w' res
```

**Comment by Russoul** [comment]
REPL will only evaluate terms legal for compile time evaluation. It won’t run IO programs.
Use `:exec <your IO program here>` instead

`trace` is a hack: it doesn’t have IO in its signature, but it silently does it in the body.

**Comment by glyh** [comment]
@Russoul That seems not working either: 
```
> :exec (trace "abc" 1)
Error: Can't find an implementation for Num (IO ?a).
```

**Comment by Russoul** [comment]
That's because, as I said, `trace` is a hack :) Just don't use it in REPL.

**Comment by glyh** [comment]
OK I got it, thanks.

**Comment by gallais** [comment]
`:exec` runs `IO` computations.


So if you try `:exec (trace "abc" 1)`, Idris infers that `1` must be
an IO computation and complains that there is no `Num (IO ?a)` instance.

If you use `:exec (pure $ trace "abc" 1)` instead everything works out.
