### ISSUE TITLE
Nat should be optimized for (==) and compare

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#1579]
Nat is optimized for (+), minus, (*), natToInteger and integerToNat.

I think it should also be optimized for (==) and compare, since (==) and compare are IMO more primitive than (+), minus, and especially (*). Having some primitives optimized and some not caused confusion for myself, and is hard to debug without profiling and/or looking at the Idris2 source code.

**Comment by stefan-hoeck** [comment]
This is a duplicate of #1182
