### ISSUE TITLE
NonEmpty doesn't work with list comprehensions

### ISSUE THREAD

**Issue by CodingCellist** [idris-lang/Idris2#1581]
# Steps to Reproduce
Write a function which uses a provably non-empty list, then use a list-comprehension with the function e.g.

```idris
import Data.List

foo : (l : List a) -> {auto 0 ok : NonEmpty l} -> a

bar : Integer
bar = foo [1..1000]
```

# Expected Behavior
This type-checks since the list `[1..1000]` is non-empty.

# Observed Behavior
```idris
Error: While processing right hand side of bar. Can't find an implementation for NonEmpty (rangeFromTo (fromInteger 1) (fromInteger 1000)).

LComp:6:7--6:20
 2 |
 3 | foo : (l : List a) -> {auto 0 ok : NonEmpty l} -> a
 4 |
 5 | bar : Integer
 6 | bar = foo [1..1000]
           ^^^^^^^^^^^^^
```

**Comment by gallais** [comment]
The implementation of the `Range` interface in `Prelude.Types` are not `public export`.
Have you tried to make them publicly accessible?
