### ISSUE TITLE
Interface record objects are not being reused

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#1614]
Consider the following two sample programs:

```idris
module IO

main : IO ()
main = do putStrLn "1"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
          putStrLn "2"
```

and

```idris
module IO2

go : HasIO io => io ()
go = do putStrLn "1"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"
        putStrLn "2"

main : IO ()
main = go
```

The generated Scheme file of the second example is less than half the size of the first (same for the compiled binary generated by Chez, so Chez seems not to be able to optimize the redundant interface objects away). The implementation of `go` is a single line of 2'600 characters of Scheme code. The implementation of the first `main` function on the other hand is a single line of almost 33'000 (!) characters of Scheme code. The reason: The HasIO interface record is recreated inline time and time again, while in the case of `go` it is being passed as an implicit argument to the function and reused in every call to `putStrLn`.

This might already be a known issue, given that the Idris2 compiler uses `Core` instead of monadic `IO` directly. And yet it might still affect the size and performance of the generated code of the compiler, because this happens whenever an overloaded function is being called.

So, here's my question: How do other languages with interface-like constructs (typeclasses) handle this?

**Comment by Russoul** [comment]
I think this is a general problem of auto-search: we should reuse the intermediate search results when 
running subsequent searches.
(Interface resolution is a special case of auto-search in Idris2. Or maybe the two terms are identified in Idris2 terminology)
I believe there are a few unresolved issues on the tracker that are related to this problem.

**Comment by stefan-hoeck** [comment]
This has been fixed with the addition of CSE, so I guess I'll close it.
