### ISSUE TITLE
v0.4.0 breaks compatibility with OpenBSD

### ISSUE THREAD

**Issue by Kaiepi** [idris-lang/Idris2#1618]
v0.3.0 can be installed OK on my system, but not v0.4.0 for a couple different reasons:
- GMP is a GNU library, and isn't included in search paths by default, so compilation of RefC fails.
- `sha256sum`is a GNU coreutil. On OpenBSD, when installed with the `coreutils` package, it is named `gsha256sum` instead. Alternatively, `openssl sha256 -r` produces equivalent output and is included on FreeBSD, DragonFly, NetBSD, and OpenBSD; Windows' `certutil` should offer similar capabilities as well.

A build of Idris2 v0.4.0 on OpenBSD can be completed by:
- Patching all instances of `Libraries.Utils.Binary.hashFile` to use `gsha256sum` or `openssl sha256 -r` (`src`, `bootstrap`).
- Installing the `gmp` package and setting `LD_LIBRARY_PATH="/usr/local/lib" C_INCLUDE_PATH="/usr/local/include"` in the environment for `gmake bootstrap-racket`.

But including GMP this way doesn't work for `gmake test`. I'm not comfortable deciding how to fix either issue on my own.

**Comment by fabianhjr** [comment]
There is some talk about including a sha256sum into idris as a helper lib in https://github.com/idris-lang/Idris2/pull/1584

**Comment by gallais** [comment]
I'm confused: isn't the sha dependency entirely optional as long as you don't
use the experimental flag?

**Comment by fabianhjr** [comment]
The checking of the hash is optional. It is still recorded in the TTC.

**Comment by gallais** [comment]
Hash check should hopefully be fixed by #1618

**Comment by fabianhjr** [comment]
Hey @Kaiepi, the PR got merge. Could you try the latest version from the main branch?

**Comment by Kaiepi** [comment]
@fabianhjr `gmake` and `gmake install` do their thing with the environment setup now. `gmake bootstrap-racket` still looks for `sha256sum`.

**Comment by Kaiepi** [comment]
A complete installation can now be performed minus the workarounds.

**Comment by melted** [comment]
Can we close the issue then?
