### ISSUE TITLE
Show type signatures as is in `--mkdoc` API reference

### ISSUE THREAD

**Issue by joelberkeley** [idris-lang/Idris2#1637]
I'd like users to see type signatures as I write them in the library. Currently they are expanded, so that `[1]` has become `(Data.Vect.:: Z Nat 1 (Data.Vect.Nil Nat))` which is very difficult to parse.

**Comment by gallais** [comment]
I think this was fixed: 

```
module Issue1637

import Data.Vect

export
One : Vect 1 Nat
One = [1]

export
test : One === [1]
test = Refl
```

gives me `test : One = [1]` in the html doc.

As for displaying the type as it was written by the user, this is already covered by #1387.
