### ISSUE TITLE
dirOpen -> openDir was forgotten in idris2-boot/support/c

### ISSUE THREAD

**Issue by wchresta** [idris-lang/Idris2#166]
While thoroughly testing the bootstrapping process, I stumbled over a misnamed C function:

```
Exception in foreign-procedure: no entry for "idris2_dirOpen"
```

After digging around, it became clear that the `c` helper functions were not correctly renamed in https://github.com/edwinb/Idris2-boot/blob/master/libs/base/System/Directory.idr#L38-L42 (and the corresponding functions in `support/c`). This is leading to an incompatibility between `idris2-boot` and `idris2` during the build step.

I believe this problem did not appear in CI because the test step in the bootstrapping build  https://github.com/idris-lang/Idris2/blob/master/Makefile#L42 appears to be using the C-bindings of `idris2-boot` rather than the c bindings of `idris2` proper.

This issue tracks fixing of idris2-boot and changing tests in CI to catch these kinds of problem in the future.

**Comment by wchresta** [comment]
After some more digging, the difference `openDir` <-> `dirOpen` between idris2 and idris2-boot might be because the latter needs to be compatible with idris1.

This means the error was probably on my end due to a misunderstanding of how the c-headers and the builds interact with eachother.

**Comment by edwinb** [comment]
the only thing I did in idris2-boot was change the name of the library functions. I didn't see the need to go any further, except perhaps for tidiness.

**Comment by wchresta** [comment]
I think I'm just confused between bootstrapping and full building and three different idris versions. Sorry to bother.

**Comment by attila-lendvai** [comment]
i'm seeing this, and it's confusing the hell out of me.

i'm working on the Guix packaging that does a full bootstrap, and i see this when i'm building `0.2.1` using `0.1.1` as the host (i.e. idris2-boot).

i can make most of the tests pass (298/304), but i cannot make **all** of them pass with any combination of the `libidris2_support.so` host vs. guest versions.

the best result i can get is when i add the **host's** `libidris2_support.so` to the `LD_LIBRARY_PATH` of the generated executable, but then new definitions are missing, like `idrnet_socket`, or `idris2_writeBufferData`, causing the few failures.

---

the wrapper script that starts it all up (the package definition places the host's `.so` under `lib/`):

```
#!/gnu/store/fvhj74pghapbjvsvj27skvkra1by1965-bash-minimal-5.0.16/bin/bash
export IDRIS2_PREFIX="/gnu/store/zfgw3jx2c2xcbjbnsrj1q8adqy9zd9ni-idris2-0.2.1"
export LD_LIBRARY_PATH="/gnu/store/zfgw3jx2c2xcbjbnsrj1q8adqy9zd9ni-idris2-0.2.1/lib${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH"
export CC="gcc"
export CHEZ="/gnu/store/cbp2nmygsirxh4gksr90wfgr1dnpaybm-chez-scheme-9.5.4/bin/scheme"
exec -a "$0" "/gnu/store/zfgw3jx2c2xcbjbnsrj1q8adqy9zd9ni-idris2-0.2.1/bin/.idris2-real" "$@"
```

so, it's the old version that contains `dirOpen`:
```
$ nm /gnu/store/zfgw3jx2c2xcbjbnsrj1q8adqy9zd9ni-idris2-0.2.1/lib/libidris2_support.so 2>&1 | grep dirOpen
00000000000027e0 T idris2_dirOpen
```

notice that `dirOpen` is not present in the sources, but it is present in the compiler output?! does it leak from the host? where is it coming from?
```
alendvai@lelap /tmp/guix-build-idris2-0.2.1.drv-30/source$ grep -r dirOpen .
Binary file ./build/exec/idris2_app/libidris2_support.so matches
./build/exec/idris2_app/idris2.ss:(define Directory-System-prim_openDir (lambda (farg-0 farg-1) ((foreign-procedure #f "idris2_dirOpen" (string) void*) farg-0)))
Binary file ./tests/build/exec/runtests_app/libidris2_support.so matches
```

the source only has `openDir` in it:
```
alendvai@lelap /tmp/guix-build-idris2-0.2.1.drv-30/source$ grep -r openDir .
Binary file ./support/c/libidris2_support.a matches
Binary file ./support/c/libidris2_support.so matches
./support/c/idris_directory.h:void* idris2_openDir(char* dir);
./support/c/idris_directory.c:void* idris2_openDir(char* dir) {
Binary file ./support/c/idris_directory.o matches
./src/Core/Directory.idr:dirExists dir = do Right d <- openDir dir
./src/Core/Directory.idr:    = do Right d <- openDir dir
./build/exec/idris2_app/idris2.ss:(define Directory-System-prim_openDir (lambda (farg-0 farg-1) ((foreign-procedure #f "idris2_dirOpen" (string) void*) farg-0)))
./build/exec/idris2_app/idris2.ss:(define Directory-System-openDir (lambda (arg-0 ext-0) (let ((act-15 (Directory-System-prim_openDir arg-0 ext-0))) ((Directory-System-case--2438-942 arg-0 act-15 (Prelude-C-47C-61_Eq__Int (PrimIO-prim__nullAnyPtr act-15) (Prelude-fromInteger_Num__Int 0))) ext-0))))
./build/exec/idris2_app/idris2.ss:(define Directory-Core-dirExists (lambda (arg-0 ext-0) (let ((act-15 (Directory-System-openDir arg-0 ext-0))) (let ((sc0 act-15)) (case (vector-ref sc0 0) ((1) (let ((e-2 (vector-ref sc0 1))) (let ((act-16 (Directory-System-closeDir e-2 ext-0))) (Prelude-pure_Applicative__IO 'erased 0 ext-0)))) (else (Prelude-pure_Applicative__IO 'erased 1 ext-0)))))))
./build/exec/idris2_app/idris2.ss:(define Directory-Core-dirEntries (lambda (arg-0 ext-0) (let ((act-15 (Directory-System-openDir arg-0 ext-0))) (let ((sc0 act-15)) (case (vector-ref sc0 0) ((1) (let ((e-2 (vector-ref sc0 1))) (let ((act-16 (Directory-Core-getEntries e-2 ext-0))) (let ((act-17 (Directory-System-closeDir e-2 ext-0))) (Prelude-pure_Applicative__IO 'erased (vector 1 act-16) ext-0))))) (else (let ((e-5 (vector-ref sc0 1))) (Prelude-pure_Applicative__IO 'erased (vector 0 e-5) ext-0))))))))
Binary file ./build/ttc/Core/Directory.ttc matches
Binary file ./libs/base/build/ttc/System/Directory.ttc matches
Binary file ./libs/base/build/ttc/System/Directory.ttm matches
./libs/base/System/Directory.idr:%foreign support "idris2_openDir"
./libs/base/System/Directory.idr:prim_openDir : String -> PrimIO DirPtr
./libs/base/System/Directory.idr:openDir : HasIO io => String -> io (Either FileError Directory)
./libs/base/System/Directory.idr:openDir d
./libs/base/System/Directory.idr:    = do res <- primIO (prim_openDir d)
```

what happened to that commit above that mentions this issue? is it something that i could backport to fix this? if so, could someone point me to the commit or definitions that needs to be backported?
