### ISSUE TITLE
[RFC] Renaming the main branch

### ISSUE THREAD

**Issue by mattpolzin** [idris-lang/Idris2#1682]
How do folks feel about renaming the `master` branch? I am partial to the fairly well adopted `main` renaming, but open to other alternatives.

For anyone unfamiliar with the current movement away from using the name "master" for the main branch of `git` repositories: It quite simply allows us to avoid a word that carries a lot of historical baggage. Renaming away from "master" allows a project such as Idris to express solidarity and remove language that makes some uncomfortable even if it is not uncomfortable for everyone. It is important, as always, to remember that any individual's _lack_ of discomfort over the name "master" does not invalidate another individual's discomfort.

There is plenty of room for debate and plenty of people have already debated the merits of avoiding the word "master"; I kindly request that if you think that renaming the main branch is a bad idea, you refrain from turning this thread into an argument for why "master" is not a **bad** word. Instead, please voice your opinion that it is unnecessary to rename the main branch without rehashing that debate here. Similarly, if someone voices the opinion that the branch renaming is unnecessary, please refrain from trying to convince them otherwise -- these are good conversations to have, but they can quickly derail a relatively simple question like: Do we as a community want to rename the main branch?

However, if you _do_ support renaming the main branch, please also let us know you have that opinion by either commenting (and optionally suggesting a name other than "main") or giving this proposal a thumbs up or heart.

There are two pragmatic considerations with renaming the main branch:
1. Tooling needs to be updated (I would be happy to take that on).
2. Developers need to adjust their locally checked out repositories and begin referencing a different branch name when merging upstream into their work.

I think the latter is the biggest hit to the developer community, though my personal opinion is that it is a small price to pay in order to say "we see no need to use a word that makes some potential contributors feel unwelcome" (and my muscle memory about "master" is transitioning to "main" fast).

**Comment by melted** [comment]
In my experience, it's not much of a hassle to update local git installs with it. I'd be in favor of it, it's becoming standard so it's something we should do sooner or later.

**Comment by donovancrichton** [comment]
I also don't really think it's that much of a hassle. Main is shorter to type.

**Comment by fabianhjr** [comment]
I favor `main` over `master` but didn't feel like bikeshedding the default branch name so hadn't brought it up;  though this is something that a maintainer or the BDFL Edwin Brady should decide since it is mostly work on their end. (Count me as a *Ay* / +1 for whatever that is worth)

**Comment by gallais** [comment]
No opposition on my end. What do we need to update?

* CI workflow files
* ?

**Comment by CodingCellist** [comment]
I think this is a good idea. The main challenges would be updating all files that reference or rely on the `master` terminology, but if you (@mattpolzin) are fine with doing that, then I think it's probably good to make the move sooner rather than later (also in terms of how many people need to change their local configs)  : )

**Comment by CodingCellist** [comment]
I would suggest creating a PR with a task-/todo-list? That way people can assist if they want? I'm happy to help with this migration, I just don't know what things need updated  : )

**Comment by mattpolzin** [comment]
It sounds like this idea is generally well-received. 

As suggested above, I would like to hear from @edwinb if possible before next steps because he always has veto power on something like this. 

If we want to go for it, I can create the suggested PR with steps needed. I just checked and none of the tooling internal to the project references the master branch, so as far as I know for this project, the next steps are:
1. Update CI workflows. 
2. Use GitHub's branch rename feature (available to project admin's) to rename `master` to main. 
3. All developers follow GitHub's handy tooltip (shows up next time you visit the repository in a web browser after the rename) to update their local repositories. Alternatively, what I always do is just pull the new main branch and delete my local master branch. 
4. There might be release tooling Edwin has written outside of the repository that needs updating.

**Comment by mattpolzin** [comment]
5. Blog post like Edwin writes for each release? I could put together some thoughts on such a brief blog post (essentially writing it but leaving publishing for Edwin) to explain the reasoning behind the move similarly to how GitHub itself and other open source projects like Swift have done.

**Comment by edwinb** [comment]
Sorry, I wasn't paying attention even when tagged. No objections from me.

**Comment by mattpolzin** [comment]
Closing this as completed!
