### ISSUE TITLE
Erased argument mishandled in value-level type definition

### ISSUE THREAD

**Issue by bijan-S** [idris-lang/Idris2#1693]
# Steps to Reproduce

```idris
Ty : Type
Ty = {0 a : Type} -> a
```

# Expected Behavior

This should typecheck properly, since `{0 a : Type} -> a` is a valid type.

# Observed Behavior

This fails to typecheck with the following error:

```idris
Error: While processing right hand side of Ty. a is not accessible in this context.

Ty : Type
Ty = {0 a : Type} -> a
        ^
```

The typechecker seems to incorrectly assume that in the definition of `Ty` the quantity of `a` is 0, when it should allow unrestricted usage of `a` in the type definition itself.

The same also happens with linear arguments:

```idris
Ty : Type
Ty = (1 a : Type) -> a
```
```idris
Error: While processing right hand side of Ty. Trying to use linear name a in non-linear context.

Ty : Type
Ty = (1 a : Type) -> a
        ^
```

**Comment by gallais** [comment]
I think this is a duplicate of #1436

**Comment by bijan-S** [comment]
I don't quite understand the reasoning for this given in #1436. It seems like allowing types like this to exist at runtime would only affect pattern-matching on them, which would just be identical to pattern matching on normal function types.

**Comment by gallais** [comment]
The idea being that if `{0 a : Type}` is erased you're going to have a hard
time recursively matching on `a` in the body.

Note that

```idris
0 Ty : Type                                                                                                                     
Ty = {0 a : Type} -> a
```

is accepted because `Ty` is marked as erased too which means we know for sure
we'll never end up matching on it!

**Comment by bijan-S** [comment]
I'm still not entirely sure about this design choice, but I don't know enough about Idris 2's internals to justify removing this restriction, so I'll just close it here.
