### ISSUE TITLE
Clauses that match on arguments other than the first don't get simplified

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris2#173]
# Steps to Reproduce
```
data Subs : List a -> List a -> Type where
  Nil  : Subs [] []
  Skip : Subs xs ys -> Subs xs      (a::ys)
  Take : Subs xs ys -> Subs (a::xs) (a::ys)

compSub : Subs xs ys -> Subs ys zs -> Subs xs zs
compSub  Nil        Nil       = Nil
compSub  sxy       (Skip syz) = Skip $ compSub sxy syz
compSub (Skip sxy) (Take syz) = Skip $ compSub sxy syz
compSub (Take sxy) (Take syz) = Take $ compSub sxy syz

compSubHelp : compSub sxy (Skip syz) = Skip (compSub sxy syz)
```

# Expected Behavior

The corresponding clause auto-simplifies, so the proof is trivial:
```
compSubHelp = Refl
```

# Observed Behavior

We have to make `s1` non-erased and match on it:
```
compSubHelp : {sxy : Subs xs ys} -> compSub sxy (Skip syz) = Skip (compSub sxy syz)
compSubHelp {sxy = Nil}    = Refl
compSubHelp {sxy = Skip _} = Refl
compSubHelp {sxy = Take _} = Refl
```

Also, if we change the signature of `compSubHelp` to `compSub sxy (Skip syz) = Skip $ compSub sxy syz`, we get the following error:
```
Operator '=' is non-associative
```

**Comment by ziman** [comment]
If you swap the first two clauses of `compSub`, the `Refl` proof goes through. Otherwise reduction probably gets stuck on the first clause.

**Comment by edwinb** [comment]
This is the expected behaviour - the case tree can't make progress until it has a concrete value for the first argument. The equations you give aren't necessarily definitional equalities, because they might be overlapping. While in this case, there isn't a later case that would match, spotting that in general would be pretty expensive.

**Comment by clayrat** [comment]
Ah, interesting, thanks! What do you think about the `non-associative` error?

**Comment by gallais** [comment]
> What do you think about the non-associative error?

Idris is not sure whether the type should be parsed as `(f = g) x` or `f = (g x)`
because the relative fixities of `_=_` and `_$_` is not specified.

**Comment by clayrat** [comment]
Ah, so is this an issue in the lexer or parser proper?
