### ISSUE TITLE
Context displayed incorrectly when pattern matching on indexed structure

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris2#174]
# Steps to Reproduce

```
data Subs : List a -> List a -> Type where
  Nil  : Subs [] []
  Skip : Subs xs ys -> Subs xs      (y::ys)
  Take : Subs xs ys -> Subs (y::xs) (y::ys)

compSub : Subs xs ys -> Subs ys zs -> Subs xs zs
compSub  sxy       (Skip syz) = Skip $ compSub sxy syz
compSub (Skip sxy) (Take syz) = Skip $ compSub sxy syz
compSub (Take sxy) (Take syz) = Take $ compSub sxy syz
compSub  Nil        Nil       = Nil

lp : Subs (x::xs) ys -> Subs xs ys
lp (Skip s) = Skip $ lp s
lp (Take s) = Skip s

Uninhabited (Subs (x::xs) xs) where
  uninhabited Nil impossible
  uninhabited (Skip s) = uninhabited $ lp s
  uninhabited (Take s) = uninhabited s

antiSym : Subs xs ys -> Subs ys xs -> xs = ys
antiSym  Nil            syx       = Refl
antiSym (Take {y} sxy) (Take syx) = cong (y ::) $ antiSym sxy syx
antiSym (Skip sxy)      syx       = absurd $ compSub syx sxy
antiSym  sxy           (Skip syx) = ?hole
```

# Expected Behavior

```
> :t hole
 0 ys : List a
   syx : Subs ys xs
   sxy : Subs (y :: xs) ys
 0 xs : List a
-------------------------------------
hole : y :: ys = xs
```

# Observed Behavior
```
> :t hole
 0 ys : List a
   syx : Subs ys ys
   sxy : Subs (y :: ys) ys
 0 xs : List a
-------------------------------------
hole : y :: ys = ys
```

If we now try to solve the hole with `absurd sxy` as the context view suggests, we get `Can't find an implementation for Uninhabited (Subs (y :: ys) ys)`. The expected solution of `absurd $ compSub sxy syx` works normally however.

**Comment by edwinb** [comment]
There's two different `ys` involved here. If you change the type to

    antiSym : Subs xs zs -> Subs zs xs -> xs = zs

Then you'll see

     0 zs : List a
       syx : Subs zs ys
       sxy : Subs (y :: ys) zs
     0 xs : List a
    -------------------------------------
    hole : y :: ys = zs

The name `ys` comes from the type of `Skip` and only isn't displayed because it has an internal name (`ys` itself isn't in scope since it doesn't appear in the type or the lhs - maybe this should be displayed differently). For example, you can bind it explicitly:

    antiSym  sxy           (Skip {ys=i_am_here} syx) = ?hole

Then for `hole` you'll see:

     0 zs : List a
     0 i_am_here : List a
       syx : Subs zs i_am_here
       sxy : Subs (y :: i_am_here) zs
     0 xs : List a
    -------------------------------------
    hole : y :: i_am_here = zs

So I'm not sure what this *should* show, but what it *does* show is explainable.

**Comment by gallais** [comment]
This is #35
