### ISSUE TITLE
Irrefutable pattern in `let` binding in a type declaration stops patterns from accessing implicit arguments in its scope

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1743]
# Steps to Reproduce
```idris
works : (n : (Nat, Nat)) -> let mk = n in {y : Bool} -> (z : Bool) -> String
works (m, k) {y} z = ?h1

fails : (n : (Nat, Nat)) -> let (m, k) = n in {y : Bool} -> (z : Bool) -> String
fails (m, k) {y} z = ?h2
```
# Expected Behavior
Both should type-check fine.

# Observed Behavior
Only the first definition type-checks, the second one fails with:
```
 line 5 col 0:
     While processing left hand side of fails. y is not a valid argument in fails ?n ?z.
     
     Foo:5:1--5:19
      1 | works : (n : (Nat, Nat)) -> {y : Bool} -> (z : Bool) -> String
      2 | works (m, k) {y} z = ?h1
      3 | 
      4 | fails : (n : (Nat, Nat)) -> let (m, k) = n in {y : Bool} -> (z : Bool) -> String
      5 | fails (m, k) {y} z = ?h2
          ^^^^^^^^^^^^^^^^^^
```

**Comment by edwinb** [comment]
Ooh, interesting. This is probably because of the desugaring introducing a new function. The elaboration order on the LHS will mean that it doesn't know that `y` exists yet. This should really be independent of elaboration order (well, everything should).

**Comment by edwinb** [comment]
It turns out, as I thought seemed most likely, this is about elaboration order. If we choose to go right to left, we might not yet know what the implicits are called. In that case, we shouldn't reject the program but rather wait and see if it works once we have more information. I have a fix for this coming.
