### ISSUE TITLE
Fails to build with --inc chez enabled

### ISSUE THREAD

**Issue by donovancrichton** [idris-lang/Idris2#1757]
If I enable the `opts --inc chez` line of the `idris.ipkg` file then Idris fails to build after the initial bootstrap on Ubuntu 20.04.

### Steps to reproduce
1. uncomment line 16 of the `idris2.ipkg` so that we now have: `opts = "--inc chez"`
2. `make distclean` to remove any previous idris installations and making sure we're starting fresh.
3. `rm -rf ~/.idris2` (replace with your Idris2 prefix) to be *extra* sure we're starting fresh.
4. `make bootstrap SCHEME=scheme IDRIS2_INC_CGS=chez PREFIX=~/.idris2`
5. `make install`
6. `make clean`
7. `make all SCHEME=scheme IDRIS2_INC_CGS=chez PREFIX=~/.idris2` (I left the flags in to be extra sure)

We now get the following warnings and error:
```
46/202: Building Core.Context (src/Core/Context.idr)
Warning: Compiling hole Core.Context.decode
...
66/202: Building Core.Unify (src/Core/Unify.idr)
Warning: Compiling hole Core.Unify.search
...
89/202: Building TTImp.Elab.Check (src/TTImp/Elab/Check.idr)
Warning: Compiling hole TTImp.Elab.Check.check
Warning: Compiling hole TTImp.Elab.Check.checkImp
Warning: Compiling hole TTImp.Elab.Check.processDecl
...
202/202: Building Idris.Main (src/Idris/Main.idr)
Uncaught error: INTERNAL ERROR: Missing .so:Network/Socket/Raw.so
make: *** [Makefile:63: ~/.../idris2/build/exec/idris2] Error 1

This happens with chez scheme 9.5 and 9.5.5 (the latter with --threads)

**Comment by edwinb** [comment]
You need to make sure all the libraries are installed with incremental compilation. I do that with `IDRIS2_INC_CGS=chez make install-libs`. I don't plan to make this any easier for the moment, although after the next release I'll add `--inc chez` to the library which should make this problem go away.

**Comment by edwinb** [comment]
Actually I might be talking rubbish here - we probably just need to update the bootstrap code to allow putting `--inc chez` in the libraries, because we don't use the previous version to build the libraries. Then there'd be no need for that annoying hack.

**Comment by donovancrichton** [comment]
I had completely forgotten that there was a make target for `install-libs`. 
Running `IDRIS2_INC_CGS=chez make install-libs` before `make all` solves my problem, thanks @edwinb!
