### ISSUE TITLE
if-expression requires parentheses within string interpolation

### ISSUE THREAD

**Issue by danielkroeni** [idris-lang/Idris2#1767]
When using an `if`-expression within string interpolation an error gets reported. But the error mentions that the token 'if' belongs to the expected tokens.

# Steps to Reproduce
Evaluate the following string:
`"\{ if True then "a" else "b" }"`

# Expected Behavior
I would expect that it evaluates to `"a"` 
or a parse error that says that `if` is not allowed in this position.

# Observed Behavior
```
Main> "\{ if True then "a" else "b" }"
Couldn't parse any alternatives:
1: Expected 'case', 'if', 'do', application or operator expression.
(Interactive):1:5--1:7
 1 | "\{ if True then "a" else "b" }"
         ^^
```

It works as expected when the `if`-expression is surrounded with parentheses.
```
Main> "\{ (if True then "a" else "b") }"
"a"
```

# Idris2 Version
Version 0.4.0-5f3480120

**Comment by andylokandy** [comment]
@andrevidela Do you have any idea about it?

**Comment by andylokandy** [comment]
I printed the token for examples:

```
"\{ (if True then "a" else "b") }"
[multiline string begin, string interp begin, symbol (, if, identifier True, then, multiline string begin, string "a", string end, else, multiline string begin, string "b", string end, symbol ), string interp end, string end, end of input]

"\{ if True then "a" else "b" }"
[multiline string begin, string interp begin, if, identifier True, then, multiline string begin, string "a", string end, else, multiline string begin, string "b", string end, string interp end, string end, end of input]
```

seems that all strings are identified as multiline strings.

**Comment by andrevidela** [comment]
that's incorrect but that shouldn't cause the problem that we see here, mhhhh

**Comment by andrevidela** [comment]
@andylokandy I quickly tried adding `commit` after parsing the `if_` keyword but no change. It looks like it's stuck a `simpleExpr`.

**Comment by andrevidela** [comment]
I think I've figured it out. An `if` statement was not considering `InterpEnd` as a valid closing token for a block. Adding this in and running the tests, fingers crossed. The fix should also help with do notation etc

**Comment by andylokandy** [comment]
@andrevidela that's amazing! Anyway I'll investigate the weird multiline string a bit.

**Comment by andylokandy** [comment]
I've figured it out! It was a silly printing problem, the flag for whether the string multiline is showed in the opposite:

https://github.com/idris-lang/Idris2/blob/34167d58bbfd16d74948d96512ed2e6eb6db2eb2/src/Parser/Lexer/Source.idr#L58-L59
https://github.com/idris-lang/Idris2/blob/34167d58bbfd16d74948d96512ed2e6eb6db2eb2/src/Parser/Lexer/Source.idr#L87-L88

**Comment by andrevidela** [comment]
Those booleans are evil…
