### ISSUE TITLE
A partial function blindly assumed to be total

### ISSUE THREAD

**Issue by Sventimir** [idris-lang/Idris2#1782]
Tested on `51f59b95308b015e9b596a8e071cbb5b77b64e7c` (today's `master` branch).

# Steps to Reproduce
The following code compiles just fine. Note that althought the function contains a recursive call in one of its branches, no attempt whatsoever is made to prove its totality. Yet, it is marked as such and the totality checker seems to blindly accept that.

```
import Data.Fin
import Data.Nat
import Data.Nat.Factor

||| Given a natural number n, this function returns a pair of numbers
||| (e, m) such that m is odd and (power 2 e) * m = n. It is almost
||| total, except for 0, which cannot be expressed as such a product.
||| Indeed, given 0 the function loops indefinitely, but the compiler
||| does not seem to mind
export
total
factorOutTwos : (n : Nat) -> (Nat, Nat)
factorOutTwos n with (decFactor n 2)
  factorOutTwos n | ItIsNotFactor (ProperRemExists q FZ prf) =
    (0, n)
  factorOutTwos n | ItIsFactor (CofactorExists q prf) =
    let (e, m) = factorOutTwos q in
    (S e, m)
```

# Expected Behavior
This function should be rejected by the totality checker, but it is not.

# Observed Behavior
The above module  compiles just fine and can be run in the REPL. The function seems to return correct results for most inputs, but given 0 it loops forever, because 2 is indeed considered a factor of 0, it's cofactor (`q`) being also 0, which makes the function step into the recursive call with the same argument over and over again.

**Comment by ohad** [comment]
Seems to be the irrefutable pattern in `let`:

```idris
total
foo : Nat -> (Nat, Nat)
foo  n = let (baz1, baz2) = foo n
         in (baz1, baz2)
```

**Comment by ohad** [comment]
Also tagged it with 'proof of false' since:
```idris
total
hack : Nat -> (Void, Void)
hack n = let (baz1, baz2) = hack n
         in (baz1, baz2)

total
boom : Void
boom = fst (hack 0)
```

**Comment by Sventimir** [comment]
@ohad you mean this happens whenever a result of a recursive call is bound to a name by a `let` binding? This very serious then.

**Comment by Russoul** [comment]
Those look similar: https://github.com/idris-lang/Idris2/issues/1460

**Comment by gallais** [comment]
> Those look similar: #1460

I just checked and it is indeed also fixed. I've added as a test case.
Thanks!
