### ISSUE TITLE
Bootstrap broken on Ubuntu 20.04 due to bump of required chezscheme version

### ISSUE THREAD

**Issue by timsueberkrueb** [idris-lang/Idris2#1784]
By using `__collect_safe`, the minimum required chez scheme version was bumped from `9.5.0` to `9.5.1`. This breaks bootstrapping in Ubuntu 20.04 when using chez scheme from the archive. This is not a problem in newer Ubuntu releases because they contain a newer version of chez scheme (the CI runs 21.04 which ships `9.5.4`, hence it did not fail).

```console
cp support/c/libidris2_support.so bootstrap-build/idris2_app/
sed 's/libidris2_support.so/libidris2_support.so/g; s|__PREFIX__|/home/tim/Dev/GitHub/idris-lang/Idris2/bootstrap-build|g' \
	bootstrap/idris2_app/idris2.ss \
	> bootstrap-build/idris2_app/idris2-boot.ss
/bin/sh ./bootstrap-stage1-chez.sh
Bootstrapping SCHEME=chezscheme IDRIS2_VERSION=0.4.0
Building idris2-boot from idris2-boot.ss
compiling idris2_app/idris2-boot.ss with output to idris2_app/idris2-boot.so
Exception: invalid foreign-procedure convention __collect_safe at line 579, char 95 of idris2_app/idris2-boot.ss
make: *** [Makefile:217: bootstrap] Error 255
```

Is there an alternative to `__collect_safe` that could be used to get compatibility with chez scheme 9.5.0 back? Otherwise I think it would be good to document the minimum required scheme version in `INSTALL.md`.

**Comment by gallais** [comment]
We could revert https://github.com/idris-lang/Idris2/commit/52c21c6182e11d2e1fe352c02c03e3e834437865 as Edwin mentions it's not strictly needed.

**Comment by edwinb** [comment]
Oh, that's awkward. It's because I generate the bootstrap code with a version that has `__collect_safe` available. I'll remove them and it should be okay, but I'll need to take that into account when updating the code. Or write a script for it instead of just using `cp` like I usually do.

**Comment by edwinb** [comment]
#1786 should fix this but I won't close until you confirm that it does

**Comment by timsueberkrueb** [comment]
It did, thank you very much for the quick fix!
