### ISSUE TITLE
Exception when using %builtin Natural Fin

### ISSUE THREAD

**Issue by sumeet** [idris-lang/Idris2#1799]
# Steps to Reproduce
Run the following module with `Exception in unbox: 1 is not a box` with current Idris2/main with either Scheme or Racket backends via `idris2 --exec main Main.idr`

```idris
module Main

import Data.Fin

%builtin Natural Nat
%builtin Natural Fin

%builtin NaturalToInteger finToInteger

main : IO ()
main = putStrLn $ show $ finToInteger $ FS $ FZ {k=34}
```

# Expected Behavior
`1` is printed out

# Observed Behavior
```console
~/finCrash> idris2 --exec main Main.idr
Exception in unbox: 1 is not a box
```

**Comment by gallais** [comment]
I wonder whether this is related to incremental compilation: you can't change the
representation of `Fin` in a client module and do incremental builds. We will probably
need to restrict `%builtin` to the module the datatype was defined in.

**Comment by Z-snails** [comment]
Turns out `%builtin Natural` is utterly broken when it comes to multiple modules. I'll work on a fix now.
