### ISSUE TITLE
Confusing error message with renamed module

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris2#180]
`Data.List` defines an inductive family `NonEmpty`. I am being absent-minded and
importing `Data.List` qualified as `NonEmpty`. Watch as everything blows up in
my face:

```idris
module Argh

import Data.List as NonEmpty

argh : (xs : List a) -> Maybe (NonEmpty xs) 
argh [] = Nothing
argh (_ :: _) = Just IsNonEmpty
```

```idris
1/1: Building Argh (Argh.idr)
Argh.idr:7:22--8:1:While processing right hand side of argh at Argh.idr:7:1--8:1:
When unifying NonEmpty ?a (?x :: ?xs) and NonEmpty (_ :: _)
Mismatch between:
	NonEmpty ?a (?x :: ?xs)
and
	NonEmpty (_ :: _)
Error(s) building file Argh.idr
```

This problem originally showed up in gallais/idris-tparsec#27

**Comment by edwinb** [comment]
This is probably because `as` hasn't been implemented yet beyond syntax. I should add that detail to the `README` at least. And possibly it should warn. Or, we could do a proper solution and actually implement it...

**Comment by supachai19** [comment]
ไม่มีคำอธิบาย

**Comment by supachai19** [comment]
> `Data.List``NonEmpty`กำหนดครอบครัวอุปนัย ฉันถูกเหม่อลอยและ
> การนำเข้ามีคุณสมบัติเป็น`Data.List` `NonEmpty`ดูทุกอย่างที่ระเบิดขึ้น
> บนใบหน้าของฉัน:
> 
> ```idris
> โมดูลโอ๊ะ
> 
> การนำเข้าข้อมูล รายการเป็นNonEmpty
> 
> argh  : ( xs : รายการ a) ->  อาจ (NonEmpty xs)
> argh [] =  ไม่มีอะไร 
> argh ( _  ::  _ ) =  แค่ IsNonEmpty
> ```
> 
> ```idris
> 1 / 1 :  อาคาร โอ๊ะ ( โอ๊ะ. IDR)
>  โอ๊ะ idr : 7: 22--8: 1: ขณะประมวลผลด้านขวาของ argh ที่ Argh.idr: 7: 1--8: 1:
>  เมื่อรวมNonEmpty หรือไม่ a ( ? x :: ? xs) และNonEmpty ( _ :: _ )
>  ไม่ตรงกันระหว่าง: NonEmpty ? a ( ? x :: ? xs)
>  และNonEmpty ( _ :: _      
> 	  
> 	  )
>  ข้อผิดพลาด (s) การสร้างไฟล์โอ๊ะ IDR
> ```
> 
> ปัญหานี้เดิมปรากฏใน[gallais / idris-tparsec # 27](https://github.com/gallais/idris-tparsec/issues/27)

**Comment by gallais** [comment]
This was fixed by #410
