### ISSUE TITLE
Equal `if then else` clauses aren't deemed equal

### ISSUE THREAD

**Issue by L-as** [idris-lang/Idris2#1809]
# Steps to Reproduce
```idris
ifThenElse' : Bool -> a -> a -> a
ifThenElse' True x _ = x
ifThenElse' False _ x = x

good1 : Bool -> a -> a
good1 b x = ifThenElse' b x x

good1' : (b : Bool) -> (x : a) -> good1 b x = ifThenElse' b x x
good1' _ _ = Refl

good2 : Bool -> a -> a
good2 b x = ifThenElse b x x

good2' : (b : Bool) -> (x : a) -> good2 b x = ifThenElse b x x
good2' _ _ = Refl

good3 : Bool -> a -> Bool
good3 b x = if b then True else False

good3' : (b : Bool) -> (x : a) -> good3 b x = if b then True else False
good3' _ _ = Refl

bad : Bool -> a -> a
bad b x = if b then x else x

bad' : (b : Bool) -> (x : a) -> bad b x = if b then x else x
bad' _ _ = Refl
```

# Expected Behavior
`bad'` should type check AFAICT.

# Observed Behavior
`bad'` doesn't type check.

**Comment by andrevidela** [comment]
Isn't this expected behaviour? There is no way idris can tell the two branches are the same if you don't pattern match on `b` in `bad'`?

**Comment by ohad** [comment]
If this issue is blocking you, here's a workaround:
```idris
bad' : (b : Bool) -> (x : a) -> bad b x = if b then x else x
bad' True _ = Refl
bad' False _ = Refl
```

**Comment by gallais** [comment]
This is an expected behaviour: `if_then_else_` is sugar for declaring
a toplevel function defined by pattern matching on the boolean.
Pattern-matching functions are only equal if they have the same name,
not up to their pattern-matching definitions being the same.

**Comment by L-as** [comment]
I am not sure that isn't a bug. I have had trouble proving things for `filter` because of this.

**Comment by L-as** [comment]
I couldn't use the workaround because AFAICT I couldn't pattern match on the term, though this may be due to my inexperience.

**Comment by gallais** [comment]
Every time you write `if_then_else_` in the source code, it gets elaborated
to a new function with a unique name. Two pattern-matching functions that
are written the same are not equal just by virtue of their code looking the
same e.g.

```idris
id1 : Nat -> Nat
id1 Z = Z
id1 (S n) = S n

id2 : Nat -> Nat
id2 Z = Z
id2 (S n) = S n

-- the following won't work
nope : id1 === id2
nope = Refl
```

Your best bet is to *never* write `if_then_else_` when you mean to refer to
an already existing one. Use an underscore instead and let Idris figure out
by unification that you're referring to an old function. It will then solve
the constraint by using the *internal* name that was given to that `if...`
function.

**Comment by L-as** [comment]
Why are pattern-matching functions not checked for equality? Isn't this core to dependent types?

**Comment by gallais** [comment]
Core to dependent types is the comparison of things in head normal form.
Once you have stuck terms you can throw in more or less magic depending
on how much work you are willing to do. I'm not sure syntactic equality
of pattern-matching definitions would bring that much to the table compared
to say eta-equality or fusion rules so I don't see it landing any time soon.

I'll close this as it's an expected behaviour.

**Comment by L-as** [comment]
How come `good3` is fine then?
