### ISSUE TITLE
Can't use function defined in `where` block in `with` 

### ISSUE THREAD

**Issue by alexhumphreys** [idris-lang/Idris2#1813]
# Steps to Reproduce

```haskell
-- ok
foo : Int -> Int -> Bool
foo n m with (n + 1)
  foo n m | 2 = True
  foo n m | _ = False

-- error
bar : Int -> Int -> Bool
bar x y with (doPlus x)
  bar x y | 2 = True
  bar x y | _ = False
where
  doPlus : Int -> Int
  doPlus x = x + 1
```

# Expected Behavior

Both should compile and be equivalent.

# Observed Behavior

The function `bar` throws the following error:
```haskell
"Foo.idr" 15L, 245C written
Error: Wrong number of 'with' arguments: expected 1 but got 0.

Foo:13:10--13:11
 09 | bar x y with (doPlus x)
 10 |   bar x y | 2 = True
 11 |   bar x y | _ = False
 12 | where
 13 |   doPlus : Int -> Int
               ^
```

# Notes

I don't use `with` much so maybe I'm doing something simple wrong, but I would have expected this to be possible.

**Comment by gallais** [comment]
Doesn't this `where` attach to the last clause i.e. it's not even available
in `bar x y | 2 = ?here`.

As for your problem, I expect you should be able to use a local definition in
the `with`.

**Comment by alexhumphreys** [comment]
Ah true, it does attach to the last clause! Maybe this issue should just be titled "I don't know how `where` or `with` works" :D

So how would one declare a local definition to attach to the `with`? The following (and various indentations of the `where`) is a parse error:
```haskell
bar : Int -> Int -> Bool
bar x y with (x + 1)
where
  doPlus : Int -> Int
  doPlus x = x + 1
  bar x y | 2 = True
  bar x y | _ = False
```

**Comment by gallais** [comment]
This is what I'd write (I mean, not really, but if you do want a local
definition in a `with` then this is what I'd write):

```
bar : Int -> Int -> Bool
bar x y
  with (
  let doPlus : Int -> Int
      doPlus x = x + 1
  in x + 1)
  bar x y | 2 = True
  bar x y | _ = False
```

**Comment by alexhumphreys** [comment]
Haha can see why you wouldn't write that 😅
Ok do maybe this isn't a bug but more a feature request? I also don't feel super strongly about this, so I'm happy to close it.
Basically just ran into this while trying to dance around already declared names in #1808, and between `%hide` and local namespaces (and the fun `let` trick you showed) there's other solutions to that issue.
