### ISSUE TITLE
JS: ReferenceError: Can't find variable: require due to sysos

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#1839]
# Steps to Reproduce

Compile with `--cg javascript`. Run the program in a browser.

# Expected Behavior

Program works.

# Observed Behavior

https://github.com/idris-lang/Idris2/blob/523c0a6d7823d2b9a614d4a30efb52da015f9367/support/js/support.js#L48-L49
```
ReferenceError: Can't find variable: require
```

**Comment by stefan-hoeck** [comment]
I'll have a look at this.
