### ISSUE TITLE
`==` is not total

### ISSUE THREAD

**Issue by dvc94ch** [idris-lang/Idris2#1841]
```idris
%default total

data Value = Null | Array (List Value)

Eq Value where
    Null == Null = True
    Array x == Array y = x == y
    _ == _ = False
```
results in
```sh
idris2 idris_bug.idr --check
1/1: Building idris_bug (idris_bug.idr)
Error: /= is not total, possibly not terminating due to recursive
path Main./= -> Main.== -> Main.==

idris_bug:5:1--8:19
 5 | Eq Value where
 6 |     Null == Null = True
 7 |     Array x == Array y = x == y
 8 |     _ == _ = False

Error: == is not total, possibly not terminating due to recursive
path Main./= -> Main.== -> Main.==

idris_bug:5:1--8:19
 5 | Eq Value where
 6 |     Null == Null = True
 7 |     Array x == Array y = x == y
 8 |     _ == _ = False
```
seems wrong to me?

**Comment by gallais** [comment]
The termination checker is purely syntactic. It has no notion that
equality for lists of `a` only uses equality for elements of type `a`
on strict subterms of the list. So it cannot possibly detected as
terminating.

The current workaround is to either `assert_total (x == y)` or to
mutually define equality for `Value` and `List Value`. In this second
case it becomes apparent that all the recursive calls are performed
on something smaller and are thus safe.

**Comment by dvc94ch** [comment]
Thanks, that worked. I guess the issue can be closed then.

**Comment by gallais** [comment]
I think so: we already have #1170 as the feature request to make this kind
of inlining automated.
