### ISSUE TITLE
`require is not defined` when running html (Javascript) output

### ISSUE THREAD

**Issue by falsifian** [idris-lang/Idris2#1854]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce

1. Build and install idris2 at commit 4a9f00078a5d03840b702dbc3bff3c139f202389. (I suspect the problem was introduced 599d0635e90c11b565353bb5a8063938f7fbd24c, but here I'm listing the commit I tested.)

2. Compile some program with `-o html --cg javascript`. As a minimal example, I tried the following program, compiled with `~/.idris2/bin/idris2 -o h.html --cg javascript h.idr`.
```
main : IO ()
main = pure ()
```

3. Open the resulting html file in Chromium, and open the developer console.

# Expected Behavior

No errors; program runs normally.

# Observed Behavior

The program does not run. In the Javascript console, I see:
```
h.html:55 Uncaught ReferenceError: require is not defined
    at h.html:55
```

(Of course, for the minimal example above, "program does not run" is not an observable symptom, but you get the idea.)

**Comment by falsifian** [comment]
Pinging @stefan-hoeck since I suspect this problem started with the big refactor in #1609. Apologies if I'm mistaken.

**Comment by Z-snails** [comment]
I believe this is the same issue as #1839.

**Comment by falsifian** [comment]
Thanks, I'll close this one then.
