### ISSUE TITLE
While compiling: `Error: Control.Monad.Error.Either.EitherT not a data type`

### ISSUE THREAD

**Issue by falsifian** [idris-lang/Idris2#1856]
# Steps to Reproduce

1. Build `idris2` at git head (commit 4a9f00078a5d03840b702dbc3bff3c139f202389 should do it).
2. Using that, build https://github.com/stefan-hoeck/idris2-dom and its dependencies at git head (using `idris2 --install`).

# Expected Behavior

The libraries are compiled and installed.

# Observed Behavior

When building `idris2-dom`:

```
[nix-shell:~/src/idris2/idris2-dom]$ idris2 --install dom.ipkg                  
 1/85: Building JS.Util (src/JS/Util.idr)                                       
 2/85: Building JS.Inheritance (src/JS/Inheritance.idr)                         
 3/85: Building JS.Marshall (src/JS/Marshall.idr)                               
 4/85: Building JS.Any (src/JS/Any.idr)                                         
 5/85: Building JS.Callback (src/JS/Callback.idr)                               
Error: Control.Monad.Error.Either.EitherT not a data type 
```

I can work around this by inserting `import Control.Monad.Error.Either` into `src/JS/Callback.idr` in the `idris2-dom` source. (At least, it got past `JS.Callback`; it's still going...)

I'm filing this bug against the compiler rather than the library because what I'm seeing doesn't look like a normal compiler error, and because the behaviour doesn't really make sense to me.

(I think I've seen at least one other case where I fixed a strange error by adding a `import` line that didn't look like it should be needed.)

**Comment by stefan-hoeck** [comment]
The reason is, that `JS.Callback` is publicly exporting something of type `JSIO cb`, which is an alias for `EitherT JSErr IO cb` and `EitherT` is not in scope. To the best of my knowledge, this is expected behavior as described in #1754. One solution is to use `import public Control.Monad.Either` in module `JS.Util`.

I'll add that fix to idris2-dom.

**Comment by falsifian** [comment]
Okay. I think what threw me here is that the error message doesn't include a line number or a snippet of code, like other compiler errors do. That made me think the compiler died in a nasty, unexpected way.
