### ISSUE TITLE
can't use VIM ide-mode to generate definitions

### ISSUE THREAD

**Issue by rgrover** [idris-lang/Idris2#186]
I'm using the idris2-vim plugin. I can no longer generate definitions from type declarations starting from commit 696db7f5 (merge by Niklas Larsson). The following from the command-line continues to work:
```sh
idris2 --find-ipkg <filename>.idr --client ':ac! <lineno> <name>'
```

# Steps to Reproduce
Declare a function's type and attempt to generate a definition.

# Expected Behavior
There should be an initial definition with a hole on the right-hand side of the equality.

# Observed Behavior
No change.

Things work fine until commit 1d078f78.

**Comment by edwinb** [comment]
Given these steps, I can't reproduce this on the latest master. Are you up to date with everything including idris2-vim? Maybe it's something about your vim setup that idris2-vim doesn't deal with properly? If the command line works fine, that's all idris2-vim does, so I don't think this is a problem with Idris itself.

**Comment by rgrover** [comment]
I am up to date with idris2-vim. I also suspect that it could be something with my NeoVim setup that idris2-vim doesn't deal with. I build/install Idris2 using:
```sh
make clean
make bootstrap SCHEME=chezscheme
make install
```

If I replace Idris install-dir compiled from 1d078f78 with anything more recent, my vim doesn't behave well. Going back to the install-dir compiled from 1d078f78, things work normally from within vim. 
Strangely, things continue to work from the command line, using idris2 --client.

I'll try removing all other Vim packages and see if idris2-vim works any better. 

Any quick tips on debugging idris2-vim? I've tried using `echo` from within `IdrisCommand`, but the output gets lost quickly and no trace can be seen using `:messages`.

**Comment by rgrover** [comment]
I have removed all plugins and settings, and reduced init.vim to a bare minimum (keeping only `edwinb/idris2-vim` and my colour preferences). I still see the same behaviour. Switching the .idris2 install-dir to something built after 1d078f7 prevents me from using REPL commands from within vi. The current workaround for me is to stay with version 1d078f7. 

If the problem is still with my vim settings, maybe I'll realize it given some more time. Meanwhile, if anyone can suggest ways to debug `edwinb/idris2-vim`, I'll be happy to experiment.

**Comment by jinwoo** [comment]
After I rebuilt from HEAD, I'm having a similar problem. In Vim, if I reload a file with `<leader>r`, it fails with:

```
Uncaught error: INTERNAL ERROR: build/ttc: File Read Error
```
I notice that https://github.com/idris-lang/Idris2/pull/190 upped the TTC version to 30. Would it be related?

**Comment by andylokandy** [comment]
I'm the author of https://github.com/idris-lang/Idris2/commit/696db7f58f8157b7fb1ae1bc771e42a56bf2555c, but I can't reproduce the issue in vscode-idris, and the Generate Definition works fine on the latest master. Can you find out what exactly the arguments and stdin vim-mode passed to idris2 executable?

**Comment by rgrover** [comment]
From within vim, when I ask for a type, the following system call is executed: 
```
idris2 --find-ipkg '<expanded-path-to-source>.idr' --client ':t hole'
```
It seems that newer versions of idris2 have issues with the full path. I get the following error when I run the same from the command line: `Uncaught error: INTERNAL ERROR: build/ttc: File Read Error`
I've tried the previous version of Idris2 (i.e. at 1d078f7), and that works fine.

The newer versions of idris2 also work correctly (from the command line) when using unexpanded paths.

**Comment by rgrover** [comment]
This is a potential workaround under idris2-vim:

```diff
diff --git a/ftplugin/idris2.vim b/ftplugin/idris2.vim
index 5e8f163..d4e3a75 100644
--- a/ftplugin/idris2.vim
+++ b/ftplugin/idris2.vim
@@ -34,7 +34,7 @@ endfunction
 function! s:IdrisCommand(...)
   let idriscmd = shellescape(join(a:000))
 "  echo("idris2 " . expand ('%:p') . " --client " . idriscmd)
-  return system("idris2 --find-ipkg " . shellescape(expand('%:p')) . " --client " . idriscmd)
+  return system("idris2 --find-ipkg " . shellescape(expand('%')) . " --client " . idriscmd)
 endfunction
 
 function! IdrisDocFold(lineNum)
```

**Comment by andylokandy** [comment]
@rgrover I can reproduce the error. I'll submit a fix soon.

**Comment by edwinb** [comment]
I believe this is resolved now.
