### ISSUE TITLE
feature request: give -> a precedence, increase base precedences

### ISSUE THREAD

**Issue by MarcelineVQ** [idris-lang/Idris2#187]
As I understand it currently -> doesn't have a precedence, it is right associative but always of lower precedence than any you can set yourself.  
This interacts poorly if you wish to mix and match your own arrow-like operators since they can never be of lower or equal precedence than ->
Haskell chose precedence 0 for their -> but I feel that would be shortsighted here, we don't have an upper limit on precedence assignment so there's no reason to be at the bottom.

Assuming my understanding of -> above is correct I suggest a precedence of `infixr 10` for -> and at the same time bump the all the infix precedences present in base by 10. This retains -> at the same effective precedence you'd be used to, while giving room for things to be defined that bind less tightly than ->

You could be inclined to write your own arrow to assign it precedence, e.g.
```idris
infixr 6 ~>
(~>) : Type -> Type -> Type
(~>) a b = a -> b
```
but now you have one less arrow form available since there's only so many keys/symbols available. It's also not clear to me how you'd write an explicit pi type, e.g. `(x : a) ~> B x`  with your own arrow type.

Comments on this topic are more than welcome, it's possible this suggestion is shortsighted itself and I'd be glad to hear why

**Comment by edwinb** [comment]
One problem that immediately comes to mind is that `->` isn't an operator in the usual sense, but a binder, so it doesn't fit into the usual scheme of resolving precedence. It's more like a lambda than an operator. So if we decide this is a good thing to do, I'm not sure how easy it is to implement, if it's possible at all.

**Comment by ziman** [comment]
It feels like there are two kinds of `->`, in different syntactic contexts.
1. `(n : T) -> T'`, where the arrow appears after a name binding
2. `T -> T'`, where the arrow appears after a term

So we could parse `->` as an operator if it appears after a term, but parse it as a `Pi` if it appears after a name binding. When I go through the possible combinations in my mind, I think this should also work fine if you combine both in the same type signature.

That might help with instances for `(->)`, too, perhaps?

**Comment by edwinb** [comment]
@ziman that's an interesting thought and probably worth investigating further...

**Comment by ziman** [comment]
`=>` is a problem. Even if we fix up `->`, you can't have `foo ~> bar => baz` parse as `foo ~> (bar => baz)` because `=>` can't be fixed the same way; it would clash with the lambda and case branch syntax.

On the other hand, both `foo ~> (_ : bar) => baz` and `foo ~> (_ : bar) -> baz` already associate to the right, even without any changes to the compiler.

**Comment by ziman** [comment]
So it's actually a simple rule; whenever you want to use a custom arrow in a type signature, it must be followed by a named binder, and no changes to the syntax are needed.

**Comment by gallais** [comment]
I am a bit concerned that if you have written a telescope and then realise
that some of the arguments do not need to be named because they are not
mentioned later on, removing these useless names could lead to a different
parse. This seems potentially very confusing.

**Comment by MarcelineVQ** [comment]
Just as some background info: the reason wanting a precedence for -> came up was that I was writing a linear arrow that I wanted to have the same precedence as ->
```idris
infixr 0 ~>
(~>) : Type -> Type -> Type
(~>) a b = (1 _ : a) -> b

foo : (x : a) -> d ~> r -> g
foo = ?foo_rhs
```
Even at precedence 0 this parses as
```idris
foo : (x : a) -> (d ~> r) -> g
-------------------------------------
foo_rhs : a -> ((1 _ : d) -> r) -> g
```

Whereas I was after
```idris
foo_rhs : a -> (1 _ : d) -> r -> g
```
And in fact we can get this via explicit parens of our own
```idris
foo : (x : a) -> d ~> (r -> g)
-------------------------------------
foo_rhs : a -> (1 _ : d) -> r -> g
```
Which is what led me to wonder, if we can create this precedence we want with ( ) why can't -> just have a precedence anyway so that we can at least match it with our own operators.

**Comment by ziman** [comment]
You can have it for `->` but you can't have it for `=>`:

You can't talk about operator precedence without making `=>` an operator. However, this will break a lot of stuff:
* How should `\x : y => z => w` parse? As `\(x : y => z) => w` or as `\(x : y) => (z => w)`? 
* The same goes for `case x of foo => bar => baz`. Imagine that `Main.(=>)` is a data constructor.

 This means it would be inconsistent so I gave up on it.

**Comment by MarcelineVQ** [comment]
Thanks for experimenting ziman
I'm convinced from this conversation that having nicer looking terms that use arrows isn't worth making special corners for people to stub their toes on
