### ISSUE TITLE
Ambiguity with duplicate record names in different namespaces

### ISSUE THREAD

**Issue by berewt** [idris-lang/Idris2#1871]
If we try to use the same field name and the same record name in two different namespaces, it crashes at compile time when the compiler try to generate the dotted field accessors.

# Steps to Reproduce

Compile: 

```
module Test

namespace A

  public export
  record Dup where

namespace B
  
  public export
  record Dup where
    constructor MkDup
    label : Nat
```

# Expected Behavior

Compilation should pass.

# Observed Behavior

Error:

```
Error: While processing type of .label. Ambiguous elaboration. Possible results:
    Test.B.Dup
    Test.A.Dup
```

**Comment by Russoul** [comment]
Linking #628
