### ISSUE TITLE
[ elab ] Quotation of a dependent pair type under value-returning `%runElab` results in a hole unexpectedly

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#1878]
# Steps to Reproduce

Unified examples gist (e.g., for the future regression test) [can be found here](https://gist.github.com/buzden/454d70dfc61fbdb335eb213491b91174).

Consider a primitive elaboration script that just quotates a type and logs it:

```idris
extract : Type -> Elab Unit
extract ty = logTerm "debug.elab" 0 "type" !(quote ty)
```

Consider a macro that does the same (it can have the same body as the non-macro function, it does not matter).

```idris
%macro
extract' : Type -> Elab Unit
extract' = extract
```

Consider also couple of additional declarations:

```idris
data Y : Nat -> Type where
  Y0 : Y 0
  Y1 : Y 1

X : Type
X = (n : Nat ** Y n)
```

Then use both macro and non-macro versions:

```idris
%runElab extract X

u : Unit
u = extract' X
```

Expectedly get the same logged terms:

```
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) (%lam RigW Explicit (Just n) Prelude.Types.Nat (Y n)))
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) (%lam RigW Explicit (Just n) Prelude.Types.Nat (Y n)))
```

Now, inline the `X` type in the elaboration calls:

```idris
%runElab extract (n : Nat ** Y n)      
      
u : Unit      
u = extract' (n : Nat ** Y n)
```

No change in the logged terms, as expected. Good.

---

Now, change datatype definitions a little bit:

```idris
data Y : Nat -> Type -> Type where
  Y0 : Y 0 Int
  Y1 : Y 1 Nat

X : Type
X = (n : Nat ** x : Type ** Y n x)
```

Run as in the very first example:
```idris
%runElab extract X

u : Unit
u = extract' X
```

Get expectedly same logged terms:
```
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) (%lam RigW Explicit (Just n) Prelude.Types.Nat ((Builtin.DPair.DPair %type) (%lam RigW Explicit (Just x) %type ((Y n) x)))))
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) (%lam RigW Explicit (Just n) Prelude.Types.Nat ((Builtin.DPair.DPair %type) (%lam RigW Explicit (Just x) %type ((Y n) x)))))
```

Now, inline `X` in the elaboration calls:

```idris
%runElab extract (n : Nat ** x : Type ** Y n x)

u : Unit
u = extract' (n : Nat ** x : Type ** Y n x)
```

# Expected Behavior

No change in logging, i.e.
```
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) (%lam RigW Explicit (Just n) Prelude.Types.Nat ((Builtin.DPair.DPair %type) (%lam RigW Explicit (Just x) %type ((Y n) x)))))
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) (%lam RigW Explicit (Just n) Prelude.Types.Nat ((Builtin.DPair.DPair %type) (%lam RigW Explicit (Just x) %type ((Y n) x)))))
```

# Observed Behavior

The right half of the topmost dependent pair goes to be a hole when called through a macro:

```
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) (%lam RigW Explicit (Just n) Prelude.Types.Nat ((Builtin.DPair.DPair %type) (%lam RigW Explicit (Just x) %type ((Y n) x)))))
LOG debug.elab:0: type: ((Builtin.DPair.DPair Prelude.Types.Nat) ?p)
```

**Comment by buzden** [comment]
I realised that `%macro` annotation does not matter. In the example above its enough to have
```idris
v : Unit
v = %runElab extract (n : Nat ** x : Type ** Y n x)
```

instead of call to the macro `extract'` to reach the unexpected behaviour. I.e. the mode of `%runElab` matters, whether is it a value-returning or top-level one.

**Comment by gallais** [comment]
This feels like a missing call to normalisation to inline the hole result.
