### ISSUE TITLE
Replace `ENV` var check being used to disable colors with `TTY` check.

### ISSUE THREAD

**Issue by mattpolzin** [idris-lang/Idris2#1917]
https://github.com/idris-lang/Idris2/pull/1908 introduced a `base` library function `System.File.Meta.isTTY/1` that will check whether a file handle (like `stdout`) is a terminal. Although not a perfect proxy, checking for TTY is often used to determine if the receiving file handle will support ANSI control sequences like those used to send colored text to a terminal.

Currently, the Idris 2 compiler checks the `TERM` environment variable to see if it has the value `"dumb"` and if so then it turns color output off: https://github.com/idris-lang/Idris2/blob/9865765d1dfc0a065804dcfe9c8d572664c44f5b/src/Idris/Pretty/Render.idr#L33

Checking the `TERM` environment variable is an established way of determining color support as well, but checking it for equality with `"dumb"` is a bit fragile. The code comments suggest the primary motivator for the check is emacs, which as best I can tell (without being an emacs user myself) is also _not_ going to register as a TTY device. That means that the TTY check will support existing use cases and additional situations as well.

For example, right now Idris 2 is happy to output ANSI color codes to the following Mac OS pasteboard copy command; paste the resulting text into a text editor and you'll get gibberish! A TTY check will catch that case and avoid sending ANSI codes to `pbcopy`:
```shell
idris2 --check Main.idr | pbcopy
```

**Comment by gallais** [comment]
By the way this `TERM` check is also used in the `Test.Golden` file.
(IIRC there's a bug too because we check for `"DUMB"` rather than `"dumb"`).
