### ISSUE TITLE
Type checking goes slow when type that is needed but not imported occurs using a monad

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#1925]
In the following _intentionally_ non successfully type-checking code, when C.idr is type checked, Idris takes a very long time. With every line added to the monad below, the time to type check increases at an ever increasing rate.

A.idr: https://gist.github.com/redfish64/2821c599fb0f76ec094227ce2468c8e5
```
module A

export
data AFoo = MkAFoo
```

B.idr: https://gist.github.com/redfish64/52c3128df21d883e58e2cbeeb17412a9
```
module B

import Control.Monad.State

import A

public export
X : Type -> Type
X = State AFoo
```

C.idr: https://gist.github.com/redfish64/09600b55dc0b436b5912f7a65808ef0a
```
module C

import Control.Monad.State
import B

-- there is an error in this code, since C doesn't import A, but B relies of A to describe
-- the type 'X'. Idris responds with the following appropriate error message, but takes a long time
-- to figure out what's wrong.
-- Error: While processing right hand side of foo. Undefined name A.AFoo. 

foo : X ()
foo = 
  do
    --with each uncommented "pure ()" line, the time to typecheck (resulting in an error) increases more and more
    -- real	0m1.161s
    -- user	0m1.084s
    -- sys	0m0.071s
    pure ()
    -- real	0m3.046s
    -- user	0m2.975s
    -- sys	0m0.071s
    pure ()
    -- real	0m6.214s
    -- user	0m6.121s
    -- sys	0m0.094s
    pure ()
    -- real	0m10.020s
    -- user	0m9.879s
    -- sys	0m0.140s
    pure ()
    -- real	0m13.749s
    -- user	0m13.615s
    -- sys	0m0.134s
    pure ()
    -- real	0m20.486s
    -- user	0m20.345s
    -- sys	0m0.139s
    pure ()
    -- real	0m25.057s
    -- user	0m24.889s
    -- sys	0m0.169s
    pure ()
    -- real	0m32.198s
    -- user	0m32.023s
    -- sys	0m0.175s
    pure ()
    -- real	0m39.932s
    -- user	0m39.693s
    -- sys	0m0.238s
    pure ()
```

# Steps to Reproduce

Type check

# Expected Behavior

Quickly fail.

# Observed Behavior

Slowly fails.

**Comment by Russoul** [comment]
I thought Edwin fixed it just a few weeks ago.
Are you running a recent Idris build?

**Comment by redfish64** [comment]
I just tried it with the latest commit, 971afa9f5d699f9061d473a87dd60e5649aac1ce

```
[tim@yellowhat:~/projects/idris2_learn/LongTypeChecking]$ time idris2 --build
3/3: Building C (C.idr)
Error: While processing right hand side of foo. Undefined name A.AFoo. 


real	0m44.419s
user	0m44.174s
sys	0m0.247s
```

**Comment by edwinb** [comment]
I did fix one instance of this, where it results from ambiguity, but I think there's a couple of other places where it should abandon due to unrecoverable errors earlier. I've encountered this one recently too, so this is a handy small reproducible example of it, thanks. I'm looking at it now.
