### ISSUE TITLE
buildIdris flake failing with mv error

### ISSUE THREAD

**Issue by locallycompact** [idris-lang/Idris2#1932]
Hi, I'm using the flake template from here, but it does not seem to install correctly.

https://gitlab.homotopic.tech/idris/contravariant/-/jobs/2345

```
       > mv: missing destination file operand after '/nix/store/7dw8qs6f2jdzdg06fligs1bqdnjcvcp7-contravariant/bin'
       > Try 'mv --help' for more information.
```

**Comment by locallycompact** [comment]
So I guess this is due to this line

https://github.com/idris-lang/Idris2/blob/main/nix/buildIdris.nix#L38

Which mvs build/exec, but if you don't specify an executable there is no build/exec. I get a build/ttc with the compiled module files.

**Comment by locallycompact** [comment]
Ok, I see it needs to be `defaultPackage = pkgs.installLibrary;` not `defaultPackage = pkgs.build;`. I feel like that should be the default.

**Comment by gallais** [comment]
Your best bet for this kind of issues is to ask on the nix channel on discord
