### ISSUE TITLE
idris2-0.5.0 breaks compatibility with busybox sha256sum

### ISSUE THREAD

**Issue by nmeum** [idris-lang/Idris2#1935]
Hello, I maintain a idris2 package for [Alpine Linux](https://alpinelinux.org). By default, Alpine uses a Busybox instead of GNU userland. Busybox provides several of the utilities provided by GNU coreutils. However, while it aims for POSIX compatibility it does not support all kinds of GNU extensions. idris2-0.4.0 used to work fine on Alpine, however, since 9b8de95a38c3dc501aa5ad6f46c4aeb7e57a83aa (which is included with idris2-0.5.0) the `--tag` option is used with `sha256sum`. While busybox has a `sha256sum` utility, this utility does not support the `--tag` option thus requiring installation of GNU coreutils which is a bit unfortunate.

It would be possible to add busybox to the following case distinction:

https://github.com/idris-lang/Idris2/blob/257783275ee6b4ee2e8465fffe8daf94a5679300/src/Core/Options.idr#L240-L249

however, this would require checking `busybox sha256sum` before checking for `sha256sum`, i.e. cause the busybox applet to take precedence over `sha256sum` if both are installed. Furthermore, this would require fiddling with the parsing code again as the parser currently always uses the last word from the `sha256sum` output and since busybox does not support `--tag` the checksum is always output as the first word:

https://github.com/idris-lang/Idris2/blob/9865765d1dfc0a065804dcfe9c8d572664c44f5b/src/Core/Binary/Prims.idr#L421-L423

Alternatively, it might make sense to check for openssl first, this would allow making idris depend on openssl on Alpine instead of making idris depend on the entire GNU coreutils toolchain?

**Comment by edwinb** [comment]
Given that this hash function is only used if an experimental option is set, I don't think we should be failing if the executable isn't found, but rather that experimental option shouldn't be available. I'll change its behaviour. I'm about to do a patch release anyway, for a different reason, so this change might as well be included in it.

**Comment by edwinb** [comment]
Oh, it's worse than that isn't it though, because just knowing the utility is there isn't enough, we also need to know how it works and what options it takes. I'm inclined to disable this option completely for the sake of a working portable release - we can come back to it and resolve the details after that.

**Comment by edwinb** [comment]
This should work now, since we no longer run the executable. We'll have to find another way to work out source hashes if we need it.
