### ISSUE TITLE
Non-parsing of brace application of an operator field in a record

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#1943]
# Steps to Reproduce

```idris
record Foo where
  constructor MkFoo
  (^) : Nat

AFoo : Foo
AFoo = MkFoo { (^) = 42}
```

# Expected Behavior

Type-check fine, or complain about the operator-named field `(^)`.

# Observed Behavior

```
Parse.idr line 6 col 0:
     Couldn't parse declaration.
     
     Parse:6:1--6:5
      2 |   constructor MkFoo
      3 |   (^) : Nat
      4 | 
      5 | AFoo : Foo
      6 | AFoo = MkFoo { (^) = 42}
          ^^^^
```

**Comment by gallais** [comment]
The culprit:

https://github.com/idris-lang/Idris2/blob/a0846af5fa60b3cb48a261b90660fc2f9a896d18/src/Idris/Parser.idr#L228

Should probably be also offer `parens operator`.
