### ISSUE TITLE
`runElab` can't resolve `check` under `lambda`

### ISSUE THREAD

**Issue by berewt** [idris-lang/Idris2#1946]
# Steps to Reproduce

Compile:

```
module Test
import Language.Reflection

%language ElabReflection

itPasses : Integer
itPasses = %runElab (do
  x <- check (IPrimVal EmptyFC (BI 3))
  pure x)

itFails : Integer -> Integer
itFails = %runElab (lambda Integer $ \v => do
  x <- check (IPrimVal EmptyFC (BI 3))
  pure v)
```

# Expected Behavior

Compilation passes.

# Observed Behavior

`itFails`fails... Looking at the log, it seems that the compiler isn't able to resolve `check` in the second case.

For `itPasses`:
```
LOG eval.stuck:5: Stuck function: Language.Reflection.check
LOG eval.ref.data:50: Found data constructor: Language.Reflection.Check
```

while `itFails` can't resolve `check` after:
```
LOG eval.stuck:5: Stuck function: Language.Reflection.check
```

**Comment by berewt** [comment]
I tried to pass `Language.Reflection.Elab` to `public export`. Then, if I use `Check` instead of `check`, it works.
My understanding is that the issue lies somewhere in `Core.Normalise.evalRef`, where the compiler get stuck too early, but I'm not sure how to fix it (yet).

**Comment by berewt** [comment]
Indeed, removing the `redok` check in `Core.Normalise.evalRef` solve this particular issue as well (it may introduce endless loop though (?)).

**Comment by buzden** [comment]
I'm not sure the problem is exactly in `check` inside `lambda` since this one typecheks:

```idris
itFails' : Integer -> Integer
itFails' = %runElab lambda Integer $ \v => do
  check (IPrimVal EmptyFC (BI 3))
```

So, maybe there is some problem is `>>=` under `lambda` or so? There is at least one strange behaviour related to `>>=` in elab, namely #1886.

**Comment by berewt** [comment]
Yea, I think bind plays a role there. And it's probably bind with a non empty context, as if the variable introduced by lambda locked the interpretation of the lhs of bind. But it's weird that ˋpureˋ doesn't suffer from the same limitations in a similar use.

**Comment by Russoul** [comment]
I think this issue has disappeared in the recent Idris builds. This works on my machine.

**Comment by berewt** [comment]
I still have a weird elaboration behivour that seems to be improved by setting `Elab` to `public export` IIRC, but I need to test it and provide a minimal failing example (and ideally, grasp why visibility impact it).
Not sure whether it's worth the effort as the new core may impact it too.

**Comment by berewt** [comment]
But it's more than likely antother issue, so I can close this one atm.

**Comment by Russoul** [comment]
Yeah, I definitely remember that there are visibility issues in elaborator reflection. But there is an issue for that already anyway.
