### ISSUE TITLE
Fix "TODO deprecated" in the parser

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris2#1959]
We should make this an actual warning:

https://github.com/idris-lang/Idris2/blob/a9ccf4db4f69677c5287a1278ab167247dac161d/src/Idris/Parser.idr#L798-L800

Especially now that we have a deprecation mechanism:

https://github.com/idris-lang/Idris2/blob/a9ccf4db4f69677c5287a1278ab167247dac161d/src/Idris/Parser.idr#L567

**Comment by AlexDikelsky** [comment]
Could I try to fix this issue? I tried changing the code to

```
      = withWarning "Warning message" $ do b <- bounds (do kw <- option False
                                 (decoratedKeyword fname "record"
                                   $> True)
                           decoratedSymbol fname "{"
                           commit
                           fs <- sepBy1 (decoratedSymbol fname ",") (field kw fname indents)
                           decoratedSymbol fname "}"
                           pure $ forget fs)
           pure (PUpdate (boundToFC fname b) b.val)
```
but I'm not sure how to check if that worked.

Also, is there an example of code that should trigger this warning?

**Comment by gallais** [comment]
I think you only want the warning message if the keyword is actually found.

As for test cases, this controls the fact we have two syntaxes for record
updates:

```idris
record Tuple (a : Type) where
  constructor MkTuple
  fst : a
  snd : a

-- deprecated
suc1 : Tuple Nat -> Tuple Nat
suc1 p = record { fst = S p.fst } p

-- new style
suc2 : Tuple Nat -> Tuple Nat
suc2 p = { fst := S p.fst } p
```
