### ISSUE TITLE
Shorthand version of `with` view does not parse

### ISSUE THREAD

**Issue by bkomuves** [idris-lang/Idris2#2005]
In the [chapter "Views and the `with` rule"](https://idris2.readthedocs.io/en/latest/tutorial/views.html), the Idris2 documentation claims that 

> If the view refined argument pattern is unchanged from the original function argument pattern, then the left side of | is extraneous and may be omitted

This indeed works using idris1, but not using idris2 (tested with version 0.5.1). Copying the example from the documentation:

```
filter : (a -> Bool) -> Vect n a -> (p ** Vect p a)
filter p [] = ( _ ** [] )
filter p (x :: xs) with (filter p xs)
  filter p (x :: xs) | ( _ ** xs' ) = if (p x) then ( _ ** x :: xs' ) else ( _ ** xs' )
```

the above is accepted, however the shorthand version below, again copied from the docs, is not accepted:

```
filter : (a -> Bool) -> Vect n a -> (p ** Vect p a)
filter p [] = ( _ ** [] )
filter p (x :: xs) with (filter p xs)
  | ( _ ** xs' ) = if (p x) then ( _ ** x :: xs' ) else ( _ ** xs' )
```

## Steps to Reproduce

Copy the second snippet into a new idris source file (optionally add `import Data.Vect` and `%hide Data.Vect.filter` at the beginning), and load it the REPL.

## Expected Behavior

The compiler should accept it (or the documentation should be updated; but I would prefer the short version to work).

## Observed Behavior

I got the error message

```
Error: Couldn't parse any alternatives:
1: Expected 'case', 'if', 'do', application or operator expression.

with:14:3--14:4
 10 | 
 11 | filter : (a -> Bool) -> Vect n a -> (p ** Vect p a)
 12 | filter p [] = ( _ ** [] )
 13 | filter p (x :: xs) with (filter p xs)
 14 |   | ( _ ** xs' ) = if (p x) then ( _ ** x :: xs' ) else ( _ ** xs' )
        ^
... (37 others)
```

**Comment by gallais** [comment]
I don't know that it has ever worked in Idris2.
I have recently added ellipsis which you can see a bit further down the file.

I suppose we should remove that outdated part of the manual.

**Comment by bkomuves** [comment]
I think this can be closed now, as the documentation build is fixed.
