### ISSUE TITLE
Wrong totality check

### ISSUE THREAD

**Issue by jinwoo** [idris-lang/Idris2#202]
The sample code below shows that the totality checker mistakenly thinks the `case` expression covers all the cases when it's actually missing the `Just FZ` case.

# Steps to Reproduce

File: test.idr

```idris
module Main

import Data.Strings
import Data.Vect
import System

%default total

ints : Vect 4 Int
ints = [1, 2, 3, 4]

main : IO ()
main = do
  [_, arg] <- getArgs
      | _ => do putStrLn "One argument expected."
                exitFailure
  let n = stringToNatOrZ arg
  case natToFin n (length ints + 1) of
       Nothing => do putStrLn "Invalid number."
                     exitFailure
       Just (FS i) => putStrLn $ "Value: " ++ show (index i ints)
```

# Expected Behavior

The compiler must report that there's a missing case `Just FZ`.

# Observed Behavior

The code compiles fine. And in the REPL, `:total main` says `Main.main is total`. And the program crashes at run-time when given the value `0`.

```
$ ./build/exec/test 0
ERROR: Unhandled input for Main.case block in 2621(311) at test.idr:13:1--22:1
```

**Comment by edwinb** [comment]
The fact that the program crashes with that message at run time suggests that the coverage checker is calculating coverage correctly, but something is stopping it reporting the result.

**Comment by jinwoo** [comment]
👍
