### ISSUE TITLE
Slow typechecking on `Int` operation when `Data.Fin.fromInteger` is in scope

### ISSUE THREAD

**Issue by cypheon** [idris-lang/Idris2#2032]
# Steps to Reproduce

```idris
import Data.Fin

addMillion : Int -> Int
addMillion x = 2000000 + x
```

`idris2 --timing --check AddMillion.idr`

# Expected Behavior

Program should typecheck within a reasonable time.

# Observed Behavior

Idris2 uses lots of memory and takes a long time. With a larger number (e.g. 20 million), it uses >8GB ram and is not finished after 5 minutes.

```
1/1: Building AddMillion (AddMillion.idr)
TIMING ++ Parsing AddMillion.idr: 0.000s
TIMING ++ Reading imports: 0.077s
TIMING +++ Check RHS AddMillion:4:1--4:27: 14.894s
TIMING +++ Building compile time case tree for Main.addMillion: 0.000s
TIMING +++ Building size change graphs Main.addMillion: 0.000s
TIMING +++ Checking Coverage Main.addMillion: 0.000s
TIMING +++ Totality check overall: 0.000s
TIMING ++ Processing decls: 14.895s
TIMING ++ Compile defs: 0.000s
TIMING + Elaborating AddMillion.idr: 14.973s
TIMING + Build deps: 15.076s
TIMING + Loading main file: 15.078s
```

# Additional Notes

A bisect shows this was introduced by d4263441b7fe13e483d0363878b05ddef913e280 and is probably related to (the type of?) the new `fromInteger` implementation.
Maybe there is a way to somehow "deprioritize" the `fromInteger` from `Fin` so that `fromInteger : Integer -> Int` is tried first?

# Workarounds

There are a few workarounds available, all of which make typechecking finish within ~200ms:

Reverse the operands:
```idris
addMillion x = x + 2000000
```

Force type of the integer literal:
```idris
addMillion x = the Int 2000000 + x
```

Hide `fromInteger`:
```idris
%hide Data.Fin.fromInteger
addMillion x = 2000000 + x
```

**Comment by gallais** [comment]
> Maybe there is a way to somehow "deprioritize" the fromInteger from Fin so that fromInteger : Integer -> Int is tried first?

I don't think that's possible: the `Int` one comes from the `Num` implementation and the monomorphic
alternative will always be tried first.

**Comment by andrevidela** [comment]
Maybe a warning that large numbers might be slow to compile would help?

**Comment by gallais** [comment]
668c2214748cbae457f5d011174ec483e6ceabc2 has introduced a big slow down to frex so chances are we will revert this and the final fix will have to be different

**Comment by cypheon** [comment]
A bit of background how I discovered this: In an older Idris2 version, the following code was compiling fine for me:

```idris
import Data.Vect
[...]
makeNameId : Int -> Int
makeNameId nid = 0x80000000 + nid
```

After an update to a newer Idris2 version, the compilation seemed stuck. Which caught me a bit off guard and it took a while to find the offending line in a larger source file. After that, it was quite easy to find several workarounds.

I could imagine other users stumbling upon this, so I'm trying to think of ways to at least make it unlikely that this happens by accident (I assume the number of people writing `0x80000000` and expecting it to be typed as `Fin 0x80000001` is quite small).

Unfortunately, I don't understand why the change to the type of `Fin.fromInteger` in d4263441b7fe13e483d0363878b05ddef913e280 was done, how the performance regression is caused, and if it can be reworked (or maybe even partially reverted?).

In case the `%unhide` proposal (#2138) is accepted, maybe it could be an option to `%hide` `Fin.fromInteger` by default and let users that need it `%unhide` it on demand? However, this kind of behaviour would of course need to be documented well.

**Comment by bkomuves** [comment]
I believe there are several related issues here, but this particular one seems to be caused by the proof search in  `Fin.fromInteger`: It asks for a proof of inequality between two `Nat`-s, but `Nat`-s are not (yet) optimized at compile time (they really use the unary representation).

The following alternative implementation of the relevant parts of `Data.Fin` demonstrates this, and also gives a possible (if hacky) fix:

```
public export
data Fin : (n : Nat) -> Type where
    FZ : Fin (S k)
    FS : Fin k -> Fin (S k)

public export
last : {n : _} -> Fin (S n)
last {n=Z} = FZ
last {n=S _} = FS last

unsafeNatToFin : (x : Nat) -> Fin n
unsafeNatToFin x = believe_me (last {n=x})

unsafeIntegerToFin : (x : Integer) -> Fin n
unsafeIntegerToFin x = unsafeNatToFin $ cast {from=Integer} {to=Nat} x

-- fast
public export
fromInteger : (x : Integer) -> {n : Nat} -> {auto 0 prf : So (x < cast {from=Nat} {to=Integer} n)} -> Fin n
fromInteger x = unsafeIntegerToFin x

-- slow
public export
fromInteger' : (x : Integer) -> {n : Nat} -> {auto 0 prf : So (cast {from=Integer} {to=Nat} x < n)} -> Fin n
fromInteger' x = unsafeIntegerToFin x
```

If you replace `Data.Fin` by this library, then the above example compiles with normally speed using the "fast" version, but slowly if you replace `fromInteger` by the slow `fromInteger'` version.
