### ISSUE TITLE
"instance arguments" to allow to pass custom interface/class implementations to the functions

### ISSUE THREAD

**Issue by srghma** [idris-lang/Idris2#205]
in agda class implementations are "first class objects"

https://agda.readthedocs.io/en/v2.6.1/language/instance-arguments.html#instance-resolution

one can pass implementations with `{{ ... }}` brackets

e.g. something like this should be possible, thought I didnt try really

```agda
open import Data.Nat
open import Data.Bool
open import Data.List

record Eq {a} (A : Set a) : Set a where
  field
    _==_ : A → A → Bool

open Eq {{...}} public

instance
  eqList : ∀ {a} {A : Set a} → {{Eq A}} → Eq (List A)
  _==_ {{eqList}} []       []       = true
  _==_ {{eqList}} (x ∷ xs) (y ∷ ys) = x == y && xs == ys
  _==_ {{eqList}} _        _        = false

  eqNat : Eq Nat
  _==_ {{eqNat}} = natEquals

myEqNat : Eq Nat -- instance that always returns true
_==_ {{myEqNat}} = true

ex : Bool
ex = (1 ∷ 2 ∷ []) == (1 ∷ 3 ∷ []) -- returns false

ex1 : Bool
ex1 = (1 ∷ 2 ∷ []) (== {{myEqNat}}) (1 ∷ 3 ∷ []) -- returns true
```

**Comment by edwinb** [comment]
You can already do this, using either `@{myInterface}` to give an explicit value for the next auto implicit, or by using the usual `{c = myInterface}` to give an explicit value for the argument `c`, if it happens to be named in the type.

**Comment by edwinb** [comment]
Details here: https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html#named-implementations

**Comment by srghma** [comment]
tnx, didnt know this possible, awesome language
