### ISSUE TITLE
Align FFI with C FFI

### ISSUE THREAD

**Issue by xavierzwirtz** [idris-lang/Idris2#2062]
## Summary

I am working on creating an Idris library to wrap raylib. This is currently quite painful due to raylib preferring to use pass by value instead of pass by reference wherever possible. Due to Idris use of Chez Scheme as its primary backend, Chez Schemes opinions of struct FFI has influenced Idris implementation of `Struct`. There are two separate issues, functions that return a struct by value, and accessing a member of a struct that is a value struct instead of a pointer to a struct.

A possible solution to functions that return a struct by value is to update to support the chez (&) ftype. However this method still allocates a pointer and places the value at that pointer. This will have some performance ramifications that are unavoidable when using the chez backend, however when using the RefC backend I think it would be better to directly match the C FFI and not require wrapping all struct values with pointers.

As far as accessing members of a struct that are a value struct, that is currently unsupported by chez scheme.

These issues drive towards the current implementation of FFI within idris being mapped to chez schemes subset of the C FFI, instead of the more primordial C FFI. This causes pain and performance loss when doing FFI with C from within the RefC backend.

## The proposal

I think a possible solution would be creating a lower level FFI that directly maps to the C FFI that can be utilized when using RefC. Then from this lower level FFI a subset could be derived that supports the chez backend.

**Comment by locriacyber** [comment]
[C99 also defines a lot of other types](https://en.cppreference.com/w/c/language/type) like 32-bit IEEE floating point number and complex numbers. Each backend should have its own supported FFI data types.

**Comment by xavierzwirtz** [comment]
The compiler currently computes a `CFType` only for `MkForeign`, the `CFType` does not get attached to the return type of `MkForeign` in a usable fashion. I believe that for `prim__getField` to work `CFType` needs to be attached to the expression so that when compiling an application of `prim__getField` the accessed fields `CFType` can be used to call `packCFType` and pack it for the RefC runtime.

**Comment by ColeDeanShepherd** [comment]
How did you solve this, Xavier?

**Comment by xavierzwirtz** [comment]
I cut bait and moved on. The memory model of Idris as it stands does not align well with passing by struct.

**Comment by GunpowderGuy** [comment]
> I cut bait and moved on. The memory model of Idris as it stands does not align well with passing by struct.
Please, could you elaborate?

Do you mean that idris2 is too tied to chezscheme to not follow its ffi limitations ?
