### ISSUE TITLE
Incorrect parenthesization in pretty-printed type signature

### ISSUE THREAD

**Issue by gergoerdi** [idris-lang/Idris2#2072]
(originally discovered using `idris2-dom`, but simplified below to be self-contained)

```
import Data.List.Elem

public export
Types : (0 a : Type) -> Eq a => List Type

export
body :  (0 _ : Eq t1)
     => {auto 0 _ : Elem Bool (Types t1)}
     -> (obj : t1)
     -> IO ()
```

Loading this file, Idris 2 shows the following type for the hole `body`:

```
- + Main.body [P]
 `-- {auto 0 conArg : Eq t1} -> {auto 0 _ : Elem Bool Types t1} -> t1 -> IO ()
```

This is wrong, because the type of the witness should be `Elem Bool (Types t1)`, i.e. `Types` is a function that is applied on `t1`.

Interestingly, removing the `Eq a` constraint from `Types` fixes this:

```
import Data.List.Elem

public export
Types : (0 a : Type) -> List Type

export
body :  (0 _ : Eq t1)
     => {auto 0 _ : Elem Bool (Types t1)}
     -> (obj : t1)
     -> IO ()
```

```
- + Main.body [P]
 `-- {auto 0 _ : Eq t1} -> {auto 0 _ : Elem Bool (Types t1)} -> t1 -> IO ()
```

**Comment by gallais** [comment]
Thank you. There are indeed a few bugs in the pretty printer (including when `Delay`
is involved). It's good to have a small test case.
