### ISSUE TITLE
Infinite hang with `extraRuntime` set to a directory instead of a file

### ISSUE THREAD

**Issue by gwerbin** [idris-lang/Idris2#2079]
# Steps to Reproduce

Run:
```sh
idris2 --directive extraRuntime=/any/directory --exec 'anything'  Anything.idr
```

# Expected Behavior

Compiler exits with an error, informing the user that `extraRuntime` must refer to a file, not a directory.

# Observed Behavior

The program produces no output and appears to hang indefinitely, using a significant fraction of CPU (65% at minimum, sometimes as high as 95%).

It can be killed with `Ctrl-C`, although the longer you leave this running the longer it takes to respond and exit. Maybe there is some kind of infinite loop?

**Comment by gwerbin** [comment]
I misunderstood the docs. `extraRuntime` should be a single file.

However, the right thing to do here should probably just be to crash with an error, rather than hang forever.

**Comment by gallais** [comment]
I'm getting

> Error: File error in /any/directory : File Not Found

**Comment by gwerbin** [comment]
> I'm getting
> 
> > Error: File error in /any/directory : File Not Found
> 
> Edit: I'm being daft. I've tried with a directory that actually exists and:
> 
> > Error: File error in Dog : Is a directory

Huh! Did you try it with a filename like `.` or `./support/chez`?

**Comment by gallais** [comment]
> Error: File error in . : Is a directory
> Error: File error in ./support/chez/ : Is a directory

**Comment by gwerbin** [comment]
I don't know if I can reproduce this. I will close and make a new issue if it comes up again.
