### ISSUE TITLE
[Proposal] A new `%deprecate` pragma

### ISSUE THREAD

**Issue by mattpolzin** [idris-lang/Idris2#2082]
- [x] I have read [CONTRIBUTING.md](../../CONTRIBUTING.md).
- [x] I have checked that there is no existing PR/issue about my proposal.

## Summary

I propose we add a `%deprecate` pragma that has the behavior of marking the following definition such that when that definition is used the compiler produces a warning to the effect of "_x_ is deprecated and will be removed in a future version." 

## Motivation

It can be very useful for API and package developers to let consumers know that it is no longer recommended to use part of the API and furthermore that part of the API will be removed in the future.

This allows a package author to phase out old code over the course of more than one release version while giving consumers a heads up that they should change their code.

## The proposal

I propose we add a no-argument `%deprecate` pragma

I suggest "deprecate" as a command much like "nomangle" and "noinline" rather than using the past-tense ("deprecated") that otherwise would also feel natural to me.

The `%deprecate` pragma would be used just prior to a definition that the developer wants to mark as deprecated. This means the following stylistic choices are all valid:
```idris
%deprecate
export
foo : String -> String
foo x = x
```

```idris
export
%deprecate
foo : String -> String
foo x = x
```

```idris
export %deprecate
foo : String -> String
foo x = x
```

```idris
%deprecate export
foo : String -> String
foo x = x
```

The `%deprecate` pragma causes the compiler to produce a warning at the call site, not the definition site. This means the above examples do not produce compiler warnings, but the following example does:
```idris
bar : String
bar = foo "hello"
```

The exact wording of the warning is less critical to the proposal, but I propose the above produce the warning:
```shell
Warning: Deprecation warning: Main.foo is deprecated and will be removed in a future version.
```

It is often useful to provide some guidance to the end-user to help them modify their code to produce the same results without using the now-deprecated function. I propose we co-opt the existing documentation mechanism for this purpose.

For example, suppose that instead the above `foo` was defined as:
```idris
||| Please use @id@ instead. `foo` was always just a specialized form of @id@ anyway.
%deprecate
export
foo : String -> String
foo x = x
```

The warning produced by the above `bar` definition would now be:
```shell
Warning: Deprecation warning: Main.foo is deprecated and will be removed in a future version.
  Please use @id@ instead. `foo` was always just a specialized form of @id@ anyway.
```

### Technical implementation

Although I am still accepting feedback on the proposal, I encourage you to check out the pull request and see how it feels: https://github.com/idris-lang/Idris2/pull/2086.

## Alternatives considered

Two alternatives are worth mentioning because they both came up during Discord conversations.

1. The `%deprecate` pragma could be passed a `String` argument (maybe optional) that would describe the deprecation.
2. The `%deprecate` pragma could be passed a `Version` argument indicating the version at which the deprecated definition will be removed entirely.

I feel that using the existing code-doc feature (`|||` comments) to provide the same space for describing the deprecation as a `String` argument would have is an elegant way to keep complexity down. I firmly believe that both from the perspective of a compiler developer and from the perspective of an end-user, fewer "special" or "one-off" things are better.

There are three reasons I am not proposing we immediately add a `Version` argument to the pragma. First, the pragma can gain support for a `Version` argument later (I feel it should not be required, anyway, because deprecation should not always need to be tied to a known timeline). Second, a `Version` argument will carry a fair bit of complexity (which makes it even nicer to be able to add it as a separate and second stage). Third, I am not convinced that an argument to the pragma is the best way to get the functionality described in Discord: End users are informed of the removal version and the source code with the deprecated definition stops compiling at the indicated version forcing removal of the code. More on the subject of how I think that functionality could look later assuming others agree that it can be a separate concern.

## Conclusion

We've had the ability to produce deprecation warnings in the compiler for a bit now -- let's expose that to end-users to deprecate their own definitions (and additionally use where & when relevant to standard library development)!

**Comment by jfdm** [comment]
Just to add that this brings across another pragma that Idris1 had. So kudos.
