### ISSUE TITLE
Multiline strings issue when running tests on Github CI

### ISSUE THREAD

**Issue by ska80** [idris-lang/Idris2#2087]
This is a follow-up issue to PR #2044 

The `idris2/pkg003` test always fails on Windows and NixOS when running tests on Github CI.  Running tests locally doesn't exhibit this problem.

# Steps to Reproduce

Re-run all CI workflows for PR #2044 (before the `4cb83984c` commit)

# Expected Behavior

All started CI workflows should finish successfully.

# Observed Behavior

The `idris2/pkg003` test always fails on Windows and NixOS (`windows-bootstrap-chez` and `nix-bootstrap-chez` workflows) with the following error:
```
idris2/pkg003: FAILURE                                           02.882s
Expected:
1/1: Building Main (Main.idr)
Not all command line options can be used to override package options.

Overridable options are:
    --quiet
    --verbose
    --timing
    --log <log level>
    --dumpcases <file>
    --dumplifted <file>
    --dumpvmcode <file>
    --debug-elab-check
    --codegen <cg>
    --directive <directive>
    --build-dir <dir>
    --output-dir <dir>

Packages must have an '.ipkg' extension: "malformed-package-name".
Uncaught error: File error (non-existent-package.ipkg): File Not Found

Given:
1/1: Building Main (Main.idr)
Not all command line options can be used to override package options.
Overridable options are:
    --quiet
    --verbose
    --timing
    --log <log level>
    --dumpcases <file>
    --dumplifted <file>
    --dumpvmcode <file>
    --debug-elab-check
    --codegen <cg>
    --directive <directive>
    --build-dir <dir>
    --output-dir <dir>

Packages must have an '.ipkg' extension: "malformed-package-name".
Uncaught error: File error (non-existent-package.ipkg): File Not Found
```

**Comment by CodingCellist** [comment]
Copying gallais's message from the discord:

> We've disabled a test on the windows CI [for pr #2722] because it would fail in a really incomprehensible & irreproducible way. If someone can reproduce it & is willing to investigate, we'll happily accept PRs :slightly_smiling_face:

**Comment by dunhamsteve** [comment]
I believe the underlying issue here is that nix is using a bootstrapped compiler to run the tests. I've reproduced this on nixos with the same command that CI uses:
```
nix-build -A checks.x86_64-linux
```
And it reproduces in `nix-shell` and a plain build on macos, if I just do a bootstrap followed by test, without rebuilding the compiler with the bootstrapped version.

**Comment by andylokandy** [comment]
The cause of the problem might be the way the multiline parser handles line wraps in Windows, where the "\r\n" line wrap is seen as two separate line wraps. We might try [setting](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings#:~:text=text%20eol%3Dcrlf-,*%20text%20eol%3Dlf,-The%20first%20one) "LF" as the eol in the ".gitattributes" file.
