### ISSUE TITLE
Data.String.Parser contains an infinite loop

### ISSUE THREAD

**Issue by bkomuves** [idris-lang/Idris2#2099]
In `Data.String.Parser` (from contrib), the functions `some` and `many` cause an infinite loop (and memory consumption blows up too). For some reason (see below for more details), this only appears to happen in the interpreter / REPL, but not in the chez backend, which I guess why it wasn't noticed before (I haven't checked the other backends).

I believe the reason for this is how `some` is defined:
```
mutual
    some : Monad m => ParseT m a -> ParseT m (List a)
    some p = [| p :: many p |]     
    --       ^^^^^^^^^^^^^^^^^
    -- I believe this is desugared to:
    -- some p = (::) <$> p <*> many p

    many : Monad m => ParseT m a -> ParseT m (List a)
    many p = some p <|> pure []
```

Calling `some p` evaluates `p <*> many p` which evaluates `many p` which in turns evaluates `some p`, and so on...

This can be fixed by either using a version of `<*>` which is lazy in the second argument, or by using do notation:
`some p = do { x <- p ; xs <- ps ; pure (x::xs) }`. I'm not sure if the latter results in a worse performance or not.

### Comparison with GHC

I managed to reproduce the above with GHC too (by replicating the relevant parts of the `Data.String.Parser` using strictness annotations to emulate the same behaviour), and basically the same thing happens: 
- it loops in GHCi
- if the parser type is a newtype or just a function, then it works when compiled with optimizations
- if the parser type is data type with a single strict field, then it loops even when compiled with optimization. But in Haskell that's different from a newtype, while I guess in a strict language like Idris these two notions (newtype and single-constructor data type with a single argument) should agree?

So I'm guessing that chez is eliminating the single constructor and doing some optimizations which somehow eliminates the issue; but with the "official semantics", I think it should in fact loop?

## Steps to Reproduce

In the REPL, type 
```
:module Data.String.Parser
parse (many letter) "hello"
```

## Expected Behavior

It should print
```
Right (['h', 'e', 'l', 'l', 'o'], 5)
```
which is what `:exec parse (many letter) "hello"` does.

## Observed Behavior

Infinite loop and memory consumption blowup.

## Meta

There should be maybe a template for library issues?

**Comment by bkomuves** [comment]
By the way, this bug was introduced by commit 969f5443a9a728e9f8fa9709c5d893324a140f16

Before that, `some` was define as `some p = pure (!p :: !(many p))`, which does not have this problem.

**Comment by nmeum** [comment]
I am also running into this. @clayrat since you authored 969f544 do you have any idea how this would be resolved best?
