### ISSUE TITLE
Named interfaces do not simplify in typechecker

### ISSUE THREAD

**Issue by alebahn** [idris-lang/Idris2#2105]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
Compile the following:

```
import Control.WellFounded

%default total

sumSize : Sized a => List a -> Nat 
sumSize [] = 0 
sumSize (x :: xs) = size x + sumSize xs

[listSumSize] Sized a => Sized (List a) where
  size = sumSize


sizeIsSumSize : Sized a => (list : List a) -> size @{listSumSize} list = sumSize list
sizeIsSumSize list = Refl
```

# Expected Behavior
This typechecks

# Observed Behavior
You get this error:
```
Error: While processing right hand side of sizeIsSumSize. Can't solve constraint between: sumSize list and size list.

NamedSize:14:22--14:26
 10 |   size = sumSize
 11 |
 12 |
 13 | sizeIsSumSize : Sized a => (list : List a) -> size @{listSumSize} list = sumSize list
 14 | sizeIsSumSize list = Refl
                           ^^^^
```

**Comment by buzden** [comment]
This is expected behaviour. You you name that start with a little letter which by convention means that it is quantified, like name `a` in the same signature. You need to use either a name start starts with a capital letter, or fully qualify your current name in the signature, or play with `%unbound_implicits off` pragma.

**Comment by gallais** [comment]
As @buzden said. You should get a warning from idris when loading the module you posted:

> Warning: We are about to implicitly bind the following lowercase names.
You may be unintentionally shadowing the associated global definitions:
  listSumSize is shadowing Main.listSumSize
