### ISSUE TITLE
Commit af27bce2e22e0093dac0b819dbc4a318d8fab49b breaks valid literate code

### ISSUE THREAD

**Issue by petithug** [idris-lang/Idris2#211]
Commit af27bce2e22e0093dac0b819dbc4a318d8fab49b in the old Idris2 repo breaks valid literate code:

- A Bird mark alone (i.e. no space after it) is valid.
- A code block must start with an empty line (unless it is at the beginning of the file) and must end with an empty line (unless it is at the end of the file).
- ">" symbols elsewhere in the text are interpreted as Bird marks (i.e. not just at the beginning of a line).
- Processing a literate file with 100000 empty lines takes 27 seconds, whereas a non-literate file with the same number of empty lines takes only 2 seconds.

Additionally there is no such thing as a reversed Bird mark.

Please revert commit af27bce2e22e0093dac0b819dbc4a318d8fab49b.

**Comment by gallais** [comment]
The commmit in question: https://github.com/edwinb/Idris2-boot/commit/af27bce2e22e0093dac0b819dbc4a318d8fab49b

Ping @jfdm 

I don't agree with the "please revert" strategy. This commits adds new literate
modes that are useful. If there is a bug it makes sense to fix it but we should
not get rid of all of its content...

**Comment by petithug** [comment]
I updated the bug with the third thing that breaks literate code.

**Comment by petithug** [comment]
And added a final fourth issue with that commit.

**Comment by petithug** [comment]
I stand by my recommendation of reverting that commit.  Removing the literate part should be part of a preprocessing step, not of the tokenization step.  I am annotating (with Idris code) texts that are hundreds of pages long, and that commit is preventing that.  In the old idris2 repo I just reverted the commit in my private branch but for some reason the reverted patch no longer applies in the new repo.

**Comment by jfdm** [comment]
Sorry, i have been busy on annual leave, and won't necessarily have the time to address this any time soon.

> A Bird mark alone (i.e. no space after it) is valid.

I somewhat disagree with this, but we could rewrite the code to accept this.

>  A code block must start with an empty line (unless it is at the beginning of the file) and must end with an empty line (unless it is at the end of the file).

The code I submitted should take this into account.

>  ">" symbols elsewhere in the text are interpreted as Bird marks (i.e. not just at the beginning of a line).

The code I submitted should take this into account, but a minimal failing example we can add to the test suit would be appreciated.

> Processing a literate file with 100000 empty lines takes 27 seconds, whereas a non-literate file with the same number of empty lines takes only 2 seconds.

Presumably, this will be dependent upon how fast Idris' lexer is, and maybe to a certain extent how the lexers used by `Text.Literate` are defined. There *might* be gains to find here, I am not sure.

> Additionally there is no such thing as a reversed Bird mark.

I think this is a moot point, and can be seen as a improvement upon the literate style.

**Comment by petithug** [comment]
Here's the current test for my fix restoring the previous processing for Bird marks (so I can continue working):

----
> module Lit
>
> %default total

a > b

< not a line of code
----

Also here's the speed comparisons, first for the current code:
- idris2 with 100000 empty lines: 1.56s
- literate idris2 with 100000 empty lines: 28s
- literate idris2 with 100000 lines with text: 3141s

After restoring the code I wrote for Bird marks:
- literate idris2 with 100000 empty lines: 28s
- literate idris2 with 100000 lines with text: 110s

**Comment by jfdm** [comment]
Ah, I misread your statement about misidentified bird marks! I though the Idris code was being mangled not the non-code blocks. Sorry about that.

**Comment by gallais** [comment]
The motivating example

```idris
> module Lit
>
> %default total

a > b

< not a line of code
```
seems fixed so I'll close for now.
