### ISSUE TITLE
Source directory "." not recognized as current directory

### ISSUE THREAD

**Issue by locriacyber** [idris-lang/Idris2#2122]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
Create a new directory and add the following files **in the same directory**.

test.ipkg
```
package test
modules = Reverse
sourcedir = "."
```

Reverse.idr
```
reverse : List a -> List a
reverse xs = revAcc [] xs where
  revAcc : List a -> List a -> List a
  revAcc acc [] = acc
  revAcc acc (x :: xs) = revAcc (x :: acc) xs

main : IO ()
main = ()
```

Then run `idris2 --check --find-ipkg Reverse.idr`
# Expected Behavior
idris should recognize the source directory is current directory.
# Observed Behavior
```
> idris2 --check --find-ipkg Reverse.idr
Uncaught error: Error: Error: Source file "Reverse.idr" is not in the source directory "/tmp/test/idris/."
```

Related to https://github.com/bamboo/idris2-lsp-vscode/issues/6

**Comment by ohad** [comment]
This might have something to do with the `--find-ipkg`, because `idris2 --build test.ipkg` works as expected.

**Comment by buzden** [comment]
A tiny note:

> ```diff
> +    sdir = fromMaybe "" $ do
> +             sdir <- msdir
> +             guard (sdir /= ".")
> +             pure sdir
> ```

looks like

```diff
+    sdir = fromMaybe "" $ filter (/= ".") msdir
```

**Comment by locriacyber** [comment]
This fix feels very not portable and does not handle things like "abcde/..". Then again, I'm not sure if it's worth it.

Path is OS dependent, and we should use implementation provided by the OS like [std::filesystem::current_path](https://en.cppreference.com/w/cpp/filesystem/current_path) if we really want to get it right.
