### ISSUE TITLE
Type checker issue with type defined by induction on an argument

### ISSUE THREAD

**Issue by jakeelituv** [idris-lang/Idris2#215]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
```
In : (x : a) -> (l : List a) -> Type
In x [] = Void
In x (x' :: xs) = (x' = x) `Either` In x xs

appendEmpty : (xs : List a) -> xs ++ [] = xs
appendEmpty [] = Refl
appendEmpty (x :: xs) = rewrite appendEmpty xs in Refl

in_app_iff : {l : List b} -> {l' : List b} -> In a (l++l') -> (In a l `Either` In a l')
in_app_iff {l = []} {  l' = []} x = Left x
in_app_iff {l = []} {  l' = (y :: xs)} x = Right x
in_app_iff {l = (y::xs)} {  l' = []} x = rewrite sym (appendEmpty xs) in Left x
in_app_iff {l = (y::xs)} {l' = (z::ys)} (Left prf) = Left (Left prf)
in_app_iff {l = (y::xs)} {l' = (z::ys)} (Right prf) =
                                          let induc : Either (In a xs) (Either (z = a) (In a ys))= in_app_iff {l = xs} {l' = z :: ys} prf  in
                                          case induc of
                                                (Left l) => Left $ Right l
                                                (Right r) => Right r
```
# Expected Behavior
Should compile since
```
induc : Either (In a xs) (Either (z = a) (In a ys))
-------------------------------------
hole : Either (Either (y = a) (In a xs)) (Either (z = a) (In a ys))

```
is what is shown by the type checker when the case expression is replaced by ?hole.
Also it compiles on Idris 1. Defining `In` instead by the following 
```
data In : a -> List a -> Type where
  Left  : (x' = x) -> In x (x' :: xs)
  Right : In x xs -> In x (x' :: xs)
```

solves the issue. (Thanks to @gallais  for pointing this out)

# Observed Behavior
Type checks up until the very last line and then there's an error:
```
When unifying Either (z = xs) (In xs ys) and Either (z = a) (In a ys)
Mismatch between:
	xs
and
	a

```

**Comment by edwinb** [comment]
I think this is probably because in Idris 1, `case` abstracts over the value being inspected in the type, and in Idris 2 it doesn't. This is the first thing I've seen that's affected by that. I guess we should have the Idris 1 behaviour, but it does have the potential to be very slow since it requires evaluating the type to be sure all occurrences are found. I suppose that could be done syntactically, but then it's not as general. We have a similar potential performance problem with `with`.

**Comment by gallais** [comment]
This now works.
