### ISSUE TITLE
Parameterized type inside type interface

### ISSUE THREAD

**Issue by nickdrozd** [idris-lang/Idris2#2195]
When writing an interface for a generic type, I would like to be able to use that type as a parameter for other types, like this:

```idris
interface
Interface ty where
  TyList : Type
  TyList = List ty

  TyCount : Type
  TyCount = (Nat, ty)

  function : ty -> TyList -> TyCount
```

But I get this response:

```
     While processing right hand side of {Default implementation of TyList:0}. ty is not accessible in
     this context.
     
     asdf:4:17--4:19
      1 | interface
      2 | Interface ty where
      3 |   TyList : Type
      4 |   TyList = List ty
                          ^^
```

Is this the expected behavior? I don't know if this is a bug report or a feature request, but I would like to be able to do it.

**Comment by gallais** [comment]
You can either:

1. make `ty` runtime relevant by using the telescope syntax instead of the name-only one: `interface (ty : Type) where (...)`
2. make `TyList` runtime irrelevant by writing `0 TyList : Type`

**Comment by nickdrozd** [comment]
That solved part of my problem. Here's another part. This typechecks fine:

```idris
interface
Interface (ty : Type) where
  TyList : Type
  TyList = List ty

  f : List ty -> Bool

implementation
{ty : Type} -> Interface ty => Eq (List ty) where
  x == y = f x && f y
```

(It isn't the problem, but notice the required "explicit implicit" in the implementation signature.)

Now I would like for `f` to work on `TyList`:

```idris
interface
Interface (ty : Type) where
  TyList : Type
  TyList = List ty

  f : TyList -> Bool
```

As per the suggestion, this typechecks. But now the implementation doesn't work:

```idris
interface
Interface (ty : Type) where
  TyList : Type
  TyList = List ty

  f : TyList -> Bool

implementation
{ty : Type} -> Interface ty => Eq (List ty) where
  x == y = f x && f y
```

```
 `-- asdf.idr line 10 col 11:
     While processing right hand side of ==. Can't find an implementation for Interface ?ty.
     
     asdf:10:12--10:15
      06 |   f : TyList -> Bool
      07 | 
      08 | implementation
      09 | {ty : Type} -> Interface ty => Eq (List ty) where
      10 |   x == y = f x && f y
                      ^^^     
```

Is there a way to tell the implementation that `TyList` is the same as `List ty`? Or implement `Eq TyList` directly?

**Comment by buzden** [comment]
> Is there a way to tell the implementation that `TyList` is the same as `List ty`?

This is not true in the general case. `TyList` in your declaration is defined as `List ty` only **by default**. So, any implementation of the interface `Interface` can declare `TyList` to any type it wants. You may want to add a value of some type like `TyList = List ty` to your interface, but this seems to show some design flaw.

**Comment by nickdrozd** [comment]
> This is not true in the general case. `TyList` in your declaration is defined as `List ty` only **by default**. So, any implementation of the interface `Interface` can declare `TyList` to any type it wants. You may want to add a value of some type like `TyList = List ty` to your interface, but this seems to show some design flaw.

That's a great observation, and indeed there was a design flaw in my interface. Thanks!
