### ISSUE TITLE
realpath does not exist on Mac

### ISSUE THREAD

**Issue by vfrinken** [idris-lang/Idris2#221]
trying to install Idris2 in a Mac using
`make bootstrap SCHEME=chez`
aborts with an error message that `realpath` cannot be found, which is not surprising, since realpath doesn't exist.

i propose to include something like this
```bash
realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}
```
(found in https://github.com/whatwg/html-build/issues/90)

**Comment by keram** [comment]
Hi @vfrinken realpath is required for installation and as mentioned in https://github.com/idris-lang/Idris2/blob/master/INSTALL.md  you can install it on Mac as part of coreutils
`brew install coreutils` 
cheers!

**Comment by ska80** [comment]
I believe this issue can be closed.

**Comment by gallais** [comment]
Fixed by Homebrew/homebrew-core/pull/71562

**Comment by gallais** [comment]
Can we check in the makefile that the required dependencies are
installed & complain if it's not the case?

**Comment by ska80** [comment]
> Can we check in the makefile that the required dependencies are
> installed & complain if it's not the case?

This PR #1210 checks if `realpath` exists for Chez and Racket backends. I didn't put this check in the makefile because only Chez and Racket use `realpath` at the moment.

**Comment by benhormann** [comment]
> Can we check in the makefile that the required dependencies are
> installed & complain if it's not the case?

Not really, it is also a runtime dependency i.e. compiled "Hello world" app includes same script.

Racket's `raco exe` has an option to include libs, maybe it is possible to embed the support lib? Chez mentions concatenating object files. Failing that, a shell imitation of realpath isn't a bad way to go (easy to fix when it breaks).

---

```shell
## The following is equivalent to: DIR=$(dirname $(realpath $0))
## Non-GNU systems don't always have realpath/grealpath installed.
DIR=$PWD
LINK=$0
while [ -n "$LINK" ]; do
  # If LINK is not absolute, join with DIR.
  [ -n "${LINK##/*}" ] && LINK=$DIR/$LINK
  DIR=$(dirname "$LINK")
  LINK=$(readlink "$LINK")
done
# Canonicalize path.
DIR=$(cd -P "$DIR" && pwd -P)
# Note: For non-POSIX systems, try without the -P option.
ERR=$?; [ 0 = $ERR ] || {
  echo "Script '$0' expects POSIX shell and read access." >&2
  exit $ERR
}
```
Should work on all modern systems, so let's replace the whole <code>case &grave;uname&grave;</code> block?
This way <code>, "\\"&grave;dirname \\"$DIR\\"&grave;\\"/\\"" ++ target ++ "\\" \\"$@\\""</code> becomes `, "\"$DIR/" ++ target ++ "\" \"$@\""`.

Caveat: `cd -P` only works on POSIX systems, according to: https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.70/html_node/Limitations-of-Builtins.html#index-cd
For such old shells, the $() and ${} syntax might not work either.
