### ISSUE TITLE
Idris in WSL does not handle files with CRLF newlines correctly in error messages

### ISSUE THREAD

**Issue by jmanuel1** [idris-lang/Idris2#2226]
I'm running Idris 2 0.5.1 in WSL and editing files in Windows because I didn't want to bother with compiling Idris for Windows. If this use case is unsupported, let me know.

# Steps to Reproduce

Attempt to load the following file (here is a [gist](https://gist.github.com/jmanuel1/030e88997aba04a28b47bacfc3e7dc3e) of it):

```idris
module Issue
{- comment added to make it clear which lines are being displayed -}
fun : () -> Int
fun () = True
```

# Expected Behavior

I get a type error "Mismatch between: Bool and Int." at line 4, column 10, and `True` is underlined in the error message. So, a message like this:

```
Error(s) building file Issue.idr: While processing right hand side of fun. When unifying:
    Bool
and:
    Int
Mismatch between: Bool and Int.

Issue:4:10--4:14
 1 | module Issue
 2 | {- comment added to make it clear which lines are being displayed -}
 3 | fun : () -> Int
 4 | fun () = True
              ^^^^
```

# Observed Behavior

The error message and given location are right, but the wrong source lines are displayed. There are extra blank lines; I presume this is due to carriage return and line feed being counted as separate newline characters. The source span underlined in the error message is wrong. The message I get looks like this:

```
Error(s) building file Issue.idr: While processing right hand side of fun. When unifying:
    Bool
and:
    Int
Mismatch between: Bool and Int.

Issue:4:10--4:14
 1 | module Issue
 2 | 
 3 | {- comment added to make it clear which lines are being displayed -}
 4 | 
              ^^^^
```

This behavior does not occur if I change the newlines in the file to line feeds.

# Other notes

I also have problems with Idris copying the wrong line when it does a case split, even though it knows what pattern to split. This seems to be related to newlines, too, but I don't know how related it is to the current issue.

**Comment by dagit** [comment]
Are you able to run the idris2 test suite in WSL? I'm guessing a ton of tests would fail.

**Comment by jmanuel1** [comment]
I just tried that using the source tarball from the website, and only one test failed that was related to sockets and the Chez backend (`chez/chez014`). Then I converted the newlines in the `idris2/error001` test to LF and ran the tests again, and that test failed too.

**Comment by gallais** [comment]
This may be fixed in `main` now that we are using `base`'s `lines` (following #2230)
which seems to be doing the right thing. `Libraries.Data.String.Extra` was breaking
on `isNL` but the function in `base` does take care to recognise `\r\n` as a single
newline marker.

**Comment by jmanuel1** [comment]
It seems to be fixed in `main` now. Even case splitting works. Although... the code I get generated from the compiler uses LF. But I think that's a separate issue. I guess this issue can be closed.
