### ISSUE TITLE
When srcTime == ttcTime: ModTree and ProcessIdr disagree on if file should be rebuilt

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#2239]
Why are the times checked twice?

According to ModTree, when `srcTime == ttcTime`, the file should be rebuilt.
https://github.com/idris-lang/Idris2/blob/1576a578a0e490ada19fe82571fc5ea23d47a8d1/src/Idris/ModTree.idr#L145-L151
According to ProcessIdr, when `srcTime == ttcTime`, the file should not be rebuilt.
https://github.com/idris-lang/Idris2/blob/266e06cab799de0c874739e5f29cd68d8324340c/src/Idris/ProcessIdr.idr#L228-L233

**Comment by mattpolzin** [comment]
This is fixed by https://github.com/idris-lang/Idris2/pull/2188
