### ISSUE TITLE
[stdlib: network] `recvAll` has faulty semantics 

### ISSUE THREAD

**Issue by Russoul** [idris-lang/Idris2#2282]
# Steps to Reproduce
Here is the function, taken directly from `network`:
```idris
export
recvAll : HasIO io => (sock : Socket) -> io (Either SocketError String)
recvAll sock = recvRec sock [] 64
  where
    partial
    recvRec : Socket -> List String -> ByteLength -> io (Either SocketError String)
    recvRec sock acc n = do res <- recv sock n
                            case res of
                              Left c => pure (Left c)
                              Right (str, res) => let n' = min (n * 2) 65536 in
                                                  if res < n then pure (Right $ concat $ reverse $ str :: acc)
                                                  else recvRec sock (str :: acc) n'

```
The function sits in a `recv` loop, reading the inputstream no more than N bytes at a time.
N starts at 64, gets doubled each time the next packet is read, capped at 65536 bytes.
The function breaks the loop when the previously received packet length is strictly less than N.

The semantics is wrong, because packet length can be arbitrary and vary from machine to machine and packet to packet.
The function can only have stable semantics when one knows that the client will interrupt the connection at the end of the stream. If so, it can be implemented by sequentially reading bytes from the stream, as much as possible, until an error is caught (recv returns `Left _`). The error code can be returned with the accumulated string.

**Comment by octeep** [comment]
I've made a PR based on what you suggested. Do you mind checking if the PR fixes the problem? I don't know how to reliably test if `recvAll` works correctly or not.

**Comment by Russoul** [comment]
Yeah, writing a test case for it seems rather hard. I can’t test in my use case either, because my hypothetical client doesn’t close the connection, so I can’t "receive-it-all". The solution you have is pretty much exactly what I had in mind though.

**Comment by octeep** [comment]
The PR just got merged. Maybe this issue can be closed now?

**Comment by Russoul** [comment]
Thank you! Closing!
