### ISSUE TITLE
[ performance ] (>>=) and (<*>) for List have quadratic runtime complexity.

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#2288]
# Steps to Reproduce

Build and run the following program:

```idris
import Data.SnocList

replicateTR : Nat -> a -> List a
replicateTR n v = go n Nil
  where go : Nat -> List a -> List a
        go 0     xs = xs
        go (S k) xs = go k (v :: xs)

main : IO ()
main = printLn . length $ [1..5000] >>= (\n => replicateTR n n)
```

# Expected Behavior

Runs in a few seconds on reasonably modern hardware.

# Observed Behavior

Still not done while I write this issue... But I'll submit a PR with a fix soonish.

**Comment by gallais** [comment]
Fixed by #2289
