### ISSUE TITLE
Provide a nice way to work with socket with binary data

### ISSUE THREAD

**Issue by octeep** [idris-lang/Idris2#2307]
- [ yes ] I have read [CONTRIBUTING.md](../../CONTRIBUTING.md).
- [ yes ] I have checked that there is no existing PR/issue about my proposal.

## The proposal

Currently the network library is designed to work with String, which makes handling binary data near impossible since String is null terminated (See #2211). While `Network.Socket.Raw` provides `sendBuf` and `readBuf`, they are extremely difficult to work with since it uses pointer operations, and also the underlying C bindings treats the buffer as int for some reason, then attempts to convert the endianness of the ints with `buf_ntohl` ([Here](https://github.com/idris-lang/Idris2/blob/523c0a6d7823d2b9a614d4a30efb52da015f9367/support/c/idris_net.c#L259) and [Here](https://github.com/idris-lang/Idris2/blob/523c0a6d7823d2b9a614d4a30efb52da015f9367/support/c/idris_net.c#L283)). 

The only viable option would be to create your own C library, something like [this](https://github.com/octeep/idris2-tls/blob/master/c/idristls.c) and [this](https://github.com/octeep/idris2-tls/blob/master/src/Utils/Network/C.idr), which imports correct headers depending on the platform, and provide a unified interface for network operation across different OSes.

Such change could be easily implemented by removing the `buf_ntohl` calls in `support/c/idris_net.c`, then make some wrapper functions that uses `List Bits8` that call `prim__idrnet_send_buf` and `prim__idrnet_recv_buf`. I would be happy to make a PR that does this, but before I do that, I want to know if there is a fundamental reason why the `buf_ntohl` calls even exist in the first place?

**Comment by cypheon** [comment]
The "IDE mode" currently uses `prim__idrnet_fdopen` to convert the socket FD to a `FILE *`. Maybe it's possible to use that `File` to read binary data into a buffer? (Not as a final interface, but could be used as a primitive to implement a nice interface on top of?)

https://github.com/idris-lang/Idris2/blob/3c532ea35d45345bdf8daa2bd22351b705e10ad8/src/Idris/IDEMode/REPL.idr#L40-L46

**Comment by octeep** [comment]
> The "IDE mode" currently uses `prim__idrnet_fdopen` to convert the socket FD to a `FILE *`. Maybe it's possible to use that `File` to read binary data into a buffer? (Not as a final interface, but could be used as a primitive to implement a nice interface on top of?)
> 
> https://github.com/idris-lang/Idris2/blob/3c532ea35d45345bdf8daa2bd22351b705e10ad8/src/Idris/IDEMode/REPL.idr#L40-L46

Sure, I will give that a try. Not sure how it would work with socket with async flag, but I will give it a test.
