### ISSUE TITLE
Failure to parse where at line start

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#234]
The following simple example fails to parse in Idris 2

# Steps to Reproduce
```idrid
data Bool' : Type
where
  True' : Bool'
  False' : Bool'
```

# Expected Behavior

This code parses correctly in Idris 1

# Observed Behavior

'''
Welcome to Idris 2.  Enjoy yourself!
1/1: Building t (t.idr)
t.idr:2:1--2:1:Parse error: Couldn't parse declaration (next tokens: [where, identifier True', symbol :, identifier Bool', identifier False', symbol :, identifier Bool', end of input])
'''

**Comment by edwinb** [comment]
Idris 1 is the one that's wrong here. `where` should be indented at least one character further than the outer definiition.
