### ISSUE TITLE
Eta-expansion doesn't work? 🤔

### ISSUE THREAD

**Issue by ice1000** [idris-lang/Idris2#2355]
# Steps to Reproduce

I tested on https://learn-idris.net/play instead of locally installed Idris2, because I only have a cellphone and I didn't find a way to install Idris2 on my cellphone. I'm unsure if they use latest Idris2, so please help me confirm if it's already fixed or not, thanks very much!

Choose Idris v2 and use the below code, it checks:

```idris
data W : (a : Type) -> (b : a -> Type) -> Type where
    Sup : (x : a) -> (b x -> W a b) -> W a b

listIndex : (a : Type) -> (Maybe a) -> Type
listIndex _ Nothing = Void
listIndex _ (Just x) = ()

ListW : Type -> Type
ListW a = W (Maybe a) (listIndex a)

nilW : ListW a
nilW = Sup Nothing (\x => void x)
```

But if we eta-contract the last lambda, the code no longer checks:

```idris
nilW = Sup Nothing void
```

# Expected Behavior

![image](https://user-images.githubusercontent.com/16398479/158640988-2883bb35-6964-42c2-9ca7-c96cbee40956.png)

# Observed Behavior

```
While processing right hand side of nilW at play.idr:12:1--14:1:
When unifying (0 _ : Void) -> ?a and ?b ?x -> W ?a ?b
Mismatch between:
	(0 _ : Void) -> ?a
and
	?b ?x -> W ?a ?b
Error(s) building file /tmp/tmpg9b_6r7q/play.idr: play.idr:12:1--14:1:When elaborating right hand side of Main.nilW:
play.idr:12:20--14:1:When unifying: ((0 x : $resolved1156) -> ?Main.{a:266}_[a[1]]) and (({arg:242} : (?Main.{b:264}_[a[0]] ?Main.{x:265}_[a[0]])) -> ($resolved1166 ?Main.{a:263}_[a[1]] ?Main.{b:264}_[a[1]]))
	play.idr:12:20--14:1:Type mismatch: ((0 x : $resolved1156) -> ?Main.{a:266}_[a[1]]) and (({arg:242} : (?Main.{b:264}_[a[0]] ?Main.{x:265}_[a[0]])) -> ($resolved1166 ?Main.{a:263}_[a[1]] ?Main.{b:264}_[a[1]]))
```

**Comment by gallais** [comment]
We don't have quantity subtyping so no you can't eta-contract a function whose relevant argument is used in a runtime irrelevant position.

**Comment by ice1000** [comment]
Thanks!

**Comment by ice1000** [comment]
How do I understand the error messages btw? It's full of meta variables
