### ISSUE TITLE
Cast from `String` to `Double` inconsistent on refc vs chez-scheme

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#2362]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
```idris
zero : Double
zero = cast "0"

zero_zero : Double
zero_zero = cast "0.0"

main : IO ()
main = do
    printLn $ zero == zero_zero
    printLn $ show zero == show zero_zero
```
Compile with refc or chez/racket backend

# Expected Behavior
On refc or nodejs:
```
True
True
```
As I'd expect
# Observed Behavior
On chez and racket:
```
True
False
```

# Possible fixes
1 - use a different scheme function to cast strings to floats
2 - add `0.0` to the output to make convince scheme it is a float

**Comment by dunhamsteve** [comment]
Probably related to #2261 - Backends represent Infinity differently when rendering and parsing strings. I believe the behavior of the schemes is specified in the R?RS specs.  I presume, but haven't checked, that javascript has a similar spec.
