### ISSUE TITLE
Type variable that should be inferred isn't accessible

### ISSUE THREAD

**Issue by memoryallocator** [idris-lang/Idris2#2378]
Is the behavior described below intentional? I use Idris 2 0.5.1.

# Steps to Reproduce
Try to compile the following:
**Case 1.**
```
import Data.Vect

rotateEmpty2d : {-- {m : _} -> --} Vect 0 (Vect m a) -> Vect m (Vect 0 a)
rotateEmpty2d [] = replicate _ []
```
**Case 2.** The first case's code, but with the `{m : _} ->` part uncommented.

# Expected Behavior
In both cases, the code compiles.

# Observed Behavior
**Case 2** compiles successfully.
**Case 1** gives an error:
```
Error: While processing right hand side of rotateEmpty2d. m is not accessible in this context.

Curr:4:30--4:31
 1 | import Data.Vect
 2 | 
 3 | rotateEmpty2d : Vect 0 (Vect m a) -> Vect m (Vect 0 a)
 4 | rotateEmpty2d [] = replicate _ []
```
Why can't the compiler infer the type by the function's signature? Why does it have to access `m`?

**Comment by michaelmesser** [comment]
This isn't a bug.
```
rotateEmpty2d : Vect 0 (Vect m a) -> Vect m (Vect 0 a)
```
is the same as
```
rotateEmpty2d : {0 m : _} -> Vect 0 (Vect m a) -> Vect m (Vect 0 a)
```
In this case `m` is erased and is not available at runtime so you cannot pass it to replicate. `_` in `replicate _ []` is inferred to be `m`.
