### ISSUE TITLE
Different behavior in inferring of types between with record and with data

### ISSUE THREAD

**Issue by bglgwyng** [idris-lang/Idris2#240]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
```idris
data ErrorT: e -> (m: Type->Type) -> (a: Type) -> Type where
  ET: m (Either e a) -> ErrorT e m a

-- 1. type of e is given
-- data ErrorT: (e: Type) -> (m: Type->Type) -> (a: Type) -> Type where
--   ET: m (Either e a) -> ErrorT e m a
  
-- 2. record style
-- record ErrorT e (m: Type->Type) a where
--   constructor ET
--   runErrorT: m (Either e a)
  
implementation Monad m => Functor (ErrorT e m) where
  map f (ET m) = ET (do
                        Right x <- m
                          | Left y => pure $ Left y
                        pure $ Right $ f x)

implementation Monad m => Applicative (ErrorT e m) where
  pure = ET . pure . Right
  (ET f) <*> (ET fa) = ET (do Right x <- f
                                | Left e => pure $ Left e
                              Right y <- fa
                                | Left e => pure $ Left e
                              pure $ Right (x y))
```
# Expected Behavior
No type error occurs.
# Observed Behavior
```
EitherT.idr:15:10--16:3:While processing right hand side of pure at EitherT.idr:15:3--16:3:
When unifying a -> ErrorT e m a and a -> ErrorT e m a
Mismatch between:
        Type
and
        type_of_e
```
I think Idris can get `e` belongs to `Type` because `e` is applied to `Either` in `ET` definition.
But it seems not. You can find that the commentized definitions 1, 2 are working correctly.

**Comment by edwinb** [comment]
The types aren't equivalent. Your definition 1 is equivalent instead to:

    data ErrorT: Type -> (m: Type->Type) -> (a: Type) -> Type where
      ET: m (Either e a) -> ErrorT e m a

And the type you're using is equivalent to:

    data ErrorT: (some_name : e) -> (m: Type->Type) -> (a: Type) -> Type where
      ET: m (Either e a) -> ErrorT e m a

So Idris is behaving correctly here.
