### ISSUE TITLE
Failing block does not feel a coverage error

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#2402]
This piece of code definitely fails with a coverage error:

```idris
%default total

x : Bool -> Nat
x True = 0
```

fails with

```
Error: x is not covering.

X:5:1--5:16
 1 | %default total
 2 | 
 3 | x : Bool -> Nat
     ^^^^^^^^^^^^^^^

Missing cases:
    x False
```

# Steps to Reproduce

Put this code into a failing block:

```idris
%default total

failing

  x : Bool -> Nat
  x True = 0
```

# Expected Behavior

Typechecks

# Observed Behavior

Fails with

```
Error: Failing block did not fail.

X:3:1--6:13
 3 | failing
 4 | 
 5 |   x : Bool -> Nat
 6 |   x True = 0
```

**Comment by gallais** [comment]
Oooooh that happens in an even further check (desugar -> elaborate -> cover / positivity / termination check)!

Thanks for the test case, I'm really glad we're ironing out all of these errors.
