### ISSUE TITLE
RefC backend emits "ERROR_NOT_DOUBLE_OR_STRING" to generated file

### ISSUE THREAD

**Issue by j-nava** [idris-lang/Idris2#2446]
The RefC backend apparently emits `switch` statements differently depending on the primitive FFI type of the variable to be tested, but the `Bits` types are not taken into account.

The contrib function `Language.JSON.Data.b16ToHexString` is affected by this. 

# Steps to Reproduce

Compile the following module with the RefC backend.

```haskell
module Main

foo : Bits16 -> String
foo = \case
    1 => "42"
    _ => ""

main : IO ()
main = 
  print (foo 1)
```

# Expected Behavior
# Observed Behavior
```C
Value *Main_foo
(
    Value * var_0
)
{
    Value * tmp_35 = NULL;                                   // Main:3:7--3:12
    switch(ERROR_NOT_DOUBLE_OR_STRING(var_0, 1, ERROR_NOT_DOUBLE_OR_STRING)){
                                                             // Main:3:7--3:12
      case 1 :
      {
        tmp_35 = (Value*)makeString("42");
        break;
      }
      default :
      {
        tmp_35 = (Value*)makeString("");
      }
    }
    free(ERROR_NOT_DOUBLE_OR_STRING);
    Value *returnValue = tmp_35;
    return returnValue;
}
```

**Comment by Z-snails** [comment]
Here is the relevant function in the refc code https://github.com/idris-lang/Idris2/blob/main/src/Compiler/RefC/RefC.idr#L427-L438
This shouldn't be too hard to fix yourself, the `BitsXY` types are `B8`, `B16`, etc

**Comment by j-nava** [comment]
I fixed this locally for `Bits16` so that I could compile `Language.JSON` by duplicating what is being done for type `double`
Should I do the same for the other types and create a PR, or does it need a better solution?

**Comment by Z-snails** [comment]
I suggest make changes to the function I linked to, rather than where `Double` is handled
(Basically copy the lines with `(I8 x) => True` but change `I` to `B`)

**Comment by j-nava** [comment]
Yeah, I see how this works now. 
Do you guys usually write tests for small fixes like this one?

**Comment by Z-snails** [comment]
I would be happy to merge it without a tes, as this seems very unlikely to break unless we add more integer types, which we can't test now. But feel free to add one if you want

**Comment by j-nava** [comment]
Okay! As much as I'm curious about how the compiler tests are handled, I'm going to leave that for my second issue. 😄 
Thank you!

**Comment by kuruczgy** [comment]
For me the original example with the #2447 fixes now prints the empty string instead of `42`, which is still not the expected behavior. I opened #2452 for this.
