### ISSUE TITLE
RefC bad implementation for switch on Bits types

### ISSUE THREAD

**Issue by kuruczgy** [idris-lang/Idris2#2452]
# Steps to Reproduce
```
x : Bits8
x = 0

main : IO ()
main = do
  putStrLn $
    case x of
      0 => "good"
      _ => "bad"
```

# Expected Behavior
`good`

# Observed Behavior
`bad`

# Notes
The `BITS` cases are missing in this function: https://github.com/idris-lang/Idris2/blob/4a761ea5235d8f4838fcf49407b5f44af2e29de1/support/refc/runtime.c#L81

#2446 seems closely related

I think what's most probable is that #2447 just forgot to add the new cases in the `extractInt` function. @j-nava, could you maybe confirm that you can also reproduce this issue?

I plan on making a PR shortly, unless someone beats me to it.

**Comment by j-nava** [comment]
@kuruczgy I can reproduce it. Your example prints `bad`.
