### ISSUE TITLE
Exception: attempt to reference unbound identifier fork-thread at line 271, char 6 of idris2_app/idris2-boot.ss

### ISSUE THREAD

**Issue by ki9gpin** [idris-lang/Idris2#2477]
I have scheme 9.5.8 installed .
When executing "make bootstrap SCHEME=scheme"   the following error occurs
Exception: attempt to reference unbound identifier fork-thread at line 271, char 6 of idris2_app/idris2-boot.ss

**Comment by buzden** [comment]
Are you sure that your chez scheme is compiled with threads support? It is required and documented.

**Comment by Z-snails** [comment]
This is possibly a duplicate of #2287
Please see if the fix/issue there is the same as yours

**Comment by ki9gpin** [comment]
Thanks   both of you @buzden @Z-snails . 
Building scheme with threads support solved the issue.
