### ISSUE TITLE
ANSI escape code

### ISSUE THREAD

**Issue by ki9gpin** [idris-lang/Idris2#2478]
WSL Ubuntu 
Windows Terminal 

Idris2 fails to capture the arrow keys.
Not sure if  this is  an Idris2  or wsl problem .

![image](https://user-images.githubusercontent.com/44522075/168439739-f3d884f0-eb02-45bc-808c-86c479750bfd.png)

**Comment by gallais** [comment]
This is a duplicate of #54.
