### ISSUE TITLE
[ regression ] Packages with same transitive dependencies no longer build

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#2494]
Today I got a couple of mails from GitHub: Most of my packages' nightly builds failed. It looks like their (transitive) dependencies are no longer acceptable to Idris2. For instance: `elab-util` has a dependency on `base >= 0.5.1`, as does `sop`, which also depends on `elab-util`. Idris now complains that sop would depend on two versions of the same package.

Is this expected behavior? Pinging @Z-snails because this surely comes from #2469 .

Now, in case of `sop`, this could easily be resolved: Remove the dependency on `base` because this is already available from `elab-util`. However, assume we have the following dependency graph where `A` depends on `B` and `C`, and both `B` and `C` would depend on `D`? Would Idris now also shout at us? Could it resolve the issue via the package bounds given in the dependencies of `B` and `C`?

I suggest the following: We undo #2469 (for now), try to fix the issue, and then I will run  @Z-snails PR version against the current *pack* collection to see how it goes.

**Comment by Z-snails** [comment]
Reverting the commit now, I'll make sure to check with pack when I get round to fixing it

**Comment by stefan-hoeck** [comment]
Transitive dependencies have been (re)implemented in #2584 . Therefore, this can be closed.
