### ISSUE TITLE
[ regression ] Package dependencies not resolved correctly

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#2528]
I'm afraid #2496 caused another regression with package resolution. The build of today's pack nightly failed with lots of errors. I do realize that we have tested this one or two weeks ago, and I still don't understand the details, but am going to have a closer look now.

Two links:
* [Pack's current package status](https://github.com/stefan-hoeck/idris2-pack-db/blob/main/STATUS.md)
* [Log of the collection check](https://github.com/stefan-hoeck/idris2-pack-db/runs/6786236169?check_suite_focus=true)

This could be an issue of pack itself, because I changed how it passes `IDRIS2_PACKAGE_PATH` to the compiler, but so far, this wasn't an issue. Will report back here. Pinging @Z-snails  in the meantime.

**Comment by stefan-hoeck** [comment]
OK, I'm quite sure now that this is pack related. Will closed this, if this is indeed the case.

One thing I realized with this change, however, is that `.ipkg` files of (transitive) dependencies must now have the same name as the name of the package. Or do I get this wrong?

**Comment by mattpolzin** [comment]
It’s not pack I don’t think. My nightly CI for pg-idris started failing as well: https://github.com/mattpolzin/pg-idris/runs/6785534578?check_suite_focus=true

**Comment by stefan-hoeck** [comment]
There might be several issues at work then. I definitely introduced a bug in pack-admin yesterday, which let to lots of failures when building today's nightly. Also, my own packages built fine in their nightly CI. But yes, the error message in your CI run is definitely related to #2496 .

**Comment by Z-snails** [comment]
I don't have time to fix this right now, so I'll revert it and let someone else work on it.

**Comment by stefan-hoeck** [comment]
Transitive dependencies have been (re)implemented in #2584. Therefore, this can be closed.
