### ISSUE TITLE
A view argument is not visible

### ISSUE THREAD

**Issue by jinwoo** [idris-lang/Idris2#253]
The `groupByN` function from exercise 1 in Chapter 10 of Type-driven Development with Idris doesn't work with Idris2.

Is this a valid language change in Idris2, or is it a bug in the compiler implementation?

# Steps to Reproduce

```idris
data TakeN : List a -> Type where
  Fewer : TakeN xs
  Exact : (n_xs : List a) -> TakeN (n_xs ++ rest)

takeN : (n : Nat) -> (xs : List a) -> TakeN xs
takeN 0 _ = Exact []
takeN (S _) [] = Fewer
takeN (S k) (x :: xs) = case takeN k xs of
                             Fewer => Fewer
                             Exact n_xs => Exact (x :: n_xs)

groupByN : (n : Nat) -> (xs : List a) -> List (List a)
groupByN n xs with (takeN n xs)
  groupByN n xs | Fewer = [xs]
  groupByN n (n_xs ++ rest) | Exact n_xs = n_xs :: groupByN n rest
```

# Expected Behavior

The code must be built without errors.

# Observed Behavior

The compiler says that `rest` is not accessible.

```
1/1: Building ex_10_1 (ex_10_1.idr)
ex_10_1.idr:15:63--16:1:While processing right hand side of with block in groupByN at ex_10_1.idr:15:3--16:1:
rest is not accessible in this context
Error(s) building file ex_10_1.idr
```

I have to modify the code like below to make it work. That is, change `rest` to an explicit argument to `Exact`.

```idris
data TakeN : List a -> Type where
  Fewer : TakeN xs
  Exact : (n_xs : List a) -> (rest : List a) -> TakeN (n_xs ++ rest)

takeN : (n : Nat) -> (xs : List a) -> TakeN xs
takeN 0 rest = Exact [] rest
takeN (S _) [] = Fewer
takeN (S k) (x :: xs) = case takeN k xs of
                             Fewer => Fewer
                             Exact n_xs rest => Exact (x :: n_xs) rest

groupByN : (n : Nat) -> (xs : List a) -> List (List a)
groupByN n xs with (takeN n xs)
  groupByN n xs | Fewer = [xs]
  groupByN n (n_xs ++ rest) | Exact n_xs rest = n_xs :: groupByN n rest
```

**Comment by jinwoo** [comment]
https://idris2.readthedocs.io/en/latest/typedd/typedd.html#chapter-10 explains this for the `SnocList` case. So I should make the `rest` argument explicit in the above example. Closing this.

**Comment by gallais** [comment]
It does not have to be explicit as much as it has to be written down manually:
all of the variables introduced by the machine are assigned the quantity `0` and
therefore cannot be used in computations.

So you could go with:

```idris
  Exact : (n_xs : List a) -> {rest : List a} -> TakeN (n_xs ++ rest)
```

**Comment by jinwoo** [comment]
@gallais Ah, that's much better. Thanks!
