### ISSUE TITLE
let binder with signature makes all binders top level

### ISSUE THREAD

**Issue by MarcelineVQ** [idris-lang/Idris2#255]
Idris 2, version 0.2.0-a0d9ce201
# Steps to Reproduce
```idris
module Main
foo1 : ()
foo1 = let z = 'z' in ()

foo2 : ()
foo2 = let a = 'a'
           b : () -> ()
           b _ = ()
           c = the Int 1
      in ()
```
# Expected Behavior
typechecks
# Observed Behavior
`No type declaration for Main.a` or `No type declaration for Main.c` if `a` is commented out.  Given that it calls them `Main.a` or `Main.c` I have assumed that all binders are being moved to the top level, though it might just be where the search ended. This is re-enforced by providing the declarations:
```idris
module Main
b : Int -- item of interest
b = 1

a : Char
c : Int

foo2 : ()
foo2 = let a = 'a'
           b : () -> ()
           b _ = ()
           c = the Int 1
      in ()
```
^ is just fine.
The further item of interest is that the b in foo2 that (I assume) is also lifted does not have any weird interactions with an existing top level b.

**Comment by gallais** [comment]
Cf. #136 

We have to make some decisions wrt the resulting ambiguity.

**Comment by MarcelineVQ** [comment]
oop, that was painfully easy to find as a duplicate issue :> I'll remember to check that next time.
thanks @gallais
