### ISSUE TITLE
Weird rewrite error: "Rewriting by [...] did not change type [...]"

### ISSUE THREAD

**Issue by ngeiswei** [idris-lang/Idris2#2573]
# Steps to Reproduce

Load the following file in Idris2

https://gist.github.com/ngeiswei/858fe47f2ff3ac6f0f19ef0c7e37ad17

# Expected Behavior

Compilation succeeds.

# Observed Behavior

Compilation fails with error:

```
     While processing right hand side of prf. Rewriting by foo x = x did not change type foo x < y = True.
     
     Test:13:16--13:38
      09 | eq f x = believe_me ()
      10 | 
      11 | ||| Prove that if x < y then (foo x) < y
      12 | prf : Ord a => (a -> a) -> (x, y : a) -> x < y = True -> Test.foo x < y = True
      13 | prf f x y lt = rewrite (eq f x) in lt
                          ^^^^^^^^^^^^^^^^^^^^^^
```

Note that if either

```haskell
foo x = if x < x then x else x
```
is replaced by
```haskell
foo x = x
```

or

```haskell
eq : Ord a => (a -> a) -> (x : a) -> Test.foo x = x
eq f x = believe_me ()
```
is replaced by
```haskell
eq : Ord a => (x : a) -> Test.foo x = x
eq x = believe_me ()
```
(and therefore `(eq f x)` is replaced by `(eq x)`), then it works.  Which is telling me that it might be a bug with `rewrite`.

**Comment by gallais** [comment]
```
prf @{o} f x y lt = rewrite eq @{o} f x in lt
```
is accepted so it's probably a constraint solving issue.

**Comment by ngeiswei** [comment]
@gallais, could you elaborate (or point me to a documentation explaining) why inserting `@{o}` happens to bypass the problem?

**Comment by dunhamsteve** [comment]
The `@{o}` on the LHS matches the `Ord a` instance that is being passed into proof, and the `@{o}` on the RHS is passing it into `eq` as the `Ord a` instance.  I'm not sure how it gets two different instances in the other case as the only way it could get its hands on an `Ord a` is to take the implicit argument.  Interesting that this version works too:

```idris
prf : Ord a => (a -> a) -> (x, y : a) -> x < y = True -> Test.foo x < y = True
prf f x y lt = 
    let foo = (eq f x) in rewrite foo in lt
```

**Comment by gallais** [comment]
>  Interesting that this version works too:

IIRC `let` has a bunch of forced constraint solving steps after the elaboration of the let-bound expression.
This is the code that would need to be duplicated in the `rewrite` case to fix the issue.

**Comment by dunhamsteve** [comment]
I have a fix for this (1348820) that works, but might not be what you were describing. It mirrors how `let` works by creating an implicit type for the rule and checking the rule against that type instead of `Nothing`.  Should I PR that or is there a problem with it?

**Comment by gallais** [comment]
I think this is more of an accidental success in that it somehow gets things restarted.
I would rather explicitly call constraint solving like I've done in #2579. I'm tempted to
make it `LastChance` but for now I've left it at `Normal`.

**Comment by dunhamsteve** [comment]
Thanks for the feedback. My solution felt a little like magic / side-effect dependent.

I didn't know about `solveConstraints`. I had tried `runDelayed`, thinking it would process constraints (that's what is being used in `let`), but that didn't work.  I've been meaning to look into how the search / constraint solving stuff works, maybe I'll take a look tonight.
