### ISSUE TITLE
Parser error: Operator '=' is non-associative

### ISSUE THREAD

**Issue by nickdrozd** [idris-lang/Idris2#258]
In Idris 1 it is possible to say:

```idris
Even : Nat -> Type
Even n = (half : Nat ** n = half * 2)

Odd : Nat -> Type
Odd n = (haf : Nat ** n = S $ haf * 2)
```

In Idris 2, `Even` works, but `Odd` raises some kind of parser error:

```
Operator '=' is non-associative
```

Adding parentheses makes it go through:

```idris
Odd : Nat -> Type
Odd n = (haf : Nat ** n = (S $ haf * 2))
```

As a user, I would prefer not to have to worry about adding parens like that.

**Comment by ziman** [comment]
https://github.com/idris-lang/Idris2/issues/173#issuecomment-634192388
