### ISSUE TITLE
`flip` doesn't work with implicit dependent arguments

### ISSUE THREAD

**Issue by joelberkeley** [idris-lang/Idris2#2589]
# Steps to Reproduce

Compile
```
index' : (xs : List Nat) -> (n : Nat) -> {auto 0 ok : InBounds n xs} -> Nat
index' = flip index
```

# Expected Behavior

Successfully compiles. I think it should be possible to compile this. The implicit argument is dependent on the previous two, but reordering them should be OK.

# Observed Behavior

Fails to compile with
```
Error: While processing right hand side of index'. Can't solve constraint between: ?c [no locals in scope] and {auto 0 _ : InBounds arg arg} -> Nat.

 346 | 
 347 | public export
 348 | index' : (xs : List Nat) -> (n : Nat) -> {auto 0 ok : InBounds n xs} -> Nat
 349 | index' = flip index
                ^^^^^^^^^^
```

**Comment by gallais** [comment]
Are you suggesting we change the type of `flip` from

```
flip : (a -> b -> c) -> b -> a -> c
```

to

```
flip : {0 c : a -> b -> Type} -> ((x : a) -> (y : b) -> c x y) -> (y : b) -> (x : a) -> c x y
```
?

I expect that this will make type inference less likely to succeed and lead to confusing errors.

**Comment by joelberkeley** [comment]
no. I can see that being unwise, for your reasons, and because it's harder to read. Would that be necessary? I had hoped/expected that it would be possible to modify the compiler/type checker to realise this is possible

**Comment by gallais** [comment]
> I had hoped/expected that it would be possible to modify the compiler/type checker to realise this is possible

The type of `flip` is explicitly about non-dependent functions so there is no
hope that a change in the compiler could give you what you want.

**Comment by joelberkeley** [comment]
hmmm, ok in that case I'll make a local `dflip` with that signature

**Comment by joelberkeley** [comment]
btw i think `dflip` might be a useful addition to the stdlib
