### ISSUE TITLE
Nested `with` application rules aren't clearly defined

### ISSUE THREAD

**Issue by jinwoo** [idris-lang/Idris2#261]
# Steps to Reproduce

An Idris2 version of `isSuffix` that is written in the TDD book (10.2.3).

```idris
import Data.List.Views

isSuffix : Eq a => List a -> List a -> Bool
isSuffix input1 input2 with (snocList input1, snocList input2)
 isSuffix [] input2 | (Empty, s) = True
 isSuffix input1 [] | (s, Empty) = False
 isSuffix (xs ++ [x]) (ys ++ [y]) | (Snoc x xs xsrec, Snoc y ys ysrec)
    = if x == y then isSuffix xs ys | (xsrec, ysrec)
                else False
```

# Expected Behavior

`isSuffix` must be total, as written in the book, because it recurses over smaller structures.

# Observed Behavior

Compiler thinks it's not total.

```
Main> :l IsSuffix.idr
Loaded file IsSuffix.idr
Main> 
Main> 
Main> 
Main> :total isSuffix
Main.isSuffix is possibly not terminating due to recursive path Main.isSuffix -> Main.with block in 1397 -> Main.with block in 1397 -> Main.with block in 1397
```

**Comment by edwinb** [comment]
It can't tell this is total because the smaller arguments are inside a pair and it doesn't look. If Idris 1 thinks this is total, I don't know how...

**Comment by jinwoo** [comment]
I can see how Idris 1 could make this total because the original code from the TDD book uses nested `with`.

```idris
isSuffix : Eq a => List a -> List a -> Bool
isSuffix input1 input2 with (snocList input1)
    isSuffix [] input2 | Empty = True
    isSuffix (xs ++ [x]) input2 | (Snoc rec) with (snocList input2)
         isSuffix (xs ++ [x]) [] | (Snoc rec) | Empty = False
         isSuffix (xs ++ [x]) (ys ++ [y]) | (Snoc xsrec) | (Snoc ysrec)
                = if x == y then isSuffix xs ys | xsrec | ysrec
                            else False
```

But Idris 2 doesn't support nested `with`, and https://idris2.readthedocs.io/en/latest/typedd/typedd.html#chapter-10 suggests to use a pair instead (the code given in the first comment above).

This is unfortunate because this code appears in the section in the book that explains how to make such functions total by using recursive views.

So it seems that views are less useful in Idris 2 than in Idris 1. Should I avoid using multiple views at the same time?

**Comment by edwinb** [comment]
Idris 2 is certainly supposed to support nested with. Maybe there's an issue with the recursive call syntax that needs looking into. But there's no way Idris is going to see that this is total.

**Comment by jinwoo** [comment]
But you said in https://idris2.readthedocs.io/en/latest/typedd/typedd.html#chapter-10,

> In IsSuffix.idr, the matching has to be written slightly differently. The recursive with application in Idris 1 probably shouldn’t have allowed this!

😉

**Comment by edwinb** [comment]
That isn't me saying that nested with isn't supported... it's me saying that the rules for recursive with application aren't very clearly defined. I think this confused some people with Idris 1 (and to be honest, it confused me when I wrote that document and it's confusing me again now).

I need to nail down the rules for recursive with application.

**Comment by jinwoo** [comment]
Oh, I see. Sorry I misunderstood that sentence. I also notice that the doc also says "This doesn’t yet get past the totality checker, however, because it doesn’t know about looking inside pairs." I missed that part when I filed this ticket.

**Comment by edwinb** [comment]
Hmm, I think I can see a way to go with the with application. I've renamed the issue as a reminder to do something about it.

**Comment by edwinb** [comment]
This works and is total:

    isSuffix : Eq a => List a -> List a -> Bool
    isSuffix input1 input2 with (snocList input1)
      isSuffix [] input2 | Empty = True
      isSuffix (xs ++ [x]) input2 | (Snoc x xs xsrec) with (snocList input2)
        isSuffix (xs ++ [x]) [] | (Snoc x xs xsrec) | Empty = False
        isSuffix (xs ++ [x]) (ys ++ [y]) | (Snoc x xs xsrec) | (Snoc y ys ysrec)
            = if x == y then isSuffix xs ys | xsrec else False

I think Idris 2's rules are the right ones - the with application on the RHS has to match against the LHS with the same number of with arguments. I can only speculate about what Idris 1 might be doing - perhaps ignoring the `ysrec` because the match fails. I'll update the document.

I should still write this down in more detail.

**Comment by jinwoo** [comment]
It indeed works. But does this code mean that the snoc list for `input2` is re-created for each recursion?

**Comment by edwinb** [comment]
What this comes down to is that the recursive structure of the view doesn't reflect the recursion structure of `isSuffix`, and the idea of a recursive view is to capture that recursion structure. `isSuffix` is recursive on both lists at once, but `snocList` only recurses on one list at a time. So, in the end, this is a bad example and either shouldn't have been in the book in the first place, or should have been covered in more depth. I think a couple of examples in this chapter have suffered from the feature (with application) being developed as the chapter was being written.

The rule for with application on the RHS is the same as on the LHS, that is: in an expression `exp | arg`, `exp` must match one of the parent LHSs, and that is the part of the function which will be called recursively.

So I think Idris 2 is behaving exactly as expected, both on `with` and on totality checking. Yes, the totality checking can be improved, and maybe someone will do that one day, but I think it's too big and open ended to leave open. Maybe it's a thing that could be added to the Contributions Wanted page on the wiki.

**Comment by ziman** [comment]
For some reason the invocation of `f | x | y` does not seem to work as I think it should, possibly for forced patterns:
```idris
g : Bool -> Bool
g x with (not x)
  g x | y with (not y)
    g x | y | z = g True | False | True  -- checks fine

data T : Bool -> Type where
  MkT : (x : Bool) -> T (not x)

t : (x : Bool) -> T x

f : Bool -> Bool
f x with (t x)
  f (not y) | MkT y with (t y)  -- x.idr:13:6--13:11:With clause does not match parent
  f (not (not z)) | MkT (not z) | MkT z = f True | MkT False | MkT True
```
Definition `g` checks fine but `f` complains on line 13. If I replace the RHS of `f` on line 14 with a hole, the error disappears from line 13 and everything checks fine.

**Comment by ziman** [comment]
Could we perhaps extend `with` to support multiple arguments at once, like in Agda? Then we wouldn't need pairs for this. I'm not sure how hard it is; I tried it but it goes deep into `TTImp` and then I hit code that I can't clearly see how to extend.

For the time being, I guess the only way is to elaborate the with clause manually:
```idris
isSuffix' : Eq a => (0 xs : List a) -> (0 ys : List a) -> SnocList xs -> SnocList ys -> Bool
isSuffix' [] _ Empty _ = True
isSuffix' _ [] _ Empty = False
isSuffix' (xs ++ [x]) (ys ++ [y]) (Snoc x xs recx) (Snoc y ys recy) =
  if x == y
    then isSuffix' xs ys recx recy
    else False

isSuffix : Eq a => List a -> List a -> Bool
isSuffix input1 input2 = isSuffix' input1 input2 (snocList input1) (snocList input2)
```

Optionally, polish it with some implicits to emphasise where the computation happens:
```idris
isSuffix' : Eq a => {0 xs : List a} -> {0 ys : List a} -> SnocList xs -> SnocList ys -> Bool
isSuffix' Empty _ = True
isSuffix' _ Empty = False
isSuffix' (Snoc x xs recx) (Snoc y ys recy) =
  if x == y then isSuffix' recx recy else False

isSuffix : Eq a => List a -> List a -> Bool
isSuffix input1 input2 = isSuffix' (snocList input1) (snocList input2)
```
