### ISSUE TITLE
Another proof of `Void`

### ISSUE THREAD

**Issue by alahijani** [idris-lang/Idris2#2633]
(I couldn't find a similar reported bug, so here it goes. Feel free to close as a duplicate if it's already captured.)

It is easy to build a proof of `Void` by wrapping a function in a data constructor and then doing case analysis on it. Idris will happily accept an `impossible` clause that claims a "unifying function" does not exist. In the following example a unifying function is any function `f : Bool -> Bool` that simultaneously unifies `f True` with  `True` and ` f False` with `False`. Functions out of `Bool` are not a well-founded class, so I don't see a reason why idris should so confidently rule out the existence of a counterexample like `id`.

# Steps to Reproduce
Try the following code in any recent version of `idris2` or `idris`:

```idris
infix 0 =^=
data (=^=) : a -> a -> Type where
  Cong : (f : Bool -> a) -> f True =^= f False

total
good : True =^= False
good = Cong id

total
not_good : Not (True =^= False)
not_good (Cong _) impossible -- but this is not impossible :(

total
explode : t
explode = void (not_good good)
```

# Expected Behavior
The `impossible` clause should be a compiler error.

# Observed Behavior
Idris happily convinces itself that functions out of `Bool` are a closed, well-founded class and accepts my absurd impossibility claim.

**Comment by MarcelineVQ** [comment]
What version of idris is this occurring on?
On `Idris 2, version 0.5.1-23e3695d7` I get
`Impossible pattern gives an error:
Can't solve constraint between: ?_ True and True.`

**Comment by alahijani** [comment]
My bad. This only happens on my Idris 1 (version 1.3.3). 

I also tested it on  [Try Idris](https://tryidris.herokuapp.com/console) which I assumed used Idris 2, but seems like it uses Idris 1.
