### ISSUE TITLE
Test for not implemented feature is stuck rather than failing

### ISSUE THREAD

**Issue by zenntenn** [idris-lang/Idris2#264]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce

Create the folder tests/idris2/interpreter003
Create the files in interpreter003:
expected (https://gist.github.com/zenntenn/c580e5841695bd067b7f0e0c2a27fb8a)
input (https://gist.github.com/zenntenn/b8217d30f6f3c4e4ac19300103fed10e)
run (https://gist.github.com/zenntenn/0439e2c696e60380c73e4eae8afc1864)

Then at the top level directory for Idris2 do:
make clean
make all
make test only=idris2/interpreter003

# Expected Behavior

Test should fail, as long as no one has implemented search yet, if they have it might need to be some other test case.

# Observed Behavior
make gets stuck, output is:
`$ make test only=idris2/interpreter003`
`make[1]: Entering directory '/c/msys64/home/joshua.hillerup/source/Idris2/tests'
./build/exec/runtests ../../../build/exec/idris2 --interactive --only idris2/interpreter003
`

**Comment by edwinb** [comment]
I can't reproduce this. Is there a newline at the end of your input file? Also I usually end the input file with an explicit :q.

**Comment by zenntenn** [comment]
@edwinb I've updated the input file to have a `:q` after, and a blank line below that.  I did the `make clean` `make all` and then `make test only=idris2/interpreter003` and it's been running for over 10 minutes and it's still running.  It also generated the same output file.

**Comment by zenntenn** [comment]
The output file it's creating is here: https://gist.github.com/zenntenn/f55ae887eac53c373bf22e33730c05e5

**Comment by zenntenn** [comment]
This running under msys2 on Windows 10 if that helps.  I can bootstrap and build Idris2 successfully in this setup, as well as run `make test` in the folder that has just the master branch in it.

**Comment by zenntenn** [comment]
When I do Ctrl+C it gives this error, maybe the numbers can help narrow this down `make[1]: *** [Makefile:6: test] Interrupt
make: *** [Makefile:82: test] Interrupt
`

**Comment by melted** [comment]
But that sends --interactive, if the test doesn't work it will stop and wait for y or n. I don't know why you don't get that output though.

**Comment by melted** [comment]
Interactive is a bad default when testing from the makefile

**Comment by edwinb** [comment]
Is this resolved now? I'm just trying to tidy up a bit...

**Comment by melted** [comment]
Yes, it was solved
