### ISSUE TITLE
Case-splitting introduces shadowed name if function name and constructor argument match

### ISSUE THREAD

**Issue by CodingCellist** [idris-lang/Idris2#2640]
# Steps to Reproduce

Have the following code:

```idris
data Chaos : Type where
  Emerald : (colour : _) -> Chaos

colour : Chaos -> ()
colour c = ?colour_rhs
```

Note that the inner argument of the Chaos `Emerald` constructor has the same name as the function, i.e.  `colour`. If we interactively case-split on `c` now, we get:

```idris
colour (Emerald colour) = ?colour_rhs_0
```

Which Idris rightly complains about:

```
Error: Declaration name (colour) shadowed by a pattern variable.
```

# Expected Behavior

The interactive case-split should spot that the name is not free, and so should instead move on to the next/default name when generating the pattern.

# Additional info

We already check this when a named argument to the function matches the name of a pattern, e.g.

```idris
foo : (colour : Integer) -> Chaos -> ()
foo colour c = ?foo_rhs
```

Case-splitting on `c` here generates `(Emerald x)`, correctly detecting that `colour` isn't available as a name. We just need to do something similar for when it's the name of the function itself.

**Comment by ohad** [comment]
This is related to (but different from) #1742 : the fix to both needs to ensure that the generated name is a valid, fresh, variable name.
