### ISSUE TITLE
Building idris2 with the bootstrap version gives RTS error following attempt of allocating a huge heap

### ISSUE THREAD

**Issue by FranckS** [idris-lang/Idris2#268]
Hi there,

I wanted to update my Idris2 (currently on version 0.1.0-45d02a11b, from before the self-hosting of Idris2).
I'm running trouble for compiling the latest Idris2, both with my old Idris2 and with the official bootstrapping version (sometimes called Idris2-in-Idris1, from here https://github.com/edwinb/Idris2-boot ).

I'll only detail the trouble with the bootstrap version, as I assume this is more annoying that it does not build with this version of Idris2 that is specifically designed for it. (and my current idris2 could be a bit broken, which should not be the case of the bootstrap version).

I did manage to install Idris2boot with Idris1 (I'm using the Version 1.3.2-git:0417c53fb).
I also added the folder $HOME/idris2boot into my path (in my .profile file), as I already did for the $HOME/idris2 folder.
(by the way, we should update [the installation file of the bootstrap version](https://github.com/edwinb/Idris2-boot/blob/master/INSTALL.md) which tells that "The default installation directory is $HOME/.idris2" as the idris2boot executable is in fact installed in ./idris2boot).

Thus, If I do :
$ idris2boot

It runs the REPL of idris2boot ( Version 0.1.1-e9611b4ee ) and I effectively get the message that this is a bootstrap version, no longer developed. Everything is ok here.

Now, I want to install the latest Idris2 using this bootstrap version.

I've just cloned it.
Then I do :
$ make distclean

to make sure that everything is clean.

And following the [installation procedure of Idris2](https://github.com/idris-lang/Idris2/blob/master/INSTALL.md), I did :

$ make all IDRIS2_BOOT=idris2boot

Which goes well at the start :

> cc -Wall  -fPIC -O2   -c -o idris_file.o idris_file.c
> cc -Wall  -fPIC -O2   -c -o idris_support.o idris_support.c
> cc -Wall  -fPIC -O2   -c -o idris_net.o idris_net.c
> cc -Wall  -fPIC -O2   -c -o getline.o getline.c
> cc -Wall  -fPIC -O2   -c -o idris_directory.o idris_directory.c
> idris_directory.c: In function ‘idris2_currentDirectory’:
> idris_directory.c:11:4: warning: ignoring return value of ‘getcwd’, declared with attribute warn_unused_result [-Wunused-result]
>     getcwd(cwd, 1024);
>     ^~~~~~~~~~~~~~~~~
> cc -Wall  -fPIC -O2   -c -o idris_buffer.o idris_buffer.c
> idris_buffer.c: In function ‘idris2_readBufferFromFile’:
> idris_buffer.c:145:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
> [...]
> echo 'module IdrisPaths' > src/IdrisPaths.idr
> echo 'export idrisVersion : ((Nat,Nat,Nat), String); idrisVersion = ((0,2,0), "d71bfef73")' >> src/IdrisPaths.idr
> echo 'export yprefix : String; yprefix="/home/franck/.idris2"' >> src/IdrisPaths.idr
> idris2boot --build idris2.ipkg
> 1/144: Building Core.FC (src/Core/FC.idr)
> 2/144: Building Core.Name (src/Core/Name.idr)

And it's only when it reaches the step 40/144 that it fails with the following error message :

40/144: Building Core.Primitives (src/Core/Primitives.idr)
RTS ERROR: Unable to allocate heap. Requested 8751446623104 bytes.
Makefile:57: recipe for target 'build/exec/idris2' failed
make: *** [build/exec/idris2] Error 1

If I try to run it again :

40/144: Building Core.Primitives (src/Core/Primitives.idr)
RTS ERROR: Unable to allocate heap. Requested 8735164991968 bytes.
Makefile:57: recipe for target 'build/exec/idris2' failed
make: *** [build/exec/idris2] Error 1

So it looks like it tries to allocate a *huge* amount of memory (8 terabytes, right?), and this is not always the exact same amount.

Any idea on what could cause that, and how I could try to fix it?
I did looked briefly at Primitives.idr, but I must admit this is a bit too cryptic for me.

Any idea would be most welcome! Many thanks.

Franck

**Comment by melted** [comment]
It should be noted that I don't know if it's exactly that commit that is the culprit. I'm running a git bisect now.

**Comment by melted** [comment]
It was that, the bisection landed on the "Add Bits Primitives" commit.

**Comment by melted** [comment]
Hmmm, feels like it's one of the primitives that is broken in Idris 1.

**Comment by melted** [comment]
It's the calls to prim__shl_Integer for the B64 handling that goes awry. If I remove them it works.

**Comment by melted** [comment]
putting in 
```
b64max : Integer
b64max = 8784606558888
``` 
instead and substituting the uses fixes the build for Primitives (it stops on an unrelated problem in another file)
