### ISSUE TITLE
TypeDD: the example Hangman.idr doesn't type check

### ISSUE THREAD

**Issue by fniu** [idris-lang/Idris2#2738]
# Steps to Reproduce
Run `idris2 --check tests/typedd-book/chapter14/Hangman.idr`
The file can be found at: https://github.com/idris-lang/Idris2/blob/main/tests/typedd-book/chapter14/Hangman.idr

# Expected Behavior
Type check
# Observed Behavior

```
1/1: Building tests.typedd-book.chapter14.Hangman (tests/typedd-book/chapter14/Hangman.idr)
Warning: We are about to implicitly bind the following lowercase names.
You may be unintentionally shadowing the associated global definitions:
  letters is shadowing Main.letters

tests.typedd-book.chapter14.Hangman:28:3--28:8
 24 |
 25 |   Won :  GameCmd () (Running (S guesses) 0) (const NotRunning)
 26 |   Lost : GameCmd () (Running 0 (S guesses)) (const NotRunning)
 27 |
 28 |   Guess : (c : Char) ->
        ^^^^^
```
Renaming the function `letters` seems to fix the issue. If this is indeed the case, I can submit a PR to fix it.

**Comment by gallais** [comment]
Is it just a warning or actually a failure to build?

**Comment by fniu** [comment]
Right... It is just a warning. I was a bit misled by the warning message in idris2-mode which appears as "Error".
Sorry for the false alarm.
