### ISSUE TITLE
[ parser ] Already defined message points to module keyword.

### ISSUE THREAD

**Issue by andorp** [idris-lang/Idris2#2769]
# Steps to Reproduce
Compiling this program:
```
module Issues.AlreadyDefinedRec

record SomeRecord where
  constructor SomeRecord
  field : Int

```

# Expected Behavior
The 'SomeRecord already defined' message should point to the constructor part.

# Observed Behavior
The 'SomeRecord already defined' message points to the module.

**Comment by andorp** [comment]
I am reporting this in the spirit of https://github.com/idris-lang/Idris2/pull/2744

**Comment by andorp** [comment]
idris2 --version
Idris 2, version 0.5.1-23e3695d7

**Comment by dunhamsteve** [comment]
If we can use the FC of the whole record definition, we get this message, which may be localized enough:
```
1/1: Building Issue2769 (Issue2769.idr)
Error: Issue2769.SomeRecord is already defined.

Issue2769:3:1--5:14
 3 | record SomeRecord where
 4 |   constructor SomeRecord
 5 |   field : Int
```

If we want to point directly at the `SomeRecord`, it's going to be a bigger change - an FC would have to be added to TTImp, which would affect the TTC version and elab reflection.

There is a similar issue with `interface`, which has an optional `constructor` declaration. For example:

```idris
data Foo = Bar

interface Blah where
  constructor Bar
```

**Comment by andorp** [comment]
> If we want to point directly at the `SomeRecord`...

@dunhamsteve I think your PR is already an improvement. Thanks for implementing it.
