### ISSUE TITLE
let parameters within a function specified in a certain way leak into main

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#2782]
In the following code, `y` within `foo` becomes defined as `Main.y` and is accessible from the other function, `fee`:

https://gist.github.com/redfish64/975ab9f95fb508021ba2948781db59a0

```
foo : Integer
foo = 
  let z : Int
      z = 1
      
      y = 1
  in y
    

fee : Integer
fee = y
```

This only happens if I give `z` a type. If I comment out `z : Int` it errors apprpriately.

# Steps to Reproduce

Typecheck

# Expected Behavior

```
- + Errors (1)
 `-- ParamBug.idr line 12 col 6:
     While processing right hand side of fee. Undefined name y. 
     
     ParamBug:12:7--12:8
      08 |   in y
      09 |     
      10 | 
      11 | fee : Integer
      12 | fee = y
                 ^
```     

# Observed Behavior

OK!

**Comment by dunhamsteve** [comment]
If I add another let:
```idris
foo : Integer
foo =
  let a = 1 in
  let z : Int
      z = 1

      y = 1
  in y
    
fee : Integer
fee = y
```
I get:
```
1/1: Building Temp (Temp.idr)
Error: While processing right hand side of foo. While processing right hand side of y. Can't find an implementation for Num ((a : ?_) -> ?_).

Temp:7:11--7:12
 3 |   let a = 1 in
 4 |   let z : Int
 5 |       z = 1
 6 | 
 7 |       y = 1
```
Which seems weird.  Looks like it thinks y is being applied to a? 

Using the alternate syntax `y := 1` resolves the issue:
```idris
foo : Integer
foo =
  let z : Int
      z = 1

      y := 1
  in y
    
fee : Integer
fee = y
```
Wild guess is that it's parsing the following as one function definition, then noticing that `y` is not z and splitting it off into its own function definition, but in the wrong scope:
```idris
z : Int
z = 1
y = 1
```

**Comment by dunhamsteve** [comment]
Yeah, I think related to #1952 - that code is being triggered for `y`:
```
LOG declare.def:5: Missing type declaration for the alias Main.y. Checking first whether it is a misspelling.
LOG declare.def:5: Not a misspelling: go ahead and declare it!
```

See also #2592

**Comment by gallais** [comment]
Ugh, I thought I had already reverted the alias feature. :weary:
