### ISSUE TITLE
passing functions with implicits args sometimes fails unexpectedly and sometimes doesn't fail unexpectedly.

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#2788]
In the below code, `boo` and `bee` typecheck as expected. But when I placed the implicit arg in front ,as with `foo` and `fee`, it no longer type checks with the error below. Also, `cee` typechecks even though when it calls `coo` it's passing a func with the second arg explicit to `coo` which expects the second arg to be implicit.

https://gist.github.com/redfish64/abe69eec15761f921c371feb77f644e4

```
boo : (Int -> {x : Int} -> Int) -> Int -> Int
boo fn v = fn v {x=35}

bee : (Int -> {x : Int} -> Int) -> Int
bee fn = boo fn 1

foo : ({x : Int} -> (y: Int) -> Int) -> Int -> Int
foo fn v = fn {x=35} v

fee : ({x : Int} -> (y: Int) -> Int) -> Int
fee fn = foo fn 1

coo : (Int -> {x : Int} -> Int) -> Int -> Int
coo fn v = fn {x=35} v

cee : (Int -> Int -> Int) -> Int
cee fn = coo fn 1
```

# Steps to Reproduce

Typecheck

# Expected Behavior

`cee` fails to typecheck, `fee` typechecks fine.

# Observed Behavior

`cee` typechecks fine, `fee` fails with the following error:

```
- + Errors (1)
 `-- LearnFunc.idr line 14 col 13:
     Unsolved holes:
     Main.{x:880} introduced at: 
     LearnFunc:14:14--14:16
      10 | foo : ({x : Int} -> (y: Int) -> Int) -> Int -> Int
      11 | foo fn v = fn {x=35} v
      12 | 
      13 | fee : ({x : Int} -> (y: Int) -> Int) -> Int
      14 | fee fn = foo fn 1
                        ^^
```

**Comment by gallais** [comment]
In

```
fee : ({x : Int} -> (y: Int) -> Int) -> Int
fee fn = foo fn 1
```

implicit lambdas are introduced eagerly and then, because the missing value
cannot be reconstructed by unification, Idris complains.

`fee fn = foo fn 1` is elaborated to `fee fn = foo (\ {x} => fn {x = ?a}) 1`

In general you should only use implicit arguments for things that can be
reconstructed by unification.
