### ISSUE TITLE
Question: why functor laws are not required in the interface?

### ISSUE THREAD

**Issue by freddi301** [idris-lang/Idris2#2809]

**Comment by gallais** [comment]
Please only use the bug tracker to report issues / feature requests.
This is better posted to the mailing list, or the learning channel of the discord server.

Incidentally, [there is an answer to this question in the FAQ](https://idris2.readthedocs.io/en/latest/faq/faq.html#why-don-t-the-functor-applicative-monad-and-other-interfaces-include-the-laws).

**Comment by freddi301** [comment]
Sorry and thank you :)

**Comment by freddi301** [comment]
I couldn't find the laws about functors in the lib. Any hint?

**Comment by freddi301** [comment]
self reply

> I couldn't find the laws about functors in the lib. Any hint?

last line in https://idris2.readthedocs.io/en/latest/faq/faq.html#why-don-t-the-functor-applicative-monad-and-other-interfaces-include-the-laws
