### ISSUE TITLE
Custom backend (chez CG based): Module Prelude not found

### ISSUE THREAD

**Issue by nukisman** [idris-lang/Idris2#2874]
I try to reproduce simple example of tutorial by creating minimal custom backend: https://idris2.readthedocs.io/en/latest/backends/custom.html

# Environment
- OS: Mac OS Montery (12.2.1)
- Idris2 installed via homebrew at `/usr/local/Cellar/idris2/0.6.0`
```
$ idris2 --libdir
/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0

$ idris2 --paths
+ Working Directory      :: "/Users/uruk/job/idris2-custom-backend"
+ Source Directory       :: Nothing
+ Build Directory        :: "build"
+ Local Depend Directory :: "depends"
+ Output Directory       :: "build/exec"
+ Installation Prefix    :: "/usr/local/Cellar/idris2/0.6.0/libexec"
+ Extra Directories      :: [".", "/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/prelude-0.6.0", "/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/base-0.6.0"]
+ Package Directories    :: []
+ CG Library Directories :: ["/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/lib", "/Users/uruk/job/idris2-custom-backend"]
+ Data Directories       :: ["/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/support"]
```

# Steps to Reproduce
- Install idris2 to the system as a library:
  - Git checkout https://github.com/idris-lang/Idris2 (62811c56)
  - `make install-api`, so I successfully get this:
    ```
    $ ls /usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/
    base-0.6.0      idris2-0.6.0    linear-0.5.1    prelude-0.6.0   test-0.6.0
    contrib-0.6.0   lib             network-0.6.0   support
    ``` 
- Git checkout project from https://github.com/nukisman/idris2-custom-backend/tree/cg/chez
- Build compiler with custom "Lazy" backend from tutorial (based on chez CG)
```
$ make build-lazy
time idris2 \
                --verbose \
                --cg chez \
                --directive pretty \
                -o lazy-idris2 \
                -p prelude \
                -p base \
                -p contrib \
                -p idris2 \
                -p network \
                src/Lazy.idr
1/1: Building src.Lazy (src/Lazy.idr)
       97.57 real        91.94 user         4.98 sys

$ find build
build
build/ttc
build/ttc/src
build/ttc/src/Lazy.ttc
build/ttc/src/Lazy.ttm
build/exec
build/exec/lazy-idris2_app
build/exec/lazy-idris2_app/lazy-idris2.so
build/exec/lazy-idris2_app/lazy-idris2.ss
build/exec/lazy-idris2_app/compileChez
build/exec/lazy-idris2_app/libidris2_support.dylib
build/exec/lazy-idris2
```
- Run built compiler
```
$ make run-lazy-0
./build/exec/lazy-idris2 --cg lazy src/Hello.idr -o hello
Error: Module Prelude not found

(Interactive):1:1--1:1
 1 | module Main
     

Error: Undefined name unsafePerformIO. 

(Interactive):1:1--1:1
 1 | module Main
     

make: *** [run-lazy-0] Error 1
```
- I also have tried to add package prelude as explicit dependency
```
$ make run-lazy-1
./build/exec/lazy-idris2 \
        -p prelude \
        -o hello \
        src/Hello.idr
Uncaught error: Can't find package prelude (any)
make: *** [run-lazy-1] Error 1
```
- And try to specify location of prelude by fixing some paths
```
$ make run-lazy-2
IDRIS2_PREFIX=/usr/local/Cellar/idris2/0.6.0/libexec \
        IDRIS2_PATH=/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/prelude-0.6.0 \
        ./build/exec/lazy-idris2 \
        -p prelude \
        -o hello \
        src/Hello.idr
Error: Module Prelude not found

(Interactive):1:1--1:1
 1 | module Main
     

Error: Undefined name unsafePerformIO. 

(Interactive):1:1--1:1
 1 | module Main
     

make: *** [run-lazy-2] Error 1
```
# Expected Behavior

Modules from embedded library `prelude`  (like `Prelude` and `PrimIO`) should be found

# Observed Behavior

- `Error: Module Prelude not found`
- `Error: Undefined name unsafePerformIO.`

**Comment by mattpolzin** [comment]
I think I know what is going on. Can you post the output of `ls /usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/prelude-0.6.0`?

**Comment by mattpolzin** [comment]
What I believe is causing problems is that you had Idris 2 version 0.6.0 installed on your system but when you check out the latest head of the repo and install the Idris 2 api using it you are actually getting an incompatible version of the API -- it still says it's "v0.6.0" but it's actually well on its way to being the next release version and importantly there's a breaking change with how package files are installed to the system after 0.6.0. 

Try this:
1. Remove the installed Idris 2 API (specifically delete the `/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/idris2-0.6.0` folder, not all of the packages). 
2. Check out the Idris 2 repo at the v0.6.0 tag. 
3. `make clean` and then `make install-api`.

**Comment by nukisman** [comment]
@mattpolzin Thanks a lot! 
Now it works: 
```
$ make run-lazy
IDRIS2_PREFIX=/usr/local/Cellar/idris2/0.6.0/libexec \
        ./build/exec/lazy-idris2 \
                -o hello \
                src/Hello.idr
I'd rather not.
```
