### ISSUE TITLE
Custom backend (node CG based): No supported backend found in the definition of Prelude.IO.prim__putChar

### ISSUE THREAD

**Issue by nukisman** [idris-lang/Idris2#2875]
I try to reproduce simple example of tutorial by creating minimal custom backend (but **node** based, not chez): https://idris2.readthedocs.io/en/latest/backends/custom.html

# Environment
- OS: Mac OS Montery (12.2.1)
- Idris2 installed via homebrew at `/usr/local/Cellar/idris2/0.6.0`
- NodeJS v18.12.1
```
$ idris2 --libdir
/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0

$ idris2 --paths
+ Working Directory      :: "/Users/uruk/job/idris2-custom-backend"
+ Source Directory       :: Nothing
+ Build Directory        :: "build"
+ Local Depend Directory :: "depends"
+ Output Directory       :: "build/exec"
+ Installation Prefix    :: "/usr/local/Cellar/idris2/0.6.0/libexec"
+ Extra Directories      :: [".", "/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/prelude-0.6.0", "/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/base-0.6.0"]
+ Package Directories    :: []
+ CG Library Directories :: ["/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/lib", "/Users/uruk/job/idris2-custom-backend"]
+ Data Directories       :: ["/usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/support"]
```

# Steps to Reproduce
- Install idris2 to the system as a library:
  - Git checkout https://github.com/idris-lang/Idris2 (102d7ebc - tag v0.6.0)
  - `make install-api`, so I successfully get this:
    ```
    $ ls /usr/local/Cellar/idris2/0.6.0/libexec/idris2-0.6.0/
    base-0.6.0      idris2-0.6.0    linear-0.5.1    prelude-0.6.0   test-0.6.0
    contrib-0.6.0   lib             network-0.6.0   support
    ``` 
- Git checkout project from https://github.com/nukisman/idris2-custom-backend/tree/cg/node
- Build compiler with custom "Lazy" backend from tutorial (but using `--cg node`)
```
$ make build-lazy
time idris2 \
                --verbose \
                --cg node \
                --directive pretty \
                -o lazy-idris2 \
                -p prelude \
                -p base \
                -p contrib \
                -p idris2 \
                -p network \
                src/Lazy.idr
1/1: Building src.Lazy (src/Lazy.idr)
Error: INTERNAL
ERROR: No supported backend found in the definition of Prelude.IO.prim__putChar. Supported backends: "node","javascript". Backends in definition: "C".
       55.34 real        53.66 user         1.54 sys
```

# Expected Behavior

No errors while building custom compiler. 
E.g. `chez`-based compiler pass this (and next) steps successfully: https://github.com/idris-lang/Idris2/issues/2874

# Note:
Other programs compile and run successfully using node CG:
```
$ make build-hello
time idris2 \
                --verbose \
                --cg node \
                -o hello.js \
                src/Hello.idr
1/1: Building src.Hello (src/Hello.idr)
        1.18 real         1.04 user         0.13 sys

$ make run-hello
node build/exec/hello.js
Hello
```

**Comment by Z-snails** [comment]
I doubt that was the only FFI function preventing idris from compiling on node, so feel free to reopen this if that is the case.
Although I doubt idris will be able to compile to JS any time soon, as there is now the 'scheme evaluator' which is fairly tightly tied to the scheme backend.
