### ISSUE TITLE
Quantity checker gets confused by applications 

### ISSUE THREAD

**Issue by andrevidela** [idris-lang/Idris2#2895]
In some complicated programs involving `0` or `1` the linearity checker sometimes throws 

> *complicated type* not a function type

The error message itself leaves a lot to be desired because the names aren't printed. More more importantly, this error is almost always a bug and workarounds are readily accessible, so either:
- the workarounds are wrong and it's a bug
- the error itself is a bug
- None of this is a bug, the error message should be changed.

Given how intuitive the workaround are, I suspect it's number 2 and the linearity checked should be updated to avoid this error entirely. I have two code samples,
one where the error is triggered by a pattern, and one where the error is triggered by a lambda

# Steps to Reproduce

#### Trigger with pattern

```haskell
record Ty where
  constructor MkTy
  0 obj : Type

record TyProj (d: Ty) where
  constructor MkTyProj
  proj : d.obj

record Id (x : Type) where
  constructor MkId
  getId : x

DepLensToDepOptic :
  {c1 : TyProj (MkTy (Nat -> Type))} ->
  Id (c1.proj 3) -> -- remove the Id works
  Type
DepLensToDepOptic (MkId b') = ?hu
```

#### Trigger with lambda

```haskell
record Ty where
  constructor MkTy
  0 obj : Type

record TyProj (d: Ty) where
  constructor MkTyProj
  proj : d.obj

DepLensToDepOptic :
  {c1 : TyProj (MkTy (Nat -> Type))} ->
  (c1.proj 3) ->
  Type
DepLensToDepOptic =
   (\(b) => ?mmm)
-- DepLensToDepOptic b = ?hole -- this works
```

# Expected Behavior

Should typecheck, specially given that:

- In the first case, removing `Id`  works.
- In the second case, putting `b` in the lhs works

# Observed Behavior

```
Linearity checking failed on (Main.TyProj.(.proj) [__] c1[0]) ([__] not a function type)
```
and
```
Linearity checking failed on (Main.TyProj.(.proj) [__] c1[1]) ([__] not a function type)
```
respectively

**Comment by andrevidela** [comment]
worth noting that #1435 has an example of this error popping up as well

**Comment by dunhamsteve** [comment]
There are two branches in that case statement that produce this error, in both of these cases it is the default branch that is being hit, and the scrutinee is `NErased _ Placeholder`.

https://github.com/idris-lang/Idris2/blob/30866fa89297ebf1d991d75b34e4cf2e7b12733c/src/Core/LinearCheck.idr#L351-L353

It is being applied to 3 (I added logging of `toFullNames a`):
```
LOG totality:3: Main.TyProj.(.proj) must be: covering
Error: Linearity checking failed on (Main.TyProj.(.proj) [__] c1[1]) ([__] not a function type) ([__]) applied to ((Prelude.Types.S (Prelude.Types.S (Prelude.Types.S Prelude.Types.Z))))
```
I've included the previous log message, at level 50, in case it helps establish some context.

**Comment by andrevidela** [comment]
I've gotten to the same conclusion, it looks like the `lcheck` of `proj c1` returns `NErased` but shouldn't

**Comment by dunhamsteve** [comment]
If it helps, the Erased is coming from LinearCheck.idr:665 (I put some dummy FC at likely locations and that's the one that showed up for both cases).

https://github.com/idris-lang/Idris2/blob/30866fa89297ebf1d991d75b34e4cf2e7b12733c/src/Core/LinearCheck.idr#L665

**Comment by andrevidela** [comment]
removing this line seems to fix the issue https://github.com/idris-lang/Idris2/blob/30866fa89297ebf1d991d75b34e4cf2e7b12733c/src/Core/LinearCheck.idr#L327

**Comment by dunhamsteve** [comment]
oh, shoot, you're right, ignore my last comment. I missed that it was adding 1 when printing the FC.

**Comment by gallais** [comment]
> That seems to be a performance optimization but how should we test performance for this case?

I would say it has more to do with the fact that an erased term should not count towards your linearity budget?

**Comment by andrevidela** [comment]
I assume the linearity budget is accounted for by the `Usage` context which isn't affected by this change, which would explain why removing this line doesn't break anything in the tests
