### ISSUE TITLE
let ; in do notation fails to parse

### ISSUE THREAD

**Issue by fonqL** [idris-lang/Idris2#2923]
# Steps to Reproduce

```
main: IO ()
main = do
  let x = 123; print x
```

This can be parsed well in idris1, but not in idris2.
And [idris2 document](https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html#monads-and-do-notation) say it should be a valid expression.

# Expected Behavior
Compile success.

# Observed Behavior
Compile error.

**Comment by buzden** [comment]
It is written not so clear in this particular place, but generally clauses can be separated by semicolon only if the body of `do` is enclosed in curly braces. The same applies, by the way, to `case`. So, your example should not parse, but, say
```idris
main: IO ()
main = do {
  let x = 123; print x}
```
should.

**Comment by fonqL** [comment]
Still error.
```
Error: Last statement in do block must be an expression

1:3:16--3:23
 1 | main: IO ()
 2 | main = do {
 3 |   let x = 123; print x}
                    ^^^^^^^
```

**Comment by buzden** [comment]
Yeah, this is indeed strange, especially considering that a newline after `;` makes this parse normally.

**Comment by Alex1005a** [comment]
It seems that bind with pattern matching is also incorrectly rejected.
```idris
validDoBlock : IO ()
validDoBlock =
  do { Just x <- pure (Just 123) | Nothing => pure () ; print x }
```
And rewrite in do block are parsed correctly.
```idris
main : IO $ Singleton (0 * 10)
main =
  do { rewrite multZeroLeftZero 10 ; pure $ Val 0 }
```
