### ISSUE TITLE
Compiler can't determine correct `allFins` in client code

### ISSUE THREAD

**Issue by guygastineau** [idris-lang/Idris2#2938]
https://github.com/idris-lang/Idris2/blob/87ebe7d9327fa08028ec010e97bb5c4759a51031/libs/base/Data/Fin.idr#L160

I am making a linear array implementation with safe indexing.  I have a function for mapping the indices to build a linear array and convert it to an immutable version:

``` idris
public export
mapIndices : (n : Nat) -> a -> (Fin n -> a) -> IArray n a
mapIndices n x f = toIArray (newArray n x (go $ allFins n))
  where
    go : List (Fin n) -> (1 _ : LinArray n a) -> LinArray n a
    go []        arr = arr
    go (i :: is) arr = go is (write arr i (f i))
```

But the compiler only finds https://github.com/idris-lang/Idris2/blob/87ebe7d9327fa08028ec010e97bb5c4759a51031/libs/base/Data/Fin.idr#L168

I expected it to disambiguate the functions based on the type, which is clearly given in the `go` function of the where clause.  I also tried using the namespace directly, `List.allFins`, but I think it ends up just searching in `Data.List`, because it says the name does not exist.

Is there some other way to use namespaces explicitly that I am missing?

**Comment by gallais** [comment]
Can you please post a self-contained (ideally minimised) example?

**Comment by guygastineau** [comment]
``` idris
module AllFinsDisambiguation

import Data.Fin

finsFor : (n : Nat) -> List (Fin n)
finsFor = allFins
```
With the above in a file called `AllFinsDisambiguation.idr` in emacs running `C-c C-l` I get the following:

```
- + Errors (1)
 `-- AllFinsDisambiguation.idr line 6 col 10:
     While processing right hand side of finsFor. When unifying:
         (n : Nat) -> List1 (Fin (S n))
     and:
         (n : Nat) -> List (Fin n)
     Mismatch between: List1 (Fin (S n)) and List (Fin n).
     
     AllFinsDisambiguation:6:11--6:18
      2 | 
      3 | import Data.Fin
      4 | 
      5 | finsFor : (n : Nat) -> List (Fin n)
      6 | finsFor = allFins
```

**Comment by guygastineau** [comment]
I am using `Idris 2, version 0.6.0-9a2ad66b7` on arch linux from the AUR.  I rebuilt it yesterday with a fresh pull, and all test suites passed.

**Comment by guygastineau** [comment]
Further inspection of my build scripts shows I am actually using the source hosted at https://www.idris-lang.org/idris2-src/idris2-0.6.0.tgz which is from October of last year (though it seems to be the current release).

**Comment by stefan-hoeck** [comment]
Your example works fine on my end (current HEAD of Idris2). The `List` version of `allFins` has been added in #2903 , so it seems in your version of the standard lists, only the `List1` version exists.

**Comment by guygastineau** [comment]
@stefan-hoeck thank you.  A classic case of looking at the wrong version of the docs.  Sorry for the noise.  I guess I must consider using the bleeding edge of Idris then.

**Comment by stefan-hoeck** [comment]
Unfortunately, new Idris releases happen rather infrequently, so many of the community stay close to HEAD. Consider using a package manager such as [pack](https://github.com/stefan-hoeck/idris2-pack) for keeping track of your Idris compiler and packages. I'm also an arch user, but use pack for keep Idris up to date.
