### ISSUE TITLE
Idris complains that two identical with clauses containing a sugared dependent pair are in fact not identical.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris2#297]
Idris2 complains that a valid with clause contain a sugared dependent pair doesn't match its parent.

Given the following Idris2 program:

```
data Foobar : String -> Type where
  MkBar : (s : String) -> Foobar s

test : (foobar : (x ** Foobar x)) -> String
test (MkDPair fst snd) with (snd)
  test (MkDPair fst snd) | (MkBar fst) = ?test_rhs__rhs_

test' : (foobar : (x ** Foobar x)) -> String
test' (s ** foobar) with (foobar)
  test' (s ** foobar) | with_pat = ?test'_rhs_rhs
```

Note both functions were completed using Idris2's interactive editing, with the difference being the second function had the argument rewritten by hand to a sugared dependent pair.

# Steps to Reproduce

Enter the program into a module called `With.idr` and type check it with Idris2.

# Expected Behavior

The program should type-check presenting two holes ready to be filled in.
Prior to adding the with-clause to `test'` Idris2 accepted a sugared dependent pair on the LHS.

# Observed Behavior

Idris complains that the with clauses in `test'` are mismatched.

```
- + Errors (1)
 `-- With.idr line 11 col 7:
     With clause does not match parent
```

**Comment by edwinb** [comment]
I wonder if this is due to the overloaded syntax not having being resolved yet at the point when it checks it's a valid `with` clause. I see there are `IAlternative` constructors so probably it just needs to look inside there when checking for the match.

**Comment by jfdm** [comment]
thanks!
