### ISSUE TITLE
Build Idris2 compiler for NodeJS

### ISSUE THREAD

**Issue by freddi301** [idris-lang/Idris2#2979]
I'm trying to build the idris compiler to a js executable for nodejs.
 
 The ultimate goal is:
 - build idris2 for nodejs and publish a package on npmjs so users can install js artifact with `npm install idris2`
 - once the node build is done, use browserify to make a idris2 compiler build for the browser
 - include a idris2 web editor in the idris site eventually
 
I'm trying with this command:

 ```idris2 --codegen node --build idris2.ipkg```
 
 [related issue](https://github.com/idris-lang/Idris2/issues/1349)

**Comment by freddi301** [comment]
Till now i get this error

```
Uncaught error: INTERNAL ERROR: No supported backend found in the definition of System.File.ReadWrite.prim__readChar. Supported backends: "node","javascript". Backends in definition: "C".
```

And it keeps popping up even after i added

```
%foreign "C:fgetc,libc 6"
		"node:lambda:() => { throw new Error() }"
prim__readChar : FilePtr -> PrimIO Int
```

**Comment by mattpolzin** [comment]
The compilation of Idris will use currently installed libraries to build itself before then using the new build of itself to rebuild all libraries. If you want to make a change to a library to test how it will impact building the compiler, you need to explicitly rebuild just that library and then install it and then rerun a build of the compiler. 

While admirable, you'll likely hit a number of issues (some show-stopping, if my vague recollection is correct) with building the compiler with the Node backend. To date, no one has done the work to build the compiler with any non-scheme backends, though at one point RefC was close.

Here's a likely partial list of missing Node FFI functions: https://github.com/idris-lang/Idris2/issues/2207

You may also run into the lacking support for a scheme interpreter, but I don't recall if that interpreter support ever got used by the compiler code itself.

**Comment by dunhamsteve** [comment]
I suspect stack or memory size might be an issue, too.  But I've entertained similar ideas, and it wouldn't hurt to at least catalog where the process gets stuck.

I have gotten TinyIdris and  an earlier version of Yaffle working in the browser by compiling for node and stubbing out the node api. But they couldn't do interaction in the browser, because of the async thing.    (I do wonder if we could compile IO to async functions, but I haven't explored the idea.)

The other thing that might be worth exploring is writing a WASM back end. It's only my long list of ideas.

**Comment by freddi301** [comment]
I managed to build the executable. I stubbed the missing node ffi. Now il will try to make it compile a single file at least. [commit](https://github.com/idris-lang/Idris2/commit/2278934133969c5d79fbb90da7938a8b04a60fa0)

**Comment by freddi301** [comment]
Implemented some more ffi. [commit](2278934133969c5d79fbb90da7938a8b04a60fa0)

Now the error i get is:

```
Welcome to Idris 2.  Enjoy yourself!
Uncaught error: Error: Module Prelude not found
```

I-m posting here the advanvements maybe somebody interested hooks in 😃

**Comment by freddi301** [comment]
I'm closing the issue as i managed to compile a working executable for nodejs in favor of this pull request https://github.com/idris-lang/Idris2/pull/2981
