### ISSUE TITLE
Chez's eager evaluation of zero-argument functions is unsound

### ISSUE THREAD

**Issue by Z-snails** [idris-lang/Idris2#3003]
```idris
-- no_clauses.idr
%default total

bad : (0 _ : Z = S Z) -> Void
bad _ impossible

data BadPrf = Ok | No (Z = S Z)

Show BadPrf where
    show Ok = "Ok"
    show (No prf) = absurd $ bad prf

main : IO ()
main = printLn Ok
```

# Steps to Reproduce

```sh
> idris2 -x main no_clauses.idr
```

# Expected Behavior

Outputs `Ok`

# Observed Behavior

Crashes with the message `No clauses`

This is caused by idris producing the following scheme code:
```scheme
(define Main-bad (blodwen-error-quit "No clauses"))
```

Because `Main.bad` is a zero argument function, idris tries to eagerly evaluate it, however the function has no definition so this can't work.

(this was discovered in #3002, however #3002 is not the root cause)

**Comment by dunhamsteve** [comment]
I think this will do the trick:

```
diff --git a/src/Compiler/Opts/ToplevelConstants.idr b/src/Compiler/Opts/ToplevelConstants.idr
index e7bf46cd6..addef99a1 100644
--- a/src/Compiler/Opts/ToplevelConstants.idr
+++ b/src/Compiler/Opts/ToplevelConstants.idr
@@ -15,7 +15,7 @@ import Libraries.Data.SortedMap
 --          Call Graph
 --------------------------------------------------------------------------------
 
--- direct calls from a top-level funtion's expression to other
+-- direct calls from a top-level function's expression to other
 -- top-level functions.
 0 CallGraph : Type
 CallGraph = SortedMap Name (SortedSet Name)
@@ -104,7 +104,8 @@ sortDef n = do
   appendDef t
 
 isConstant : (recursiveFunctions : SortedSet Name) -> (Name,FC,NamedDef) -> Bool
-isConstant rec (n, _, MkNmFun [] _) = not $ contains n rec
+isConstant rec (n, x, MkNmFun [] (NmCrash _ _)) = False
+isConstant rec (n, x, MkNmFun [] y) = not $ contains n rec
 isConstant _   _                  = False
 
 export
```

**Comment by dunhamsteve** [comment]
I can PR this (with test) after CI completes, or you can fold it into #3002.  I've verified that it fixes the issues over there too.

**Comment by Z-snails** [comment]
Have you checked this works even if the crash is hidden behind another function?

eg
```idris
%noinline
foo : (0 _ : Z = S Z) -> Void
foo _ impossible

%noinline
bah : (0 _ : Z = S Z) -> Void
bah prf = foo prf
```

**Comment by dunhamsteve** [comment]
I did not think of that, but I should have.  It does not handle this case.

If we want to keep eager evaluation, one option is to take the call graph that we have in the body of `sortDefs` and enumerate functions that crash or call something that crashes.  But if "crashes" is determined by my pattern match, it might not find crashes that are buried deeper in the function.

**Comment by dunhamsteve** [comment]
I implemented that proposal at e46de0e.  It doesn't treat a function as constant if it crashes somewhere in its body or if it transitively calls a function that can crash.

There are 36 top level functions in idris2 that it decides to not make constants. Eight of them are the `codegen*` functions and the rest are csegen.  1065 top level functions that remain as constants.

**Comment by stefan-hoeck** [comment]
My two cents on this: The unsoundness here does not necessarily come from the codegen/runtime but from the code itself: I can't think of a usecase where `bad` should not be annotated with quantity zero. Unfortunately, the argument of `absurd` does not have quantity zero, which is a mistake in my opinion. But you can always write `void (absurd bad)`.

It's perfectly reasonable for the runtime to fail if you define a toplevel constant that leads to an error. I'd argue that most strict programming languages would behave like this.

**Comment by dunhamsteve** [comment]
If we want to address this issue, there a simpler approach at dunhamsteve/idris2@3c179d0 that doesn't traverse the functions.  Although perhaps the original `isConstant` tweak is sufficient if the goal is to get #3002 working. 

It looks like #3002 would be useful.  But now I'm wondering what the exact issue is over there. What is getting erased to cause this?   I build a vanilla idris and grepped "No clauses" out of libs/prelude, and I see stuff like:

```scheme
(define PreludeC-45Show-u--show_Show_Void (lambda (arg-0) (blodwen-error-quit "No clauses")))
```

But that wouldn't be a unit type getting erased - it's a void type being erased. Could #3002 be addressed by not erasing void types?

**Comment by Z-snails** [comment]
> It's perfectly reasonable for the runtime to fail if you define a toplevel constant that leads to an error. I'd argue that most strict programming languages would behave like this.

I disagree with that, in my opinion zero argument functions should be treated semantically as actual functions not constants


@dunhamsteve 
The functions which are being made into zero argument functions are likely implementations of `Uninhabited` such as `Uninhabited (Z = S Z)`
(the crash definitely comes from `Prelude.Uninhabited`)

**Comment by stefan-hoeck** [comment]
> I disagree with that, in my opinion zero argument functions should be treated semantically as actual functions not constants Edit: #3002 also turns functions with arguments into zero-argument functions, so the backend should preserve behaviour.

That sounds reasonable. The semantics are indeed different here.
