### ISSUE TITLE
Type Checker bug using dependent types with a "Bind" pattern (ex STrans)

### ISSUE THREAD

**Issue by redfish64** [idris-lang/Idris2#301]
In order to learn Idris / Idris2 I decided to try and port the contrib library over to Idris2. But I'm running into the following type checker error. 

Below is a simplified version of "STrans" from Control/ST.idr in the idris 1 contrib library.

https://gist.github.com/redfish64/8924d6c7f7a77fa474cf160c1ffc4cde

I've tried this code both with v0.2.0 and the latest commit in master as of now (59800e1f).   

```
public export
data STrans : (ty : Type) ->
              Int -> (myoutfn : ty -> Int) ->
              Type where
     Pure : (result : ty) -> STrans ty (out_fn result) out_fn 
     Bind : {st2_fn : b -> Int} -> -- if you comment this out, it works
            STrans a st1 st1_fn -> ((result : a) -> 
            STrans b (st1_fn result) st2_fn) ->
            STrans b st1 st2_fn

-- this works
foo : STrans Bool 0 (\res => if res then 1 else 0)
foo = Pure False

-- this works, too
foo2 : STrans Bool 0 (\res => if res then 1 else 0)

-- but implement it using bind, and we have some trouble
foo3 : STrans Bool 0 (\res => if res then 1 else 0)
foo3 = Bind (Pure False) (const $ Pure False)
```

# Steps to Reproduce

Compile and idris2 reports type error.

# Expected Behavior

OK!

# Observed Behavior
- + Errors (1)
 `-- LearnBug.idr line 19 col 30:
     While processing right hand side of foo3 at LearnBug.idr:20:1--21:1:
     Main.case block in 1207(282) is not accessible in this context

Note the error highlights the *definition* of foo3, not the implementation, but the only difference between foo2 and foo3 is foo3 has an implementation.

**Comment by gallais** [comment]
In `Pure` you are letting Idris implicitly quantify over `out_fn` which it happily does **at multiplicity 0**.
In `Bind` you are explicitly introducing `st2_fn` and assign it an **unlimited quantity**.

Putting the two together, with `Bind _ (const $ Pure False)` you're getting an
`out_fn` at multiplicity 0 & unification tries to use it as a solution for
`st2_fn` at an unrestricted multiplicity. That won't work.

That being said, here we have a closed term so I don't see the harm in
duplicating the term even if its multiplicity is 0.
