### ISSUE TITLE
Show module docstring for namespace indexes

### ISSUE THREAD

**Issue by scarf005** [idris-lang/Idris2#3014]
- [x] I have read [CONTRIBUTING.md](https://github.com/idris-lang/Idris2/blob/main/CONTRIBUTING.md).
- [x] I have checked that there is no existing PR/issue about my proposal.

## Summary

|   Before  |  After   |
|-----------|----------|
| ![before] | ![after] | 

[before]: https://github.com/idris-lang/Idris2/assets/54838975/74ca5491-c055-4789-84e7-7859666e3d3a
[after]: https://github.com/idris-lang/Idris2/assets/54838975/25b3d367-0240-4122-9055-8f0ca86bb70a

## Motivation

|   [Hoogle][search-hoogle]  |  [Idris2][search-idris2]  |
|-----------|----------|
| ![hoogle] | ![idris] | 

[hoogle]: https://github.com/idris-lang/Idris2/assets/54838975/c58dfcca-61fb-4aba-ac16-1344bb3f705f "hoogle display"
[idris]: https://github.com/idris-lang/Idris2/assets/54838975/a0eb27ca-cc1a-4332-b2f1-765f3f2ccfb0

[search result on hoogle][search-hoogle] shows module summary, which is very helpful for beginners.

[search-hoogle]: https://hoogle.haskell.org/?hoogle=List
[search-idris2]: https://test.idris-lang.org/Idris2/base/

## The proposal

As shown in [summary](#Summary), provide brief summary for each modules.

### Technical implementation

1. use module docstring 

```idr
||| Types and functions for reasoning about time.
module System.Clock
```

will output `Types and functions for reasoning about time.`

2. add it to resulting html.
3. truncate if it's too long.
4. use [`flexbox`](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) and [`justify-content: space-around`](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) to make it pretty.

**Comment by Matthew-Mosior** [comment]
See https://github.com/idris-lang/Idris2/pull/3351

**Comment by scarf005** [comment]
> See #3351

looks great, could you [link this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) too so it gets closed when the PR is merged?

**Comment by Matthew-Mosior** [comment]
> > See #3351
> 
> looks great, could you [link this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) too so it gets closed when the PR is merged?

Sounds good, I updated the description of the PR.

**Comment by gallais** [comment]
It's now live at https://test.idris-lang.org/Idris2/base/
