### ISSUE TITLE
Bootstrapped Idris2 fails to resolve paths when `IDRIS2_PREFIX` is manually set

### ISSUE THREAD

**Issue by scarf005** [idris-lang/Idris2#3022]
# Summary

```
# ...logs
/home/scarf/repo/Idris2/bootstrap-build/bin/idris2 --build idris2.ipkg
Uncaught error: EmptyFC:Failed to resolve the dependencies for idris2app:
  required network any but no matching version is installed

make[1]: *** [Makefile:67: /home/scarf/repo/Idris2/build/exec/idris2] Error 1
make[1]: Leaving directory '/home/scarf/repo/Idris2'
make: *** [Makefile:249: bootstrap] Error 2
```

Idris2 bootstrapped from source (commit 23694c7e5af11c263d4dba7f40c550d9bc37509c) with custom environment variables cannot resolve dependency paths.

## environment

environment variables (followed from [official docs](https://idris2.readthedocs.io/en/latest/reference/envvars.html))

IDRIS2_PREFIX: /home/scarf/.local/share/idris2
PACK_DIR: /home/scarf/.local/share/pack
PATH: /home/scarf/.idris2/bin /home/scarf/.pack/bin # ...

scheme version: 9.5.9 (built from source with threads enabled)
OS: Kubuntu 23.04 x86_64
Shell: fish 3.6.0

```
$ SCHEME=scheme ./bootstrap-build/bin/idris2 --paths
+ Working Directory      :: "/home/scarf/repo/Idris2"
+ Source Directory       :: Nothing
+ Build Directory        :: "build"
+ Local Depend Directory :: "depends"
+ Output Directory       :: "build/exec"
+ Installation Prefix    :: "/home/scarf/.local/share/idris2"
+ Extra Directories      :: ["."]
+ Package Directories    :: []
+ CG Library Directories :: ["/home/scarf/.local/share/idris2/idris2-0.6.0/lib", "/home/scarf/repo/Idris2"]
+ Data Directories       :: ["/home/scarf/.local/share/idris2/idris2-0.6.0/support"]
```

## build log

[build.3.log](https://github.com/idris-lang/Idris2/files/12095912/build.3.log)

**Comment by CodingCellist** [comment]
> PATH: /home/scarf/.local/share/idris2 /home/scarf/.local/share/pack # ...

Might it be that PATH should point to `[...]/bin` for both of those? I.e.

```
/home/scarf/.local/share/idris2/bin
/home/scarf/.local/share/pack/bin
```

?  : )

**Comment by CodingCellist** [comment]
Latest `main` seems to bootstrap fine when using a similar directory structure for me. Could this be a [pack](https://github.com/stefan-hoeck/idris2-pack) issue rather than an Idris2 issue?

**Comment by scarf005** [comment]
> Might it be that PATH should point to [...]/bin for both of those? I.e.

...oh, must've mistyped, thanks for finding out. it doesn't seem to work after changing PATH, tho.

[build.2.log](https://github.com/idris-lang/Idris2/files/12104723/build.2.log)

**Comment by scarf005** [comment]
was finally able to build by explicitly setting `IDRIS2_DATA` and `IDRIS2_PACKAGE_PATH`.
as @stefan-hoeck suggested, i believe this is due to my `IDRIS2_PREFIX` env var explicitly est to $XDG_DATA_HOME/idris2` (that is, `/home/scarf/.local/share`).

```
IDRIS2_DATA=./bootstrap-build/idris2-0.6.0/support  IDRIS2_PACKAGE_PATH=./bootstrap-build/idris2-0.6.0/ ./bootstrap-build/bin/idris2 --verbose --build idris2.ipkg
```

**Comment by stefan-hoeck** [comment]
As noted on discord, I have experienced this before. In my case, setting `IDRIS2_PREFIX` was an issue during bootstrapping. If you are using pack, please only set the `PACK_DIR` variable. Pack should take care of everything else.

**Comment by CodingCellist** [comment]
@scarf005 are we good to close this in that case?  : )

**Comment by scarf005** [comment]
Well it's a major bug in bootstrap process so i doubt we should. I'm planning to open a PR (when i get some time)

**Comment by gallais** [comment]
Thanks for the bug report & the investigation!
