### ISSUE TITLE
Misapplication of `Delay` causes indentation error instead of type mismatch

### ISSUE THREAD

**Issue by CodingCellist** [idris-lang/Idris2#3036]
If `Delay` is applied to multiple arguments (an easy mistake to make when constructing codata), the parser reports an indentation error rather than a type mismatch (like when you've accidentally used a type-name instead of its constructor) or otherwise more appropriate error.

## Steps to Reproduce

Self-contained example:

```idris
module DelayParse

public export
data MyStream : Type where
  (::) :  (anA : a)
       -> (nextA : a -> a)
       -> Inf MyStream
       -> MyStream

public export
go : a -> (a -> a) -> MyStream
go initA fn =
  MyStream.(::) initA fn (Delay (fn initA) fn)
  -- the above should be `Delay (go (fn initA) fn)`
```

## Expected Behavior

An error along the lines of "`Delay` expects a `MyStream` not an [insert cryptic `?ty1 -> ?ty2 -> Type` here]".

## Observed Behavior

Indentation error:

```
Error: Not the end of a block entry, check indentation.

DelayParse:13:24--13:25
 09 |
 10 | public export
 11 | go : a -> (a -> a) -> MyStream
 12 | go bar fn =
 13 |   MyStream.(::) bar fn (Delay (bar fn) fn)
                             ^
```

**Comment by gallais** [comment]
It's a parse error because `Delay` is not a constructor like e.g. `S`, it's a language
construct that expects exactly one argument.
We could perhaps tweak the parser to give back a better error message.
