### ISSUE TITLE
pure foreign functions via C FFI do not evaluate in REPL

### ISSUE THREAD

**Issue by tinlyx** [idris-lang/Idris2#3065]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
The issue can be reproduced using the same example in [documentation](https://idris2.readthedocs.io/en/latest/ffi/ffi.html#ffi-example) , which creates an C foreign function for adding two integers. 

small.c:
```
#include <stdio.h>

int add(int x, int y) {
    return x+y;
}
```
Compiled under Ubuntu 22.04 LTS via:
```
gcc -shared smallc.c -o libsmall.so
```

The idris2 file (0.6.0):
```
%foreign "C:add,libsmall"
add : Int -> Int -> Int
```

Now trying to evaluate it in the REPL:

```
add 70 24
```

# Expected Behavior

The expected result is:

`94`

same as evaluating `(+) 70 24`.

# Observed Behavior

The REPL just echoes back the expression without evaluating it.

`add 70 24`

Note: putting the `add` inside and `IO ()` function and then exec-ing it does work, as with the original example .

**Comment by tinlyx** [comment]
I don't understand your comment in relation to the issue. The question is about evaluating pure functions _without_ the :exec and `IO ()`.  I think `:exec` is not about pure functions, as the documentation says that:

> 
> You can also execute expressions directly:
> 
> Main> :exec expr
> 
> Again, expr must have type IO ().

So if one implements a pure `add` function as described in the linked example, one would expect it to be behave like `(+)`. I am new to idris, and not familiar with the stages, but the REPL does do evaluation (in addition to typechecking), doesn't it?

Could you please elaborate how the stages/phases makes the `IO ()` and `:exec` necessary here, or provide a link?

**Comment by stefan-hoeck** [comment]
As @gallais said, foreign function calls do not get reduced / evaluated at compile time. The only primitive functions and values that do get evaluated are the ones built into the compiler. Therefore, this is expected behavior. `:exec` at the REPL properly compiles and runs an expression of type `IO ()`, therefore, we get proper runtime behavior there.
