### ISSUE TITLE
Function of Pair with two unknown, equal types unexpectedly typechecks

### ISSUE THREAD

**Issue by j-towns** [idris-lang/Idris2#3069]
I'm new to using Idris, apologies in advance if this is a known issue or if I am mistaken in some way, I wasn't quite sure what to search for to try to find this in past issues.

# Steps to Reproduce
On Idris 2, version 0.6.0-5fd5b1e73:
```
0 CoupledPair : Type
CoupledPair = {0 x : Type} -> Pair x x

 -- This doesn't typecheck (expected)
f : CoupledPair -> (Nat, Int)
f y = y

 -- This typechecks (unexpected)
g : CoupledPair -> (Nat, Int)
g y = (fst y, snd y)
```

# Expected Behavior
I expected neither `f` nor `g` to typecheck.

# Observed Behavior
The function `f` doesn't typecheck, the function `g` does, despite their definitions being equivalent.

**Comment by j-towns** [comment]
I also expected to be able to match on `y`, as in
```
h : CoupledPair -> (Nat, Nat)
h (y1, y2) = (y1, y2)
```
but that also fails with
```
Error: While processing left hand side of h. Sorry, I can't find any elaboration which works. All errors:
If Builtin.Pair: When unifying:
    Type
and:
    (x, x)
Mismatch between: Type and (x, x).

Flipper:31:4--31:7
 27 |  -- f : CoupledPair -> (Nat, Int)
 28 |  -- f y = y
 29 |
 30 | h : CoupledPair -> (Nat, Nat)
 31 | h (y1, y2) = (y1, y2)
         ^^^

If Builtin.MkPair: When unifying:
    (?a, ?b)
and:
    (x, x)
Mismatch between: (?a, ?b) and (x, x).

Flipper:31:4--31:7
 27 |  -- f : CoupledPair -> (Nat, Int)
 28 |  -- f y = y
 29 |
 30 | h : CoupledPair -> (Nat, Nat)
 31 | h (y1, y2) = (y1, y2)
```

**Comment by gallais** [comment]
It's perhaps clearer if we make the arguments explicit.

In `f`there is no way to pick an `x` such that the problem will typecheck:
1. the first component forces `?a = Nat`
2. but the second demands `?a = Int`

```idris
failing "When unifying: (Int, Int) and: (Nat, Int)"

  f : CoupledPair -> (Nat, Int)
  f y = y {x = ?a}
```

In `g` however there *2 separate* calls to `y` and so that is just fine:

```idris
g : CoupledPair -> (Nat, Int)
g y = (fst (y {x = Nat}), snd (y {x = Int}))
```

As for h, you cannot pattern match on a function as if it had the type of its result.
You need to first apply it e.g.

```idris
i : CoupledPair -> (Nat, Nat)
i y = let (y1, y2) = y {x = Nat} in
      (y1, y2)
```

**Comment by j-towns** [comment]
Thanks very much for the fast response.

Is there a way to introduce two values into scope which have the same, unknown type, and have that type be inferred based on the way they are used? In other words, is there a way to define `CoupledPair` such that it behaves in the way that I was expecting?

**Comment by gallais** [comment]
You can write

```idris
j : (?, ?) -> (Nat, Nat)
j y = y
```

but I don't think it's super idiomatic.

**Comment by j-towns** [comment]
But `?` (which I wasn't aware of, is that similar to an underscore in Agda?) doesn't seem to constrain the types of the two elements to be equal, i.e.
```
g : (?, ?) -> (Nat, Int)
g y = y
```
typechecks and I don't want it to.

In Agda I can do what I want like this:
```agda
CoupledPair : {A : Set} -> Set
CoupledPair {A} = A × A

f : CoupledPair -> Nat × Nat
f (x , y) = (x , {!!})
```
In that hole, it is already known that y has type Nat.

**Comment by gallais** [comment]
I don't know that that's possible.

**Comment by j-towns** [comment]
It actually looks like I can get what I want using `?`, like this:
```
CoupledPair : (x : Type) -> Type
CoupledPair x = Pair x x

 -- This doesn't typecheck
f : CoupledPair ? -> (Nat, Int)
f y = y

 -- This typechecks
g : CoupledPair ? -> (Nat, Nat)
g y = y

 -- And I can match on y
h : CoupledPair ? -> (Nat, Nat)
h (y1, y2) = (y1, ?hole) -- ?hole here is known to have type Nat

```
I'm surprised that `?` fed to an explicit argument works, but making `x` an implicit argument with no `?` doesn't. But the above is definitely good enough for my use case — I have types that are a bit more complicated than Nat and Int and really don't want to have to write them out everywhere.

Would it be helpful if I submitted a pr adding `?` to the docs? I didn't see it anywhere in the 'crash course', but it might already be somewhere else. I was also considering doing this for `\case`, which I don't think is documented either.

Thanks anyway @gallais for the help.
