### ISSUE TITLE
Document `%unsafe`

### ISSUE THREAD

**Issue by andrevidela** [idris-lang/Idris2#3072]
- [x] I have read [CONTRIBUTING.md](https://github.com/idris-lang/Idris2/blob/main/CONTRIBUTING.md).
- [x] I have checked that there is no existing PR/issue about my proposal.

## What needs to be documented

We have added `%unsafe` in but there is not documentation for it.

## Current status

| Documented  | Area |
| ------------- | ------------- |
| N/A | REPL |
| <ul><li>[ ] </li></ul> | Online  |
| N/A  | Source code  |
| N/A | Code samples |

**Comment by dunhamsteve** [comment]
If we want to go further, here are all of the pragmas I found in `Parser.idr` and the documentation files they appear in, if any.  There is a second list of pragmas in `Pragmas.idr` - I believe it is only used for auto-completion.

| pragma | documents |
| ------ | --------- |
| MkWorld | backend-cookbook.rst, multiplicities.rst |
| TTImpLit |
| World | backend-cookbook.rst, multiplicities.rst |
| allow_overloads |
| ambiguity_depth | updates.rst |
| auto_implicit_depth |
| auto_lazy |
| builtin | builtins.rst, pragmas.rst |
| charLit |
| declsLit |
| default | updates.rst, parsing.rst, theorems.rst |
| defaulthint |
| deprecate | pragmas.rst |
| doubleLit |
| export |
| extern |
| foreign | ffi.rst, readline.rst, refc.rst, backend-cookbook.rst, chez.rst, gambit.rst, libraries.rst, javascript.rst, racket.rst |
| globalhint |
| hide | pragmas.rst |
| hint | updates.rst, miscellany.rst |
| inline | pragmas.rst |
| integerLit | overloadedLit.rst |
| language | updates.rst |
| logging | debugging.rst |
| macro |
| name | pragmas.rst |
| nameLit |
| nf_metavar_threshold |
| noinline | pragmas.rst |
| nomangle | libraries.rst (this is deprecated, use export) |
| pair |
| prefix_record_projections | records.rst, typesfuns.rst |
| rewrite |
| runElab |
| search |
| search_timeout |
| spec |
| start |
| stringLit | overloadedLit.rst |
| syntactic |
| tcinline |
| transform | builtins.rst |
| unbound_implicits | overview.rst |
| unhide |
| unsafe |

Also, `%auto_implicits` is mentioned in `faq.rst`, but it does not exist. I believe `%unbound_implicits` was intended.

**Comment by andrevidela** [comment]
This is amazing work, we should definitely use this table to track documentation status

**Comment by dunhamsteve** [comment]
There is also a `%cg`, which I missed because it's handled directly in the Lexer. For javascript, you can do:
```idris
%cg node {minimal}
```
and it's the same as adding `--directive minimal` on the command line.  (It breaks if you have spaces in the `{}`.)

For chez and racket, it looks like this can be used to embed instructions to load extra runtime files (and also library files)
```idris
%cg chez {extraRuntime=/path/to/file.ss}
```

**Comment by andrevidela** [comment]
I think we can close this now, thanks for your amazing work @dunhamsteve
