### ISSUE TITLE
Failing block passes when any statement is false

### ISSUE THREAD

**Issue by CodingCellist** [idris-lang/Idris2#3077]
This came up during a project I'm working on: I didn't catch an implementation error because I was relying on `failing`-blocks to test things, except the blocks compile successfully when only one of the statements within fail, rather than all of them.

I'm unsure if this is intended behaviour. I can sort of see it being useful when you've got a bigger example which is false, e.g. in a blog post or paper, and you want all the parts leading up to the false statement being neatly grouped in the corresponding `failing`-block. However, I think the resulting behaviour is confusing and that `failing`­­-blocks should behave like "all" rather than "any"; having the valid code outside the block, even if it is code that leads down a false path, seems acceptable to me.

# Steps to Reproduce

Shrunk case:

```idris
module MultiFail

failing
  invalid : False === True
  invalid = Refl

  valid : True === True
  valid = Refl

-- this one surprised me; the first statement can be valid
failing
  fine : True === True
  fine = Refl

  scary : False === True
  scary = Refl

-- hey, we can fail failing blocks! neat!
failing "Failing block did not fail"
  failing
     expected : True === True
     expected = Refl
```

# Expected Behaviour

Neither of the first two `failing` blocks above should pass.

# Observed Behaviour

Compiles fine.

**Comment by gallais** [comment]
I would argue this is the intended behaviour.

It is convenient to be able to have valid auxiliary definitions in a failing block
so that we can introduce some needed machinery without polluting the scope.

**Comment by CodingCellist** [comment]
> It is convenient to be able to have valid auxiliary definitions in a failing block so that we can introduce some needed machinery without polluting the scope.

For things where the machinery is not part of the general file, would `where`-blocks be an acceptable alternative? Or local-`let` if better reading flow is desired?  : )

**Comment by gallais** [comment]
What about mutual definitions? Or data/record/function definitions that show up in the type of later ones?
I think it's just easier to have `n` failing blocks if you want to document that `n` separate definitions are failing.

**Comment by CodingCellist** [comment]
> What about mutual definitions? Or data/record/function definitions that show up in the type of later ones? I think it's just easier to have `n` failing blocks if you want to document that `n` separate definitions are failing.

Forward declarations? They, along with data/record , work inside `where` and local-`let` afaict  : )

Anyway, I'm willing to accept that this might just be a stylistic preference and move on. We should document it, but that's #3073 ^^
