### ISSUE TITLE
pkg006 test fails

### ISSUE THREAD

**Issue by MithicSpirit** [idris-lang/Idris2#3084]
See title. Happens on both my machine (Arch Linux with AUR idris2-git package) and in a Debian docker container when building the latest commit. I haven't bisected yet to find where this problem originated, but I believe that commit cf9a73f86 is clean. All other tests are fine.

The diff when accepting it as the new golden value is
```diff
diff --git a/tests/idris2/pkg/pkg006/expected b/tests/idris2/pkg/pkg006/expected
index e96b65d49..da1f9c5ba 100644
--- a/tests/idris2/pkg/pkg006/expected
+++ b/tests/idris2/pkg/pkg006/expected
@@ -1,7 +1,4 @@
 Uncaught error: EmptyFC:Failed to resolve the dependencies for test3:
   required foo >= 0.4 && < 0.5 but no matching version is installed

-Uncaught error: EmptyFC:Failed to resolve the dependencies for test4:
-  required baz any but no matching version is installed
-
 Warning: Deprecation warning: version numbers must now be of the form x.y.z
```
I can submit a PR with this if desired, although looking at the test I feel like the current expected value is correct.

**Comment by dunhamsteve** [comment]
This passes locally for me (M1 mac, racket chez).  It looks like it's expecting `baz` to be missing, but it is not.  What I suspect is happening is that the `pkg016` test is running simultaneously, is installing `baz`, and the `pkg006` test sees it.  I believe this patch would fix it:
```patch
diff --git a/tests/idris2/pkg/pkg006/expected b/tests/idris2/pkg/pkg006/expected
index e96b65d49..062d9354e 100644
--- a/tests/idris2/pkg/pkg006/expected
+++ b/tests/idris2/pkg/pkg006/expected
@@ -2,6 +2,6 @@ Uncaught error: EmptyFC:Failed to resolve the dependencies for test3:
   required foo >= 0.4 && < 0.5 but no matching version is installed

 Uncaught error: EmptyFC:Failed to resolve the dependencies for test4:
-  required baz any but no matching version is installed
+  required baz2 any but no matching version is installed

 Warning: Deprecation warning: version numbers must now be of the form x.y.z
diff --git a/tests/idris2/pkg/pkg006/test4.ipkg b/tests/idris2/pkg/pkg006/test4.ipkg
index 0488b832e..ffffbf346 100644
--- a/tests/idris2/pkg/pkg006/test4.ipkg
+++ b/tests/idris2/pkg/pkg006/test4.ipkg
@@ -1,4 +1,4 @@
 package test4

-depends = baz,
+depends = baz2,
           bar >= 1
```

**Comment by MithicSpirit** [comment]
I think that I had `-j1` in my `$MAKEFLAGS`, so I don't think that it would be running simultaneously (unless Idris does multiple jobs by itself rather than leaving it up to `make`; if so, is there a way to disable this?). I'll test your patch tomorrow to see if it fixes it, though.
FWIW, both attempts were using chez, so I'll also try seeing if I get the same issue on racket.

**Comment by dunhamsteve** [comment]
The parallelization is in the test-runner app itself, not in make, but you can say `threads=1`.

Might have to fix this right (keep them from playing in the directory). I pushed a clean branch before my patch, and it was pkg015 that failed.

**Comment by MithicSpirit** [comment]
Good news: the patch does fix it.
Interestingly, after some more testing, it seems like the error only occurs when self-hosting rather than bootstrapping, but both on chez and racket.
