### ISSUE TITLE
Strange parser error when named implementation with an implicit argument goes after `%logging`

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#3097]
# Steps to Reproduce

Consider the following code:

```idris
import Data.Vect

[Named] {n : Nat} -> Show (Vect n a) where
  show x = "whatever"
```

It typechecks well.

Now, add a `%logging` directive:

```idris
import Data.Vect

%logging "elab" 100

[Named] {n : Nat} -> Show (Vect n a) where
  show x = "whatever"
```

# Expected Behavior

Typechecks well, too

# Observed Behavior

```console
Error: Expected '}'.

BugImplImplLogging:5:12--5:13
 1 | import Data.Vect
 2 | 
 3 | %logging "elab" 100
 4 | 
 5 | [Named] {n : Nat} -> Show (Vect n a) where
                ^
```

**Comment by dunhamsteve** [comment]
That's a fun one.  There is a second, inline `%logging` parser that expression after it here:
https://github.com/idris-lang/Idris2/blob/32b639ca3c7fc8ef374e35469bdec51199a063e6/src/Idris/Parser.idr#L602-L608
If you comment it out everything is fine. I think that is getting hit first, before the parser for top level directives. If we move the `directiveDecl` parser up in the list, before `implDecl`, then everything is fine:
```
diff --git a/src/Idris/Parser.idr b/src/Idris/Parser.idr
index d31360de4..6845dfabd 100644
--- a/src/Idris/Parser.idr
+++ b/src/Idris/Parser.idr
@@ -1848,6 +1848,8 @@ topDecl fname indents
          pure [d]
   <|> do ds <- claims fname indents
          pure (forget ds)
+  <|> do d <- directiveDecl fname indents
+         pure [d]
   <|> do d <- implDecl fname indents
          pure [d]
   <|> do d <- definition fname indents
@@ -1873,8 +1875,6 @@ topDecl fname indents
          pure [d]
   <|> do d <- transformDecl fname indents
          pure [d]
-  <|> do d <- directiveDecl fname indents
-         pure [d]
   <|> do dstr <- bounds (terminal "Expected CG directive"
                           (\case
                              CGDirective d => Just d
```

**Comment by dunhamsteve** [comment]
I suspect part of the issue (why it doesn't happen more often) is that parsing `[` in an expressions is not checking indentation.

**Comment by dunhamsteve** [comment]
Oh, and there is some dead code in `directiveDecl` that parses `%runElab` to `PReflect`, which prints "Reflection is not implemented yet". The real deal (`runElabDecl`) parses to a `PRunElabDecl`.  Probably should  take out `PReflect` too, since it is vestigial.
