### ISSUE TITLE
Test racket/conditions007 fails due to type mismatch

### ISSUE THREAD

**Issue by MithicSpirit** [idris-lang/Idris2#3104]
```diff
diff --git a/tests/racket/conditions007/expected b/tests/racket/conditions007/expected
index 9dc3af56b..146b6f430 100644
--- a/tests/racket/conditions007/expected
+++ b/tests/racket/conditions007/expected
@@ -1,4 +1,20 @@
-Where are you mother?
-Where are you mother?
-Where are you mother?
-Sorry I'm late children! Weren't there more of you?...
+Encountered undefined name Main.main
+Error: While processing right hand side of main. When unifying:
+    IO ()
+and:
+    IO ()
+When unifying:
+    IO (List ())
+and:
+    IO ()
+Mismatch between: List () and ().
+
+Main:34:8--34:22
+ 30 |                 mutexRelease cvMutex
+ 31 |
+ 32 |        sleep m
+ 33 |        putStrLn "Sorry I'm late children! Weren't there more of you?..."
+ 34 |        for impatients $ \t => threadWait t
+             ^^^^^^^^^^^^^^
+
+Warning: compiling hole Main.main
```

Not really sure why this is happening; maybe the type of `for` was changed at some point?

I am on Debian (docker) using chez 9.5.8 and racket v8.7.

**Comment by buzden** [comment]
This can be fixed by replacing `for` with `for_`, but after this it should fail like `conditions006`

**Comment by dunhamsteve** [comment]
These two tests were commented out before the test refactor:
https://github.com/idris-lang/Idris2/blob/c52b029986e47d02f60fd2d59d79d1c9baaba0c1/tests/Main.idr#L343-L344

They should be disabled.  But we also might want to make sure racket tests are run in CI.

**Comment by dunhamsteve** [comment]
Looks like CI was disabled because it was timing out (https://github.com/idris-lang/Idris2/pull/2045/commits/f7bfd90fb76ef3bb82a4803806a1d61c21def883), and that was done after these two tests were disabled, so CI probably can't be reenabled until that issue is sorted out.
