### ISSUE TITLE
in runElab, equivalently shown types reify differently

### ISSUE THREAD

**Issue by MarcelineVQ** [idris-lang/Idris2#311]
Idris 2, version 0.2.0-1008dae9b

The types and expressions that use them have been separated to mimic the real code I derived this from.
# Steps to Reproduce
typecheck
```idris
module Main

import Language.Reflection
%language ElabReflection

foo : (sometype : TTImp) -> (iname : Name) -> Elab ()
foo sometype iname  = do
    let h = %runElab check goodExpr
    let i = %runElab check badExpr -- comment me to see the logged output
    logMsg  0 $ "interface: " ++ show iname
    logTerm 0 "type" $ sometype
    logTerm 0 "gt" goodType -- Exactly the same!
    logTerm 0 "bt" badType  -- Exactly the same!
    logTerm 0 "ge" goodExpr -- Exactly the same.
    logTerm 0 "be" badExpr  -- Exactly the same.
    
    r <- quote h
    logTerm 0 "r" r -- A check to see we really reified a completed search
                    -- And that we don't just have a TTImp of ISearch
    pure ()
  where
    goodType : TTImp
    goodType = `(Prelude.Ord Int)

    goodExpr : TTImp
    goodExpr = `(the ~(goodType) %search)

    badType : TTImp
    badType = `(~(IVar EmptyFC iname) ~(sometype))

    badExpr : TTImp
    badExpr = `(the (~(badType)) %search)

%runElab foo `(Int) `{{Prelude.Ord}}

```
# Expected Behavior
compilation completes
# Observed Behavior
An error of `src/Language/Elab/Deriving/Newtype.idr:39:28--39:35:Can't reify as Name` referring to `let i = %runElab check badExpr`
This is fairly confusing as, as the logs will show, these types and expressions are exactly the same.
That suggests to me that it's some sort of scope or environment error.

Here's what the logs give, they'll look slightly different than yours if you try because I made `Show RawImp` a little more verbose to be completely sure that the output was the same. `r` is not that important but included because it's in the code:
```
LOG 0: interface: Prelude.NS UN Ord
LOG 0: type: primval:Int
LOG 0: gt: (Prelude.UN Ord `app` primval:Int)
LOG 0: bt: (Prelude.UN Ord `app` primval:Int)
LOG 0: ge: ((UN the `app` (Prelude.UN Ord `app` primval:Int)) `app` %search)
LOG 0: be: ((UN the `app` (Prelude.UN Ord `app` primval:Int)) `app` %search)
LOG 0: r: (((((((((Prelude.DN Ord at Prelude.idr:258:1--281:1 [Just UN ty = primval:Int]) `app` Prelude.DN Eq implementation at Prelude.idr:208:1--212:1) `app` (%lam RigW Explicit (Just {arg:976}) primval:Int (%lam RigW Explicit (Just {arg:977}) primval:Int ((Prelude.DN compare `app` {arg:976}) `app` {arg:977})))) `app` (%lam RigW Explicit (Just {arg:978}) primval:Int (%lam RigW Explicit (Just {arg:979}) primval:Int ((Prelude.DN < `app` {arg:978}) `app` {arg:979})))) `app` (%lam RigW Explicit (Just {arg:980}) primval:Int (%lam RigW Explicit (Just {arg:981}) primval:Int ((Prelude.DN > `app` {arg:980}) `app` {arg:981})))) `app` (%lam RigW Explicit (Just {arg:982}) primval:Int (%lam RigW Explicit (Just {arg:983}) primval:Int ((Prelude.DN <= `app` {arg:982}) `app` {arg:983})))) `app` (%lam RigW Explicit (Just {arg:984}) primval:Int (%lam RigW Explicit (Just {arg:985}) primval:Int ((Prelude.DN >= `app` {arg:984}) `app` {arg:985})))) `app` (%lam RigW Explicit (Just {arg:986}) primval:Int (%lam RigW Explicit (Just {arg:987}) primval:Int ((Prelude.DN max `app` {arg:986}) `app` {arg:987})))) `app` (%lam RigW Explicit (Just {arg:988}) primval:Int (%lam RigW Explicit (Just {arg:989}) primval:Int ((Prelude.DN min `app` {arg:988}) `app` {arg:989}))))
```

**Comment by MarcelineVQ** [comment]
I should mention that this came about from trying to get the names of the fields of an interface in order to derive them for newtypes. The best I could come up with was to reify the instance for the type that the newtype wraps and then insert the wrapping into that.

But I can't do that since this way of using runElab programatically isn't going through. It's a bit of a blocker because I can't think of a way to just get the field-names/methods of an interface, which would suit me fine as an option.

One thing I tried, which actually worked once compiled, was to create an instance with a body like
```
`(believe_me $ the (~(iVar iname `iApp` wrappedty)) %search)
```
but it's not very nice in practice since the types end up confused as newtypes aren't compiled away until compile-time. You end up with things like `MkFoo 3 == MkFoo 4` giving you `intToBool (prim__eq_Int (MkFoo 3) (MkFoo 4))` instead of `False`, which works at compile-time but is clearly no-good otherwise.

**Comment by MarcelineVQ** [comment]
Issue seems related to variables not being chased quite far enough depending on the context. Even just having something in a where or not can affect it, e.g.
```idris
test : Elab ()
test = do
    let e : TTImp = `(Ord Int)
    let h1 = %runElab check `(the (~(goodType)) %search) -- good
    let h2 = %runElab check `(the (~(e)) %search) -- bad
    pure ()
  where
    goodType : TTImp
    goodType = `(Ord Int)

%runElab test
```
here `goodType` becomes an NDCon but `e` is an NApp despite being defined to be the same thing in source.

**Comment by gallais** [comment]
What happens if you replace the let-binding with a local definition?

```idris
let e : TTImp
    e = ...
in
```

**Comment by MarcelineVQ** [comment]
Yep that form is accepted just fine which makes it analogous to `goodType`.
The original has things in a separate definition form that does fail though, there line `i` is failing to complete due to evalClosure on `badExpr` reducing to NApp instead of NDCon which is what reifying expects.
evalClosure is being applied at src/TTImp/Elab/RunElab.idr:83  
and reifying that is done at  src/TTImp/Elab/RunElab.idr:87

**Comment by MarcelineVQ** [comment]
crap this is probably working as intended isn't it, "let i = %runElab check badExpr" is probably run before "%runElab foo `(Int) `{{Prelude.Ord}}" so badExpr can't be reduced further? I'd need some way to not %runElab until it's required in order for that to work out.

**Comment by MarcelineVQ** [comment]
This seems to be working as intended after all, we can't expect idris to know when just the right time is to execute a %runElab.
