### ISSUE TITLE
Interface resolution problem in the presence of GADTs.

### ISSUE THREAD

**Issue by Sventimir** [idris-lang/Idris2#3112]
I think I have found a bug in interface resolution. The following is the simplest example I could come up with. It requires a GADT, which essetially objectifies a function (`not` in this case), stating input and output type of the function and a monadic context in which the computation takes place.

# Steps to Reproduce
https://gist.github.com/Sventimir/462e9cbc76534356664f3cf00d37157e

```
module Test

%default total

public export
data Instr : (Type -> Type) -> Type -> Type -> Type where
  INot : Monad m => Instr m Bool Bool

exec : Monad m => Instr m x y -> x -> m y
exec INot x = pure ?exec_rhs
```

# Expected Behavior
This should typecheck and suggest that `?exec_rhs` should have type `Bool`.

# Observed Behavior
Instead, Idris complains that `m` is not an instance of `Applicative` (as required by the use of `pure`), even though it is declared to be an instance of `Monad`, which means it must be an `Applicative` as well. The problem can be worked around by adding an explicit constraint `Applicative m`.

```
- + Errors (1)
 `-- src/Test.idr line 10 col 14:
     While processing right hand side of exec. Can't find an implementation for Applicative m.
     
     Test:10:15--10:29
      06 | data Instr : (Type -> Type) -> Type -> Type -> Type where
      07 |   INot : Monad m => Instr m Bool Bool
      08 | 
      09 | exec : Monad m => Instr m x y -> x -> m y
      10 | exec INot x = pure ?exec_rhs
                         ^^^^^^^^^^^^^^

```

**Comment by stefan-hoeck** [comment]
I think this is expected and desired behavior, since in `exec`, two implementations of `Monad m` are in scope as can be verified by the following example, which will fail with a clearer error message:

```haskell
public export
data Instr : (Type -> Type) -> Type -> Type -> Type where
  INot : Monad m => Instr m Bool Bool

exec : Monad m => Instr m x y -> Monad m
exec INot = %search
```

The reason is, that `INot` already encapsulates a value of type `Monad m`, so the `Monad m` constraint on `exec` is not only redundant, but also confuses proof search.

**Comment by stefan-hoeck** [comment]
The following two versions behave as expected:

```haskell
public export
data Instr : (Type -> Type) -> Type -> Type -> Type where
  INot : Monad m => Instr m Bool Bool

exec : Instr m x y -> m y
exec INot = pure True
```

```haskell
public export
data Instr : (Type -> Type) -> Type -> Type -> Type where
  INot : Instr m Bool Bool

exec : Monad m => Instr m x y -> m y
exec INot = pure True
```

**Comment by Sventimir** [comment]
Indeed. I thought both these constraints are required, but maybe that was back when I was doing a similar thing in Haskell. Not a bug then, thank you!

**Comment by andrevidela** [comment]
There is something to say about the error message, it definitely should be better, but I don't know if there is a straight-forward way to improve it

**Comment by gallais** [comment]
`%search` should definitely record its failed attempts and optionally report the ones that took at least one successful step before failing.
