### ISSUE TITLE
Totality checker goes crazy with a match on a dependent uninhabited type

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#3143]
# Steps to Reproduce

Consider the following code:

```idris
import Data.Nat

ltTransitive : (n, m, k : Nat) -> n `LT` m -> m `LT` k -> n `LT` k

ltAntiSymmetric : (n, m : Nat) -> (n `LT` m) -> Not (m `LT` n)
ltAntiSymmetric n m nm mn = do
  let u = ltTransitive n m n nm mn
  case u of
    LTEZero impossible
```

It is reasonably correct and typechecks well.

Now, consider two transformations, which shouldn't change anything:

1. Inline the variable `u`:

   ```idris
   ltAntiSymmetric : (n, m : Nat) -> (n `LT` m) -> Not (m `LT` n)
   ltAntiSymmetric n m nm mn = do
     case ltTransitive n m n nm mn of
       LTEZero impossible
   ```

2. Add another `impossible` case:

   ```idris
   ltAntiSymmetric : (n, m : Nat) -> (n `LT` m) -> Not (m `LT` n)
   ltAntiSymmetric n m nm mn = do
     let u = ltTransitive n m n nm mn
     case u of
       LTEZero impossible
       LTESucc _ impossible
   ```

# Expected Behavior

Both changes snippets typecheck well, as the original one.

# Observed Behavior

Basically the same complaint by the totality checker in two forms:

For the first change:

```
Error: ltAntiSymmetric is not covering.

StrangeInliningVoid:11:1--11:65
 11 | ltAntiSymmetric : (n, m : Nat) -> (n `LT` m) -> Not (m `LT` n)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Calls non covering function Main.case block in ltAntiSymmetric
```

For the second change:

```
Error: While processing right hand side of ltAntiSymmetric. let u = LTESucc _ in let n = S right in ($resolved3435) m (S right) mn nm (LTESucc _) is not a valid impossible case.

StrangeInliningVoid:12:5--16:25
 12 | ltAntiSymmetric n m nm mn = do
 13 |   let u = ltTransitive n m n nm mn
 14 |   case u of
 15 |     LTEZero impossible
 16 |     LTESucc _ impossible
          ^^^^^^^^^^^^^^^^^^^^
```

**Comment by mjustus** [comment]
I am mostly curious why Idris thinks that the first program is covering! I don't think it should be obvious to the coverage checker.

**Comment by buzden** [comment]
> I am mostly curious why Idris thinks that the first program is covering! I don't think it should be obvious to the coverage checker.

Why not? You don't have to list all `impossible` cases (thankfully), so it's usually enough to list all possible once, or at least one impossible if there are no possible once.

**Comment by mjustus** [comment]
The scrutinee here has type `LTE (S n) n`. We should be able to match on it with `LTESucc x` with pattern variable `x` of type `LTE (S n') n'`, where `n := S n`. So, although uninhabited, pattern matching alone will not be enough to prove it.

We've discussed this bug in the Idris meeting today. Here is a slight reduction of the test case:

```
import Data.Nat

%logging "declare.def.impossible" 6

failing
  irrefl : {n : Nat} -> LT n n -> Void
  irrefl LTEZero impossible

irreflCase : {n : Nat} -> LT n n -> Void
irreflCase x =
  case x of
    LTEZero impossible
```

printing debug messages

```
LOG declare.def.impossible:3: Generated impossible LHS: ($resolved3373 {imp:0} ($resolved3113 {imp:1}))
LOG declare.def.impossible:3: Checking for impossibility: ((Main.irrefl [n = _]) (((Data.Nat.LTESucc [right = _]) [left = _]) _))
LOG declare.def.impossible:5: No empty pat
```
for `irrefl` and

```
LOG declare.def.impossible:3: Generated impossible LHS: ($resolved3389 {imp:0} {imp:1})
```

for the second.

Note that the generated clause for `irreflCase` has no constructors! @edwinb suspects that the fault lies in `getImpossibleTerm`: https://github.com/idris-lang/Idris2/blob/main/src/TTImp/Impossible.idr
