### ISSUE TITLE
bash completion option is broken

### ISSUE THREAD

**Issue by steveno** [idris-lang/Idris2#3144]
I just installed a fresh copy of chez from git master and then used that to install fresh copy of Idris from git master. By chance in install.md I noticed that Idris would generate a bash completion script for me. But it doesn't appear to work?

```
me@host:~/Projects/idris/Idris2 (main)$ idris2 ---bash-completion-script idris2
     ____    __     _         ___
    /  _/___/ /____(_)____   |__ \
    / // __  / ___/ / ___/   __/ /     Version 0.6.0-d6aa70dbe
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org
 /___/\__,_/_/  /_/____/   /____/      Type :? for help

Welcome to Idris 2.  Enjoy yourself!
File error in ---bash-completion-script: File Not Found
Main> 
```

**General Info**

- Linux host 6.5.0-10-generic 10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 13 13:49:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- ```
  steveno@host:~$ scheme --version
  9.9.9-pre-release.20
  ```

**Comment by dunhamsteve** [comment]
I believe the issue is that you have three hyphens in front of `bash-completion-script` instead of two.  With two hyphens I get:
```
% idris2 --bash-completion-script idris2
_idris2()
{
  ED=$([ -z $2 ] && echo "--" || echo $2)
  COMPREPLY=($(idris2 --bash-completion $ED $3))
}

complete -F _idris2 -o default idris2
```

**Comment by steveno** [comment]
That's embarrassing... I apologize for the noise.
