### ISSUE TITLE
Declaration quotes of type declarations causes error

### ISSUE THREAD

**Issue by luxtonychen** [idris-lang/Idris2#3168]
It seems that, since __commit ea093ff__, the declaration quote `` `[] `` on type declarations will cause an __undefined name error__.

# Steps to Reproduce
Trying to load the following code into REPL:
```idris
import Language.Reflection

%language ElabReflection

data_decl : List Decl
data_decl = `[data T = A | B]

record_decl: List Decl
record_decl = `[record R where]
```

# Expected Behavior
The code can be loaded, and we can inspect the value of `data_decl` and `record_decl` (confirmed behaviour in the __commit 305604d__).

# Observed Behavior
Following errors present:
```
- + Errors (2)
 |-- test.idr line 6 col 12:
 |   While processing right hand side of data_decl. Undefined name Language.Reflection.TTImp.Default. 
 |   
 |   test:6:13--6:30
 |    2 | 
 |    3 | %language ElabReflection
 |    4 | 
 |    5 | data_decl : List Decl
 |    6 | data_decl = `[data T = A | B]
 |                    ^^^^^^^^^^^^^^^^^
 |   
 `-- test.idr line 9 col 14:
     While processing right hand side of record_decl. Undefined name Language.Reflection.TTImp.Default. 
     
     test:9:15--9:32
      5 | data_decl : List Decl
      6 | data_decl = `[data T = A | B]
      7 | 
      8 | record_decl: List Decl
      9 | record_decl = `[record R where]
                        ^^^^^^^^^^^^^^^^^
```

**Comment by buzden** [comment]
This is indeed a bug resulted in internal reflectio valeus forgotten to be renamed during renaming, which was requested by reviewers of the original PR. The fix is simple and I made a PR for this
