### ISSUE TITLE
Mention Homebrew formula as alternative installation method

### ISSUE THREAD

**Issue by vladimyr** [idris-lang/Idris2#317]
Usually, I would just do a PR adding those few lines of markdown but I'm unsure where do you want to place them 🤔 
If anyone can point me in the right direction I'll gladly update docs myself or someone else can do that if they like. It is distributed under `idris2` moniker: https://formulae.brew.sh/formula/idris2#default 🎉

**Comment by keram** [comment]
nice @vladimyr  !
https://github.com/idris-lang/Idris2/blob/master/INSTALL.md and
 https://github.com/idris-lang/Idris2/blob/master/docs/source/tutorial/starting.rst would be good place to add this for Mac users
