### ISSUE TITLE
Failure to eliminate pattern case when matching by type

### ISSUE THREAD

**Issue by tauroid** [idris-lang/Idris2#3218]
Hi, I'm pretty new to Idris so apologies if this matches a known issue or is just a mistake. The purpose of this is to do (something like) `sequence` to a tuple. If there's a different way to accomplish that, I'd love to know.

My guess is that the below error is due to some inability to remove `Pair _ _` from the list of possible types, but there's a big chance I'm wrong in assuming it should be able to do that.

Thanks for any help.

# Steps to Reproduce
I've reduced the problem (not very far from the original) to a smallish case:
```
record Record (t : Type) (v : t) where
  constructor MkRecord
  someStuff : List String

tupleToTupleOfRecords : (t : Type) -> (v : t) -> Type
tupleToTupleOfRecords (Pair ta tb) (a,b) = Pair (Record ta a) $ tupleToTupleOfRecords tb b
tupleToTupleOfRecords t v = Record t v

makeTupleRecord : (t : Type) -> (v : t) -> tupleToTupleOfRecords t v -> Record t v
makeTupleRecord (Pair ta tb) (a,b) (ra,rb) = MkRecord (ra.someStuff <+> (makeTupleRecord tb b rb).someStuff)
makeTupleRecord t v r = r
```

# Expected Behavior
I believe this should typecheck, as the second case of `makeTupleRecord` should correspond to the second case of `tupleToTupleOfRecords`.

# Observed Behavior
I get:
```
While processing right hand side of makeTupleRecord. Can't solve constraint
     between: tupleToTupleOfRecords t v and Record t v.
     
     Justification:48:25--48:26
      44 | tupleToTupleOfRecords t v = Record t v
      45 | 
      46 | makeTupleRecord : (t : Type) -> (v : t) -> tupleToTupleOfRecords t v -> Record t v
      47 | makeTupleRecord (Pair ta tb) (a,b) (ra,rb) = MkRecord (ra.someStuff <+> (makeTupleRecord tb b rb).someStuff)
      48 | makeTupleRecord t v r = r
                                   ^
```

**Comment by gallais** [comment]
Each clause is checked in isolation: the catchall does not get to know that `Pair a b`  has already
been matched.

The solution is to define a view. There are a number of additional subtleties (such as the fact that
the wrong case tree gets generated if you use a `with`, or the lack of eta making some definitions
too strict) so you need to define a bunch of auxiliary functions to guide Idris the right way.

This works:

```record Record (t : Type) (v : t) where
  constructor MkRecord
  someStuff : List String

data View : Type -> Type where
  APair : (a, b : Type) -> View (Pair a b)
  Other : (a : Type) -> View a

view : (a : Type) -> View a
view (Pair a b) = APair a b
view x = Other x

tupleToTupleOfRecordsV : View ty -> ty -> Type
tupleToTupleOfRecords : (t : Type) -> (v : t) -> Type

tupleToTupleOfRecordsV (APair ta tb) v = Pair (Record ta (fst v)) $ tupleToTupleOfRecords tb (snd v)
tupleToTupleOfRecordsV (Other ty) v = Record ty v

tupleToTupleOfRecords t v = tupleToTupleOfRecordsV (view t) v

makeTupleRecord : (t : Type) -> (v : t) -> tupleToTupleOfRecords t v -> Record t v
makeTupleRecord t@_ v rs with (view t)
  _ | APair ta tb = MkRecord (someStuff (fst rs) <+> (makeTupleRecord tb _ (snd rs)).someStuff)
  _ | Other ty = rs
```

**Comment by tauroid** [comment]
Thank you! I understand. This must be the first situation I encounter where I match, with a catchall, on a variable which affects the type of the result. I can also see that this isn't special to `Type`, as I assumed it was; this also gives a similar error:

```
data X = A | B

t : X -> Type
t A = Int
t B = Bool

f : (x : X) -> t x
f A = 3
f x = True
```
```
While processing right hand side of f. Can't solve constraint between: Bool and t x.
     
match.idr:9:7--9:11
   |
 9 | f x = True
   |       ^^^^
```

Thank you for providing a solution as well! I think the missing piece may have been that the typechecker needs positive information about how the value was constructed to compute the dependent type, rather than accumulating a negative case list like I thought it did. I guess `tupleToTupleOfRecords` using `view t` in its body allows the definite constructor of `view t` in the case match to carry through into `tupleToTupleOfRecordsV`? No worries if it's not quite that simple, I know basically nothing about how the unifier works so can pick it up in my own time.
