### ISSUE TITLE
`idris2 --init` doesn't check a name of a package

### ISSUE THREAD

**Issue by DanMax03** [idris-lang/Idris2#3232]
# Steps to Reproduce
1. Call `idris2 --init`
2. Give a name for a package that is not a correct Idris identificator, i.e. `123_Issue`
3. Finish the package in any reasonable way (at least set everything else empty)

# Expected Behavior
The program doesn't allow such a name for a package since it doesn't compile

# Observed Behavior
The program allows to create a package with such a name

**Comment by Matthew-Mosior** [comment]
@gallais @DanMax03

Where can I look to understand what is considered a valid Idris Identifier?

**Comment by gallais** [comment]
The parsing rule is here:
https://github.com/idris-lang/Idris2/blob/91d0eb3e31b57354728f66bd7835ac715b7f9668/src/Parser/Rule/Package.idr#L114-L121

With the `isIdent` logic implemented here:
https://github.com/idris-lang/Idris2/blob/91d0eb3e31b57354728f66bd7835ac715b7f9668/src/Parser/Lexer/Common.idr#L23-L39
