### ISSUE TITLE
Constructor Duplicate

### ISSUE THREAD

**Issue by csabahruska** [idris-lang/Idris2#338]
Idris2 accepts the following program
`idris2_duplicate_constructors.idr`:
```idris
data A = B | B

data C : Type -> Type where
  D : C Int
  D : C String
```
# Steps to Reproduce

```
idris2 idris2_duplicate_constructors.idr 
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.2.0-c12118177
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/      Type :? for help                     

Welcome to Idris 2.  Enjoy yourself!
Main> :t A
Main.A : Type
Main> :t D
Main.D : C String
Main> 
```

# Expected Behavior

Should report error message.

# Observed Behavior

**Comment by edwinb** [comment]
Oh, this is a silly mistake! It checks that constructor names aren't defined, but since they're all added as part of a data type in one go, that doesn't catch the case where there's repetition within a data type. So it just overwrites the earlier one.

**Comment by csabahruska** [comment]
Where are the unit test for the fix? What kind of engineering is this?
It would fail though, the bug is still present.

**Comment by diakopter** [comment]
> What kind of engineering is this?

it's the free kind of engineering? 😜

**Comment by edwinb** [comment]
Well. You're welcome. I'd be happy to accept a PR with a test.

I get, by the way:

    1/1: Building condef (condef.idr)
    condef.idr:1:14--5:1:Main.B is already defined
    condef.idr:7:3--7:15:Main.D is already defined

This is what I expected.

**Comment by melted** [comment]
@csabahruska This kind of demeaning talk isn't welcome in this project. It's quite possible to make your point without  the insinuations. You are very welcome to contribute, but not in that manner.

**Comment by csabahruska** [comment]
Interesting, I double checked the issue before I commented.
I deleted the whole `.idris2` folder and cloned the repository and compiled from scratch.
The version hash was changed, but the issue remained.

**Comment by csabahruska** [comment]
https://github.com/idris-lang/Idris2/pull/342
Sorry for the inadequate style.

**Comment by csabahruska** [comment]
It seems I fooled myself, because I did pay attention to the output message. Indeed the issue was fixed by the commit.
