### ISSUE TITLE
Unable to `--exec` ambiguous mains

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#3398]
# Steps to Reproduce

Consider I have a file `Main.idr` with the following contents:

```idris
namespace XX

  export
  main : IO ()
  main = putStrLn "Hi, XX!"

namespace YY

  export
  main : IO ()
  main = putStrLn "Hi, YY!"
```

If we run

```console
$ idris2 --exec main Main.idr
```

we expectedly get

```console
Error: Ambiguous elaboration. Possible results:
    Main.XX.main
    Main.YY.main
```

Now, try to specify the namespace by running either

```console
$ idris2 --exec YY.main Main.idr
```
or
```console
$ idris2 --exec Main.YY.main Main.idr
```

# Expected Behavior

Runs successfully and prints
```console
Hi, YY!
```

or at least saying that namespaced main functions are not supported, if so.

# Observed Behavior

```console
Error: Undefined name YY.main. 
```
and
```console
Error: Undefined name Main.YY.main. 
```

**Comment by spcfox** [comment]
The reason for this behavior is that `--exec` does not parse the string, but simply wraps it in `Basic`
https://github.com/idris-lang/Idris2/blob/ec74792a49bf4d22509172d1f03d153ffca1b95c/src/Idris/SetOptions.idr#L518
