### ISSUE TITLE
Pull List length into prelude

### ISSUE THREAD

**Issue by stepancheg** [idris-lang/Idris2#346]
When doing toy examples, I often encounter issues like this:

```
my_head : (xs : List a) -> Either a (length xs = 0)
```

It fails with:

```
When unifying List ?a and String
Mismatch between:
	List ?a
and
	String
```

The fix is:

```
import Data.List
```

which might be unintuitive for newcomers. So probably pull `length` of `List` into prelude.

Alternatively, maybe remove `length` of `String` from the prelude.

https://learn-idris.net/play?id=IeskWNb

**Comment by edwinb** [comment]
I think you're right, it does make sense for `List.length` to be in the prelude, and it does come under the general heading of "almost any non-trivial program uses it".
