### ISSUE TITLE
Quantitative inconsistency

### ISSUE THREAD

**Issue by zraffer** [idris-lang/Idris2#356]
# Steps to Reproduce
https://gist.github.com/zraffer/0148419db461e9971ccbb0fe96852c15#file-file-idr
```
Id0 : (0 A : Type) -> Type
Id0 a = () -> a

Id1 : (1 A : Type) -> Type
Id1 a = a
```

# Expected Behavior

both function types are considered with linear argument `A`

# Observed Behavior

`Id1` is checked as linear, but `Id0` is checked as erased

**Comment by ShinKage** [comment]
Why would `a` in `Id0` be considered linear in the expected behaviour? The signature explicitly says that `a` is esared. The same applies to `IdN` as `a` without explicit multiplicity is unrestricted by default.

**Comment by zraffer** [comment]
The signatures above have been made to be compilable against the current version of Idris2.
The right signatures are linear.

Current behavior comes from built-in signatures of `(->)` and `(,)` type operators which should be linear against both arguments but currently are not.

**Comment by edwinb** [comment]
I think `Id0` should be rejected because it uses `a` while it says it doesn't. The rule for `->`, iirc, assumes it's at multiplicity `0` which I've been meaning to fix for a while.

The others seem fine, though.

**Comment by zraffer** [comment]
The `Pair` type can be defined with linear arguments:

```
record LinPair (1 t1 : Type) (1 t2 : Type) where
  constructor MkLinPair
  pr1 : t1
  pr2 : t2

Id0 : (1 a : Type) -> Type
Id0 a = LinPair () a
```

Isn't it more usable for linear computations?
