### ISSUE TITLE
A final %default directive applies to an entire file

### ISSUE THREAD

**Issue by memoryruins** [idris-lang/Idris2#361]
Idris 2, version 0.2.0 - 354830f41 

## Steps to Reproduce

```idris
%default total

data S = T | F

Eq S where

main : IO ()
main = printLn $ T == T

%default covering
```

## Expected Behavior

I expected each `%default` directive to apply to following functions, not previously defined functions.
With `%default total`, an error would be emitted due to possibly not terminating default definitions of `Eq`

```
Main.idr:15:1--16:1:main is not total:
        possibly not terminating due to recursive path Main.main -> Main.Eq implementation at src/Main.idr:7:1--11:1 -> .Main.== -> Main./= -> Main.==
```

## Observed Behavior

`%default covering` appears to apply to the entire file, overriding the previous `%default total`. When running the example, it recurses in `Eq`'s default definitions. If the second directive is commented out, the expected totality error is emitted.

Currently the ["Directives and Compiler Flags for Totality"](https://github.com/idris-lang/Idris2/blob/9f78f1cddcfaf2365135ac20c0a3e8c788e7768a/docs/source/tutorial/theorems.rst#directives-and-compiler-flags-for-totality) section of the docs warns "Not all of this is implemented yet for Idris", but I'm opening this issue in the case it helps track this or clarifies expectations :)

**Comment by MarcelineVQ** [comment]
Good catch.
I wonder if the correct behavior should be to apply %default as you encounter them, or only allow one %default per namespace.

**Comment by memoryruins** [comment]
> only allow one %default per namespace

fwiw, I think that could be reasonable too. Moments ago, I learned about https://learn-idris.net/play. which has an option for checking Idris 1 and 2. Using the original example with `v1`, it first emits a message about the missing hole in the Eq implementation (should a separate issue be created about this missing warning in `v2` ?)
```
Holes: Main.S implementation of Prelude.Interfaces.Eq
```

Changing the example to the following

```idris
%default total

recurse : Int
recurse = recurse

%default covering

recurse' : Int
recurse' = recurse'
```

Idris 1 does match the behavior described in the link, emitting an error for `recurse` while accepting `recurse'`
```
4 | recurse = recurse
  | ~~~~~~~~~~~~~~~~~
Main.recurse is possibly not total due to recursive path Main.recurse
```

**Comment by gallais** [comment]
I see that `default` is handled in the `Idris.Desugar` phase when stuff like
`logging` is propagated further down the pipeline. This means that the only
`default` that matters is the last one found in the file.

I'll try to propagate `default` further so that the various directives are
applied in turn as we process the file.

**Comment by gallais** [comment]
In the end I decided to treat `%default [REQUIREMENT]` as an invisible `REQUIREMENT`
in front of every definition that did not have a user-written one. Which is really
what a default ought to be.

**Comment by memoryruins** [comment]
Thank you for looking into this!
