### ISSUE TITLE
Interface resolution, unification still an issue

### ISSUE THREAD

**Issue by wurmli** [idris-lang/Idris2#364]
Even after trying many other simplifications the following module is the smallest I could come up showing the problem with interface resolution.

```
public export
interface Basic d where
  int   : Integer -> d
  inc   : d
  app   : d -> d -> d

infixl 1 `app`

mutual
  
  public export
  data Comp = Val Dom | Req (Dom -> Comp)
  
  public export
  data Dom  = DInt Integer | DFun (Dom -> Comp)

public export
Basic Comp where
  int = Val . DInt
  inc = Val . DFun $ \x => case x of
    DInt x => int (x+1)
    _      => int 0
  app (Val (DFun f)) (Val e2) = f e2
  app (Val _)        (Val e2) = int 0
  app (Req k)        e2       = Req (\x => app (k x) e2)
  app e1             (Req k)  = Req (\x => app e1 (k x))

public export
ttinc : Basic comp => comp
ttinc = inc `app` (int 2)
```
# Steps to Reproduce and Observed Behavior
Load IntRes into REPL and run ttinc:

```
1/1: Building IntRes (IntRes.idr)
IntRes> ttinc
(interactive):1:1--1:6:Can't find an implementation for Basic ?comp at:
1       ttinc
        ^^^^^
```
Indicating the implementation to the expression works:

```
IntRes> inc {d=Comp} `app` int 10
Val (DInt 11)
```

Change ttinc in module IntRes to:

```
ttinc = inc {d=Comp} `app` int 10
```

This produces the following:
```
IntRes> :r
Loaded file IntRes.idr
IntRes> ttinc
(interactive):1:1--1:6:Can't find an implementation for Basic ?comp at:
1       ttinc
        ^^^^^
```
# Expected Behaviour
I would expect that the search for an the implementation Comp of Basic were successful, particularly after Edwin's latest improvement on issue #363.

**Comment by edwinb** [comment]
Thanks for the bump, I need to catch up on interface things. I'll take a look soon.

**Comment by edwinb** [comment]
Ah, now that I've looked at this, I don't think it should resolve the interface. Resolution will only proceed when it knows the determining arguments for the interface. In this case, all it knows is `Basic ?comp` - so it doesn't know what `comp` is. Even though there is only one possibility in the given file, it won't even begin the search if it doesn't know what it's searching for.

This is a deliberate design choice. Otherwise, as soon as you add another implementation on another type, it'll stop working. If you say `ttinc {comp=Comp}` it is happy. Alternatively, if it knows the target type, via `the Comp ttinc`.

**Comment by wurmli** [comment]
Thank you, Edwin, that helped a lot. I hope you don't mind when I add a comment.

I clearly misunderstood "auto search". But as I don't fully understand why "[t]his is a deliberate design choice" as "[o]therwise, as soon as you add another implementation on another type, it'll stop working" let me explain why a possible alternative design choice could be even more within the philosophy of Idris.

Interfaces and their resolution seem or should be within the first stage of the compilation process: typechecking, including evaluation of expressions for dependent types as well as filling holes where possible, while keeping everything as modular as possible. This first stage should go as far as statically possible.

The typechecker gives an error when typing is wrong and doesn't produce an interpretable form of the program. It warns the user but loads the program into the interpreter when function definitions are not covering (i.e. some cases are missing) or when a function's totality cannot be proven. When there are holes, no warning is given when loading, only when compiling for an executable.

So, when an interface method is not "implemented", i.e. remains a hole, no load warning is given. This is consistent with other holes, but as interfaces and implementations are "toplevel" or "global" when imported, "auto search" could be designed more ambitiously.

As far as I understand "auto search" searches the global table(s) of typevalues that implement a particular interface. As overlapping instances are excluded the search can return a set (not a bag) of typevalues for which the interface is implemented. For the three cases, I would expect the typechecker 

to give a warning when

1) the set is empty, i.e. ho implementation exists;
2) the set has two or more elements (and the compiler expects instructions which one it should choose);

but

3) when there is exactly one element in the returned set, it can silently fill the hole.

If "auto search" could possibly be extended to a "constrained auto search", i.e. extended with search constraints (based on the interface's methods), cases 1) and 2) would probably be minimised to yet incomplete programs and programming errors.

I cannot assess all the impacts this would have on Idris2, but would bet that they are minimal and in particular that no currently correct program would not typecheck any more.

**Comment by gallais** [comment]
Closing this as I do agree that silently solving holes in a way
that is not compatible with weakening the context is a bad idea.
