### ISSUE TITLE
Idris always use <file>.idr instead of <file>.lidr

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#37]
<a href="https://github.com/petithug"><img src="https://avatars3.githubusercontent.com/u/2779694?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [petithug](https://github.com/petithug)**
_Sunday Mar 29, 2020 at 17:54 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/246_

----

This is a corner case, but an annoying one when migrating idris1 files to literate idris2 files.

# Steps to Reproduce

Crete two files with the same name, different content, but one with the ".idr" extension and the other with the ".lidr" extension.

# Expected Behavior

Loading each file in the REPL will create different build/ content.

# Observed Behavior

When loading the ".lidr" file, the ".idr file is used instead, and build/ contains the same content than for the ".idr" file.

**Comment by edwinb** [comment]
<a href="https://github.com/gallais"><img src="https://avatars1.githubusercontent.com/u/1094905?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gallais](https://github.com/gallais)**
_Wednesday Apr 01, 2020 at 13:48 GMT_

----

AFAIU this is more a problem of seeing an existing `.ttc` and loading it despite
the fact it has been generated from the `.idr` and not the `.lidr` file. What I
find strange is that, surely, we have a mechanism to detect whether a file has
been updated since the last time the `.ttc` was generated and it should kick in
here and provoke re-compilation?

**Comment by edwinb** [comment]
<a href="https://github.com/jfdm"><img src="https://avatars2.githubusercontent.com/u/331273?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jfdm](https://github.com/jfdm)**
_Wednesday Apr 01, 2020 at 20:31 GMT_

----

From a quick look over the source, I think the issue here is that Idris2 generates a `ttc` file with the file's basename. Thus, when given a literate idris file and ordinary idris file with the same basename, as per the above example, then Idris will default to the ordinary file.

See:

https://github.com/edwinb/Idris2/blob/master/src/Idris/ProcessIdr.idr#L313
https://github.com/edwinb/Idris2/blob/2c2acdcfacc230ccf8da145097af903b3df5b56a/src/Core/Directory.idr#L169

I am not sure if Idris1 has the same issue and how it dealt with it, if there was no issue.

**Comment by edwinb** [comment]
<a href="https://github.com/petithug"><img src="https://avatars3.githubusercontent.com/u/2779694?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [petithug](https://github.com/petithug)**
_Sunday Apr 05, 2020 at 19:31 GMT_

----

I do not think the presence of the ttc file is the problem:

In a clean directory creates two files, a Test.idr containing `module test` (so it is incorrect) and a Test.lidr containing `> module Test` (so it is correct).

Then run `idris2 Test.lidr`.  It says that the module name does not match the filename whichcab ne only because Test.idr is loaded instead.  Remove Test.idr and everything work fine.

**Comment by gallais** [comment]
Looking at something else, I think I have found the origin of this:

* `getBuildMods` computes the module name associated to the main file using `pathToNS`
* `mkModTree` computes *back* the file path using the module name via `nsToSource`
* `nsToSource` calls `firstAvailable` prioritising `.idr` over `.lidr`

I should have a fix fairly soon if that's indeed the issue.
