### ISSUE TITLE
`WellFounded` can not resolve its implicit parameter

### ISSUE THREAD

**Issue by berewt** [idris-lang/Idris2#374]
# Steps to Reproduce

Compile this file:

```
module Meh

import public Control.WellFounded

data Meh : Nat -> Nat -> Type where

implementation WellFounded Meh where
  wellFounded x = ?foo
```

# Expected Behavior

Compilation should pass.

# Observed Behavior

```
Control/WellFounded.idr:13:43--13:44:While processing type of wellFounded at src/Replica/Log.idr:41:1--57:1:
When unifying ?a [no locals in scope] and Nat
Pattern variable a unifies with:
	Nat
at:
13
```

Note that the compilation error is in `WellFounded` (I have the same error if I don't include the definition of `wellFounded`).

**Comment by edwinb** [comment]
Oh dear, looks like it's not dealing with implicit parameter names properly. It's supposed to substitute parameters in to the type when making the concrete method types, but it's ignoring implicits. I'd better fix this one quickly since it rather limits the usefulness of interfaces!

**Comment by edwinb** [comment]
Right, I've sent a PR that resolves this. We should probably also add a syntax to allow giving explicit values for the implicit parameters of interfaces. I expect that'll be useful one day, and we should do it just for consistency everywhere anyway.

**Comment by berewt** [comment]
Thank you! Given the intensive use of interfaces in my main project it’s more than likely that it would be useful sooner or later.
