### ISSUE TITLE
AddClause does not indent the clauses of an interface implementation

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#38]
<a href="https://github.com/petithug"><img src="https://avatars3.githubusercontent.com/u/2779694?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [petithug](https://github.com/petithug)**
_Sunday Mar 29, 2020 at 18:07 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/247_

----

When using AddClause on an interface implementation, the clause should be indented.

# Steps to Reproduce

Loading the following in the REPL and executing ":ac 4 Show"

```
data Blah : Type where
  MkBlah : Blah

Show Blah where
```
  
# Expected Behavior

```
data Blah : Type where
  MkBlah : Blah

Show Blah where
  showPrec d x = ?showPrec_rhs
```

# Observed Behavior

```
data Blah : Type where
  MkBlah : Blah

Show Blah where
showPrec d x = ?showPrec_rhs
```

**Comment by gallais** [comment]
I believe this is already covered by #40
