### ISSUE TITLE
Parser error when trying to compile a program from the REPL

### ISSUE THREAD

**Issue by eayus** [idris-lang/Idris2#405]
# Steps to Reproduce

- Open a REPL
- Attempt to compile a file using either the ":c" or ":compile" commands, as documented from the ":h" command.

# Expected Behavior

Command parses correctly.
```
Main> :c test
Main>
```

# Observed Behavior
```
Main> :c test
Parse error: Unrecognised command (next tokens: [identifier c, namespaced identifier Test.idr, end of input])
Main>
```

**Comment by edwinb** [comment]
You need to give the expression name too - it's a change from Idris 1. This is documented here: https://idris2.readthedocs.io/en/latest/backends/index.html

**Comment by eayus** [comment]
Ah, that makes sense. The REPL help dialogue needs updating to reflect this change, as it currently only mentions the filename argument:

```
:c :compile     <filename>  Compile to an executable
```

However this seems to be a little tricky (if I am understanding the code correctly, I'm not familiar with the code base), since the definition of commands assumes only a single argument:

```idris
CommandDefinition : Type
CommandDefinition = (List String, CmdArg, String, Rule REPLCmd)
```

**Comment by gallais** [comment]
It seems that the REPL help was updated as it now prints:

```idris
 :c :compile     <file> <expr>Compile to an executable
```
