### ISSUE TITLE
Random identifiers used when inspecting specific types of holes

### ISSUE THREAD

**Issue by eayus** [idris-lang/Idris2#407]
Inspecting the type of the hole `weird` in the following code yields some odd results. 

```idris
module Test

f : Nat -> Bool
f Z = False
f (S k) with (5 > k)
  f (S k) | True = True
  f (S k) | False = False

fProof : {p : Type} -> (n : Nat) -> case f n of { True => p ; False => p }
fProof 0 = ?rhs
fProof (S k) = ?weird
```

With the exact code above, asking for the type of `weird` gives me
```idris
weird : if with block in IO k (== (compare 5 k) GT) then p else p
```
Which is incorrect - specifically, it mentions the identifier `IO` which shouldn't be there.

Furthermore, the incorrect identifier changes depending on the number of functions defined previously. This slightly modified code adds a random definition above `fProof`:

```idris
module Test

f : Nat -> Bool
f Z = False
f (S k) with (5 > k)
  f (S k) | True = True
  f (S k) | False = False

randomDef : Int

fProof : {p : Type} -> (n : Nat) -> case f n of { True => p ; False => p }
fProof 0 = ?rhs
fProof (S k) = ?weird
```
Now, asking for the type of the hole `weird` gives:
```idris
weird : if with block in IORes k (== (compare 5 k) GT) then p else p
```

The hole now mentions a `IORes` instead of `IO`. Adding more and more definitions above keeps changing the identifier used.

This seems to be a problem when using a `case ... of` to match on the result of a function using a `with` clause. Looks like Idris is using indices to represent function names at some point, and it's not being resolved back properly?

**Comment by edwinb** [comment]
Oh, thanks for finding this! I had suspected something like this might happen due to the way we construct the names of with blocks - there is an integer identifier which is the resolved name of the function that's used to generate the `with` name, and otherwise doesn't matter. So this is bad pretty printing, and probably we should generate the names of `with` functions differently to be more helpful.
