### ISSUE TITLE
Implicits are undefined when first used in a case expression

### ISSUE THREAD

**Issue by eayus** [idris-lang/Idris2#409]
Not sure whether this is actually a bug (since Idris1 behaves similarly), but I found the behaviour a little odd.

Typechecking the following code...

```idris
isZ : Nat -> Bool
isZ Z = True
isZ (S n) = False

f : case (isZ n) of { _ => () }
```

gives the error
```
Undefined name n at:
    f : case (isZ n) of { _ => () }
```

I would've expected the name `n` to be resolved as an implicit parameter, especially since its type should be easily inferrable from its use. This unusual behaviour seems to be because the name is first used inside a case expression. Defining the parameter explicitly solves the problem:
```idris
f : {n : Nat} -> case (isZ n) of { _ => () }
```

**Comment by edwinb** [comment]
I think I decided not to allow this since it would be hard to infer the value at the call site, even if it's possible to infer the type in the declaration. So, my initial inclination is to leave it as it is.
