### ISSUE TITLE
Custom CG build fail

### ISSUE THREAD

**Issue by 0nkery** [idris-lang/Idris2#413]
# Steps to Reproduce

1. Create new package folder for CG.
2. Copy and paste code from custom CG example to `src/Main.idr`.
3. The command `idris2 -p idris2 -p contrib -p network src/Main.idr -o idris2-custom-cg` should do the trick.
4. Create minimal `custom-cg.ipkg`:

```
package custom-cg

depends = contrib, network, idris2

sourcedir = "src"

main = Main
executable = idris2-custom-cg
```

# Expected Behavior

Successful build with both compiler commands.

# Observed Behavior

```
1/1: Building Main (src/Main.idr)
Exception: attempt to reference unbound identifier Lexer-Text-octLit at line 1719, char 1039 of ~/idris2-custom-cg/build/exec/idris2-custom-cg_app/idris2-custom-cg.ss
```

Some functions from `Text.Lexer` module are defined in resulting .ss-file, some functions are not (e.g. `octLit`). What's the difference between two invocations?

**Comment by melted** [comment]
Try to reorder the depends line to have `idris2` first. It's bad and the imports shouldn't depend on the order, but `contrib` and `idris2` defines many of the same things.

**Comment by 0nkery** [comment]
Yup, it worked. Thanks!
