### ISSUE TITLE
WSL1 install error

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#44]
<a href="https://github.com/ice1000"><img src="https://avatars3.githubusercontent.com/u/16398479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ice1000](https://github.com/ice1000)**
_Sunday Apr 05, 2020 at 02:32 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/266_

----

Master version of Idris2, getting this:

```
Exception: (while loading libcb.so) libcb.so: cannot open shared object file: No such file or directory
chez/chez010: FAILURE
Expected:
"9\nCallback coming\nIn callback\n24\nCallback coming\nIn callback with (1, 2)\n3\n9\n'k'\n1/1: Building CB (CB.idr)\nMain> Main> Bye for now!\n"
Given:
"1/1: Building CB (CB.idr)\nMain> Main> Bye for now!\n"
chez/chez011: success
chez/chez012: success
Exception: (while loading libstruct.so) libstruct.so: cannot open shared object file: No such file or directory
chez/chez013: FAILURE
Expected:
"(40, 30)\n\"Here\": (40, 30)\nMade it!\n1/1: Building Struct (Struct.idr)\nMain> Main> Bye for now!\n"
Given:
"1/1: Building Struct (Struct.idr)\nMain> Main> Bye for now!\n"
chez/chez014: success
200/202 tests successful
Makefile:4: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/ice1000/git-repos/idris2/tests'
Makefile:123: recipe for target 'test' failed
make: *** [test] Error 2
```

Where should I obtain `libcb.so` and `libstruct.so`? I'm using Chez scheme 9.5

**Comment by edwinb** [comment]
<a href="https://github.com/timmyjose"><img src="https://avatars1.githubusercontent.com/u/2051158?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timmyjose](https://github.com/timmyjose)**
_Sunday Apr 05, 2020 at 07:10 GMT_

----

 @ice1000 

I recall a similar issue for macOS which was fixed in this PR - https://github.com/edwinb/Idris2/pull/210/files. 

I'm wondering whether the Makefile is getting confused and producing a `dll` instead of an `so` file. 

Could you check the output of `gcc -dumpmachine`? Does the output contains `cygwin`, `mingw`, or `windows`? I suspect it might be showing `mingw` in which case this would need to be taken care of in the Makefile(s).

I think `chez` is perfectly innocent here!

**Comment by edwinb** [comment]
<a href="https://github.com/ice1000"><img src="https://avatars3.githubusercontent.com/u/16398479?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ice1000](https://github.com/ice1000)**
_Monday Apr 06, 2020 at 17:57 GMT_

----

```
~/git-repos/idris2|master λ> gcc -dumpmachine
x86_64-linux-gnu
```

@timmyjose

**Comment by edwinb** [comment]
<a href="https://github.com/ice1000"><img src="https://avatars3.githubusercontent.com/u/16398479?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ice1000](https://github.com/ice1000)**
_Monday Apr 06, 2020 at 22:53 GMT_

----

With the new test suite it becomes

```
Exception: (while loading libcb.so) libcb.so: cannot open shared object file: No such file or directory
chez/chez010: FAILURE
Golden value differs from actual value.
Accept actual value as new golden value? [yn]
n
chez/chez011: success
chez/chez012: success
Exception: (while loading libstruct.so) libstruct.so: cannot open shared object file: No such file or directory
chez/chez013: FAILURE
Golden value differs from actual value.
Accept actual value as new golden value? [yn]
n
chez/chez014: success
202/204 tests successful
Makefile:5: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/ice1000/git-repos/idris2/tests'
Makefile:123: recipe for target 'test' failed
make: *** [test] Error 2
```

It's still erroring but looks nicer

**Comment by memoryruins** [comment]
With [WSL2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index), bd9498c00, and the chezscheme9.5 package in Debian Buster, idris2 successfully bootstrapped and installed.
