### ISSUE TITLE
`Data.Vect.foldrImpl` with Javascript backend exceeds stack size in browsers

### ISSUE THREAD

**Issue by memoryruins** [idris-lang/Idris2#447]
Idris 2, version 0.2.0 - 6452cdbbd

When evaluating the following in Firefox 80.0a1 and Chrome 83, an unexpected error is emitted about exceeding stack size.

```idris
import Data.Vect

namespace JsConsole
  %foreign "javascript:lambda:console.log"
  prim_log : String -> PrimIO ()
  
  export
  log : (Show a, HasIO io) => a -> io ()
  log = primIO . prim_log . show

main : IO ()
main = JsConsole.log $ the (Vect 3 String) ["red", "green", "blue"]
```

Firefox: 
```
Uncaught InternalError: too much recursion
    tailRepOptim_5
    tailRepOptim_5
    tailRepOptim_5
    tailRepOptim_5
    ...
```
Chrome: `RangeError: Maximum call stack size exceeded`

<details>
<summary>screenshot of part of the call stack</summary>

![screenshot 7667](https://user-images.githubusercontent.com/6868531/87145588-8b2b7800-c277-11ea-8123-0a7e3d44d99d.png)

and it keeps going
</details>

which shows it occurring in `foldrImpl`, which is used in `Vect`'s `Foldable` implementation and in turn is used by `List.toList` in `Vect`'s `Show` implementation.

<details>
<summary>the current generated foldrImpl</summary>

```javascript
function Data_Vect_foldrImpl(arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6){
 while(true){
  switch(arg_6.h){
   case 0:
    return arg_5(arg_4);
    break;
   case 1:
    let tailRepOptim_0 = undefined;
    let tailRepOptim_1 = undefined;
    let tailRepOptim_2 = undefined;
    let tailRepOptim_3 = arg_3;
    let tailRepOptim_4 = arg_4;
    let tailRepOptim_5 = (eta_0) => {return arg_5(arg_3(arg_6.a1)(eta_0));};
    let tailRepOptim_6 = arg_6.a2;
    arg_0 = tailRepOptim_0;
    arg_1 = tailRepOptim_1;
    arg_2 = tailRepOptim_2;
    arg_3 = tailRepOptim_3;
    arg_4 = tailRepOptim_4;
    arg_5 = tailRepOptim_5;
    arg_6 = tailRepOptim_6;
    break;
   default:
    throw new Error('unhandled con case on Data/Vect.idr:371:57--371:65');
  }
 }
}
```

</details>

by commenting out a condition in the backend's `hasTailCall`, specifically `(any (\(_, w)=>hasTailCall n w) alts)`

https://github.com/idris-lang/Idris2/blob/ffb1d6406f2df97750a5bc32821c3d87dd22e0ba/src/Compiler/ES/TailRec.idr#L12-L13

```diff
- (any (\(_, w)=>hasTailCall n w) alts) || (maybe False (hasTailCall n) d)
+ (maybe False (hasTailCall n) d)
```

and building the example again with the patched compiler, the following js is generated, which causes no issues with firefox and chrome and logs `["red", "green", "blue"]` to the console as expected.

<details>
<summary>generated javascript without tailRepOptim</summary>

```javascript
function Data_Vect_foldrImpl(arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6){
 switch(arg_6.h){
  case 0:
   return arg_5(arg_4);
   break;
  case 1:
   return Data_Vect_foldrImpl(undefined, undefined, undefined, arg_3, arg_4, (eta_0) => {return arg_5(arg_3(arg_6.a1)(eta_0));}, arg_6.a2);
   break;
  default:
   throw new Error('unhandled con case on Data/Vect.idr:371:57--371:65');
 }
}
```

</details>

cc @rbarreiro

**Comment by rbarreiro** [comment]
I will check it over the weekend

**Comment by rbarreiro** [comment]
Its because I always forget how javascript closures work: https://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example
I will have a fix soon
