### ISSUE TITLE
Can't dot-compose with void

### ISSUE THREAD

**Issue by nickdrozd** [idris-lang/Idris2#461]
Here is a simple claim:

```idris
claim : Not p -> p -> q
```

Perhaps the most straightforward way to prove it is this:

```idris
claim f x = void $ f x
```

The `x` argument can be pushed over to the other side of the `=`:

```idris
claim f = \x => void $ f x
```

So the proof is a function that takes one argument, then passes that
argument to `f`, then passes that result to `void`. In other words:

```idris
claim f = void . f
```

Except, whoops, it doesn't work:

```
     While processing right hand side of claim at bug.idr:2:1--3:1:
     When unifying (0 _ : Void) -> ?a and ?b -> ?c
     Mismatch between:
     	(0 _ : Void) -> ?a
     and
     	?b -> ?c
     at:
     2	claim f = void . f
     	          ^^^^
```

But the proof goes through fine in Idris 1:

```idris
claim : Not p -> p -> q
claim f = void . f
```

**Comment by nickdrozd** [comment]
Actually, this proof can be made even more compact. Starting with:

```idris
claim : Not p -> p -> q
claim f = void . f
```

The `f` argument can also be pushed to the other side of `=`:

```idris
claim = \f => void . f
```

The appliation of `.` can be rewritten as a prefix operator:

```idris
claim = \f => (.) void f
```

So `claim` is a function of one arg that passes that arg to `(.)
void`. In other words:

```idris
claim : Not p -> p -> q
claim = (.) void
```

These additional steps also work in Idris 1 but not Idris 2.

**Comment by ziman** [comment]
This happens because `(.) : (b -> c) -> (a -> b) -> (a -> c)` takes two unrestricted functions as arguments but `void` is an erased function.

I'm not sure how to fix this without quantity polymorphism. In the meantime, eta-expanding `void` is a workaround: `(\x => void x) . f`. Maybe the compiler could do this expansion automatically somehow? But it's still a hack, I think.

**Comment by nickdrozd** [comment]
Is there a specific reason `void` needs to erase its argument? This issue can be fixed with the simple change:

```diff
-void : (0 x : Void) -> a
+void : Void -> a
```

Is anything lost by doing this?

**Comment by ziman** [comment]
Yes. For example, you can no longer eliminate contradictions of erased proofs, like here.
```idris
f : (pfAB : Either a b) -> (0 contra : Not b) -> a
f (Left  pfA) contra = pfA
f (Right pfB) contra = void $ contra pfB
```

**Comment by gallais** [comment]
Note that you should be able to use `absurd` instead of `void`.
