### ISSUE TITLE
JavaScript backend

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#47]
<a href="https://github.com/maxdeviant"><img src="https://avatars2.githubusercontent.com/u/1486634?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxdeviant](https://github.com/maxdeviant)**
_Saturday Apr 11, 2020 at 14:57 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/276_

----

I was thinking of starting work on a JavaScript backend for Idris2.

I have some preliminary work (AST and codegen) completed [on my fork](https://github.com/maxdeviant/Idris2/commits/js-backend), but I wanted to check in before getting too deep into this.

I just saw [this commit](https://github.com/edwinb/Idris2/commit/2688f070e59d44692890ce09f30397260dbb3919) which states "This is step 0 towards pluggable back ends". Would it be better to wait until pluggable backends are in place before even thinking about a JS backend?

Also, a more general question, are other backends (like a JS one) intended to be in-tree? Or would they be handled out-of-tree?

**Comment by edwinb** [comment]
<a href="https://github.com/ziman"><img src="https://avatars1.githubusercontent.com/u/316753?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ziman](https://github.com/ziman)**
_Saturday Apr 11, 2020 at 15:37 GMT_

----

I expect that once pluggable backends are a thing, it should not be hard to port the existing ones.

Non-pluggable backends have to be in-tree.

I'm also working on a JS backend but from the opposite end: I'm looking into defunctionalisation at the moment. I have a concrete idea that I want to try out (unrestricted TCO via switch-in-while), so it's a bit of a private experiment of sorts. Besides, if it gets _too_ laborious, I might just give up. It would not be the first time. :)

But I like to have [neat generated code](https://github.com/ziman/idris-py/blob/master/examples/example.py) with comments, indentation, smart linebreaking, and everything, so i was going to use my pretty-printing library for it. A proper AST library that can do that by itself would be great, of course.

**Comment by edwinb** [comment]
<a href="https://github.com/maxdeviant"><img src="https://avatars2.githubusercontent.com/u/1486634?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxdeviant](https://github.com/maxdeviant)**
_Saturday Apr 11, 2020 at 17:08 GMT_

----

> But I like to have neat generated code with comments, indentation, smart linebreaking, and everything, so i was going to use my pretty-printing library for it.

I would just run the JS output through [Prettier](https://prettier.io/) :wink:

**Comment by edwinb** [comment]
<a href="https://github.com/shmish111"><img src="https://avatars2.githubusercontent.com/u/934267?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shmish111](https://github.com/shmish111)**
_Monday Apr 20, 2020 at 20:43 GMT_

----

Out of interest, what is the use case for a javascript back end vs WASM one?

**Comment by edwinb** [comment]
<a href="https://github.com/maxdeviant"><img src="https://avatars2.githubusercontent.com/u/1486634?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxdeviant](https://github.com/maxdeviant)**
_Monday Apr 20, 2020 at 20:59 GMT_

----

@shmish111 WASM can't currently do everything JS can do, the main thing being building web apps.

**Comment by edwinb** [comment]
<a href="https://github.com/ziman"><img src="https://avatars1.githubusercontent.com/u/316753?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ziman](https://github.com/ziman)**
_Monday Apr 20, 2020 at 22:54 GMT_

----

For the record, I've abandoned the JS project I talked about. It turns out that the JS `switch` statement does not jump in constant time, at least not in the CLI version of NodeJS.

**Comment by edwinb** [comment]
<a href="https://github.com/diakopter"><img src="https://avatars1.githubusercontent.com/u/50262?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [diakopter](https://github.com/diakopter)**
_Monday Apr 20, 2020 at 23:25 GMT_

----

@ziman 
Matúš,

If the JS switch is in a top-level function, it is likely not being JITted, just interpreted. Set up some global state and contrive a way to warm up the function, and it can be JITted..  I encountered the same problem in a prior life.

-Matt

**Comment by edwinb** [comment]
<a href="https://github.com/cypheon"><img src="https://avatars1.githubusercontent.com/u/112814?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cypheon](https://github.com/cypheon)**
_Thursday Apr 30, 2020 at 09:27 GMT_

----

@maxdeviant Being unaware of your fork, I implemented a JavaScript backend in my fork: [feature/codegen-es](https://github.com/cypheon/Idris2/tree/feature/codegen-es)

For now, the backend is directly generating the code by building a (long) string, but your approach with a separate AST seems much cleaner! So I'll have a look into switching my codegen over to use your JS AST.

**Comment by clayrat** [comment]
@cypheon it seems you've changed the branch to https://github.com/cypheon/Idris2/tree/codegen-es2020 ?

**Comment by cypheon** [comment]
@clayrat yes, I also rotated the repos, the "old" one was based on Idris2-boot, this is the new one based on (self-hosted) Idris2

**Comment by clayrat** [comment]
See https://github.com/idris-lang/Idris2/pull/415

**Comment by clayrat** [comment]
Should we close this since https://github.com/idris-lang/Idris2/pull/415 is merged?

**Comment by gallais** [comment]
Do we have a lower bound on the version of node needed?
With v8.10.0 I am getting

> 275/293 tests successful

because of a lot of syntax errors.

**Comment by maxdeviant** [comment]
@gallais From the README it looks like (at the very least) Node 10.4 or higher is needed:

> The javascript codegen uses the new BigInt, hence nodejs 10.4 or higher is required.
