### ISSUE TITLE
Int primitives have wrong behavior

### ISSUE THREAD

**Issue by MarcelineVQ** [idris-lang/Idris2#486]
# Steps to Reproduce
Write the following separate things into the repl
1 `the Int (-9223372036854775808)` -- this number is the value of 2^63 for a 64 bit signed integer
2 `shiftL 1 63`
3 `the Int (-9223372036854775808 - 1)`
4 `the Int (9223372036854775808 + 1)`
5 `the Int (92233720368547758010)` -- this number is larger than the value of 2^63 to cause what should be an overflow
# Expected Behavior
1 `-9223372036854775808`
2 `-9223372036854775808`
3 `9223372036854775807`
4 `-9223372036854775807`
5 `-70`
# Observed Behavior
1 `0`
2 `0`
3 `-1`
4 `1`
5 `92233720368547758010`

To explain
1 - 4 are caused by the operations involved (neg, -, +, shiftL) being `remainder` to 63 bits. `remainder` is the reasonable thing to use to clamp unsigned numbers but doesn't seem to be the correct method for signed based on the above.
5 `fromInteger` doesn't seem to do any actual conversion or bounds checking of Integer's given to it when making an Int.

n.b. backend devs should recheck what theirs does to see if they have correct behavior in case they just copied what scheme had

**Comment by melted** [comment]
Could you reproduce it in a compiled program?

**Comment by melted** [comment]
Just interesting to see if the behavior differs.

**Comment by MarcelineVQ** [comment]
ah sure so given
```
main : IO ()
main = do
  printLn $ the Int (-9223372036854775808) -- this number is the value of 2^63
  printLn $ shiftL 1 63
  printLn $ the Int (-9223372036854775808 - 1)
  printLn $ the Int (9223372036854775808 + 1)
  printLn $ the Int (92233720368547758010) -- this number is larger than the value of 2^63 to cause what should be an overflow
```
we get a slightly different result of
```
0
9223372036854775808
-1
1
92233720368547758010
```
where case 2 is different (I'm not sure why), but all still incorrect from my point of view.

**Comment by gallais** [comment]
All of these are working correctly now. The only subtlety is that `2` needs a type disambiguation:

```idris
Main> shiftL {a = Int64} 1 (fromNat 63)
-9223372036854775808 : Int64
```

Thanks to @stefan-hoeck I premuse.
