### ISSUE TITLE
Parse error when attempting to introduce an implict into scope inside an infix pattern match.

### ISSUE THREAD

**Issue by donovancrichton** [idris-lang/Idris2#495]
Introducing an implicit into scope on the LHS inside the pattern match of an infix data constructor results in a parsing error.
Introducing the same when the pattern match is written in _prefix form_ works as intended.

# Steps to Reproduce

```idris
data MyList : Type -> Type where
  Nil : {a : Type} -> MyList a
  (::) : {a : Type} -> a -> MyList a -> MyList a

f : MyList b -> ()
f [] = ()
f ((::) {a} x xs) = ?normal

g : MyList b -> ()
g [] = ()
g ({a} x :: xs) = ?broken

-- Also tried matching on (x {a} :: xs) , (x :: {a} xs) , and (x :: xs {a}) with various parsing or undefined name errors.
```

# Expected Behavior

`g` to pass without errors (or documentation updated to reflect the introduction of implicits into scope on infix constructors).

# Observed Behavior
```
at_break.idr:12:1--12:1:Parse error: Couldn't parse declaration (next tokens: [identifier g, symbol (, symbol {, identifier a, symbol }, identifier x, symbol ::, identifier xs, symbol ), symbol =])
Error(s) building file at_break.idr
```

Code to replicate can be found here: https://gist.github.com/donovancrichton/1f7f2e335774592cbf7f59a41d638c36

Should there be a canonical way to introduce implicits into scope inside matches on infix constructors? :)

**Comment by gallais** [comment]
Have you tried writing `((::) {a} x xs)` instead?

**Comment by donovancrichton** [comment]
Well yes, and it works just fine. I'm just wondering if there should be a canonical way to introduce an implicit into scope using an infix binding? Or if it should absolutely be a parse or undefined name error in all cases of this :)

**Comment by donovancrichton** [comment]
Oh, it looks like Idris1 has the same problem. I guess it's not really an issue then, and just something to document when talking about introducing implicits into scope.
