### ISSUE TITLE
Compilation of hello world gives error message

### ISSUE THREAD

**Issue by bigos** [idris-lang/Idris2#505]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce

Create hello world as in https://idris2.readthedocs.io/en/latest/tutorial/starting.html#checking-installation
and try to compile
```

jacek@jacek-ixtreme-M5850:~/Programming/Idris2-prog$ cat ./hello.idr 
module Main

main : IO ()
main = putStrLn "Hello world"
jacek@jacek-ixtreme-M5850:~/Programming/Idris2-prog$ idris2 ./hello.idr -o hello
File error in build/.: File Not Found
jacek@jacek-ixtreme-M5850:~/Programming/Idris2-prog$ ./build/exec/hello
Hello world
```

# Expected Behavior

No error on correct file.

# Observed Behavior

We get the error  `File error in build/.: File Not Found`

**Comment by bigos** [comment]
```
$ idris2 --version
Idris 2, version 0.2.0-5ad779f9d
```

**Comment by edwinb** [comment]
You need to invoke it as `idris2 hello.idr`, not `idris2 ./hello.idr`. It uses the path you give on the command line to build the expected module name and the leading `.` will confuse it.

**Comment by bigos** [comment]
I had to remove the build folder first. After that, your example worked. Thank you very much.
