### ISSUE TITLE
Error building Path

### ISSUE THREAD

**Issue by locallycompact** [idris-lang/Idris2#511]
```
34/153: Building Utils.Path (src/Utils/Path.idr)
src/Utils/Path.idr:23:19--23:29:While processing right hand side of dirSeparator at src/Utils/Path.idr:23:1--26:1:
Undefined name isWindows
src/Utils/Path.idr:28:20--28:30:While processing right hand side of pathSeparator at src/Utils/Path.idr:28:1--31:1:
Undefined name isWindows
src/Utils/Path.idr:260:20--261:19:While processing right hand side of isAbsolute' at src/Utils/Path.idr:260:1--267:1:
Undefined name isWindows
```

Building via the 0.2.0 version that's currently in nixpkgs.

**Comment by melted** [comment]
Only way to solve this is to update the version in nixpkgs as that lacks a function in its lib that is used by the compiler.

**Comment by locallycompact** [comment]
Ok I'll take a look at that thanks, closing.

**Comment by locallycompact** [comment]
Actually, would there be any chance of a minor version update so I can justify the jump?

**Comment by melted** [comment]
Edwin was talking of a 0.2.1, so there's a good chance, but it didn't get out before the vacation.

Idris2 is changing a lot and a lot of bugs get quashed, so staying at releases isn't really advisable at the moment. On the other hand, we need a good milestone where we can abandon bootstrappability from Idris 1.

**Comment by locallycompact** [comment]
Ok, I can work with that. Thanks.
