### ISSUE TITLE
Type error when parsing let expressions with equality types(?)

### ISSUE THREAD

**Issue by donovancrichton** [idris-lang/Idris2#518]
# Steps to Reproduce
```idris
f : (n : Nat) -> n = n + 0
f 0 = Refl
f (S k) = 
  let ih : k = plus k 0
      ih = f k
  in rewrite sym ih in Refl
```
# Expected Behavior
Type checking :)
# Observed Behavior
```
Can't solve constraint between:
	plus k 0
and
	k
at:
6	  in rewrite ih in Refl
```
This works just fine if I put parentheses around the type `ih : (k = plus k0)`.

Here is a gist with the above code that errors:
https://gist.github.com/donovancrichton/53c8b6519637a7facc3ce663857d2a29

**Comment by gallais** [comment]
Cf. https://github.com/idris-lang/Idris2/issues/63#issuecomment-652916036

The fact that we use `=` for both assignment and the equality type
means this is unfortunately inevitably ambiguous.

**Comment by donovancrichton** [comment]
Ah, thank you @gallais! The link to the earlier issue explains the reasoning behind this well!
I'll be sure to explicitly disambiguate my equality types in local definitions with parentheses going forward :)

**Comment by gallais** [comment]
I think you can also use ===
