### ISSUE TITLE
Browsable source code 

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#52]
<a href="https://github.com/jeetu7"><img src="https://avatars1.githubusercontent.com/u/1040586?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeetu7](https://github.com/jeetu7)**
_Friday Apr 17, 2020 at 09:56 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/294_

----

MarcelineVQ (at IRC) pointed at the Agda browsable source code.  [Agda stdlib example](https://agda.github.io/agda-stdlib/ ) . This looks good for browsing source code, wherein we can go through various variables and jump across the code for declarations/definitions etc.  Also, we can discuss various approaches for doing the same here. 

- [ ] Browsable code for Idris2.
- [ ] Hosting Idris2 Browsable Code (probably on github.ion as Agda itself)
- [ ] Mechanism to convert local code written in Idris2 for local browsing.

**Comment by edwinb** [comment]
<a href="https://github.com/jeetu7"><img src="https://avatars1.githubusercontent.com/u/1040586?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeetu7](https://github.com/jeetu7)**
_Friday Apr 17, 2020 at 10:25 GMT_

----

For an example source idr file, pygments can generate prettly decent colorful html. The colors and lexer itself is customizable. Check the rarw code of gists  [input idr file](https://gist.githubusercontent.com/jeetu7/619f68c637d0d6dff972352774491a79/raw/abcd216f570b97ad58fbfd10b513078ea3454982/example.idr)and  [output html](https://gist.githubusercontent.com/jeetu7/3023939d09c182e8d78659174a08f7ac/raw/014ae4a247a2a4af548c4c215ea6f7d3f2a3588a/gistfile1.txt). The output html should be downloaded and opened in your browser. Command used is as follows:

```pygmentize -f html -O full  -o /tmp/x.html ~/tmp/example.idr ```

So getting to html colorful code is easy. 
Next is linking it with declarations.

**Comment by edwinb** [comment]
<a href="https://github.com/jeetu7"><img src="https://avatars1.githubusercontent.com/u/1040586?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeetu7](https://github.com/jeetu7)**
_Monday Apr 20, 2020 at 18:56 GMT_

----

For linking, we have to customize (extend) the html formatter for idris1 in pygments. And also, to make it support idris2, we might have to extend the pygment's lexer as well. 

For doing the linking part, we should be able to get this information from the idris2 compiler about how it parses and resolves the declaration and usage of types/variable/functions etc. Assuming the above information is available, conceptually the process of linking can go like this

1. Extracts information from compiling process about which line the compiler sees the token usage (which we want to show as clickable) and which we want to link to (the declaration of that token)
2. Modify the formatter of the pygment to add anchor to each line so that it can be hyperlinked to. Ref [Html anchor links](https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html)
3.  Generate output file with line numbered source code in html (with anchors for each line number id-ed as line number itself). Example with line numbers is already possible with pygments [Line numbered html output](https://gist.github.com/jeetu7/146ee2425fd6e0c57e873fc7d8533444)
```pygmentize -f html -O full,linenos=1 -o /tmp/x.html ~/tmp/example.idr```

4. Use  this information  in the formatter, or might be a second pass by some other script.

**Comment by edwinb** [comment]
<a href="https://github.com/gallais"><img src="https://avatars1.githubusercontent.com/u/1094905?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gallais](https://github.com/gallais)**
_Monday Apr 20, 2020 at 20:37 GMT_

----

Do we gain much by using pygment rather than outputting e.g. markdown to be
post-processed by pandoc?

Re, looking at rendered examples we can use htmlpreview.github.io.
See for instance: [your syntax highlighted file](http://htmlpreview.github.io/?https://gist.githubusercontent.com/jeetu7/3023939d09c182e8d78659174a08f7ac/raw/014ae4a247a2a4af548c4c215ea6f7d3f2a3588a/gistfile1.txt)

**Comment by edwinb** [comment]
<a href="https://github.com/jfdm"><img src="https://avatars2.githubusercontent.com/u/331273?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jfdm](https://github.com/jfdm)**
_Wednesday Apr 22, 2020 at 19:44 GMT_

----

We must also look at how it works in Idris1 where you can use the `--highlight` flag dump an SExpr containing highlighting information. There is a tool [`idrishl`](https://github.com/david-christiansen/idris-code-highlighter) which can generate HTML and LaTeX sources. The SExpr is a version of the same information sent out by Idris1 IDE mode for highlighting, and the source is the same information used by `idrisdoc` Idris1's javadoc like tool

**Comment by edwinb** [comment]
<a href="https://github.com/jeetu7"><img src="https://avatars1.githubusercontent.com/u/1040586?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeetu7](https://github.com/jeetu7)**
_Friday May 01, 2020 at 15:56 GMT_

----

@jfdm @gallais I will look into them. I might be little slow as I am learning Idris along the way. 

1. Also any pointers, at **which point I can get the info about compiler finding the linking of declaration of tokens and their usages**. Where should I start (which file or written material).  Can I store the info in some output file as in ctags. Or do I have to decipher the scheme output for that. 

2. My aim is to get it going using whichever way is possible to get a wroking method. Then switch it step by step to better tools (preferably self contained idris methods).

3. Generate line numbered linkable source code. Now you can link to a particular line using
    file:///tmp/x.html#line-5. Check the bottom two links for only html and particular line linked. You might have to reduce the size of the browser to actually notice the difference.
        `pygmentize -f html -O full,linenos=1,lineanchors=line -o /tmp/x.html ~/tmp/example.idr`

https://htmlpreview.github.io/?https://gist.githubusercontent.com/jeetu7/2873ac9befd63b1b0ef87347b5e41540/raw/3423e337d024df2f41653b2bd52614b1e6b7cb33/idris_doc_2.html

https://htmlpreview.github.io/?https://gist.githubusercontent.com/jeetu7/2873ac9befd63b1b0ef87347b5e41540/raw/3423e337d024df2f41653b2bd52614b1e6b7cb33/idris_doc_2.html#line-5

**Comment by gallais** [comment]
Katla (https://github.com/idris-community/katla/) now has an html backend.
The main feature missing as far as I'm concerned is jump-to-definition href links but that's for the katla issue tracker.

![katla-numbered-html](https://user-images.githubusercontent.com/1094905/143298609-ee8ca9ce-6ce9-4ef2-801e-d4ad7b093139.png)
