### ISSUE TITLE
Parsing Parentheses is not performant.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris2#532]
# Steps to Reproduce

Take the following [straightforward implementation of the Intrinsically Typed STLC in Idris and an ill-typed program](https://gist.github.com/jfdm/1233cba2c3ab9473fe1b0be233aad3ec) and compile with Idris2.

# Expected Behavior

Idris2 will type check the file in a reasonable amount of time.

# Observed Behavior

Idris2 takes an unreasonable amount of time.

Specifically if we observe the timings (acquired using `--timing`) we see that there is nothing inherently wrong with the code and its elaboration.
Idris2 **just** takes a *long* time to parse.

```
1/1: Building Lambda (Lambda.idr)
TIMING Parsing Lambda.idr: 110.247s
TIMING Reading imports: 0.032s
TIMING Processing decls: 0.004s
TIMING Compile defs: 0.000s
TIMING Elaborating Lambda.idr: 110.285s
...
TIMING Build deps: 110.291s
TIMING Loading main file: 110.292s
```

This is potentially due to the amount of Parentheses on the RHS of the equation for `term`. If we comment out this term then compilation takes a reasonable amount of time.

**Comment by gallais** [comment]
I think it's related to the call to `dpair` in `bracketedExpr`, we:

* parse an expression
* look for a comma that we don't find
* backtrack
* parse the expression again
* find the closing parens
* conclude it was just a `(expr)`

We should be able to refactor the grammar so that we parse this expr only once.

**Comment by edwinb** [comment]
It is indeed dependent pairs, I've just verified this experimentally! I may have a quick fix...
