### ISSUE TITLE
"Invisible" code blocks and lines in OrgMode files are actually visible.

### ISSUE THREAD

**Issue by stasoid** [idris-lang/Idris2#542]
[Documentation](https://idris2.readthedocs.io/en/latest/reference/literate.html) says that 

> * Comment blocks that begin with `#+COMMENT: idris` are treated as invisible code blocks.
> * Invisible code lines are denoted with `#+IDRIS:`.

But idris2 actually executes those blocks and lines.

### Steps to Reproduce
Create file `test.org` with this content: `#+IDRIS: main:IO();main=print 1`, compile and run it.

### Expected Behavior
Compilation fails with `Uncaught error: (script):1:1--1:1:Undefined name main`.

### Observed Behavior
Compilation succeeds, the resulting program prints `1`.

**Comment by gallais** [comment]
I would expect invisible code blocks to be taken into account
(otherwise why have them at all / not commented out?) but hidden
when generating the pretty document.

**Comment by stasoid** [comment]
Oh, *that's* what "invisible" means... It would be good to have it explained in the docs then, because it is not obvious at all (to me, anyway).
