### ISSUE TITLE
Allow recovery in Elab monad

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [idris-lang/Idris2#544]
It would be nice to allow a way to recover from failure in the elaboration monad, such that for example a checkType can fail without stopping elaboration completely. This would allow a user to write their own search algorithms as macros/Elab actions.

**Comment by edwinb** [comment]
This is planned, yes. I'd like the search to be extensible, at least, and it'd be nice if it was possible to write the whole search process in Elab.

**Comment by gallais** [comment]
Fixed by #2008
