### ISSUE TITLE
Help needed for State Tranformer

### ISSUE THREAD

**Issue by wurmli** [idris-lang/Idris2#546]
I try to write an execStateT, using a recent Idris2 and following closely the example of execState in Control.Monad.State, but I don't succeed. The compiler "[c]an't find the implementation for Monad ?m"

# Steps to Reproduce
Try to build the following module:
```
module MonadState

import Control.Monad.State

execStateT : Monad m => StateT s m a -> s -> m s
execStateT st = lift snd . runStateT st

execStateT' : Monad m => StateT s m a -> s -> m s
execStateT' st = lift (Builtin.snd) . runStateT st

execStateT'' : StateT Nat List Nat -> Nat -> List Nat
execStateT'' st = lift (Builtin.snd) . runStateT {m=List} st
```
# Expected Behavior
The module is built and loaded into the repl.
# Observed Behavior
```
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.2.0-15b31e69d
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/      Type :? for help                     

Welcome to Idris 2.  Enjoy yourself!
1/1: Building MonadState (MonadState.idr)
MonadState.idr:7:22--7:25:While processing right hand side of execStateT at MonadState.idr:7:1--9:1:
Ambiguous elaboration at:
7       execStateT st = lift snd . runStateT st
                             ^^^
Possible correct results:
        ?postpone [locals in scope: a, s, m, {conArg:729}, st]
        ?postpone [locals in scope: a, s, m, {conArg:729}, st]
MonadState.idr:10:18--10:37:While processing right hand side of execStateT' at MonadState.idr:10:1--12:1:
Can't find an implementation for Monad ?m at:
10      execStateT' st = lift (Builtin.snd) . runStateT st
                         ^^^^^^^^^^^^^^^^^^^

MonadState.idr:13:19--13:38:While processing right hand side of execStateT'' at MonadState.idr:13:1--14:1:
Can't find an implementation for Monad ?m at:
13      execStateT'' st = lift (Builtin.snd) . runStateT {m=List} st
```
Help would be greatly appreciated!

**Comment by ShinKage** [comment]
You need `map` instead of `lift`, since the expression `runState st : s -> m (a, s)` is already in the correct monad.

**Comment by wurmli** [comment]
> You need `map` instead of `lift`, since the expression `runState st : s -> m (a, s)` is already in the correct monad.

Did you mean "runState" or "runStateT"? I use runStateT and map would work, i.e. compiles and effects something, because "StateT stateType f" is a Functor, but map and lift have different effects.

**Comment by ShinKage** [comment]
> > You need `map` instead of `lift`, since the expression `runState st : s -> m (a, s)` is already in the correct monad.
> 
> Did you mean "runState" or "runStateT"? I use runStateT and map would work, i.e. compiles and effects something, because "StateT stateType f" is a Functor, but map and lift have different effects.

I meant `runStateT`.

**Comment by wurmli** [comment]
@ShinKage : Thank you for your hint and, yes, you are right, but it took me a while to convince myself.

**Comment by gallais** [comment]
Note that help requests are probably more appropriate on the mailing list
rather than the bug/feature tracker.
