### ISSUE TITLE
FFI only reading up to 32 bit integers (e.g. no uint64_t -> Bits64)

### ISSUE THREAD

**Issue by neriglissar** [idris-lang/Idris2#549]
Hi, I created a small example to test whether one can read/write `Bits64, Bits32` etc. through the C FFI:

https://github.com/neriglissar/idris2-int-test

I found that:
- Reading from C into Bits64 is capped at 32 bits
- Reading from C into Bits16 can exceed 16 bits
- Writing more than 32 bits to C crashes the runtime

Hope someone is able to fix this for the Scheme backend! Thanks.

# Steps to Reproduce
```
1/1: Building Integers (Integers.idr)
Integers> :exec run
```
```
1/1: Building Integers (Integers.idr)
Integers> :exec fun
```
# Expected Behavior
```
1/1: Building Integers (Integers.idr)
Integers> :exec run
====== Bits 64 ======
C:     18446744073709551615
Idris: 18446744073709551615
C:     18446744073709551615
Idris: 18446744073709551615
```

````
Integers> :exec fun
====== Bits 64 ======
Idris: 18446744073709551615
C:     18446744073709551615
````
# Observed Behavior
```
1/1: Building Integers (Integers.idr)
Integers> :exec run
====== Bits 64 ======
C:     18446744073709551615
Idris: 4294967295
C:     4294967295
Idris: 4294967295
```
and also
````
====== Bits 16 ======
C:     4294967295
Idris: 4294967295
C:     4294967295
Idris: 4294967295
`````
````
Integers> :exec fun
====== Bits 64 ======
Idris: 18446744073709551615
Exception in write__uint64: invalid foreign-procedure argument 18446744073709551615
````

**Comment by SmiVan** [comment]
Something must be wrong with the way the foreign procedure is composed, as running 
```scheme
(load-shared-object "integers.so")
(define extfun (foreign-procedure "write__uint64" (unsigned-64) void*))
(extfun 18446744073709551615)
```
in scheme works just fine and prints the expected
```
C:     18446744073709551615
```
rather than the exception that is produced with the idris execution.

**Comment by neriglissar** [comment]
> Something must be wrong with the way the foreign procedure is composed, as running
> 
> ```scheme
> (load-shared-object "integers.so")
> (define extfun (foreign-procedure "write__uint64" (unsigned-64) void*))
> (extfun 18446744073709551615)
> ```
> 
> in scheme works just fine and prints the expected
> 
> ```
> C:     18446744073709551615
> ```
> 
> rather than the exception that is produced with the idris execution.
> 
> Found the problem, on inspecting the scheme file generated it seems that `write__unit64` is converted to
> 
> ```scheme
> (define Integers-write__uint64 (lambda (farg-0 farg-1) ((foreign-procedure #f "write__uint64" (unsigned) void*) farg-0)))
> ```
> 
> which does indeed cause the exception
> 
> ```scheme
> > (define extfun (foreign-procedure "write__uint64" (unsigned) void*))
> > (extfun 18446744073709551615)
> ```
> 
> `Exception in extfun: invalid foreign-procedure argument 18446744073709551615`
> 
> This `unsigned` vs `unsigned-64` difference is likely the same issue that causes the `MAX_u64` to get compressed to 32 bits, as that appears to use `unsigned` too:
> 
> ```scheme
> (define Integers-get__MAX_uint64 (lambda (farg-0) ((foreign-procedure #f "get__MAX_u64" () unsigned) )))
> ```
> 
> Here's what seems to be the core of the problem - all BitsN types are turned into `CFUnsigned` without accounting for their size,
> https://github.com/idris-lang/Idris2/blob/e93fba3952649762d8d165124c0888756547dacf/src/Compiler/CompileExpr.idr#L509-L512
> 
> 
> which means that they all get turned into Scheme's `unsigned` in the compiler.
> https://github.com/idris-lang/Idris2/blob/0a7ea69df56a06d721d284ab414d6d74eba2b8f0/src/Compiler/Scheme/Chez.idr#L170
> 
> I think that this can be fixed by splitting `CFUnsigned` into `CFUnsigned8`, `CFUnsigned16`, `CFUnsigned32` and `CFUnsigned64` and compiling them to `unsigned-8`, `unsigned-16`, `unsigned-32` and `unsigned-64` accordingly, but I'd like someone who understands the bigger picture better to take a look at this.

That is very helpful. Thank you for looking into this!
