### ISSUE TITLE
Instantiating records using field names.

### ISSUE THREAD

**Issue by thomasdziedzic** [idris-lang/Idris2#553]
The way we currently create a record and instantiate it:

```idris
record Dog where
  constructor MkDog
  name : String
  age : Nat

myDog : Dog
myDog = MkDog "Idris" 2
```

The way I would like to instantiate it:

```idris
myDog : Dog
myDog = MkDog { name = "Idris", age = 2 }
```

The reason is for records with a large amount of fields, it makes it clearer what fields take on what values, rather than relying on the position of the arguments.

**Comment by gallais** [comment]
One problem I can see with this approach is the interaction with implicit fields:

```idris
record Dog where
  constructor MkDog
  {name : String}
  age : Nat

myDog : Dog
myDog = MkDog {name = "Idris"} 2
```

The definition of `myDog` looks like it could be either:

* the usual constructor + implicit name + missing field
* the new constructor + assignment (with a missing field) applied to `2`

We could maybe do something like the following?

```idris2
record MkDog { ... }
```

**Comment by gallais** [comment]
I believe this was fixed.
