### ISSUE TITLE
Multiple constrains with unreseolved type parameters on interface declaration cause typecheck issue

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#56]
<a href="https://github.com/fabianhjr"><img src="https://avatars0.githubusercontent.com/u/303897?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fabianhjr](https://github.com/fabianhjr)**
_Tuesday Apr 21, 2020 at 20:32 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/306_

----

# Steps to Reproduce

```idris
module Test

interface Interface1 a where
  x : Bool

interface Interface2 a where
  y : Bool

interface (Interface1 a, Interface2 a) => InterfaceMix a where
  z : Bool
  z = x || y 
```

# Expected Behavior

Typecheck

# Observed Behavior

```
Test.idr:11:7--11:9:While processing right hand side of Default implementation of z at Test.idr:11:3--13:1:
Can't find an implementation for Interface1 ?a
```

**Comment by edwinb** [comment]
<a href="https://github.com/gallais"><img src="https://avatars1.githubusercontent.com/u/1094905?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gallais](https://github.com/gallais)**
_Tuesday Apr 21, 2020 at 20:56 GMT_

----

Isn't the problem under-constrained?
There is no way to infer `a` from the type `x` ought to have.

**Comment by edwinb** [comment]
<a href="https://github.com/fabianhjr"><img src="https://avatars0.githubusercontent.com/u/303897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fabianhjr](https://github.com/fabianhjr)**
_Tuesday Apr 21, 2020 at 20:59 GMT_

----

I extracted this from some testing I am doing with Bools and Group interfaces,

```idris
module Algebra.Group.Commutative

import Builtin
import Algebra.Group.Magma
import Algebra.Group.Semigroup
import Algebra.Group.Monoid
import Algebra.Group.Group

%default total

public export
interface Magma a ⇒ CommutativeMagma a where
  proofOfCommutativity : (x, y: a) → x `op` y = y `op` x

public export
interface (CommutativeMagma a, Semigroup a) => CommutativeSemigroup a where

public export
interface (CommutativeMagma a, Monoid a) => CommutativeMonoid a where

public export
interface (CommutativeMagma a, Group a) => CommutativeGroup a where

{-
-- TODO: Uncomment when Idris2!306 gets fixed
(CommutativeMagma a, Semigroup a) => CommutativeSemigroup a where
(CommutativeMagma a, Monoid a) => CommutativeMonoid a where
(CommutativeMagma a, Group a) => CommutativeGroup a where
-}
```

So the idea is that from:

```idris
[BoolSumMagma] Magma Bool where
  False `op` False = False
  _     `op` _     = True

[BoolSumCommutativeMagma] CommutativeMagma Bool using BoolSumMagma where
  proofOfCommutativity False False = Refl
  proofOfCommutativity False True  = Refl
  proofOfCommutativity True  False = Refl
  proofOfCommutativity True  True  = Refl
```

The implementations of `CommutativeSemigroup` and `CommutativeMonoid` get derived.

Since it was the same error message when reduced to the one on the first message I left it as reduced as possible.

**Comment by edwinb** [comment]
<a href="https://github.com/fabianhjr"><img src="https://avatars0.githubusercontent.com/u/303897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fabianhjr](https://github.com/fabianhjr)**
_Tuesday Apr 21, 2020 at 21:25 GMT_

----

Oh, wait I get what you are refering to now.

```idris
module Test

interface Interface1 a where
  x : a

interface Interface2 a where
  y : a

interface (Interface1 a, Interface2 a) => InterfaceMix a where
  op : a -> a -> a
  z : a
  z = x `op` y 
```

This works and is less hacky

**Comment by gallais** [comment]
I still believe that the original problem was under-constrained
and thus working as expected.
