### ISSUE TITLE
Ambigous Implementations when using `using` on a constrainted interface implementation

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#57]
<a href="https://github.com/fabianhjr"><img src="https://avatars0.githubusercontent.com/u/303897?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fabianhjr](https://github.com/fabianhjr)**
_Wednesday Apr 22, 2020 at 01:23 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/307_

----

# Steps to Reproduce

```
module Test

interface Simple a where
  op : a -> a -> a

interface Simple a => Constraint a where
  square : a -> a
  square x = x `op` x  

-- And
[NamedSimple1] Simple Bool where
  op True True = True
  op _    _    = False

-- Or
[NamedSimple2] Simple Bool where
  op False False = False
  op _     _     = True

[Constrainted1] Constraint Bool using NamedSimple1 where
[Constrainted2] Constraint Bool using NamedSimple2 where
```

# Expected Behavior

Should typecheck and use their corresponding implementations

# Observed Behavior

```
Test.idr:21:1--23:1:While processing right hand side of Constrainted2 at Test.idr:21:1--23:1:
Multiple solutions found in search. Possible correct results:
	NamedSimple1
	NamedSimple2
```

**Comment by gallais** [comment]
This is now successfully accepted. \o/
