### ISSUE TITLE
literal overload and normalization problem

### ISSUE THREAD

**Issue by vfrinken** [idris-lang/Idris2#574]
A problem with literal overload and normalization as described below:

# Steps to Reproduce
Code
```
data MyData = MkMyData Nat

myFunction : (h:MyData) -> {prf:h=(MkMyData 256)} -> ()
myFunction (MkMyData x) {prf} =
    case prf of
        Refl => ?hole
```
# Expected Behavior
That this type checks, even for large numbers

# Observed Behavior
The type checker complains that the case statement is not covering
```
myFunction is not covering at:
3    myFunction : (h:MyData) -> {prf:h=(MkMyData 256)} -> ()
4    myFunction (MkMyData x) {prf} =
```
    Calls non covering function Main.case block in myFunction
even though Refl is the only constructor of =

In fact the type checker works correctly for numbers < 100. The moment the number is desugared as `S (assert_total (integerToNat 100))` instead of `S(S(S...(S Z)...))` the type checking fails.

**Comment by ShinKage** [comment]
Note: If non desugared version of `Nat`s are used in the signature, both coverage checker and desugaration phase work fine, even with multiple hundreds of constructors (and notably without getting slower).

**Comment by gallais** [comment]
The desugarer needs to find the right balance between generating
a massive term and desugaring literals into constructors. My advice
is to write `2 ^ 8` instead of `256` and let normalisation do the job.
