### ISSUE TITLE
Add exponentiation for Integers

### ISSUE THREAD

**Issue by thomasdziedzic** [idris-lang/Idris2#592]
I would like to write something like:
`2^64` and get back `18446744073709551616` like in haskell

I know about the Nat version;
Nats have a power function defined under `Data.Nat` but this is slow for `power 2 64`

@ohad mentioned I should link this issue to https://github.com/idris-lang/Idris2/issues/29 as it might be easy to add this feature along with the Double constants.

**Comment by mr-infty** [comment]
I've made a draft PR (#1084) that fixes this issue. I've chosen to ignore issue #29, as it seems unrelated. Incidentally, I'm still working on fixing the latter issue, but this will take a bit more time.

**Comment by gallais** [comment]
Fixed by #1063 (cf. `Data.Monoid.Exponentiation`)
