### ISSUE TITLE
'unpack' causes 'RangeError: Maximum call stack size exceeded' for javascript code generator

### ISSUE THREAD

**Issue by raders** [idris-lang/Idris2#596]
# Steps to Reproduce
```
module test

import Data.Stream

foo : List Char
foo = unpack $ pack $ take 4000 (repeat 'a')
```

Then run from the REPL: `:exec printLn foo`

# Expected Behavior
No errors.

# Observed Behavior
RangeError: Maximum call stack size exceeded
    at Prelude_Types_case__unpack$2cunpack$27_3621 (/Users/raders/dev/idris2-electron/build/exec/_tmp_node.js:68:98)
    at Prelude_Types_n__3694_3609_unpack$27 (/Users/raders/dev/idris2-electron/build/exec/_tmp_node.js:76:9)
    at Prelude_Types_case__unpack$2cunpack$27_3621 (/Users/raders/dev/idris2-electron/build/exec/_tmp_node.js:68:11)
    at Prelude_Types_n__3694_3609_unpack$27 (/Users/raders/dev/idris2-electron/build/exec/_tmp_node.js:76:9)
...

This works fine with the Chez Scheme backend.

**Comment by raders** [comment]
If the string length is 10000, then the error is:

RangeError: Maximum call stack size exceeded
    at Prelude_Types_take (/Users/srader/dev/idris2-electron/build/exec/_tmp_node.js:125:6)
    at Prelude_Types_take (/Users/srader/dev/idris2-electron/build/exec/_tmp_node.js:125:45)
    at Prelude_Types_take (/Users/srader/dev/idris2-electron/build/exec/_tmp_node.js:125:45)
...

So, both `unpack` and `take` are causing stack issues. Again, this works fine with the Chez Scheme backend.

**Comment by rbarreiro** [comment]
Currently the javascript backend does not optimize mutual tail recursive functions. The best solution I can think of is to inline mutual tail recursive functions. I will start to work on this but if anyone has any idea on this, they are welcome.

**Comment by gallais** [comment]
> The best solution I can think of is to inline mutual tail recursive functions.

One way to do it would be to fuse the two functions into a single one
whose type is controlled by a tag.
E.g.

```idris
mutual

  f : A -> B -> C
  f a b = fbody

  g : D -> E
  g d = gbody
```

becomes

```idris
data Tag = F | G

FusedType : Tag -> Type
FusedType F = A -> B -> C
FusedType G = D -> E

fused : (t : Tag) -> FusedType t
fused F a b = fbody [fused F/f, fused G/g]
fused G d   = gbody [fused F/f, fused G/g]
```

Of course this translation becomes complicated if e.g. `g` appears in the type of `f`.
However if you do it at the javascript level, you can ignore the types and just have
something of the form:

```javascript
function fused(tag, args) {
  switch(tag) {
  case "f" : 
     -- fbody with
     --  * args.a instead of a
     --  * args.b instead of b
     --  * fused ("f", {a: va, b: vb}) instead of f va vb
     --  * fused ("f", {d: vd})        instead of g vd
     break;
  case "g" :
     -- gbody with
     --  * args.a instead of a
     --  * args.b instead of b
     --  * fused ("f", {a: va, b: vb}) instead of f va vb
     --  * fused ("f", {d: vd})        instead of g vd
     break;
  };
};
```

**Comment by rbarreiro** [comment]
I made a merge request to solve unpack mutual recursion. Prelude_Types_take is not tail tail recursive, so it will be harder to solve.
Any idea?

**Comment by ziman** [comment]
Would `fastUnpack` from https://github.com/idris-lang/Idris2/pull/683 help?

**Comment by ziman** [comment]
Not a solution to the mutual recursion problem but https://github.com/idris-lang/Idris2/pull/683 includes `fastUnpack`, FWIW.

**Comment by raders** [comment]
Thanks @rbarreiro. This fixes the unpack issue. Unfortunately I don't have any suggestions on fixing Prelude_Types_take.
