### ISSUE TITLE
Injectivity proofs for constructors should not use their arguments

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris2#597]
I got bitten by this today, I had to edit `base/Data/Nat.idr` like so:

```diff
- succInjective : (left, right : Nat) -> S left = S right -> left = right
+ succInjective : (0 left, right : Nat) -> S left = S right -> left = right
```

because I wanted to peel off an `S` constructor in an equality proof about terms
that will not be here at runtime anymore. When we are proving that a constructor
is injective, we never actually need to have our hands on the constructor's
arguments.
	
It would be nice to fix this issue everywhere in the libs.

**Comment by shaylew** [comment]
Would it be sensible to have a (disabled by default?) warning for arguments that are unrestricted in the signature but only used 0 or 1 time in the definition? I'm happy to comb the libs for this (I'm fresh out of SPLV and looking for starter issues), but also it looks like the kind of thing that'll crop up again and again without tooling assistance.

**Comment by shaylew** [comment]
A couple of questions about the conventions for injectivity proofs:

- Almost all injectivity proofs in the libs take their left and right sides implicitly; `succInjective` seems to be an outlier. (There are still some that take implicit arguments at nonzero multiplicity, though.) Is there some rhyme or reason to this?
- Most injectivity proofs take their *proof* argument at unrestricted multiplicity... but a couple (`Data.HVect.consInjective1`) only ask for `1` of it. Is there a right answer for which to use?

I'm not sure what it even means to distinguish `0 _ : a = b`, `1 _ : a = b`, and `ω _ : a = b`. You can pattern match on `Refl` at multiplicity `0`, but e.g. `cong` takes its proof at `1` anyway. And it looks like -- because there's no subtyping for multiplicity 0 -- you stop being able to use ordinary `.` composition for injectivity proofs whose equality argument is at multiplicity `0`, which is quite painful. Is `ω` the right answer for now?

**Comment by gallais** [comment]
> Is there some rhyme or reason to this?

I don't think there is. The libraries could use being a bit more consistent in their
naming schemes & the multiplicities being used. One problem is of course that it's
going to break people's code and we do try to avoid that in `base` in particular.

> Is there a right answer for which to use?

Equality proofs should not exist at runtime anyway so I think that being able to
insist that the input proof has quantity `0` is not that important here. Of course
some user could insist in their library that they want a `(0 _ : a = b)` and then
be annoyed that the ones we provide are not compatible... :/

**Comment by shaylew** [comment]
I thought some more about this and: if I'm understanding the QTT paper correctly, wouldn't a convention of always taking equality proofs at multiplicity `0` obviate this whole issue? It doesn't matter whether you have to look at your arguments to prove something about them, if the proof you output is only ever demanded 0 times in the place it's eventually used. This would also help for proofs that really do have to pattern match on their arguments (like `finToNatInjective`).

> Equality proofs should not exist at runtime anyway so I think that being able to
> insist that the input proof has quantity 0 is not that important here. Of course
> some user could insist in their library that they want a (0 _ : a = b) and then
> be annoyed that the ones we provide are not compatible... :/

Is this not the other way around? If someone wants a `(0 _ : a = b)` and you have `p : a = b` you can pass it just fine (and the function promises not to consume it). But if someone wants `(ω _ : a = b)` and all you've got is `0 p : a = b` you're in trouble, unless you're already in an erased context. You might hope that every equality proof eventually ends up in an erased position, in which case any quantity used in constructing the proof gets zeroed out anyway... but there are places (`eqToSo`, or many uses of `Yes` in decidable equality) where we take an equality as a nonzero-quantity argument, which means we've failed to absolve the equality proof of its (transitive) resource consumption.

In any case dealing with constructor injectivity proofs in particular -- which we really can prove blindfolded -- is much simpler than all this, so I've made a PR ( #644 ) for the actual specific issue at hand here.

**Comment by gallais** [comment]
> Is this not the other way around?

With function types, the notion of caller/callee gets inverted every
time you go left of an arrow. So yes but no but yes.

For instance if the user insists on writing `(0 _ : a = b) -> Void`
but we only provide `a = b -> Void` it's quite annoying.
