### ISSUE TITLE
Allow "export public" on same line as interface declaration

### ISSUE THREAD

**Issue by ornamentist** [idris-lang/Idris2#599]
# Steps to Reproduce

The syntax:

```idris
export public interface Foo where ...

export public my_function : Int ...
```

Compiles with Idris 1 but with Idris 2 this is a syntax error. Changing to

```idris 
export public 
interface Foo where ...

export public my_function : Int ... 
```

Allows the code to typecheck.

# Expected Behavior

Could we have the option of placing the `export public` specifier on the same line as the interface declaration--as with functions?  This is especially useful with the Idris 1 `%access public export` pragma going away in Idris 2.

**Comment by gallais** [comment]
This is already possible. The error came from the fact that the directive
is `public export` and not `export public`.

> Changing to
> ```
> export public 
> interface Foo where ...
> ```
> Allows the code to typecheck.

is not true AFAICT.
