### ISSUE TITLE
Two unrelated names get equated (variable capture?)

### ISSUE THREAD

**Issue by radoye** [idris-lang/Idris2#605]
While working on SPLV20 Exercise 2.2 I observed a surprising behavior: the system seems to unify two unrelated variables based on their name. 

# Steps to Reproduce

```
data Name : Type where
     UN : String -> Name -- user written name
     MN : String -> Int -> Name -- machine generated name

-- In the term representation, we represent local variables as an index into
-- a list of bound names:
data IsVar : Name -> Nat -> List Name -> Type where
     First : IsVar n Z (n :: ns)
     Later : IsVar n i ns -> IsVar n (S i) (m :: ns)

-- And, sometimes, it's convenient to manipulate variables separately.
-- Note the erasure properties of the following definition (it is just a Nat
-- at run time)
data Var : List Name -> Type where
     MkVar : {i : Nat} -> (0 p : IsVar n i vars) -> Var vars

-- 1. Remove all references to the most recently bound variable
-- ...

-- 2. Add a reference to a variable in the middle of a scope - we'll need 
-- something like this later.
-- Note: The type here isn't quite right, you'll need to modify it slightly.
insertNameV1 : {outer : List Name} -> Var (outer ++ inner) -> Var (outer ++ n :: inner)
insertNameV1 {outer = []} (MkVar {  i = 0} First) = ?a1
insertNameV1 {outer = []} (MkVar {i = (S k)} p) = ?b1
insertNameV1 {outer = (y :: xs)} x = ?c1

insertNameV2 : {outer : List Name} -> Var (outer ++ inner) -> Var (outer ++ k :: inner)
insertNameV2 {outer = []} (MkVar {  i = 0} First) = ?a2
insertNameV2 {outer = []} (MkVar {i = (S j)} p) = ?b2
insertNameV2 {outer = (y :: xs)} x = ?c2
```

# Expected Behavior

`insertNameV1` and `insertNameV2` should have the same (kind of) goal for `?a1` and `?a2` holes. The only difference is the renaming of the implicit formal parameter `n => k` in the function type. The resulting holes are as follows

```
Holes

This buffer displays the unsolved holes from the currently-loaded code. Press
the [P] buttons to solve the holes interactively in the prover.

- + Main.a1 [P]
 `--       0 n : Name
       0 inner : List Name
     --------------------------------
      Main.a1 : Var (n :: (n :: ns))

- + Main.a2 [P]
 `--       0 k : Name
       0 inner : List Name
     --------------------------------
      Main.a2 : Var (k :: (n :: ns))
```

# Observed Behavior

In the case of `insertNameV1` the name `n` from `insertNameV1` declaration and the name `n` from `IsVar` definition get equated, resulting in different proof goals for `insertNameV1` and `insertNameV2`.

**Comment by gallais** [comment]
They're not the same but they are *printed* the same which is confusing.
This is what the issue #35 is about.

If you change the definition of `MkVar` to rename `n` to `var` then you
get the following & you can see that `var` is not mentioned in the
assumptions (because that is not something you have manually written
either in the type or on the LHS) but does appear in the conclusion:

```idris
Main> :t a1
 0 n : Name
 0 inner : List Name
------------------------------
a1 : Var (n :: (var :: ns))
Main> :t a2
 0 k : Name
 0 inner : List Name
------------------------------
a2 : Var (k :: (var :: ns))
Main> 
```

**Comment by radoye** [comment]
@gallais Thanks for the explanation. Let's close this then. 

To be clear: the only way to confirm something like this right now is to rename one of the variables and print, correct?

**Comment by gallais** [comment]
Yeah unfortunately.

In your specific case it is a bit easier to implement this function if you change
the definition of `Var` to also expose the `Name`:

```idris
data Var : Name -> List Name -> Type where
     MkVar : {i : Nat} -> (0 p : IsVar n i vars) -> Var n vars
```

And if you insist that `insertName` should be name preserving, you are forced to make
the problem unambiguous:

```idris
insertName : {outer : List Name} -> Var v (outer ++ inner) -> Var v (outer ++ n :: inner)
```

This is actually how it's done in Idris 2's implementation: we have both versions of
the `Var` wrapper (called `Var` and `NVar` respectively) and use the named `NVar` to
implement the weakening operations and do a bit of wrapping/unwrapping to get the `Var`
one from that safer one.
