### ISSUE TITLE
Make "where" clause optional in empty interface declarations

### ISSUE THREAD

**Issue by ornamentist** [idris-lang/Idris2#620]
In Idris 1 an "empty" interface has an optional "where" clause, i.e.

```idris
interface Something where
```
is equivalent to 

```idris
interface Something
```

In Idris 2 the "where" clause is always required for empty interfaces. Could the "where" be made optional on empty interfaces so we don't (visually) have a dangling where clause?

**Comment by gallais** [comment]
I don't think this is a good idea: such interfaces are declare-before-define
and thus start a mutual block that only ends when the definition actually
lands. This would make the whole rest of the file mutually-defined with the
empty interface.
