### ISSUE TITLE
Cannot prove equality between two definitionally equal terms

### ISSUE THREAD

**Issue by wenkokke** [idris-lang/Idris2#621]
# Steps to Reproduce

Load the following program with Idris2:
```idris
a1 : Char
a1 = 'a'

a2 : Char
a2 = 'a'

whyNot : a1 = a2
whyNot = Refl
```
# Expected Behavior

The terms `a1` and `a2` are definitionally equal, so I expect to be able to prove they are equal.

# Observed Behavior
```
1/1: Building crash (crash.idr)
crash.idr:8:10--8:14:While processing right hand side of whyNot at crash.idr:8:1--10:1:
When unifying a2 = a2 and a1 = a2
Mismatch between:
	a2
and
	a1
at:
8	whyNot = Refl
	         ^^^^
```

**Comment by gallais** [comment]
It's a scoping issue: when you write unapplied lowercase identifiers
in a type Idris assumes that you want them to be implicitly generalised
over.

If your module is called `Main` then writing

```idris
broken : Main.infinity1 = Main.infinity2
```

leads to a file that typechecks just fine.

**Comment by wenkokke** [comment]
Oh, that's very confusing.

**Comment by gallais** [comment]
I have a patch. It breaks the compilation of `base` because the type of elements
stored in the vector is called `elem` which is an existing function. :face_with_thermometer:

**Comment by ohad** [comment]
The problem with the proposed behaviour is that importing a module can (hypothetically, sorry) change behaviour.

There's the `%unbound_implicits on/off` pragma for that purpose.

**Comment by gallais** [comment]
I quite like the declare-before-use approach used in Agda for
implicitly generalised variables.

```idris
variable
  A B : Type
  f g : A -> B
  xs : List A

mapFusion : map g (map f xs) === map (g . f) xs
mapFusion = ?a
```

We could maybe explore a third mode of use for the `%unbound_implicits`
pragma: `declared`. It would only generalise over names explicitly
declared as generalisable in the file.

**Comment by gallais** [comment]
The decision made in #708 is to at least have warnings about shadowing.

**Comment by raffopazzo** [comment]
I hope I'm not bikeshedding here but wouldn't be more obvious to parameterise only on identifiers introduced via `forall`? So in the  code above you would write
```idris
mapFusion : forall f, g, xs . map g (map f xs) === map (g . f) xs
mapId : forall xs . map id xs === xs
```
This would of course immediately break existing code (both Idris1 and 2) but there could be a pragma to allow leaving out the `forall` which reinstates the current behaviour.

**Comment by ohad** [comment]
There is such a directive:
```idris
%unbound_implicits on/off
```

The reason we have unbound implicits is to help newcomers from languages that implicitly generalise over such variables (Haskell/OCaml).
