### ISSUE TITLE
Reflection out of sync with language

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#625]
https://github.com/idris-lang/Idris2/blob/b449e5ae8a25fbf7d558528038b885210c0572c8/src/TTImp/TTImp.idr#L198
https://github.com/idris-lang/Idris2/blob/5487290499e59e45c3af0290848a6286231bc501/libs/base/Language/Reflection/TTImp.idr#L100

This causes reflection to fail when using `ForeignFn`.

**Comment by gallais** [comment]
fixed by #646
