### ISSUE TITLE
Add enumFromTo

### ISSUE THREAD

**Issue by vmchale** [idris-lang/Idris2#629]
I used `enumFromTo` in [my code](https://github.com/vmchale/permutations/blob/master/Control/Permutation/Mod.idr#L128) in Idris 1 - I think it'd be a nice addition to the libraries!

Thanks!

**Comment by MarcelineVQ** [comment]
There's a Range interface in prelude providing the enum stuff you're used to by slightly a different name
That enum/range stuff is the underlying mechanism for list range syntax as well so you could have written `enumFromTo 0 (weaken $ natToFin m)` as `[0 .. weaken (natToFin m)]`

**Comment by gallais** [comment]
The functions have a different name but they are still here
under [the `Range` interface](https://github.com/idris-lang/Idris2/blob/master/libs/prelude/Prelude/Types.idr#L893).

**Comment by vmchale** [comment]
Ah, thanks!
