### ISSUE TITLE
one type annotation in let means all other definitions must have type annotation

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#63]
<a href="https://github.com/shmish111"><img src="https://avatars2.githubusercontent.com/u/934267?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shmish111](https://github.com/shmish111)**
_Sunday Apr 26, 2020 at 13:15 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/326_

----

If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce

Check
```
f : a -> b
f a' =
    let x : a
        x = a'
        y = 1
    in ?xyz

g : a -> b
g a' =
    let x : a
        x = a'
        y : Int
        y = 1
    in ?xyz
```

# Expected Behavior

Type checks fine

# Observed Behavior

```
Errors (1)
Test.idr:217:9
While processing right hand side of f at Test.idr:214:1--220:1:
No type declaration for Test.y
```

It can be 'fixed' by having a separate let block for things with type annotations and things without. If this is expected behaviour then:

1. I couldn't find any documentation about it
2. I found it very unintuitive. Indeed it took me a while to work out that I could have an additional block with the unannotated items

**Comment by edwinb** [comment]
<a href="https://github.com/gallais"><img src="https://avatars1.githubusercontent.com/u/1094905?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gallais](https://github.com/gallais)**
_Sunday Apr 26, 2020 at 17:48 GMT_

----

This bit of the parser is responsible: once we have seen `let` we commit to
either a block of let-binders or a block of local definitions. We could instead
allow interleavings of the two.
 https://github.com/edwinb/Idris2/blob/19426ecd141f93c34268a53ed09b5e48e64ba73b/src/Idris/Parser.idr#L553-L570

**Comment by edwinb** [comment]
<a href="https://github.com/edwinb"><img src="https://avatars1.githubusercontent.com/u/255926?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edwinb](https://github.com/edwinb)**
_Monday Apr 27, 2020 at 12:50 GMT_

----

I think it's reasonable to allow interleavings of the two different `let` forms.

**Comment by edwinb** [comment]
<a href="https://github.com/gallais"><img src="https://avatars1.githubusercontent.com/u/1094905?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gallais](https://github.com/gallais)**
_Monday Apr 27, 2020 at 17:30 GMT_

----

Fighting the type errors but I have good hope I'll have something soon.

**Comment by gallais** [comment]
Oooooh that's a spicy one:

```
 let baz : Z = S Z
     baz  with (pf 0)
      baz | (Left Refl) impossible
      baz | (Right pf') = pf'
 in baz
```

This getting parsed relied on the fact that after reading one type of let we
had committed to this style. So:

* `baz : Z = S Z` would commit to the let-binder style
* then fail to parse the rest
* backtrack and try to parse it as a topDecl
* succeed

With the new policy to allow interleaving

* `baz : Z = S Z` is parsed as a let-binder
* the rest is parsed as a local definition
* and then Idris can't make sense of the thing: `Z` is not a `Type` you silly!

I would argue that using the same symbol for propositional equality and
declaration is bad but I guess that would be such a breaking change that
there is no debating it. Not sure how to fix this.

**Comment by clayrat** [comment]
I guess by adding brackets: `bar : (Z = S Z)` and some heuristic that suggests doing this?

**Comment by gallais** [comment]
Following a related discussion on the mailing list, I have
noticed that the grammar is *already* ambiguous because of
the overloading for `(=)`. Both Idris 1 & Idris 2 parse the
following:

```idris
f : Nat
f = let p : 3 = 2 + 1 = Refl in 1
```

as

> let `p` be a local expression of type `3` and value `2 + 1 = Refl`

instead of

> let `p` be a local proof of type `3 = 2 + 1` and value `Refl`

Considering this is already the case, I have no qualm about simply
embracing the error shown above and forcing the user to use parentheses
to disambiguate the let-binding.

I will bring the PR up to speed and then merge it after a few days
unless someone complains.
