### ISSUE TITLE
Pattern-matching on lambdas can yield contradiction

### ISSUE THREAD

**Issue by ionathanch** [idris-lang/Idris2#633]
# Steps to Reproduce

```idris
%default total

test : (f : () -> Bool) -> f () = True
test (\() => True) = Refl

bad : False = True
bad = test (\() => False)
```

# Expected Behavior

This should not type check. At the very least, `test` should be marked as non-covering. I think generally, there's some issues with allowing pattern-matching on functions.

# Observed Behavior

This type checks perfectly.

**Comment by ziman** [comment]
```idris
g : Bool -> Bool
g (let x = False in x) = True
```
is also accepted as total and always evaluates to `True`

**Comment by KyleDavidE** [comment]
Two things of note about this bug

1. This checks, which I find very amusing
```
extentionality : (f : a -> b) -> (g: a -> b) -> ( (x: a) -> f x = g x ) -> f = g
extentionality f _ (\x => Refl) = Refl
```

2. Not only is this a proof of false, but the equality in bad computes
```
badCast : a -> b
badCast u = rewrite__impl (\x => if x then a else b) bad u
```

```
MOL> the String (badCast 10)
10 : String
```
