### ISSUE TITLE
Row of dependent pairs need too many parentheses

### ISSUE THREAD

**Issue by vfrinken** [idris-lang/Idris2#636]
Since 0.2.1, it is not possible to chain dependent pairs together without excessive parentheses around each pair. This not only breaks code that used to work, longer chains of dependent pairs become less readable

# Steps to Reproduce
```
this_used_to_work : (x:Nat ** y:Nat ** LTE x y)
```
# Expected Behavior
that this type checks without any problems

# Observed Behavior
```
Expected end of input (next tokens: [symbol **, identifier y, symbol :, identifier Nat, symbol **, identifier LTE, identifier x, identifier y, symbol ), end of input])
```
now, I have to write 
```
nowadays : (x:Nat ** (y:Nat ** LTE x y))
```

**Comment by Russoul** [comment]
Probably a regression after #533
