### ISSUE TITLE
Error: INTERNAL ERROR: $m is not a function application

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris2#649]
# Steps to Reproduce

```idris
test : Nat
test = let foo : (m, n : Nat) -> m === n -> Nat
           foo .m m Refl = Z
       in foo Z Z Refl
```

# Observed Behavior

```
1/1: Building letdot (letdot.idr)
Error: INTERNAL ERROR: $m is not a function application
Error(s) building file letdot.idr
```

**Comment by ziman** [comment]
The parser allows only the parenthesised form `foo .(m) m Refl = Z` for forced patterns. That's currently parsed as postfix application but #662 is a proposal to fix that.

**Comment by ziman** [comment]
I believe that this can be closed, given that we have [a test for it](https://github.com/idris-lang/Idris2/pull/662/files#diff-9342bf0e02a81ea3b2fa13bc7ac0faf7a19c60cacea0026510f8aaa559136195R80).
