### ISSUE TITLE
default interface methods are missing information they need to typecheck

### ISSUE THREAD

**Issue by MarcelineVQ** [idris-lang/Idris2#657]
# Steps to Reproduce
typecheck:
```idris
import Data.Buffer

export
data ForeignPtr : Type -> Type where
  MkFP : Buffer -> ForeignPtr a

public export
interface Storable a where
  size : Int

  peekByteOff : HasIO io => ForeignPtr a -> Int -> io a

  peekElemOff : HasIO io => ForeignPtr a -> Int -> io a
  peekElemOff fp off = peekByteOff fp (off * size {a})

Storable Bits8 where
  size = 8
  peekByteOff (MkFP b) off = getBits8 b off
```
# Expected Behavior
No issues
# Observed Behavior
I'd like to have a value in the interface that can be referred to by both user-made and default implementations but as it stands I'm unable to figure out how to achieve this for default ones.
The given codes causes:
```
Error(s) building file src/Foo.idr: While processing right hand side of peekElemOff. Undefined name a. 
src/Foo.idr:16:1--19:1
 16 | Storable Bits8 where
 17 |   size = 8
 18 |   peekByteOff (MkFP b) off = getBits8 b off
```
If we instead remove `{a}` from peekElemOff's `size {a}` thinking that `a` can be inferred from the types at hand we get:
```
Error(s) building file src/Foo.idr: While processing right hand side of {Default implementation of peekElemOff:0}.
Can't find an implementation for Storable ?a.
```
Changing `peekElemOff`'s type to `peekElemOff : Storable a => HasIO io => ForeignPtr a -> Int -> io a`, which I wouldn't have expected to work anyway, gives us:
```
Error(s) building file src/Foo.idr: While processing right hand side of {Default implementation of peekElemOff:0}.
Multiple solutions found in search of:
    Storable a
```
Which is kind of interesting because between the last two errors we go from "Can't find implementation" to 'Multiple solutions", though I think this last error isn't really important since writing `Storable a => ...` inside the `Storable a` interface is a little silly.

**Comment by gallais** [comment]
I was going to suggest `interface Storable a size | a where` but I could not
find a way to index the interface by something available at runtime (which
is strange because you can totally declare implementations relying on some
of the arguments being available at runtime).

One thing that works is making the type `size : ForeignPtr a -> Int`. I am
using `ForeignPtr` because it's conveniently sitting here but any type
constructor that can act as a proxy for `a` would do.

```idris
module Storable

import Data.Buffer

export
data ForeignPtr : Type -> Type where
  MkFP : Buffer -> ForeignPtr a

public export
interface Storable a where

  size : ForeignPtr a -> Int

  peekByteOff : HasIO io => ForeignPtr a -> Int -> io a

  peekElemOff : HasIO io => ForeignPtr a -> Int -> io a
  peekElemOff fp off = peekByteOff fp (off * size fp)

Storable Bits8 where

  size _ = 8
  peekByteOff (MkFP b) off = getBits8 b off
```

**Comment by MarcelineVQ** [comment]
Thanks @gallais, using `ForeignPtr a` as a proxy does get around this so I'll use that for now.
Interestingly using a literal Proxy leads to the same error of inference getting lost on {a},
```idris
data Proxy a = MkProxy
...
interface Storable a where
  size : Proxy a -> Int
  ...
  peekElemOff : HasIO io => ForeignPtr a -> Int -> io a
  peekElemOff fp off = peekByteOff fp (off * size MkProxy)
or
  peekElemOff fp off = peekByteOff fp (off * size {a} MkProxy)
```
possibly since `Proxy a` doesn't appear in `  peekElemOff : HasIO io => ForeignPtr a -> Int -> io a` like `ForeignPtr a` does.

**Comment by gallais** [comment]
> Interestingly using a literal Proxy leads to the same error of inference getting lost on {a},

:scream: 

I have tried `the (Proxy a) MkProxy` and get a similar problem.

My hunch is that it's the same problem: we substitute `Bits8` for `a`
in the type but not in the default term.

**Comment by gallais** [comment]
As you can see in the commit above, I have gotten interface parameters to be
available in the body and usable in the default values (if declared with an
unlimited quantity).

The next step is to fix the elaboration process of the implementations so that
we may actually instantiate these interfaces! But that won't happen tonight.

**Comment by gallais** [comment]
All of the examples in this issue are now working on my machine. :blush:
