### ISSUE TITLE
Type inference breaks on linear functions

### ISSUE THREAD

**Issue by KyleDavidE** [idris-lang/Idris2#670]
# Steps to Reproduce

```idris
the (((1 _: Nat) -> Nat) -> ((1 _: Nat) -> Nat)) id
```

# Expected Behavior

The expression type checks

# Observed Behavior

```idris
Error: When unifying (1 _ : (Nat -> Nat)) -> Nat -> Nat and ((1 _ : Nat) -> Nat) -> (1 _ : Nat) -> Nat.
Mismatch between: Nat -> Nat and (1 _ : Nat) -> Nat.

(interactive):1:50--1:52
   |
 1 | the (((1 _: Nat) -> Nat) -> ((1 _: Nat) -> Nat)) id
   |                                                  ^^
```

If I explicitly provide the type argument to id, it works. Note that fully applying id does not help.

**Comment by JoeyEremondi** [comment]
It also gives an error for `the ((1 _ : (1 _: Nat) -> Nat) -> (1 _: Nat) -> Nat) id`, i.e. even when we account for the fact that `id` is linear in its argument. 

The problem seems to be that the compiler forgets the linearity annotation when doing the unification. `the ((1 _ : (1 _: Nat) -> Nat) -> Nat -> Nat) id ` works, when it shouldn't.

**Comment by KyleDavidE** [comment]
Linearity subtyping seems to be a continual source of issues, I just checked and on the latest master and #73 still happens.

With linearity subtyping I think the example you gave should actually work, specifically notice that `the ((1 _ : (1 _: Nat) -> Nat) -> Nat -> Nat) (id {a=(1 _:Nat)->Nat})` still type checks, even though no inference is happening.

**Comment by KyleDavidE** [comment]
Also note that

```
foo : {0 p : Type -> Type} -> p ( (1 _: Nat) -> Nat ) -> p (Nat -> Nat)
foo = id
```

Type checks even though it absolutely shouldn't (instantiate p at anything that is negative on it's arguments).

But that is starting to bleed into the issues of #73

**Comment by MarcelineVQ** [comment]
dunno if it's relevant directly but linking https://github.com/idris-lang/Idris2/issues/189 just in case

**Comment by mb64** [comment]
#879 fixed this.

**Comment by gallais** [comment]
Indeed it has!
