### ISSUE TITLE
Issue with hints and search space: Can't find implementation

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#69]
<a href="https://github.com/wurmli"><img src="https://avatars2.githubusercontent.com/u/38258731?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wurmli](https://github.com/wurmli)**
_Thursday Apr 30, 2020 at 19:31 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/344_

----

This issue is related e.g. to #319, #330 and others referring to interfaces and the use of dependent types.
```
module QTTTrials

data Tbl : (n : Nat) -> Type where
  [noHints]
  Value : (k : Nat) -> (value : String) -> Tbl k

%hint
valueZero : Tbl 0
valueZero = Value 0 "zero"

%hint
valueOne : Tbl 1
valueOne = Value 1 "one"

showValue : {m : Nat} -> Tbl m => (m : Nat) -> String
showValue @{Value k value} k = value
```
# Steps to Reproduce
```
QTTTrials> :r
1/1: Building QTTTrials (QTTTrials.idr)
Loaded file QTTTrials.idr
QTTTrials> showValue Z
(interactive):1:1--1:12:Can't find an implementation for Tbl ?m
```
# Expected Behavior
I would expect that the unique values of type "Tbl 0" or "Tbl 1" are found.
# Observed Behavior
The values are not found, and even though it seems that as a search space the family of types Tbl m is taken, the two values valueOne and valueTwo are missed.

**Comment by edwinb** [comment]
This is correct behaviour, because it doesn't know what `m` to look for so won't even start the search. If you give `m` expicitly as either `0` or `1`, it works:

    Main> showValue {m=1} Z
    "one"
    Main> showValue {m=0} Z
    "zero"

I notice you have two arguments called `m`, so perhaps what you meant for the type is:

    showValue : (m : Nat) -> Tbl m => String

Then you get:

    Main> showValue Z
    "zero"
    Main> showValue 1
    "one"

I'll close this since it's expected behaviour.

**Comment by gallais** [comment]
I guess the program @wurmli wanted to write is:

```
showValue : (m : Nat) -> Tbl m => String
showValue k @{Value k value} = value
```
