### ISSUE TITLE
JavaScript Backend: Erroneous Show instance for Bool

### ISSUE THREAD

**Issue by stefan-hoeck** [idris-lang/Idris2#698]
# Steps to Reproduce
```idris
module Err

%foreign "javascript:lambda:(x,y)=> x >= y"
greaterThan : Int -> Int -> Bool

main : IO ()
main = printLn $ 1 `greaterThan` 2

```
# Expected Behavior

Building and running with Node should print 'False'.

# Observed Behavior

Building and running with Node results in an error:

Error: unhandled const case on Prelude/Show.idr:182:6--182:10

# Additional Info

The generated JS file contains the following Show implementation for Bool:

```javascript
function Prelude_Show_show$5fShow$5f$5fBool(arg_0){//Prelude/Show.idr:181:1--186:1
 switch(arg_0){
  case 0n: {
   return 'True';
   break; }
  case 1n: {
   return 'False';
   break; }
  default:
   throw new Error('unhandled const case on Prelude/Show.idr:182:6--182:10');
 }
}
```

Changing the above as follows resolves the issue:

```javascript
function Prelude_Show_show$5fShow$5f$5fBool(arg_0){//Prelude/Show.idr:181:1--186:1
 switch(arg_0){
  case true: {
   return 'True';
   break; }
   case false: {
   return 'False';
   break; }
  default:
   throw new Error('unhandled const case on Prelude/Show.idr:182:6--182:10');
 }
}
```

**Comment by stefan-hoeck** [comment]
I just realized that 'Bool' is not a supported FFI primitive. So I guess I'll have to do the conversion from the foreign Boolean myself, right? If that's the case, please excuse the noise.

**Comment by gallais** [comment]
Booleans are represented by their constructor tag. Cf.

https://github.com/idris-lang/Idris2/blob/cc31076849feb683f0da12f38706434ff1abf032/src/Compiler/CompileExpr.idr#L226-L227

**Comment by stefan-hoeck** [comment]
But in the generated JS output (see Show implementation in my original post) the Bools seem to be represented by BigInt literals. Since they are not directly mapped to the backend's builtin Booleans, shouldn't it be a type error to use them directly in a foreign function call?

I just quickly checked with some other hand-written ADT: It is accepted as the return type of a foreign function call (the following compiles just fine).

```idris
data MyThing = Yes | No String

private %foreign "javascript:lambda:()=> '' "
prim__foo : AnyPtr -> MyThing
```

So my question now is: Should it be a type error to use types other than the primitives or AnyPtr in a foreign function signature?

**Comment by gallais** [comment]
I'll close this one as #946 has a better name for the same problem.
