### ISSUE TITLE
Shadowing a top-level declaration should raise a warning or error.

### ISSUE THREAD

**Issue by lodi** [idris-lang/Idris2#704]
I ran into a confusing situation today:

```idris
%default total

fortyTwo : BitVector 5 Bit
fortyTwo = ...

toNat : BitVector n ty -> Nat
toNat bv = go bv 0
  where
    go : BitVector m ty -> Nat -> Nat
    go bv acc = ...

fortyTwoIs42 : toNat fortyTwo = 42
fortyTwoIs42 = ?rhs -- rhs : go ty n fortyTwo fortyTwo 0 = 42
```

I couldn't figure out why `toNat fortyTwo` wouldn't reduce.  I did notice that at the `?rhs` hole Idris suspiciously gave me `fortyTwo : BitVector n ty` instead of the expected `fortyTwo : BitVector 5 Bit`.  Eventually I realized that the `fortyTwo` in `toNat fortyTwo` was a fresh variable shadowing the top-level term.  The fix was to capitalize the top level term.

```idris
FortyTwo : BitVector 5 Bit
FortyTwo = ...

fortyTwoIs42 : toNat FortyTwo = 42
fortyTwoIs42 = ?rhs -- rhs : 42 = 42
```

---

Should variables be allowed to shadow other in-scope names?

**Comment by gallais** [comment]
This is a common issue. Cf. #621 for instance.

**Comment by Russoul** [comment]
@gallais How viable would it be to generalize over free variables only ? I.e global declarations, local declarations and local let bindings in scope prevent generalization if there is a name clash. 

I know how to fix this (probably) but that would require a change in the desugaring process, I think.

**Comment by gallais** [comment]
I was planning to have a look at it today. This report pushed me over the
edge of deciding to change the behaviour of this feature which is a real
trap for newcomers.

**Comment by lodi** [comment]
@Russoul, now that I think about it, generalizing only over free variables would fix this issue and #621 but cause another problem: if you add a short function with a common name--like `len` or `data--to the bottom of a long module, you risk introducing some weird type errors at the top of the module.  Or more surprisingly, things might typecheck but just start giving incorrect results.  That kind of non-locality is probably even more surprising.

I think it should just be a hard error to have a name that shadows another name, or to introduce a name that causes something else to shadow it.

**Comment by Russoul** [comment]
That's true, though a chance that a newly inserted name will be compatible with the old one (typechecker accepts it) is negligible.  Also, even with the current state of things this can happen to you:
```idris
name1 : ...
name2 : ...
...
nameJ : ...
...
nameK : ...
nameK = ... nameJ ...
...
```
If you were to insert another `nameJ` between `nameJ` and `nameK`, you'd get the same problem.
The order matters.

But at least warning users that they are about to shadow a global name would drastically help. Or even promote it to be a fatal error. 
It would be a great use for `%hide` and motivation to be thoughtful about how we name stuff.

**Comment by gallais** [comment]
The progress on this is tracked in #621 so I'll close this.
