### ISSUE TITLE
Unification error while trying to (pair-wise) add dependent pairs of Vects of IntS

### ISSUE THREAD

**Issue by timmyjose** [idris-lang/Idris2#706]
Summary: Trying to add (pair-wise) two dependent pairs of equal length, getting unification error.

# Steps to Reproduce

The full source is:

```
module AddNumVects

import Data.Vect

%default total

partial
readVect : HasIO io => io (n : Nat ** Vect n Int)
readVect = do x <- getLine
              if x == ""
                 then pure $ (_ ** [])
                 else do (_ ** ns) <- readVect
                         pure $ (_ ** (cast x :: ns))

addVectsBad : { n : Nat } -> (n ** Vect n Int) -> (n ** Vect n Int) -> (n ** Vect n Int)
addVectsBad (_ ** xs) (_ ** ys) = (_ ** zipWith (+) xs ys)

```
In particular, the `addVectsBad` function.

# Expected Behavior

I am able to pair-wise add dependent pairs of `Int`S of the same length together.

# Observed Behavior

```
AddNumVects> :r
1/1: Building AddNumVects (AddNumVects.idr)
Error: While processing right hand side of addVectsBad. When unifying Vect _ Int and Vect _ Int.
Mismatch between: _ (implicitly bound at AddNumVects.idr:21:1--21:59) and _ (implicitly bound at AddNumVects.idr:21:1--21:59).

AddNumVects.idr:21:56--21:58
    |
 21 | addVectsBad (_ ** xs) (_ ** ys) = (_ ** zipWith (+) xs ys)
    |                                                        ^^

Error(s) building file AddNumVects.idr
```

Note: I tried it will all combinations of the variables - implicit, explicit et al, that I could think of, but could not make it work. I would expect that I should be able to use `readVect` to read in vectors, validate their lengths, and then invoke this function with dependent pairs of `Vect`S of `Int`S of the same length.

**Comment by MarcelineVQ** [comment]
Some relevant minimal snippets, seeming to hint that DPair in particular is at issue:
```idris
-- case on n doesn't refine y
foo1 : {n : Nat} -> (n ** Vect n Int) -> ()
foo1 {n} (y ** z) = ?foo1_rhs

-- The above after casing `n`
-- this should be an error complaining that y unifies with Z and with S k
-- but it is instead accepted
foo1' : {n : Nat} -> (n ** Vect n Int) -> ()
foo1' {n = 0} (y ** z) = ?foo1'_rhs_1
foo1' {n = (S k)} (y ** z) = ?foo1'_rhs_2

-- probably related symptom:
-- This doesn't infer that n is Nat
-- case on n gives: Can't split on n (Can't find type of n in LHS)
-- and the hole has both `n : _` and `x : (n : Nat ** Vect n Int)`
foo2 : {n : _} -> (n ** Vect n Int) -> ();
foo2 {n} x = ?foo2_rhs

-- This will case on n just fine as you'd expect.
foo3 : {n : _} -> Vect n Int -> ();
foo3 {n} x = ?foo3_rhs
```

**Comment by gallais** [comment]
> Summary: Trying to add (pair-wise) two dependent pairs of equal length, getting unification error.
> `addVectsBad : { n : Nat } -> (n ** Vect n Int) -> (n ** Vect n Int) -> (n ** Vect n Int)`

They do not have the same length. That last type is equivalent to:

```idris
addVectsBad : { n0 : Nat } -> (n1 ** Vect n1 Int) -> (n2 ** Vect n2 Int) -> (n3 ** Vect n3 Int)
```

What you are looking for is:

```idris
addVectsGood : { n : Nat } -> Vect n Int -> Vect n Int -> Vect n Int
```

**Comment by MarcelineVQ** [comment]
Ah is this is why there's 2 n's in the hole for `foo2 : {n : _} -> (n ** Vect n Int) -> ()` ? The `n` of `(n ** Vect n Int)` is a new binder that shadows `{n : _}`?

**Comment by timmyjose** [comment]
> > Summary: Trying to add (pair-wise) two dependent pairs of equal length, getting unification error.
> > `addVectsBad : { n : Nat } -> (n ** Vect n Int) -> (n ** Vect n Int) -> (n ** Vect n Int)`
> 
> They do not have the same length. That last type is equivalent to:
> 
> ```idris
> addVectsBad : {n0 : Nat} ->
>               (n1 : Nat ** Vect n1 Int) ->
>               (n2 : Nat ** Vect n2 Int) ->
>               (n3 : Nat ** Vect n3 Int)
> ```

That's what I sort of suspected.

> What you are looking for is:
> 
> ```idris
> addVectsGood : {n : Nat} -> Vect n Int -> Vect n Int -> Vect n Int
> ```

Does this mean that we cannot have a function that adds dependent pairs together by specifying the same length for both dependent pairs (of vectS of IntS)? I would appreciate it if there is some elaboration! I'm trying to wrap my head around whether this is possible/not possible/or the wrong thing to expect. Thanks!

I will close the issue, but the discussion can continue!

**Comment by timmyjose** [comment]
> Ah is this is why there's 2 n's in the hole for `foo2 : {n : _} -> (n ** Vect n Int) -> ()` ?
> The `n` of `(n ** Vect n Int)` is a new binder that shadows the outer `{n : _}` within the scope of `(n ** Vect n Int)`?

Thanks again for your help, MarcelineVQ. You've been of great help not just this time, but quite a few times in the past as well. Really appreciate it! :-)

**Comment by gallais** [comment]
> Does this mean that we cannot have a function that adds dependent pairs together by specifying the same length for both dependent pairs (of vectS of IntS)?

You could write something like this:

```idris
addVectsWeird : (v, w : (n : Nat ** Vect n Int)) -> fst v === fst w -> Vect (fst v) Int
```

But that's not very idiomatic. The idiomatic thing is to take the two dependent pairs apart,
compare the nats for equality and, in the case where they do match up, use the function that
works on `Vect`s of the same lenght.

**Comment by timmyjose** [comment]
> > Does this mean that we cannot have a function that adds dependent pairs together by specifying the same length for both dependent pairs (of vectS of IntS)?
> 
> You could write something like this:
> 
> ```idris
> addVectsWeird : (v, w : (n : Nat ** Vect n Int)) -> fst v === fst w -> Vect (fst v) Int
> ```
> 
> But that's not very idiomatic. The idiomatic thing is to take the two dependent pairs apart,
> compare the nats for equality and, in the case where they do match up, use the function that
> works on `Vect`s of the same lenght.

Okay, that makes sense. Thank you for the explanation and rationale! Cheers.
