### ISSUE TITLE
Namespace name starting with lowercase letter doesn't work

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#710]
# Steps to Reproduce

The following code doesn't work:
```
namespace a
  export
  tf : Int -> Int -> Int
  tf x y = x + y

namespace b
  export
  tf : Int -> Int -> Int
  tf x y = x + y

t2 : Int
t2 = a.tf 1 2
```

Changing the namespace names to A,B fixes the problem:

```
namespace A
  export
  tf : Int -> Int -> Int
  tf x y = x + y

namespace B
  export
  tf : Int -> Int -> Int
  tf x y = x + y

t2 : Int
t2 = A.tf 1 2
```

# Expected Behavior

Namespaces names a,b work correctly for Idris 1

**Comment by gallais** [comment]
Namespaces are expected to start with an uppercase letter.
The fact the file even parses is surprising to me.

I am afraid we cannot revert to Idris1's behaviour as that
would be wildly incompatible with postfix projections.

**Comment by ziman** [comment]
Namely, if we allowed lowercase namespaces, then we would have a syntactic ambiguity: `a.foo` could mean "field `foo` from record `a`" or "identifier `foo` from namespace `a`". Currently, we solve this by a lexing hack: `a.foo` is always a record field and `A.foo` is always a namespaced identifier.
