### ISSUE TITLE
Parsing of comment --}

### ISSUE THREAD

**Issue by MilanKral** [idris-lang/Idris2#711]
# Steps to Reproduce

```
--}

i : Int
i = 100
```

The first line is not parsed as a comment in Idris 2.

# Expected Behavior

Idris 1 parses the file correctly.

# Observed Behavior

**Comment by gallais** [comment]
If `--}` is considered a valid one-line comment then it cannot be a valid closing
token for a multiline comment if we want things to nest properly. This means that

```idris
{-----------------------------------
This is not a valid comment anymore
-----------------------------------}
```

I think the current parser is working as expected.

**Comment by MilanKral** [comment]
I would then recommend to clarify this behaviour in Idris 2 documentation.

**Comment by gallais** [comment]
This is a duplicate of #472
