### ISSUE TITLE
Nat not optimized anymore

### ISSUE THREAD

**Issue by hedoquest** [idris-lang/Idris2#724]
The following program:

module Main 
fact : Nat → Nat                                                                            
fact 0 = 1                                                                                  
fact (S k) = (S k) * (fact k)                                                               

main : IO ()                                                                                
main = putStrLn $ show $ fact 1000   

terminates immediately in idris2 version 0.2.1 but does not in the current master version.

**Comment by gallais** [comment]
Seems to be because of #638

**Comment by gallais** [comment]
Thanks a lot for the bug report!
Hopefully that's the last of the bugs I introduced in that PR from hell! :scream:
