### ISSUE TITLE
No type-error for bogus implicit arguments matched as holes

### ISSUE THREAD

**Issue by ohad** [idris-lang/Idris2#728]
# Steps to Reproduce
```idris
f : Bool -> Bool
f (True {q = _}) = False
f _ = True
```
# Expected Behavior

Type error, since `q` isn't an implicit argument in `Bool`.

# Observed Behavior

Typechecks fine.

**Comment by Russoul** [comment]
I've already opened one today :) #725

**Comment by ohad** [comment]
Sorry! Thanks!
Did the #605 fix this one too?

**Comment by Russoul** [comment]
Yeap
