### ISSUE TITLE
Pattern matching on interface fails

### ISSUE THREAD

**Issue by Po227** [idris-lang/Idris2#735]
# Steps to Reproduce
```Idris
module Test

interface A a where
interface B a where
interface C a where
interface D a where

test : (kind : Type -> Type) -> Maybe Nat
test A = Just 1
test B = Just 2
test C = Just 3
test _ = Nothing

main : IO ()
main = putStrLn $
  (show $ test A) ++
  (show $ test B) ++
  (show $ test C) ++
  (show $ test D)

```
# Expected Behavior
Program should output `Just 1Just 2Just 3Nothing` when executed.
# Observed Behavior
Output `NothingNothingNothingNothing`.

It, however, reduces to correct normal form in REPL, in REPL `main` evals to `MkIO (prim__putStr "Just 1Just 2Just 3Nothing")`.

**Comment by gallais** [comment]
Cleaned up the output a bit:

```idris
module Issue735
 
interface A a where
interface B a where
interface C a where
interface D a where
 
test : (kind : Type -> Type) -> Maybe Nat
test A = Just 1
test B = Just 2
test C = Just 3
test _ = Nothing
 
strs : List String
strs = map (show . test) [ A, B, C, D]
 
main : IO ()
main = ignore $ traverse putStrLn strs
```

I get the same issue. Additionally `:exec main` in the REPL gives me a nasty-looking error:

> Exception in vector-ref: #<procedure at _tmpchez.ss:10779> is not a vector

**Comment by gallais** [comment]
Right, so when we replace the interfaces by `data Data = A | B | C | D`, we get sensibly
the same `case`-based scheme code for `test` except that each constructor is represented
by a unique integer (`A` is `0`, `B` is `1`, etc.) whereas the type constructors were
represented by strings (`A` is `"Issue375.A"`, etc.).

`strs` is also quite different: in the data-based one we have unary vectors containing
a tag corresponding to the constructors with no payloads whereas in the interface-based
one we have nullary unary vectors containing the *eta-expanded* type constructors
(probably the source of the "not a vector error"!).

```scheme
(define Issue735dash2-test (lambda (arg-0)
    (let ((sc0 arg-0))
         (case (vector-ref sc0 0)
             ((0) (vector 1 (+ 1 0)))
             ((1) (vector 1 (+ 1 (+ 1 0))))
             ((2) (vector 1 (+ 1 (+ 1 (+ 1 0)))))
             (else (vector 0 ))))))

;; (...)
;; somewhere in (define strs):
   (vector 1 (vector 0 ) -- cons A
   (vector 1 (vector 1 ) -- cons B
   (vector 1 (vector 2 ) -- cons C
   (vector 1 (vector 3 ) -- cons D
   (vector 0 ))))))))    -- nil
```

vs.

```scheme
(define Issue735-test (lambda (arg-0)
    (let ((sc0 arg-0))
         (case (vector-ref sc0 0)
             (("Issue735.A") (vector 1 (+ 1 0)))
             (("Issue735.B") (vector 1 (+ 1 (+ 1 0))))
             (("Issue735.C") (vector 1 (+ 1 (+ 1 (+ 1 0)))))
             (else (vector 0 ))))))

;; (...)
;; somewhere in (define strs):
   (vector 1 (lambda (eta-0) (vector "Issue735.A" eta-0)) -- cons (\x. A x)
   (vector 1 (lambda (eta-0) (vector "Issue735.B" eta-0)) -- cons (\x. B x)
   (vector 1 (lambda (eta-0) (vector "Issue735.C" eta-0)) -- cons (\x. C x)
   (vector 1 (lambda (eta-0) (vector "Issue735.D" eta-0)) -- cons (\x. D x)
   (vector 0 ))))))))                                     -- nil
```

Is the solution to simply eta-contract these things?

**Comment by gallais** [comment]
I haven't checked but wouldn't be surprised if this affects more than just the scheme backend.

**Comment by gallais** [comment]
@ziman observes that we are not allowed to match on unsaturated constructors
so the solution is probably to not allow matches on unsaturated type constructors
making the code in the original issue illegal.

```idris
isCons : (a -> List a -> List a) -> Bool
isCons (::) = True
isCons _ = False
```

fails to check with:

```idris
1/1: Building Cons (Cons.idr)
Error: Constructor Prelude.Types.:: is not fully applied.

Cons.idr:2:8--2:12
   |
 2 | isCons (::) = True
   |        ^^^^

Error(s) building file Cons.idr
```
