### ISSUE TITLE
Path handling for immutable installations

### ISSUE THREAD

**Issue by timsueberkrueb** [idris-lang/Idris2#737]
Currently, Idris 2 assumes an installation in a mutable location (e.g. `~/.idris2`). Some package managers enforce immutable installations. In fact, the [snap](https://github.com/timsueberkrueb/idris2-snap) and [nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/idris2/default.nix) packages for Idris 2 currently use some workarounds, e.g. to enable user-installation of packages (see https://github.com/timsueberkrueb/idris2-snap/issues/2). This issue is mainly motivated by my experience with the snap package, but it looks like the nix package has similar issues (CC @wchresta).

There are two main issues that the snap package currently works around (compare [src/launcher.sh](https://github.com/timsueberkrueb/idris2-snap/blob/master/src/launcher.sh.in)):

**1. Code generation**

Generated Chez code starts with a shebang pointing to the Chez scheme interpreter. This limits portability, and - without workarounds - would also break with each update of the snap package: For convenience, the snap package bundles a Chez scheme interpreter. Snap applications live in `/snap/idris2/<revision number>`, where `<revision number>` is an integer. `/snap/idris2/current` is a symlink to the current version.
By default, the generated scheme shebang points to the explicit chez location (e.g. `/snap/idris2/118/bin/chez`). As a workaround, the snap package explicitly overrides `SNAP` such that the shebang points to the `current` symlink rather than to the current explicit revision number. This works locally but is not portable (e.g. when a user would switch between a snap and a classical Idris 2 installation or between different scheme installations).

**2. User library installation**

User libraries cannot be installed to the immutable package store. However, the standard libraries are installed with the rest of the package in an immutable location. The snap package overrides various environment variables to both make Idris 2 find the standard libraries (setting `IDRIS2_PATH`) but also to enable user installation of libraries (setting `IDRIS2_PREFIX` to `~/.idris2`). Still, `idris2 --prefix` points to an invalid build-time location (`/build/idris2/parts/idris2/install`). Also, Idris' behavior is different when setting `IDRIS2_PATH`. For example, when adding `contrib` to `IDRIS2_PATH`, `contrib` gets loaded irrespective of whether or not Idris 2 is run with `-p contrib`

**Solution for the 1. issue?**

I don't know how to properly fix the first issue. I assume that chez creates this shebang - so there is probably not much Idris can do about it (?).

**Proposed solution for the 2. issue**

I think one possible solution would be for Idris 2 to support two different prefix paths:
* `IDRIS2_PREFIX` (`idris2 --prefix`): Installation prefix (e.g. `/snap/idris2/current/idris2-0.2.1/`) which is the root of the potentially readonly installation.
* `IDRIS2_USER_PREFIX` or `IDRIS2_LIBDIR` (`idris2 --libdir`): User library prefix (e.g. `~/.idris2` or `~/.idris2/idris2-0.2.1`) where Idris 2 would also install user libraries to.

By default, `IDRIS2_USER_PREFIX`/`IDRIS2_LIBDIR` could be the same as `IDRIS2_PREFIX` but packages or users could override these paths as needed. Would it be possible to configure those paths at build time?

**Alternatively** there could be another environment variable (e.g. `IDRIS2_LIB_DIRS`) similar to `IDRIS2_PATH` which allows adding arbitrary library installation paths that Idris would *scan* for libraries (rather than library locations that get loaded directly as with `IDRIS2_PATH`). The snap package could then add the immutable standard library to this path list while `IDRIS2_PREFIX` would remain `~/.idris2`.

---

I may be missing something or there may be better ways to deal with it - please let me know what you think :)

**Comment by ejconlon** [comment]
Thank you for filing this,  @timsueberkrueb . I am trying to work out how to avoid global package installations and clearly Idris2 needs some way of configuring an additional `libdir` for user package installation and resolution. In Idris1, you could override this with an environment variable, but it doesn't seem to work the same in Idris2 (and there seems to be more stuff in the libdir).

I would prefer having a `IDRIS2_INSTALL_DIR` environment variable and an `--install-dir` option. If not set, it would default to `idris2 --libdir`. Idris would install packages to this directory, and would also try to resolve them first from this directory, falling back to the global libdir.

**Comment by gallais** [comment]
I believe this is what #1078 is about.

**Comment by ejconlon** [comment]
@gallais Thanks for the reference. I commented on the PR as I think it's still missing part that allows you to configure how Idris resolves libraries.

**Comment by ejconlon** [comment]
Looks like `IDRIS2_PATH` works for resolving installed libraries.

**Comment by Qeenon** [comment]
I've rebased PR for this issue again https://github.com/idris-lang/Idris2/pull/1123
Please review if you will have time

**Comment by timsueberkrueb** [comment]
I think #1123 looks good and I think it makes sense to go ahead and merge it :+1:.

Unfortunately though, If I understand it correctly, it doesn't fix this particular issue (at least for the snap package). That is, it won't change the fact that `idris2 --prefix` might point to an invalid location at runtime. It also doesn't address the problem w.r.t. to library loading.

The problem is that it's not guaranteed where *classic* snap packages are located at runtime:

* `/snap/<name>/current/` (most commonly, e.g. on Ubuntu)
* `/var/lib/snapd/<name>/current` (on some other distros)
* `/snap/<name>_<variant>/current/` or `/var/lib/snapd/<name_variant>/current` (parallel installs feature)

This is fairly annoying, because it essentially requires the software to be relocatable. Note that this only applies to classic, i.e. unconfined snap packages like Idris. For strictly confined snaps, `snapd` uses mount namespaces to guarantee the program will always find itself under `/snap/<name>/current`. Also see [this forum thread](https://forum.snapcraft.io/t/guarantees-regarding-snap-appname-current/22397).

Again, I'm not criticizing #1123, it just addresses a different problem.

**Comment by timsueberkrueb** [comment]
This has been mostly resolved; only part missing is that `idris2 --prefix` should respect the `IDRIS2_PREFIX` environment variable if that's set.

**Comment by attila-lendvai** [comment]
i wanted to rework the build process, and the lack of proper control over the installation destination is a showstopper to me, too.

what i want to achieve is to have:
- `build/stage0`: a complete build using a bootstrap idris binary
- `build/stage1`: a complete build using `build/stage0`
- `build/stage2`: a complete build using `build/stage1` that can be recursively compared to stage1, which should yield no differences.
