### ISSUE TITLE
Unsaturated constructors are rejected in forced patterns

### ISSUE THREAD

**Issue by ziman** [idris-lang/Idris2#762]
# Steps to Reproduce

```idris
data Singleton : {a : Type} -> a -> Type where
  Val : (x : a) -> Singleton x

-- data constructors
f : Singleton (MkPair True) -> Bool
f (Val _) = True

-- type constructors
g : Singleton Maybe -> Bool
g (Val _) = True
```

# Expected Behavior

The program typechecks successfully.

# Observed Behavior

```
Error: Constructor Builtin.MkPair is not fully applied.

up.idr:4:16--4:27
   |
 4 | f : Singleton (MkPair True) -> Bool
   |                ^^^^^^^^^^^


[... an equivalent error message for g ...]
```

The data constructor (`MkPair`) is rejected even on an older `master` checkout of Idris2, `14d0141ca237ec4c548fa574dcfd335987eba754`, and probably quite far in the history, too.

The type constructor (`Maybe`) is rejected, too, as reported by @jfdm. My installed version, `14d0141`, does _not_ reject the `Maybe` constructor, which is is consistent with #735 adding the saturation check for type constructors.

My guess is that the reason for this error is that saturation is checked even on patterns that are forced. Since we do not match on forced patterns, these should not be checked for saturation.

**Comment by ziman** [comment]
Actually, even if the pattern is not forced, but isn't matched, it should not be checked, I think.

**Comment by gallais** [comment]
I've mentioned it a few times on the slack channel but never got around to
opening an issue. Minimal test case

```idris
data IsS : (Nat -> Nat) -> Type where
  Indeed : {s : Nat -> Nat} -> s === S -> IsS s
 
indeed : IsS S -> Nat
indeed (Indeed _) = Z
```

My understanding is that Idris can't differentiate between patterns on the LHS
that were user written vs. things that are pattern-looking but are just showing
up because the type you are matching on has some of its parameters instantiated.

> The type constructor (Maybe) is rejected, too, as reported by @jfdm.
> My installed version, 14d0141, does not reject the Maybe constructor,

That is because of the fix for #735 where I made sure we were *not* allowing
pattern-matching on unsaturated type constructors. The fix itself is very small:

https://github.com/idris-lang/Idris2/commit/14d0141ca237ec4c548fa574dcfd335987eba754#diff-74cc3ac87a3191802091e9e33b045a4cabbbe2d851632f04c5b5fe62885ed1d9

You ought to be able to extend the logic a little to turn this match into a dotted
pattern instead of raising an error?

**Comment by jfdm** [comment]
Thanks @ziman for raising the issue. I had some working code that failed with moving to Idris2 HEAD. The new error happens in some 'deep-ish' code, and I don't know how to fix the fix, so I am going to roll back Idris and just wait.

**Comment by gallais** [comment]
In my experience, making the arguments that are going to be forced `0`
tends to fix the issue because then Idris will not try to case-split
on them.

**Comment by jfdm** [comment]
> making the arguments that are going to be forced `0`
> tends to fix...

Ah, that 'fix' fixed it! Thanks.

**Comment by gallais** [comment]
Okay I have tried

```idris
-mkPat args orig (Ref fc (DataCon t a) n) = pure $ PCon fc n t a args
-mkPat args orig (Ref fc (TyCon t a) n) = pure $ PTyCon fc n a args
+mkPat args orig (Ref fc (DataCon t a) n)
+  = pure $ if a == length args
+      then PCon fc n t a args
+      else PUnmatchable (getLoc orig) orig
+mkPat args orig (Ref fc (TyCon t a) n)
+  = pure $ if a == length args
+      then PTyCon fc n a args
+      else PUnmatchable (getLoc orig) orig
```

and it does make both our examples legal. It is however pretty dubious:
it leads to the broken examples in `error014` to be accepted! I think it
needs to be handled earlier so that we may make use of `checkDot` to make
sure that we only accept the ones that are forced.

**Comment by gallais** [comment]
Ok, so looking at `TTImp.Elab.App`, it's a bit tricky: these implicit arguments tend to
start as metas that get solved *after* analysing further patterns on the LHS. So you need
to elaborate the whole LHS first & then retraverse it to check the introduced metas for
under-applied constructors.

Tomorrow, maybe.

**Comment by gallais** [comment]
The new fix has the same issue. :(

**Comment by gallais** [comment]
I think I have finally nailed it by a combination of both approaches tested over
the course of the past few days:

* if an argument on the LHS is elaborated to a partially applied constructor,
  emit a constraint saying it should be forced by something else on the LHS
* when generating the case tree, do not consider patterns with under-applied
  constructors as legitimate sources of splits

The working test case:

```idris
data IsS : (Nat -> Nat) -> Type where
  Indeed : (s : Nat -> Nat) -> s === S -> IsS s

------------------------------------------------------------------------
-- 1.
-- the S pattern is forced by the fact the parameter is instantiated
-- so everything is fine

-- either left implicit
indeed : IsS S -> S === S
indeed (Indeed _ eq) = Z

-- or made explicit
indeed2 : IsS S -> S === S
indeed2 (Indeed S eq) = eq

------------------------------------------------------------------------
-- 2. The S pattern is not forced by the parameter (a generic variable)

-- either don't match on it
indeed3 : IsS s -> s === S
indeed3 (Indeed s eq) = eq

-- or match on the proof that forces it
indeed4 : IsS s -> s === S
indeed4 (Indeed S Refl) = Refl
--              ^ forced by Refl

-- If you don't: too bad!
fail : IsS s -> s === S
fail (Indeed S eq) = eq
--             ^ not Refl, S not forced! OUCH
```
