### ISSUE TITLE
"Can't infer type for case scrutinee"

### ISSUE THREAD

**Issue by ulidtko** [idris-lang/Idris2#764]
Hi!

Somebody on `idris-lang@` was attempting an FFI bindings to `libcurl` and got me interested.

Of course I couldn't write it, hit this weird roadblock. Minimized to 5 lines.

### Reproducer
```idris
curl_easy_setopt : IO ()
curl_easy_setopt = do
    --let rc : Int
    rc <- pure 42
    case rc of
     -- 0 => pure handle
     e => printLn "woot"
```

### Expected Behavior
Should typecheck

### Observed Behavior
Does not:
```
test.idr:5:10--5:12:While processing right hand side of curl_easy_setopt at test.idr:2:1--8:1:
Can't infer type for case scrutinee at:
5	    case rc of
	         ^^
```

How can any of this trip up type inference — I've no slightest idea; that's one issue.

Another problem is that the `let rc : Int` does nothing. The user would gladly assist the typechecker by plopping in an annotation — but there appears no working means to do that (I'd searched the docs for "annotation", both Idris versions, found nothing useful).

So instead, the user is helpless, infuriated and angry :smiley: I do realize that's kind of expected from a research-grade language, but... oh well :man_shrugging:

**Comment by ShinKage** [comment]
Since integer literals are overloaded, the typechecker cannot infer from anywhere what the concrete type is for `42` (e.g. `Nat`, `Int` or `Integer`). Regarding annotations, you can use `rc <- the Int 42`, the `Prelude.the : (0 a : Type) -> (1 _ : a) -> a` function would force the overloaded literal to `Int`. Current syntax does not support type annotations on the left side of a do bind, since you can arbitrarly pattern match on the LHS of a do bind.
But if you have suggestion feel free to contribute 😃

**Comment by gallais** [comment]
Do blocks have `let`-bindings. You can write:

```idris
curl_easy_setopt : IO ()
curl_easy_setopt = do
    let rc : Int = 42
    case rc of
     e => printLn "woot"
```

**Comment by ulidtko** [comment]
> Since integer literals are overloaded, the typechecker cannot infer ...

Hmmm I was going to say that I'm not convinced because the same thing happens with `String`. Are string literals like `"foo"` also overloaded in Idris2?..

However, it does typecheck with `()` and `Bool`, so maybe you're right and it's a type ambiguity thing.

BTW, thanks for reminding about `the`, I vaguely recalled that it exists but just couldn't find its spelling again!

> Do blocks have let-bindings. You can write...

Yes, understood; but I need the monadic binding (hence `pure 42`) — the `rc` stands for a return code from C FFI call.

I suppose something like this would work?..

```
curl_easy_setopt : IO ()
curl_easy_setopt = do
    rc <- pure 42 `the` IO Int
    case rc of
     e => printLn "woot"
```

Nope! Same error.

**Comment by gallais** [comment]
> Are string literals like "foo" also overloaded in Idris2?..

Yes.

> Yes, understood; but I need the monadic binding (hence `pure 42`)
  — the rc stands for a return code from C FFI call.

The `pure 42` is confusing as the minimised test case ends up throwing
extra spanners in the work. My advice would be to write your example
putting these extra things as arguments to the example rather than
coming up with inhabitants.

e.g.

```idris
example : IO Int -> IO ()
example ion = do
  rc <- ion
  case rc of
    e => printLn "woot"
```

works just fine so there's clearly a problem somewhere else in your example.


> Nope! Same error.

The error message is about the scrutinee of `case` not having a type that
can be inferred so I'd put the type annotation directly on the scrutinee
like so:

```idris
curl_easy_setopt : IO ()
curl_easy_setopt = do
    rc <- pure 42
    case the Int rc of
     e => printLn "woot"
```

**Comment by gallais** [comment]
Additionally, this ``pure 42 `the` IO Int`` looks like it's calling
`the` the wrong way around: the type argument must come first.

**Comment by ulidtko** [comment]
Oh geez, I'm messing up all the things :grimacing:

**Comment by ulidtko** [comment]
@gallais that helps a lot. Thanks!

**Comment by gallais** [comment]
Note that you can be sneaky and use `do`'s `let`-binding together with
`!`-notation to give a type annotation to the result of a monadic action
without having to use `the` by writing:

```idris
curl_easy_setopt : IO ()
curl_easy_setopt = do
    let rc : Int = !(pure 42)
    case rc of
     e => printLn "woot"
```

:smiling_imp:

**Comment by MarcelineVQ** [comment]
Feel free to steal any ideas you like from https://github.com/MarcelineVQ/idris2-curl/
What is idris-lang@ btw?

**Comment by ulidtko** [comment]
> What is idris-lang@ btw?

The mailing list. https://groups.google.com/g/idris-lang

Thanks for the link!

**Comment by wurmli** [comment]
> Additionally, this `` pure 42 `the` IO Int `` looks like it's calling
> `the` the wrong way around: the type argument must come first.
> So you should write `` IO Int `the` pure 42 `` in which case you do not
> get a type error.

In fact, correctly called it works! (Is `the` defined as an operator?)
```
curl_easy_setopt : IO ()
curl_easy_setopt = do
    rc <- the (IO Int) (pure 42)
    case rc of
      41 => printLn "forty-one"    
      43 => printLn "woot"
      42 => printLn "42"
```
```
1/1: Building Scrutinee (Scrutinee.idr)
Loaded file Scrutinee.idr
Main> :exec curl_easy_setopt
"42"
Main> 
```
