### ISSUE TITLE
IDEmode highlight on function names

### ISSUE THREAD

**Issue by Yu-zh** [idris-lang/Idris2#769]
For the test file [ideMode001/LocType.idr](https://github.com/idris-lang/Idris2/blob/52ba8b00a60890e655afc515d8430ae49f81fedd/tests/ideMode/ideMode001/LocType.idr#L7)

```
data Vect : Nat -> Type -> Type where
     Nil : Vect Z a
     (::) : a -> Vect k a -> Vect (S k) a

append : Vect n a -> Vect m a -> Vect (n + m) a
append [] ys = ys
append (x :: xs) ys = x :: append xs ys
````

The function name `append` on the last line didn't get highlighted. In the expected [output](https://github.com/idris-lang/Idris2/blob/52ba8b00a60890e655afc515d8430ae49f81fedd/tests/ideMode/ideMode001/expected#L11), the two `append`s  are not covered. Should this be considered a bug?

**Comment by Yu-zh** [comment]
And maybe it's worth mentioning the protocol on highlight in the issue #768

**Comment by gallais** [comment]
This is now correctly highlighted.
