### ISSUE TITLE
Build error:  Can't disambiguate name: Main.yprefix, YafflePaths.yprefix

### ISSUE THREAD

**Issue by edwinb** [idris-lang/Idris2#77]
<a href="https://github.com/LeifW"><img src="https://avatars2.githubusercontent.com/u/28711?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LeifW](https://github.com/LeifW)**
_Friday May 15, 2020 at 13:47 GMT_
_Originally opened as https://github.com/edwinb/Idris2-boot/issues/375_

----

Just did a git pull (at 21507e64f38c3ac4a1f0fafce7fa7e5c1f59ec1d), and running "make install" fails with:
```
...
Type checking ./Idris/IDEMode/REPL.idr
Type checking ./Idris/Main.idr
./Idris/Main.idr:49:15-21:
   |
49 |               Nothing => setPrefix yprefix
   |               ~~~~~~~
When checking right hand side of Main.case block in updatePaths at ./Idris/Main.idr:47:15-21 with expected type
        Core ()

Can't disambiguate name: Main.yprefix, YafflePaths.yprefix

./Idris/Main.idr:212:7-213:19:
    |
212 |     = do putStrLn yprefix
    |       ~~~~~~~~~~~~~~~~~~~ ...
When checking right hand side of quitOpts with expected type
        IO Bool

Can't disambiguate name: Main.yprefix, YafflePaths.yprefix

make: *** [Makefile:92: dist/idris2.c] Error 1
```
Using Idris 1.3.2 provided by Arch Linux (which pulls the tarball down from GitHub releases: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/idris#n21)

**Comment by edwinb** [comment]
<a href="https://github.com/edwinb"><img src="https://avatars1.githubusercontent.com/u/255926?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edwinb](https://github.com/edwinb)**
_Friday May 15, 2020 at 14:58 GMT_

----

Did you clean everything first? You might have an out of date `YafflePaths.idr`

**Comment by buzden** [comment]
When I had this problem, cleaning helped.

**Comment by edwinb** [comment]
I'm going to close this since the build system is entirely different now. If there's still a problem, please reopen (or maybe better, open a new issue).
