### ISSUE TITLE
Both idris2 and contrib define a module called Text.Parser

### ISSUE THREAD

**Issue by shmish111** [idris-lang/Idris2#810]
https://github.com/idris-lang/Idris2/blob/master/src/Text/Parser.idr and https://github.com/idris-lang/Idris2/blob/master/libs/contrib/Text/Parser.idr both exist which can cause a problem if you wish to use both contrib and idris2api. In fact it seems to cause another issue as well: https://github.com/idris-lang/Idris2/issues/809

**Comment by andrevidela** [comment]
Should be fixed with #895
