### ISSUE TITLE
Enhance error reporting for parse errors

### ISSUE THREAD

**Issue by gallais** [idris-lang/Idris2#811]
At the moment we are getting nice errors that look something like the following
for type errors:

```
Expected `List b`, got `List a`

map : (a -> b) -> List a -> List b
map f (x :: xs) = f x :: xs
                         ^^
```

But parse errors are just `Error: Parse error at line LL:CC`. It'd be nice to
also print a little bit of the context so that users can figure out what is
wrong a little bit more easily.

It would be nice to also find a readable way to display the list of `next tokens`
(perhaps one per line?).

**Comment by andrevidela** [comment]
I think this was implemented in #1034
