### ISSUE TITLE
Mismatch between FZ and FZ

### ISSUE THREAD

**Issue by JoeyEremondi** [idris-lang/Idris2#833]
# Steps to Reproduce

The bug arose when I was trying to show that it's decidable whether a decidable predicate holds for all elements of a finite type.

```idris
import Data.Nat
import Data.Fin
import Data.Nat.Order

boundedFiniteDec :
  {0 n1 : Nat}
  -> {P : Fin (S n1) -> Type}
  -> ((x : Fin (S n1)) -> Dec (P x))
  -> (bound : Fin (S n1))
  -> Dec ((x : Fin (S n1)) -> LTE  (finToNat x) (finToNat bound) -> P x)
boundedFiniteDec dec bound with (dec bound)
boundedFiniteDec dec bound | No npf = No $ \allP => npf $ allP _ $ LTEIsReflexive _
boundedFiniteDec dec FZ | Yes pf = Yes $ \FZ, LTEZero => pf
boundedFiniteDec dec (FS bound) | Yes pf = ?rhs
```

# Expected Behavior

I'm 90% sure the program should typecheck. I'm 100% sure that if there's an error, the error should report a conflict between two distinct types.

# Observed Behavior

```
While processing right hand side of with block in boundedFiniteDec. When
unifying P FZ and P FZ.
Mismatch between: FZ and FZ.
```

If I replace  `pf` with `?goal` in the right-hand side of the second case, and do `:t goal`, the REPL reports both the goal type and the type of `pf` as `P FZ`.

**Comment by cypheon** [comment]
I think the main issue here is that the lambda `\FZ, LTEZero => pf` is _not_ a pattern match, even though it looks like one. Instead the "real" values of `FZ` and `LTEZero` (from `Data.Fin`) are shadowed by the lambda arguments (the lambda creates new bindings at the inner scope). I'm not sure of the correct terminology, so I hope I can explain it by example.

The difference be seen, when you rename the lambda arguments to lowercase (`\fz, lteZero => ?goal`). Then Idris shows the goal as following:

```
 0 n1 : Nat
   P : Fin (S n1) -> Type
   pf : P FZ
   dec : (x : Fin (S n1)) -> Dec (P x)
   fz : Fin (S n1)
   lteZero : LTE (finToNat fz) 0
------------------------------
goal : P fz
```

Then it becomes clear that the goal is in fact not `P FZ` (`FZ` from `Data.Fin`), but `P fz` (`fz` the lambda argument).

To make it clear, that the only possible argument to the lambda can be `FZ` (from `Data.Fin`), you can rewrite it like this:

```idris
boundedFiniteDec dec FZ | Yes pf = Yes $ \fz, lteZero => case fz of
                                                              FZ => pf
                                                              FS _ impossible
```
Which Idris happily accepts.

I think the error message could really be improved, e.g. showing the type of `pf` like `pf : P Data.Fin.FZ` when `FZ` is shadowed by a different binding at another scope.

**Comment by gallais** [comment]
We should perhaps reject non-lowercase names in a lambda that
is not a pattern-matching lambda...

**Comment by Russoul** [comment]
Related: #677

**Comment by gallais** [comment]
Ah! Turns out we don't need to modify the parser, just the desugarer.

**Comment by JoeyEremondi** [comment]
Well, I was hoping I was just missing something easy, and it turns out I was. Thanks for the pointers!
