### ISSUE TITLE
Implicit params in where-clause not shown in goal

### ISSUE THREAD

**Issue by JoeyEremondi** [idris-lang/Idris2#834]
# Steps to Reproduce

```idris
foo : {p : Nat -> Type} -> p 0
foo = ?rhs1
  where
    helper : {p2 : Nat -> Nat -> Type} -> p2 0 0
    helper  = ?rhs2
```

# Expected Behavior
The implicit variables from the where-defined function should be included, just like the normally defined function.
```
Main>:t rhs1
   p : Nat -> Type
------------------------------
rhs1 : p 0

Main>:t rhs2
   p : Nat -> Type
   p2 : Nat -> Nat -> Type 
------------------------------
rhs2 : p2 0 0

```

# Observed Behavior
The implicit argument to `helper` is not reported when the goal type is displayed.
```
Main>:t rhs1
   p : Nat -> Type
------------------------------
rhs1 : p 0
Main> :t rhs2
   p : Nat -> Type
------------------------------
rhs2 : p2 0 0
```

**Comment by gallais** [comment]
I think this may be caused indirectly by the fact we are not using implicit
generalisation of variables in local definitions. e.g.

```idris
foo : {p : Nat -> Type} -> p 0
foo = ?rhs1
  where
    helper : p2 0 0
    helper  = ?rhs2
```

gives an out of scope error on `p2`. Which is pretty annoying tbh.
