### ISSUE TITLE
Bug with interface is not accessible in this context

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#858]
I believe this used to work before, but it fails in Idris 2, version 0.2.1-681c1bf10.

# Steps to Reproduce

```idris
module Filterable

import Data.List

public export
interface Functor f => Filterable (f : Type -> Type) where
    catMaybes : f (Maybe a) -> f a

export
mapMaybe : Filterable f => (a -> Maybe b) -> f a -> f b
mapMaybe f a = catMaybes $ map f a
```

# Expected Behavior

No errors

# Observed Behavior

```idris
3/15: Building Filterable (src/Filterable.idr)
Error: While processing right hand side of mapMaybe. {f:3623} is not accessible in this context.

src/Filterable.idr:11:16--11:35
    |
 11 | mapMaybe f a = catMaybes $ map f a
    |                ^^^^^^^^^^^^^^^^^^^
```

**Comment by ohad** [comment]
Does `mapMaybe g x = catMaybes $ map g x` avoid the bug?

**Comment by michaelmesser** [comment]
Same error
```
3/15: Building Filterable (src/Filterable.idr)
Error: While processing right hand side of mapMaybe. f is not accessible in this context.

src/Filterable.idr:11:16--11:35
    |
 11 | mapMaybe g x = catMaybes $ map g x
```

**Comment by michaelmesser** [comment]
Explicitly writing the type of `f` avoids the issue
```
export
mapMaybe : {f : Type -> Type} -> Filterable f => (a -> Maybe b) -> f a -> f b
mapMaybe g x = catMaybes $ map g x
```

**Comment by ohad** [comment]
I just built it from current master (Idris 0.2.1-cdd0d0787) and the original code type-checks

**Comment by ohad** [comment]
This type-checks for me with master version:
```idris
module Filterable

import Data.List

public export
interface Functor f => Filterable (0 f : Type -> Type) where
    catMaybes : f (Maybe a) -> f a

export
mapMaybe : Filterable f => (a -> Maybe b) -> f a -> f b
mapMaybe f a = catMaybes $ map f a

```

**Comment by ohad** [comment]
I don't have a clue whether this is a bug or intended. Maybe @edwinb or @gallais know.

**Comment by gallais** [comment]
This is intended following #808

Cf. [the documentation](https://idris2.readthedocs.io/en/latest/tutorial/interfaces.html#quantities-for-parameters) (which, I am noticing now, has some typesetting issues)

**Comment by ohad** [comment]
Right, so I guess the non-intuitive bit is that the constraint `Filterable f` in `mapMaytbe` doesn't bind `f` with the same relevance, but rather `f` is implicitly bound  (as usual).

My intuition is that the unintuitive behaviour is binding inside the interface name, rather than allowing arbitrary telescopes when declaraing interfaces, as in:
```idris
interface {0 f : Type -> Type} -> Functor f => Filterable f where
```
but perhaps that's how type classes are usually used.

**Comment by ohad** [comment]
Or maybe the unintuitive behaviour is that we think the body of the interface doesn't need `f` at runtime because it doesn't use it, but that's an analysis we gave up on doing.

**Comment by michaelmesser** [comment]
```idris
public export
interface Functor f => Filterable (0 f : Type -> Type) where
    catMaybes : f (Maybe a) -> f a
```
fixes the issue
