### ISSUE TITLE
Use of `realpath` in MacOS not available

### ISSUE THREAD

**Issue by hbr** [idris-lang/Idris2#874]
I have just installed idris2 via `brew install idris2` and compiled the hello world program.

    idris2 hello.idr -o hello
    ./build/exec/hello

The last command gives the message

    ./build/exec/hello: line 9: realpath: command not found
    ./build/exec/hello: line 14: ./hello_app/hello.so: No such file or directory

If I `cd` into `./build/exec` and issue `./hello` I just get the first error message and the program outputs "Hello World!" as expected.

The file `hello` uses `realpath` which is not available in the bash shell of my MacOS.

**Comment by ska80** [comment]
As it is mentioned in https://github.com/idris-lang/Idris2/blob/master/INSTALL.md

you will have to install `coreutils` via `Homebrew`

**Comment by hbr** [comment]
Thanks. Now it works.

Question: Since homebrew is a packagemanager which can handle dependencies, isn't it possible to include the dependency such that `brew install idris2` install the dependency as well?

In `INSTALL.md` it is a little bit misleading, because it states that `brew install idris2` installs idris2 with all its dependencies.

**Comment by michaelmesser** [comment]
@hbr Here is the [formula](https://github.com/Homebrew/homebrew-core/blob/b59c1118dbaa3f10540f525d7955cacd3fe24d3e/Formula/idris2.rb). Perhaps you could make an issue or a PR there?

**Comment by hbr** [comment]
Unfortunately I am not familiar with the syntax of formulas in brew. Who is the author of the formula? Maybe better ask him.

**Comment by michaelmesser** [comment]
@hbr Then make an issue

**Comment by hbr** [comment]
Even only raising issues is a complicated procedure, at least unless you are a brew maintainer.

I am just a brew user. Maybe the things are not as complicated as they seem initially. But without knowledge about the brew procedures for contributors, it seems to be complicated.

Who has contributed the formula? Probably someone of the Idris team.

**Comment by KilianKilmister** [comment]
Depending on how `coreutils` is installed (eg. via macports), the commands aren't automatically `alias`ed and still have the 'g'-prefix, so `make` will error unless the scripts are changed to handle that...

**Comment by gallais** [comment]
Right that's indeed an upstream issue but hopefully my PR will get in
& it'll be fixed for everyone. Thanks @michaelmesser for the diagnostic.
