### ISSUE TITLE
`with`-rule misses the `proof` keyword 

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris2#893]
# Steps to Reproduce

```
thenCompare : Ordering -> Lazy Ordering -> Ordering
thenCompare LT y = LT
thenCompare EQ y = y
thenCompare GT y = GT

foo : (a, b : Nat) -> thenCompare (a `compare` b) o = a `compare` b
foo a b with (a `compare` b)
  foo a b | LT = Refl
  foo a b | EQ = ?hole
  foo a b | GT = Refl
```

# Expected Behavior

We should be able to add `proof prf` to the `with` rule and finish the hole with `sym prf`, as in Idris1

# Observed Behavior

We're forced to fall back on matching directly on `a` and `b`.

**Comment by buzden** [comment]
You could use a `with (@@ (a `compare` b))` from `Syntax.WithProof` in `contrib` as an ersatz.

**Comment by edwinb** [comment]
Given `Syntax.WithProof` as @buzden suggests, I've so far not been enthusiastic about implementing more syntax, since it's a feature that isn't used much and can be done in code already.

**Comment by gallais** [comment]
`Syntax.WithProof` is not as powerful though: `compare a b` will not be
abstracted over in the goal type. To recover the full power of the inspect
idiom you need to nest 2 withs. Or use a multiwith, something I have been
trying to implement for a while now but the well-scoped syntax keeps kicking
my butt.

**Comment by clayrat** [comment]
I've actually realized that the initial example is bogus, let's say I have something like the following instead:

```
foo : (a, b : Nat) -> Bool
foo  Z    b = False
foo (S _) b = False

notFoo : (a, b : Nat) -> Not (foo a b = True)
notFoo  Z    _ = uninhabited
notFoo (S _) _ = uninhabited

bar : (a, b : Nat) -> (foo a b) && c = foo a b
```

(where instead of `Nat`s and `Bool`s I have inductive types with multiple constructors, making it unpleasant to repeatedly match on all possible combinations in proofs). Now with `@@` I can finish `bar` like this:

```
bar a b with (@@ (foo a b))
  bar a b | (True  ** ab) = absurd $ notFoo a b ab
  bar a b | (False ** ab) = rewrite ab in Refl
```

I'm not sure how to regain the power of `with proof` syntax by nested matching however, so that one could keep the first line but drop the `rewrite` in the last line. The problem seems to be that subsequent matching acts both on the goal and `ab`, whereas the original syntax kept `ab` intact.

**Comment by gallais** [comment]
> I'm not sure how to regain the power of with proof syntax by nested matching however

It's the [`inspect` idiom](https://agda.github.io/agda-stdlib/README.Inspect.html).

In Idris:

```idris
record Reveal {0 a : Type} {0 b : a -> Type} (f : (x : a) -> b x) (x : a) (y : b x) where                                       
  constructor MkReveal
  proof : f x === y
 
inspect : {0 a : Type} -> {0 b : a -> Type} ->
          (f : (x : a) -> b x) -> (x : a) -> Reveal f x (f x)
inspect f x = MkReveal Refl
 
bar : (a, b : Nat) -> (foo a b) && c = foo a b
bar a b with (inspect (foo a) b)
  bar a b | eq with (foo a b)
    bar a b | eq | True  = absurd $ notFoo a b (eq .proof)
    bar a b | eq | False = Refl
```

**Comment by clayrat** [comment]
> It's the [`inspect` idiom](https://agda.github.io/agda-stdlib/README.Inspect.html).

Oh, that's interesting, should we add that to contrib as well?

**Comment by gallais** [comment]
That would indeed be a good idea.
