### ISSUE TITLE
Proof of Void due to false covering check

### ISSUE THREAD

**Issue by alebahn** [idris-lang/Idris2#899]
# Steps to Reproduce
```
import Data.Fin
import Data.Nat

%default total

data FinLTE : {k : Nat} -> Fin k -> Fin k -> Type where
  FromNatPrf : {m, n : Fin k} -> LTE (finToNat m) (finToNat n) -> FinLTE m n

lteZeroImpossible : FinLTE c FZ {k=(S j)} -> Void
lteZeroImpossible (FromNatPrf (LTESucc x)) impossible
--lteZeroImpossible (FromNatPrf LTEZero) = ?lteZeroImpossible2_rhs_1

proveVoid : Void
proveVoid = lteZeroImpossible (FromNatPrf LTEZero) {c = FZ} {j=2}
```

# Expected Behavior

This should fail to typecheck. Idris 1 gives the error:
`Main.lteZeroImpossible is not total as there are missing cases`

# Observed Behavior

The code typechecks and is considered total.

This seems to be due to the branch for LTEZero being trimmed because it can't can't solve between 0 and finToNat. This branch is a valid case despite its inability to solve.

**Comment by gallais** [comment]
Shrunk down:

```idris
%default total
 
zeroImpossible : (k : Nat) -> k === Z -> Void
zeroImpossible (S k) eq impossible
 
proveVoid : Void
proveVoid = zeroImpossible Z Refl
```

The problem is that, ignoring the impossible clause, `zeroImpossible` has no clause left
and Idris confuses itself in not checking that the telescope is indeed empty.

**Comment by gallais** [comment]
The problem is that `getPMDef` produces a case tree of the shape:

```idris
Impossible
```

instead of

```idris
case 0 of
  S k => Impossible
  Z => Unmatched
```

I don't really understand why though as everything looks sensible.

**Comment by gallais** [comment]
Uh. So for some reason when looking at `zeroImpossible (S k) eq impossible`,
Idris decides that `S` is an unmatchable function rather than seeing `S k` as
an applied data constructor. Very puzzling.
