### ISSUE TITLE
JavaScript Backend: JavaScript function counterparts don't work

### ISSUE THREAD

**Issue by DoctorRyner** [idris-lang/Idris2#906]
# Steps to Reproduce

1. For instance, use `putStr` in Main.idr
2. Compile it with the JavaScript backend

# Expected Behavior

It should work

# Observed Behavior

`Error: INTERNAL ERROR: No node or javascript definition found for Prelude.IO.prim__putStr in ["C:idris2_putStr,libidris2_support", "node:lambda:x=>process.stdout.write(x)"]`

But we clearly see that there is node definition although the error says there is none

**Comment by Russoul** [comment]
The JavaScript backend doesn't support invocation of functions written specifically for Node. Meanwhile, `prim__putStr` is one of them - the FFI string prefixes the lambda function with `node:`.

**Comment by DoctorRyner** [comment]
I didn't quite get it, why would you write a node definition if it isn't supported?

**Comment by Russoul** [comment]
We have two "JavaScript" backends which are called `node` and `javascript`, they target `Nodejs` runtime and generic browser runtime respectively.

**Comment by DoctorRyner** [comment]
Ah, I'm sorry, I didn't notice, thank you

**Comment by stefan-hoeck** [comment]
The error message was fixed in #1609, so this can probably be closed.
