### ISSUE TITLE
Function with argument of equal name causes internal error

### ISSUE THREAD

**Issue by GustavoMF31** [idris-lang/Idris2#912]
# Steps to Reproduce

Make the name of an argument to a function equal to the name of the function itself. For example:
```
n : a -> a
n n = ?n_rhs 
```
A very easy way to reach such state is by writing a higher order function called `f` and asking Idris to create a skeleton for the definition. It will then name the function received as an argument `f`, and you end up with both the original function and the argument named the same.
```
f : (a -> a) -> a
-- generating the definition results in:
f f = ?f_rhs
```

# Expected Behavior

It's expected that either the code doesn't typecheck or, perhaps more reasonably, the argument name shadows the function name. The latter is what Idris1 and Haskell do.

# Observed Behavior

The compiler fails with:
```
Error: INTERNAL ERROR: $f is not a function application
```
(where `f` is the name both the function and the argument share)

**Comment by edwinb** [comment]
Indeed. This is a duplicate of #110. I think I slightly prefer not typechecking, though there is an argument for shadowing too. Possibly one reason we never got around to fixing it was that we didn't make a decision.

Maybe sticking with the Idris 1 behaviour is the right thing.

**Comment by GustavoMF31** [comment]
In my opinion, the best would be to shadow the name, but show a warning telling the programmer about it, as there is a significant chance it happened by accident. However, not typechecking also seems like an ok solution, i'm not particularly sold on either.

I'll close the issue as it is a duplicate. Further discussion can happen on the original one.

**Comment by buzden** [comment]
> show a warning telling the programmer about it

If compiler shown a warning for every shadowing, all users of _intentional shadowing_ would be disappointed. So, it's not an easy thing.
