### ISSUE TITLE
Dummy `let` influences in the typechecking success

### ISSUE THREAD

**Issue by buzden** [idris-lang/Idris2#927]
# Steps to Reproduce

Consider a (constructive, i.e. pseudo) "axiom of choice" coding:

```idris
ch : {0 r : a -> b -> Type} -> ((x : a) -> (y : b ** r x y)) -> (f : a -> b ** (x : a) -> r x (f x))
```

with three implementations:

1. ```idris
    ch f = (\x => fst (f x) ** \x => let _ = True in snd (f x))
    ```
1. ```idris
    ch f = (\x => fst (f x) ** \x => snd (f x))
    ```
1. ```idris
    ch f = (\x => fst (f x) ** \x => DPair.snd (f x))
    ```

# Expected Behavior

All three either typecheck or give more or less the same error.

# Observed Behavior

The first one (with a dummy `let`) typechecks fine. However, the next two do not.

The second one fails because Idris can't decide between two variants of `snd`: the independent one (obviously does not typecheck) and the dependent one (see below).

If we disambiguate `snd` to `DPair.snd` (the third variant), Idris says
```
Error: While processing right hand side of ch. When unifying r x (fst (f x)) and r x (?fst x).
Can't make solution for Main.{fst:382} at ?Main.{a:380}_[b[3], a[2], r[1], f[0]]
```

**Comment by Russoul** [comment]
Oh, I remember an identical issue #589

**Comment by Russoul** [comment]
Originally the dummy let was there too, while we were discussing it on slack. But it didn't make it into the issue

**Comment by buzden** [comment]
Oh, my keyword search is bad. I tried to search before issuing, but unsuccessfully.
