### ISSUE TITLE
make test hanging in MSYS2 on Windows 10

### ISSUE THREAD

**Issue by zenntenn** [idris-lang/Idris2#939]
A few days ago I did not have this problem.

I am running MSYS2 on Windows 10.

Now when I run `make test` after doing `make clean`, `make all` and `make install` I get the following output, and then it hangs. I've let it run for 10 minutes without it moving forward past this point.

```
$ make test

NOTE: `make test` does not rebuild idris; to do that run `make`

make[1]: Entering directory '/home/HillerupJ/Idris2/tests'
./build/exec/runtests ../../../build/exec/idris2 --interactive --only
diff --git a/expected b/output
index e0edebfb..c81dc82b 100644
--- a/expected
+++ b/output
@@ -1,5 +1,5 @@
1/1: Building TypeSearch (TypeSearch.idr)
Main> prim__cast_CharString : (1 _ : Char)Char -> String

Main.sameSig : Char -> String

**Comment by ShinKage** [comment]
Should have been fixed by https://github.com/idris-lang/Idris2/pull/937, have you checked with the lastest master?

**Comment by zenntenn** [comment]
@ShinKage I had tried earlier today, but it's fixed now.
