### ISSUE TITLE
Flaky Nix CI Runs

### ISSUE THREAD

**Issue by fabianhjr** [idris-lang/Idris2#957]
Sometimes the Nix CI Test fails with the following message:

```
error (ignored): error: --- SysError --- nix
writing to file: Broken pipe
error (ignored): error: --- Error --- nix
error: --- Error --- nix-daemon
invalid operation 96
error: --- SysError --- nix
writing to file: Broken pipe
(use '--show-trace' to show detailed location information)
```

This has happened some times on PRs and on the main branch. Eg,

- https://github.com/idris-lang/Idris2/runs/1720826047
- https://github.com/idris-lang/Idris2/runs/1710561358

**Comment by Infinisil** [comment]
See #1001 for the fix
