### ISSUE TITLE
Flaky Windows CI Runs

### ISSUE THREAD

**Issue by fabianhjr** [idris-lang/Idris2#958]
There is an issue with the Windows chez/concurrency001 test that wasn't fixed by increasing/loosening the timings. This might be related to either Threading or Clock issues but I couldn't find anything particularly useful in the diagnostic of this flakyness.

```
chez/concurrency001: FAILURE
Expected:
String
Hello Foo!
Hello Bar!
Hello Idris!
Hello World!
This line is printed
This line is also printed
#1
#2
#3

Given:
String
Hello Foo!
Hello Bar!
Hello Idris!
Hello World!
This line is printed
This line is also printed
```

Eg, https://github.com/idris-lang/Idris2/runs/1725307790

**Comment by gallais** [comment]
We haven't had any issue for a very long time so I am going to mark this as solved.
