### ISSUE TITLE
Idris2 hangs when casing on a list of characters using string literal as patterns

### ISSUE THREAD

**Issue by malte-v** [idris-lang/Idris2#962]
# Steps to Reproduce

```idris
foo : String -> Nat
foo str = case unpack str of
  "bar" => 0
  "baz" => 1
  _ => 10
```

# Expected Behavior

Idris terminates (probably with an error message).

# Observed Behavior

Idris doesn't terminate.

**Comment by gallais** [comment]
It's not specific to `unpack`, it comes from the fact you are using string
literals as patterns for lists of characters.

This also makes Idris hang:

```idris
foo : List Char -> Nat
foo cs = case cs of
  "bar" => 0
  "baz" => 1
  _ => 10
```

But this works:

```idris
foo : String -> Nat
foo cs = case cs of
  ['b', 'a', 'r'] => 0
  ['b', 'a', 'z'] => 1
  _ => 10
```

**Comment by gallais** [comment]
It was a lot easier to fix than I expected!
