### ISSUE TITLE
Using Idris as a library

### ISSUE THREAD

**Issue by L-as** [idris-lang/Idris2#973]
This is more of a question, but I want to use Idris as a library, so that my program can dynamically load more Idris code. I am using the Chez Scheme backend, so it seems possible to me, but I have no idea what function in the compiler I'd call to compile an Idris file to Chez Scheme object code. Is there some accessible API, or do you have any pointers so I know where to look in the source code?

**Comment by gallais** [comment]
Once you've installed Idris2, you should also have the [`idris2api`](https://github.com/idris-lang/Idris2/blob/master/idris2api.ipkg) library
installed meaning you can reuse any of the compiler's modules.

**Comment by L-as** [comment]
Yeah, I can see that, but what function do I actually use? I couldn't find anything grepping.

**Comment by andrevidela** [comment]
[`Driver`](https://github.com/idris-lang/Idris2/blob/master/src/Idris/Driver.idr) is, for all intents and purposes, the entry point to the compiler. [`main`](https://github.com/idris-lang/Idris2/blob/master/src/Idris/Main.idr) just calls `mainWithCodegens` from `Driver` so you could start by going through the call stack and call Idris just like you would call it on the command line, but supply the arguments directly with a value of `CLOpt` (for Command Line Options)

**Comment by L-as** [comment]
Thanks!
