### ISSUE TITLE
Mention idris2-vim in readme

### ISSUE THREAD

**Issue by stepancheg** [idris-lang/Idris2#978]
I wasted a lot of time and effort until I accidentally found idris2-vim.

This project (and probably some others?) **must** be mentioned in this project readme.

**Comment by andrevidela** [comment]
Does this help? https://github.com/idris-lang/Idris2/wiki/The-Idris-editor-experience

**Comment by stepancheg** [comment]
OK, now I know there's a wiki with list of supported editors! I think adding this link explicitly to README.md would help many.
